ScratchAddons/ScratchAddons

- .github/workflows/format-code.yml
Rremove accidental files introduced in the PR.
> Fix format-code.yml

- webpages/settings/index.html
> I fixed a mistake in my html

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/new-addons.md
- .github/pull_request_template.md
None.
Comments the description of each part in the templates.
Descriptions should not appear in actual issue/PRs
Just markdown, nothing to test.
> Disable autofill for templates

- addons/discuss-button/addon.json
- addons/editor-devtools/addon.json
- addons/editor-stepping/addon.json
- addons/image-uploader/addon.json
- addons/msg-count-badge/addon.json
- addons/scratch-notifier/addon.json
**Resolves**
Resolves #95
Resolves #104
**Changes**
All addons' addon.json.
> Remove 'Scratch' from addon names, add some tags to addons, add dots to the end of the all the addons' descriptions.

- addon-api/common/Auth.js
- background/declare-scratchaddons-object.js
- background/handle-auth.js
- webpages/settings/index.html
**Resolves**
Resolves #100
**Changes**
Remove all uses of sessionId.
#100
**Tests**
Not tested, so we'll see if it works lol
> Remove addon.auth.sessionId

- addon-api/common/Auth.js
- background/handle-auth.js
> Add scratchLang, recheck cookies on csrftoken/lang change

- addons/addons.json
- addons/fix-buttons/addon.json
- addons/fix-buttons/style.css
- background/get-userscripts.js
**Resolves**
Resolves #129 
**Changes**
add load more button fix and also fix bug in w_l code they told me to
yes
**Tests**
yes i did and it works i dont know what else to tell you
> Load More Button Fix (very cool)

- background/run-addon-bg-scripts.js
- content-scripts/inject/run-userscript.js
> Add color and bold to addon ID in console logs

- addon-api/content-script/Tab.js
> Return null in editorMode, if outside project page

- .editorconfig
- addons/discuss-button/addon.json
- addons/forum-time-zones/addon.json
- addons/image-uploader/addon.json
- background/background.html
- background/get-userscripts.js
- background/handle-licenses.js
- content-scripts/inject/run-userscript.js
- libraries/license-info.json
- libraries/licenses/MIT.txt
- manifest.json
- webpages/settings/index.html
- webpages/settings/licenses.html
- webpages/settings/licenses.js
- webpages/settings/style.css
**Resolves**
Resolves #160 
Resolves #159 
**Changes**
addon.json can now have these fields:
- `userscripts` section can now have `runAtComplete` (bool, defaults to true) - if true, scripts run at onload (like it did before), and if false, at DOMContentLoaded. Userstyles load at DOMContentLoaded.
- `credits` is an array of `{"name": "string", "link": "link URL (optional)"}`
- `libraries` is an array of library name, e.g. `["md5", "text-field-edit"]`
Because it's nice
> addon.json changes

- webpages/settings/index.js
**Resolves**
Resolves #177 
**Changes**
Focuses the search box when ctrl + f is clicked.
> Ctrl + F Fix

- addons/addons.json
- addons/remove-sprite-confirm/addon.json
- addons/remove-sprite-confirm/userscript.js
**Resolves**
Resolves #156 
**Changes**
Adds remove sprite confirm addon
So many people complain they lost sprites
> Remove Sprite Confirm addon

- .prettierignore
- README.md
With this PR, I just...
- tidied up the README so it is structural
- add more info about license and installation
- remove useless badges
- remove logos because we're on GitHub, of course it's about GitHub
- add multiple badges, such as Discord, license, and some others for the future
Hope you liked it.
> Updates and tidying up on README

- addons/addons.json
- addons/youtube-fullscreen/addon.json
- addons/youtube-fullscreen/userscript.js
**Resolves**
Resolves #69
**Changes**
Adds the YouTube full screen addon.
#69
**Tests**
Seems to work.
> Add yt fullscreen

- addons/progress-bar/addon.json
- addons/progress-bar/userscript.js
**Resolves**
Fixes some bugs from #153 
**Changes**
- fixes occasional error when saving project (due to error from trying to remove an element from the document when the element isn't in the document)
- make wording of the topbar option more clear (can probably be clarified more)
- make sure that the prototype hacks don't subtly change function behavior in unexpected ways or cause errors
These should've been in the original PR
**Tests**
Everything still works.
> Progress bar followup

- addons/external-player-button/userscript.js
**Resolves**
Fullscreen is now working.
Resolves #215 
**Changes**
Just a wrong line. Should be easy to merge.
I don't know, maybe because working things are neat.
**Tests**
It works.
> Forkfullscreen

- manifest.json
> Disallow usage in incognito mode

- addons/bitmap-copy/addon.json
- addons/remove-sprite-confirm/addon.json
- content-scripts/load-redux.js
- libraries/license-info.json
Use ReDucks (ducktyped Redux, created by me) instead of real Redux.
> Use ReDucks

- addons/scratch-messaging/popup.css
- addons/scratch-messaging/popup.html
- addons/scratch-messaging/popup.js
Resolves #267, did not work on Firefox
Also fixed a weird styling issue I found on Firefox as well.
> Fix #267 (Scratch Messaging addon)

- addons/editor-dark-mode/3dark.css
- addons/editor-dark-mode/3darker.css
- addons/editor-dark-mode/dark-editor.css
> Remove style changes in project player mode

- .github/workflows/schema-validation.yml
**Resolves**
Resolves #
**Changes**
**Tests**
> Fix quotation marks typo on SV workflow

- addons/image-uploader/userscript.js
**Resolves**
resolves world language yell at me
**Changes**
innerHTML in image uploader carefully replaced with innerText
world language yelling
**Tests**
nope
> replace innerHTML with innerText in my image uploader 😎😎😎

- README.md
Changed scratchaddons.github.io to scratchaddons.com
**Resolves**
Resolves #
**Changes**
**Tests**
> Redo the website link.

- addons/scratch-messaging/popup.css
- addons/scratch-messaging/popup.html
- addons/scratch-messaging/popup.js
- addons/scratch-notifier/addon.json
- addons/scratch-notifier/background.js
**Changes**
Reworking of the CSS styling of messaging popup
Switch the Emoji used for follows (to a face icon that is less different to the other emoji used)
> Scratch Messaging Popup Styling

- background/background.html
- background/transition.js
transition.js should be removed on version 1.0.1
> Open URL on transition from Scratch Messaging

- addons/full-signature/addon.json
- addons/full-signature/style2.css
- addons/scratch-messaging/popup.html
**Resolves**
Resolves #295 
**Changes**
This adds Options to the addon, and a scroll for What I'm working on on the profiles.
**Tests**
Inspect.
> Add Settings and Scroll for What I'm working on for See Full Signature addon (Now renamed)

- addons/fix-buttons/addon.json
- addons/image-uploader/addon.json
**Resolves**
me being sad
**Changes**
i added credits to myself in 2 addons,
my addon
and maxmouse's userstyle i helped port
sad jeffalo has no addons that credit him
**Tests**
no?
> credits to me?

- addons/data-category-tweaks/userscript.js
Resolves #307 
Waits until `addon.tab.traps.workspace` is available.
> Fix #307 Blockly not yet defined

- background/get-userscripts.js
- content-scripts/cs.js
Useful to link to settings directly from scratchaddons.com
> Add direct link to settings through scratch.mit.edu

- webpages/settings/index.html
nice
**Resolves**
maybe i should have made an issue first...
**Changes**
makes the png icon in the settings page to svg
other icons and stuff on that page are png and now that theres a svg one its kinda silly to _not_ use it
**Tests**
yeah
> replace png with svg on the settings nav

- background/background.html
- background/handle-cookie.js
**Resolves**
Resolves #331 
**Changes**
Ignore Set-Cookie inside comment endpoint
Because ST is lazy
**Tests**
Tested on the best browser firefox
> Add Set-Cookie fix

- background/background.html
- background/handle-cookie.js
**Resolves**
Resolves #
**Changes**
**Tests**
> Add Set-Cookie fix (#333)

- addons/full-signature/addon.json
- addons/full-signature/expand.js
**Changes**
Adds new script for expand button instead of all full signatures.
Cause the option to expand individual signatures is cool.
> Expand Button for Full Siggy

- addons/scratch-notifier/background.js
> Fix studio comments don't notify with the full comment content (Notifier)

- webpages/settings/index.html
- webpages/settings/style.css
> Fix modifying "select" setting not disabled if addon disabled

- webpages/settings/index.html
- webpages/settings/index.js
- webpages/settings/style.css
> Fix Vue warns

- manifest.json
**Resolves**
Resolves #354 
**Changes**
Exactly what the issue mentions
Changes for v1.1
//cc @WorldLanguages
> Manifest Changes For v1.1

- popups/scratch-messaging/popup.js
**Resolves**
Resolves #356 
**Changes**
Fixes link to studio comments
Because it was broken
> Fix studio comment URL

- addons/scratchr2/remixtree.css
Doesn't resolve, but does make box header look more modern.
**Changes**
Adds a little more css.
Because modern = good
**Tests**
Inspect
> Modernizing Box Header on Remix Tree

- addons/image-uploader/userscript.js
i fixed somethings i found annoying
**Resolves**
sorry its my own code i dont think i need to make an issue right?
**changes**
i cleaned up some comments and console.logs
i found these things annoying
> slight image uploader updates

- popups/scratch-messaging/popup.css
**Changes**
Make Reply Textbox More Like Scratch
> Make Reply Textbox More Like Scratch

- addons/full-signature/expand.js
**Changes**
Huge reworking of my addon.
> Huge Reworking for Expand Signature!

- background/get-userscripts.js
- background/handle-settings-page.js
- background/imports/global-state.js
- content-scripts/cs.js
- content-scripts/inject/module.js
- manifest.json
Resolves #252: automatically update themes (no refresh needed)
Resolves #328: ability to inject userstyles when the page starts loading
Resolves #386: messageForAllTabs() not working properly in Firefox
> Userstyle rework: update themes with no refresh, inject userstyles sooner

- addons/60fps/addon.json
- addons/60fps/userscript.js
- addons/addons.json
**Resolves**
Resolves #381 
**Changes**
adds an addon that uses ctrll+click green flag to enable 60fps (disable compatibility mode)
its hecking cool
**Tests**
yeah of course
> 60fps addon

- addons/addons.json
- addons/editor-stage-left/addon.json
- addons/editor-stage-left/fix-share-the-love.js
- addons/editor-stage-left/stageleft.css
- webpages/settings/index.html
- webpages/settings/index.js
- webpages/settings/style.css
Pull request is a re-issue of #335
> Add editor-stage-left addon (resubmit)

- addons/forum-search/addon.json
- addons/forum-search/userscript.css
- addons/forum-search/userscript.js
**Resolves**
Resolves formatting issues for forum posts
**Changes**
I had some old debugging code with `console.log` that I removed, I added options to sort by newest and oldest, and I also added the ability to search based on the current page you are on, meaning if on a topic/category page, it would try to sort by only posts on that topic/category. 
I also added more post information such as when ScratchDB first and last saw the post, as well as added links to show posts only by a user who made a post. There was also a few CSS issues that required an extra element to be added.
More features for forum searching
**Tests**
Manually tested, here are a few screenshots
On homepage:
Sorting/post info:
Category:
_I still have this as beta since I feel like the design could …
> Search improvements

- background/imports/global-state.js
- background/imports/local-state.js
This was cool, but unnecessary and added too much bloat to the console logs.
> Remove "changed by [line of code]"

- addons/forum-search/userscript.js
**Resolves**
Resolves #421 
**Changes**
adds a fancy message if the search returned no hits
because otherwise people might be sad
**Tests**
yes i did by testing it
> add message if there were no hits for the forum search

- addons/scratchr2/profile.css
**Resolves**
None
**Changes**
Removes blue background from 404 errors on profile pages.
https://github.com/ScratchAddons/ScratchAddons/pull/359#issuecomment-703271021
**Tests**
Works
> Scratch 2.0 → 3.0: fix blue background on 404 profiles

- popups/cloud-games/popup.css
- popups/scratch-messaging/popup.css
- webpages/popup/index.js
> Little details in extension popup and addon popups

- background/get-userscripts.js
- content-scripts/cs.js
- manifest.json
See #456 for more information
I've also made sure it works when a Scratch page is set as a startup tab.
> Use webRequest instead of webNavigation

- manifest.json
See #456 
v1.1.0 was submitted to webstores but won't reach the public.
> Bump version to v1.1.1

- addon-api/content-script/Tab.js
Resolves #441 
Addons can now use `addon.tab.waitForElement("selector", { markAsSeen: true })`
The same element is guaranteed not to be returned again to that addon, no matter the particular options object used (in other words, `markAsSeen: false` also ignores seen elements)
> Add "markAsSeen" option on addon.tab.waitForElement

- addons/60fps/userscript.js
- addons/discuss-button/userscript.js
To be honest, I thought more than 3 addons would make use of this lol
Addons are:
- More links
- 60 fps
- Discuss button
> Use addon.tab.waitForElement(selector, {markAsSeen: true})

- webpages/settings/index.html
- webpages/settings/index.js
I introduced this issue through 0b3392c78e478cd202b7121abe201876f9efa59f, this fixes it
> Fix input autofocus on settings page

- manifest.json
- webpages/settings/index.js
**Resolves**
Resolves #482 
**Changes**
Uses version_name and version. Version name is used for feedback, so it can say prerelease.
> Use Version Name Instead Of Version

- addons/addons.json
- addons/studio-tools/addon.json
- addons/studio-tools/userscript.js
Resolves #64
Lets you leave any studio, and promote/remove by username when you're a manager.
> Add studio manager tools addon

- addons/addons.json
- addons/last-edit-tooltip/addon.json
- addons/last-edit-tooltip/userscript.js
Hover over a project's share date for information on when it was last edited.
> Last Edit Tooltip Addon

- popups/cloud-games/popup.css
- popups/cloud-games/popup.html
- popups/scratch-messaging/popup.css
- popups/scratch-messaging/popup.html
- webpages/popup/index.html
- webpages/popup/style.css
**Changes**
I'm just going to let the images do the talking
The old styling is entirely outdated. This update matches the style of the rest of the project
> Update popup styling

- addons/addons.json
- addons/dark-www/dark-www.css
- addons/remix-tree-button/addon.json
- addons/remix-tree-button/main.js
Adds a remix tree button to project pages. The default color is blue, but it lets you choose a custom one.
> New Addon: Remix tree button on project pages

- addons/addons.json
- addons/mouse-pos/addon.json
- addons/mouse-pos/style.css
- addons/mouse-pos/userscript.js
**Resolves**
Resolves #535 
**Changes**
i added a mouse x and y addon 
because it's useful, and griffpatch suggested
**Tests**
yes i tested it by seeing if it works and it works
> add mouse x y addon

- addons/scratchr2/addon.json
- addons/scratchr2/profile.css
- addons/scratchr2/scratchr2.css
- addons/scratchr2/scratchr2_comments.css
- addons/scratchr2/studio.css
**Resolves**
Resolves #540
**Changes**
Fixed a few bugs with Scratch 2.0 → 3.0, and removed some unnecessary code.
Bugs need to be fixed.
**Tests**
Works.
> Scratch 2.0 → 3.0 fixes and improvements

- popups/cloud-games/light.css
- popups/cloud-games/popup.css
- popups/cloud-games/popup.html
- popups/scratch-messaging/light.css
- popups/scratch-messaging/popup.css
- popups/scratch-messaging/popup.html
- webpages/popup/light.css
- webpages/popup/style.css
Resolves #512 
Would like feedback on the tab design and lower margins on the cards
> Fix issues with popup restyling

- addons/full-signature/working.js
Fixes the stuff @WorldLanguages said.
@Hans5958, please merge.
> Updated Scripts

- addons/remix-tree-button/addon.json
- addons/remix-tree-button/main.js
- webpages/settings/light.css
> Fixed the remix tree button addon bug and also fixed a few light theme problems

- webpages/settings/style.css
> Less Opacity On Notices

- webpages/popup/index.html
- webpages/popup/index.js
- webpages/popup/style.css
Adds version in popup:
Links to releases page, although this could be changed.
> Version in popup

- webpages/settings/index.html
I SPENT ALL DAY FIXING THIS THANK YOU FOR COMING TO MY TED TALK
> EXTREMELY VITAL FIX

- manifest.json
Adds -prerelease and bumps the version.
> Prerelease + Version Bump

- README.md
Fixes the .zip link in the readme.
> Fixed ZIP Link

- addons/infinite-scroll/forumScroll.js
**Resolves**
Resolves #584
**Changes**
Fixed infinite scrolling on https://scratch.mit.edu/discuss/search/?action=show_user
Why did the addon use `innerHTML` before?
#584
**Tests**
Works.
> Fix infinite scrolling on Show your topics/posts

- addons/better-emojis/userscript.js
**Resolves**
Resolves syntax error created when extraneous bracket was removed. 
**Changes**
I added an extra bracket at the end to close the function.
Fixes a syntax error.
**Tests**
Well, prettier didn't find any syntax errors. It just doesn't like the formatting, but hopefully it's fixed that.
> Add bracket removed when removing extraneous bracket, both of which were causing problems

- addons/60fps/userscript.js
- addons/clones/userscript.js
**Resolves**
Resolves #604
**Changes**
Fixes the bug that scratch changes in every update
So there is no bug
**Tests**
It works.
> Bug Fix - Clone Counter and 60FPS

- addons/exact-count/studio.js
**Resolves**
Resolves #598
**Changes**
Fixes a problem causing the exact count addon to show too large numbers on studios.
#598
**Tests**
Works.
> Fix exact count on studios

- background/get-addon-settings.js
See removed TODO for more info
> Remove dark mode default changer for v1.3.0

- addons/editor-stage-left/addon.json
- addons/editor-theme3/addon.json
- addons/exact-count/addon.json
- addons/exact-count/forum.js
- addons/exact-count/user.js
- addons/last-edit-tooltip/userscript.js
**Changes**
I've stopped errors from occurring if using the `Last edit tooltip` addon when the project is unshared. I've also added a warning to the `Customizable block colors` addon because it uses traps.
Just because
**Tests**
Works on chrome
Edit: I don't know how the first commit got there...
Edit: Resolves: #583
> Addon Fixes

- addons/image-uploader/addon.json
- addons/image-uploader/userscript.js
This feature is not necessary, it's better to use assets
> Do not use project thumbnails for forums image uploader

- addons/live-featured-project/addon.json
- addons/live-featured-project/script.js
This PR resolves issues that are mentioned on #633.
- Destructure addon object on the export function parameters (somehow forgot, but works)
- Remove schema from addon.json
> Live featured project: Post-merge fixes

- addons/full-signature/working.js
Resolves https://github.com/ScratchAddons/ScratchAddons/pull/630#issuecomment-723455625
> Full areas WIBD: only load data if the user clicks "load more"

- addons/resizable-comment-input/addon.json
It deserves to be a theme, in the same way the load more fix was a theme (was it?)
> Make resizable comments a theme

- .github/workflows/update-changelog.yml
This adds a workflow to update the website's changelog page from the `CHANGELOG.md` file on the `changelog` branch (or `master` if merged soon)
> Add changelog update workflow

- manifest.json
This adds -prerelease and bumps the version to 1.4.0.
> It's version bumping time again

- addons/forum-search/addon.json
- addons/forum-search/userscript.css
- addons/forum-search/userscript.js
- addons/scratchr2/forums.css
I'm not sure why the search bar elements doesn't have a margin on them. This PR adds it, along with a border on the top to separate it and changing it so it uses flex.
Keep in mind that this is quite subjective, and comments are appreciated.
> Forum search: Better styling on the search bar

- addons/progress-bar/userscript.js
- addons/progress-bar/userstyle.css
**Resolves**
A few issues with the progress bar
**Changes**
Depending on the language, the bar could be a bit broken:
It looks like this now:
Also fixed some occasional style desyncs
And fixed the asset uploading progress bar
**Tests**
it still works
> progress-bar bug fixes

- addons/infinite-scroll/userscript.css
**Resolves**
Resolves #525
**Changes**
Makes the fixed footer (infinite scrolling addon) show in front of everything else.
> Fix fixed footer showing behind projects

- addons/exact-count/forum.js
**Resolves**
Resolves #731 
**Changes**
Changes the forum exactcount to show *<number> post(s)* instead of just a number.
> Fix forum exactcount showing just a number

- addons/clones/userscript.js
i dont know i haven't tested this but theres no reason it shouldn't work
**Resolves**
Resolves #769 
**Changes**
less than or equal to
people kinda angry about it
**Tests**
no but theres no reason for it to not work
> less than or equal to

- .github/workflows/transifex.yml
This adds a GitHub Actions workflow that is triggered every day, or manually. TX_TOKEN is already uploaded to GitHub. Actual actions are located at: https://github.com/ScratchAddons/l10n-script
> Transifex integration

- addons/scratch-notifier/background.js
> Studio activity url on Scratch Notifier

- CHANGELOG.md
**Changes**
Links added for PRs and issues mentioned
It's more convenient for the devs
> Add links to issues/prs on changelog

- addons-l10n/README.md
> Update l10n README

- addons-l10n/en/animated-thumb.json
- addons-l10n/en/editor-devtools.json
- addons/animated-thumb/userscript.js
- addons/forum-quote-code-beautifier/addon.json
- libraries/CREDITS.md
- libraries/animated-thumb.js
Localizes new addon & new messages on animated-thumb
> Localization fixes

- background/load-addon-manifests.js
> Fix check for missing props

- .github/workflows/codacy-analysis.yml
This installs codacy to check our code, and PRs.
> Use Codacy

- webpages/settings/index.html
**Resolves**
Resolves #869
**Changes**
Add target="_blank" to license link.
To solve issue.
**Tests**
Tested.
> Open licenses in new tab

- addons/dark-www/addon.json
Resolves #837 
inb4 "it says multiple options by different authors available but there's only one" yes I know, but I don't think we should change it for now (unless we make this addon use CSS variables and "stuff")
> Remove Dark WWW from dark-www

- addons/editor-messages/addon.json
**Changes**
Changed "displayes" to "displays"
Because... um... it's not spelled correctly
**Tests**
N/A
> Fix spelling error in description

- addons-l10n/en/editor-devtools.json
- libraries/l10n.js
> Fix typo in l10n

- _locales/en/messages.json
- addons/my-ocular/addon.json
- background/handle-l10n.js
- background/imports/run-persistent-scripts.js
- background/l10n.js
- content-scripts/inject/l10n.js
- webpages/settings/index.html
- Fix cache generation causing English messages to be used
- Localize "Search" on options
- Localize my-ocular
> l10n bugfixes

- addons/dark-www/experimental_scratchwww.css
> Fix project comments unreadable

- popups/scratch-messaging/popup.html
> Fix "Show more messages" button not fully visible

- addons/clones/userscript.js
- addons/mouse-pos/userscript.js
Resolves #809 
Hides mouse-pos and clone counter in small stage mode
> Fix mouse-pos & clones overflowing small stage

- content-scripts/cs.js
> Firefox fix: addons don't work in backgrounded new tabs

- addons/dark-www/addon.json
- addons/scratchr2/addon.json
**Resolves**
Resolves #888
**Changes**
Adds link to JSON
> Add /news to scratchr2

- _locales/en/messages.json
- content-scripts/cs.js
This is the same as BaG's except the message is more generic.
> Warning when posting on Japanese forum

- popups/scratch-messaging/popup.html
- popups/scratch-messaging/popup.js
> Fix scratch-messaging popup link issues

- addons/forum-quote-code-beautifier/addon.json
> Fix forum-quote-code-beautifier tag

- addons/editor-theme3/theme3.js
**Resolves**
Resolves #952 
Resolves #955 
**Changes**
Adds code for handling dropdowns and extension blocks. blocklyDropDownDiv special case for event block was necessary for "when background switched to" block.
> Fix editor-color3 not being applied

- addons/onion-skinning/userscript.js
> (1.5) Fix #1035

- manifest.json
I've done this _sooooo_ many times. Oh, well. 
Do you _really_ need to know?
> Bump to 1.6.0 prerelease

- content-scripts/cs.js
- webpages/settings/index.html
- webpages/settings/index.js
- webpages/settings/style.css
**Changes**
I improved contrast on the update prompt, made the font match how it is on scratch, added light shadow, padding, border-radius.
on the more settings modal, i made it so you can click out of it, and added a little bit of blur to the backdrop
these were a few things that were bugging me
**Tests**
yes, i forced the notification to show and i opened the more settings modal
> changes to more settings, notification

- libraries/autoescaper.js
> Escape quotes

- addons/block-switching/userscript.js
**Resolves**
- Fixes #1138 
- Fixes control_forever -> control_repeat_until to not separate the substack
> block-switching bug fixes

- addons/confirm-actions/addon.json
- addons/confirm-actions/userscript.js
> confirm-actions: Check if it's profile page

- addons/scratch-notifier/background.js
- addons/scratch-notifier/comment-emojis.js
- libraries/autoescaper.js
- popups/scratch-messaging/popup.js
Also fixes a crash caused by hasOwnProperty.
> scratch-notifier: do not emojify project title

- addons/cat-blocks/addon.json
> Add period to description

- popups/cloud-games/popup.css
- popups/scratch-messaging/popup.css
- popups/scratch-messaging/popup.html
- webpages/settings/index.html
- webpages/settings/licenses.html
- webpages/settings/permissions.html
- webpages/settings/style.css
**Resolves**
Resolves #1173
**Changes**
Makes padding values in the popup and the settings page more consistent.
I also made the settings page behave better when zoomed in and made the Scratch Addons logo in the top left corner exactly the same on all pages. I just couldn't stop.
> Consistent padding and minor CSS changes

- addons/editor-devtools/userscript.js
- addons/project-info/blockcount.js
- addons/project-notes-tabs/addon.json
> Fix typo in project-notes-tab

- addons/better-quoter/userscript.js
> Resolves #1185

- addons/better-quoter/userscript.js
- fixes a crash
- fixes scrolling to wrong location
- fixes selection check (half of #1195)
> better-quoter fixes

- addons/60fps/userscript.js
- addons/addons.json
- addons/mute-project/addon.json
- addons/mute-project/userscript.js
> Play project muted

- background/handle-fetch.js
> Fix crash in fetch

- addons/full-signature/addon.json
- addons/full-signature/blocks.css
**Resolves**
fixes #1222
**Changes**
added scrollable scratchblocks
wy not
**Tests**
on Microsoft edge it works
> Scrollable Scratchblocks

- addons/full-signature/addon.json
- addons/full-signature/blocks.css
I'm reverting this PR because
1. I did not have a chance to review it
2. It's for a very specific usecase, I feel a demo is required to understand what it does, even before making a PR
3. I'm trying to avoid sending many strings near release date to translators.
@RedGuy12 Feel free to open another PR against the same code/branch, but please explain what the addon does and link to a demo where it can be tested.
@GrahamSH-LLK Please avoid merging PRs if they add new features or would require translators to retranslate a string.
> Revert #1226

- webpages/settings/style.css
> Fix Warped Icons

- background/handle-messages.js
Dumb mistake, likely on stable as well
> Fix getMsgCount not working in userscripts

- background/handle-fetch.js
Regression caused by #1198 and not properly fixed by #1224
@apple502j Dumb typo lol
> Fix addon.fetch (for real)

- webpages/settings/style.css
This fixes a longstanding tooltip bug that makes the tooltip vertically misaligned with what it's attached to.
> Fix tooltip bug

- webpages/settings/index.html
- webpages/settings/index.js
> Fix error message

- addons/remix-tree-button/addon.json
- addons/remix-tree-button/button.css
- addons/remix-tree-button/main.js
> Remove color setting from Remix Tree addon

- webpages/popup/index.js
**Resolves**
Resolves #
**Changes**
**Tests**
> Fix lint error

- addons/remix-tree-button/addon.json
- addons/remix-tree-button/main.js
Reverts ScratchAddons/ScratchAddons#1266
> Revert "Remove color setting from Remix Tree addon"

- addons/dark-www/experimental_scratchr2.css
- manifest.json
> Fix dark-www affects editor, bump to v1.7.1

- addons/semicolon/semicolon.css
This is the better fix b/c it looks the same on all pages, scratchr2 and www, light and dark modes.
Resolves #1291
> Fix Semicolon Bug

- addons/cat-blocks/addon.json
- addons/cat-blocks/userscript.js
**Resolves**
Resolves #1298
**Changes**
Adds some constants to keep code tidy and no repeated code
renamed some variables for better naming
added eye blinking
added ear scratching
**Tests**
This works fine on all hat blocks... One future problem to look into is the spacing between blocks... other than that it's a complete replica of scratch's 2020 easter egg!
> More cat block functionality

- addons/mediarecorder/userscript.js
> Add audio recording to mediarecorder

- .github/workflows/schema-validation.yml
- Revamp code
- Allow all branches to be checked
- Allow manual dispatch to check all manifests
> Updates on schema validation workflow

- addons/better-quoter/addon.json
- addons/better-quoter/userscript.js
**Resolves**
Resolves #1195
**Changes**
When using the better-quoting addon, quoting now also includes bbcode (other than scratchblocks), and adds me to the credits
They are useful and without it this addon is pretty useless (for me anyway)
**Tests**
Tested on chrome. However, there may be some tags/scenarios that I haven't thought of and therefore cause bugs.
**additional info**
- scratchblocks aren't supported
- it doesn't use innerHTML or outerHTML anymore
- you can still quote across quote, siggie, author info and date. Again, I'm too lazy to fix it.
- pls merge soon because I forgot to make a new branch so I'll have to make another fork again :)
> Better better quoting

- addons/better-quoter/userscript.js
Fixes linter failure and potential xss
> Better better better quoting

- background/l10n.js
- content-scripts/inject/l10n.js
> Break loop early if _general.json is missing

- addons/addons.json
- addons/comments-linebreaks/addon.json
- addons/comments-linebreaks/userscript.js
- addons/hide-flyout/userscript.js
**Resolves**
Resolves #207 
**Changes**
Added the addon.
Another useless-useful addon if you know what I mean
I'm back creating PRs for issues made ages ago :P
Oops! Accidentally pushed my quicc fix to this branch... Oh well... it fixed this anyway:
It's just neat to see line breaks in comments.
**Tests**
It works I guess.
Note: **MOST OF THIS TEXT WAS STOLEN FROM #209! THAT ISSUE DOES NOT HAVE ANY COPYRIGHT SO YOU MAY NOT ACCUSE ME OF STEELING. END OF ARGUMENT.**
> Line breaks in comments + bug fix

- addons/a11y/userscript.js
I didn't mean to put it there anyway.
> Take a11yObjects out of window

- addons/a11y/userscript.js
vm once again for some reason defined twice and some functions need addon APIs
> Another hotfix (was the addon tested?)

- addons/a11y/userscript.js
> Fix last bugs

- addons/hide-flyout/style.css
- addons/hide-flyout/userscript.js
**Resolves**
Resolves https://github.com/ScratchAddons/ScratchAddons/pull/1319#issuecomment-764814331
**Changes**
I used some redux for better detection for switching tabs, seeing project page, going into small screen
Fixed tons of bugs... yeah!
**Tests**
Tested... a lot!
> Smashing bugs - Hide Flyout Addon

- addons/editor-devtools/userscript.js
Related: https://github.com/ScratchAddons/DevtoolsExtension/issues/4
> Editor devtools addon: don't run if new extension is enabled

- addons-l10n/en/show-bbcode.json
- addons/addons.json
- addons/show-bbcode/addon.json
- addons/show-bbcode/userscript.js
**Resolves**
Resolves #1219
**Changes**
Adds a button that shows the BBCode of a post.
> Add Show BBCode addon

- libraries/fast-linkify.js
> Update URL regular expression

- addons/hide-flyout/addon.json
- addons/hide-flyout/userscript.js
**Resolves**
Resolves #1404
**Changes**
New setting option: Hover in category
mxmou wants it and it's not to bad :)
**Tests**
It's epic as always probably ;)
> New mode for "Auto-hide block palette" addon: Hover in category

- addons-l10n/en/search-profile.json
**Resolves**
None
**Changes**
See #1372
> Make invalid username tooltip less scary

- addons/editor-dark-mode/global.css
- addons/editor-devtools/DevTools.js
- addons/editor-devtools/userscript.css
- addons/editor-devtools/userscript.js
**Resolves**
None
**Changes**
See #1372
> Improve devtools UI

- _locales/en/messages.json
Related #892 
Not fixed yet, I want to write a little tool to spin out copy-able text.
> Add extension store description to _locales

- addons/comments-linebreaks/userscript.js
**Resolves**
Resolves #1444
**Changes**
Fixes the asterisks problem and preserves spaces left.
**Tests**
Tested on 2 profiles.
> Fix comments linebreaks spacing issues

- addons/clones/style.css
- addons/clones/userscript.js
> clones: improve performance

- popups/scratch-messaging/popup.css
- popups/scratch-messaging/popup.html
- popups/scratch-messaging/popup.js
- webpages/styles/components/tooltips.css
> Messaging Popup: Usernames of Loves and Faves on tooltip

- addons-l10n/en/mediarecorder.json
- addons/mediarecorder/style.css
- addons/mediarecorder/userscript.js
> mediarecorder: add record mic option

- popups/scratch-messaging/popup.html
Whoops, didn't notice this bc I usually have loves in a project if it has comments hehe
> Hide lovers & favers tooltip if there's no loves or faves

- popups/scratch-messaging/popup.html
lol i keep tinkering with the lovers & favers tooltip
> Scratch Messaging: use v-if instead of v-show to fix CSS issue

- manifest.json
What do you _think_ this is?
<sub><sup>(Rhetorical Question)</sup></sub>
> Bump to prerelease 1.10.0

- addons/editor-stage-left/stageleft.css
**Resolves**
Resolves #1548
**Changes**
Added z-index
**Tests**
Works.
> Left Stage addon: Popup box is partially covered

- addons-l10n/en/_general.json
- addons-l10n/en/animated-thumb.json
- addons/animated-thumb/userscript.js
- background/imports/run-persistent-scripts.js
- content-scripts/inject/run-userscript.js
- libraries/animated-thumb.js
This also adds a way for msg() to get messages from `_general.json`.
> Improve message when thumb server is down

- addons/comments-linebreaks/userscript.js
- addons/editor-devtools/DevTools.js
- addons/hide-flyout/userscript.js
Resolves some of #1444
Found while fixing lint errors.
> Trim empty lines on replies to ST comments

- addons/pause/addon.json
- addons/pause/userscript.js
**Changes**
- remove beta tag
- remove unnecessary console.log
- fix pausing blocks like "wait 10 seconds"
- keep glowing paused scripts (debatable whether this is good or not, I think it is)
- fix pausing some [weird scripts](https://user-images.githubusercontent.com/33787854/107668115-ebdbc280-6c55-11eb-8d8c-5597a5676929.png)
- fix pause not resuming old threads if the user starts a new thread while paused
- "when sprite clicked" and "when key pressed' events should not be fired when paused
- don't fall apart when sa-pause is run when already paused
> Improve pause addon

- addons/addons.json
- addons/load-extensions/addon.json
- addons/load-extensions/userscript.js
> Auto-add Extensions Addon

- addons/mediarecorder/userscript.js
**Changes**
This PR fixes the Start/stop recording button misbehaving when someone enters the editor, starts recording, leaves the editor, and goes back into the editor.
Previously the Stop recording button would become a Start recording button even though the old recording is still ongoing. Now it will still be a Stop recording button.
> Fix mediarecorder misbehaving when leaving the editor during recording

- .github/workflows/unittest.yml
meow is a unittest action, to prevent cat(astrophic) accidents in the future. It currently detects syntax error in translations.
> Add workflow for meow

- webpages/settings/index.js
> Settings page search: match by addon ID

- addons/infinite-scroll/buttonScroll.js
> Infinite scrolling: Wrong profile selector

- addons/image-uploader/addon.json
- addons/image-uploader/userscript.js
> Fix matches for image-uploader 

- addons/dark-www/addon.json
- addons/dark-www/experimental_scratchr2.css
- addons/dark-www/experimental_scratchr2_comments.css
- addons/dark-www/scrollbar.css
Changes from #1143 were removed in v1.7.0. This adds them back.
> Merge 1.6.x branch into master

- webpages/settings/index.html
- webpages/settings/index.js
Resolves #1603 (`event is not defined`)
> Use Vue $event instead of window.event in settings page

- addons/dark-www/experimental_profile.css
- addons/editor-dark-mode/experimental_editor.css
Resolves #1599
EDIT: as of Feb 17 only fixes this:
> Darkmode fixes

- addons/cat-blocks/userscript.js
Resolves #1620
// Todo: Switch completely to Blockly? DOM seems hacky. Anyway 3 cheers again for apple502j for their amazing Blockly getter code.
> Cat Blocks Addon needs spacing between blocks

- addons/editor-devtools/userscript.js
> editor-devtools: update version number and release date (v1.10.0)

- addons/discuss-button/userscript.js
> Discuss button addon: Do not touch the conference pages

- manifest.json
> Bump to v1.11.0 prerelease

- content-scripts/inject/module.js
> Detect new elements with placeholder addon.tab.scratchClass classes

- libraries/fast-linkify.js
> Linkify URLs with percents

- README.md
I did this forever ago and forgot to PR
> Add translation badges

- addons/better-featured-project/addon.json
- addons/cat-blocks/addon.json
- addons/semicolon/addon.json
> Add `"l10n": true` to some addons

- addons/infinite-scroll/buttonScroll.js
- addons/infinite-scroll/userscript.css
- Resolves #749 
- Resolves infinite message scrolling not working if URL is `/messages` instead of `/messages/`
- Cleaner code
- "Fix footer": decrease height, not sure why it had to take so much space
- Add 1px border in top of footer (if fixed)
@mxmou Please review, since I think you originally increased the height of the footer. Also, I'd like to find a good way to make the border I added darker if website dark mode is on.
> Infinite scrolling: fix bugs, improvements

- addons/scratchstats/userscript.js
**Resolves**
Resolves #1679
**Changes**
Removes profile statistics from 404 pages.
> Don't show profile statistics on 404s

- addons/dark-www/scrollbar.css
**Resolves**
Resolves #1745
**Changes**
Changes the website dark mode dark scrollbars so that they don't affect the editor.
> Make dark scrollbars not affect the editor

- addons/dark-www/scrollbar.css
**Changes**
Fixes a bug. How did I not notice this?
> Fix typo in dark-www

- background/get-userscripts.js
- content-scripts/cs.js
- webpages/settings/index.js
> Fix userstyles in list of running addons

- addons/variable-manager/userscript.js
adds a filter to make sure broadcasts don't end up the variable tab
> solve #1763

- addons/onion-skinning/userscript.js
Onion skinning and costume folders now work together properly
> Fix onion skinning and folders compatibility

- addons/folders/userscript.js
> Fix removing sprites with no names from folders

- content-scripts/cs.js
> Set default value for addonsWithUserstyles

- addons/variable-manager/userscript.js
Removes the prompt for feedback for v1.11.1
> Variable manager addon: remove feedback button

- addons/animated-thumb/addon.json
**Resolves**
Step towards fixing #1776
> Rename persistentThumb setting name

- addons/longer-wiwo/userscript.js
@RedGuy12, please learn syntax and test the changes. @WorldLanguages, please check syntax before merging.
> longer-wiwo: fix syntax error

- addons/editor-devtools/DevTools.js
**Resolves**
Resolves #1848 
This can be ported to 1.11.1 with minimum risks.
> editor-devtools: remove Clean Up Blocks

- addons/load-extensions/addon.json
> load-extensions: remove reference to video sensing

- addons/folders/userscript.js
**Changes**
- Do not let users create folders that end with / as it breaks things
- Fix bugs/crashes when dragging costumes and sounds - https://discord.com/channels/751206349614088204/751207339545198682/821174334328406057 and more
> Fix some more bugs in folders addon

- addons/full-signature/addon.json
- addons/full-signature/blocks.css
> scratchblocks scroll

- addons/better-featured-project/addon.json
- addons/better-featured-project/userscript.js
- addons/better-featured-project/userstyle.css
**Resolves**
None
**Changes**
Increases resolution of the profile page banner.
It looks better now.
**Tests**
Before:
Now:
*(I didn't remove Ocular statuses, I just didn't have the addon enabled when I took the screenshot)*
> Make profile page banner less blurry

- addons/mute-project/userscript.js
**Resolves**
Resolves #1891
**Changes**
Fixes bug
Bugs
**Tests**
Untested
> Fix macos ctrl context menus on mute addon

- addons/custom-block-shape/userscript.js
**Resolves**
@apple502j's insistent perfectionism
**Changes**
Destroyed a poor, innocent little semicolon and replaced with a plus
Because @apple502j said so
**Tests**
No negative (or positive) impacts
> Custom block shape semicolon "fix"

- addons/variable-manager/style.css
- addons/variable-manager/userscript.js
**Resolves**
Resolves #1777
**Changes**
Also makes the inputs labels so you can change their names.
**Tests**
Works with variables and lists
> Allow setting variable names in Var Manager Addon

- addons/editor-devtools/userscript.js
> editor-devtools: update version number and release date (v1.12.0)

- addons/better-featured-project/userstyle.css
**Resolves**
Resolves #2008
**Changes**
Add `z-index` to the follow/change featured project button.
> Fix unclickable follow and change featured projects buttons with profile page banner

- content-scripts/cs.js
> Implement user agent modifying

- addons/editor-stepping/userscript.js
**Resolves**
Resolves #1886
also does smarter code to highlight the right blocks.
https://user-images.githubusercontent.com/72760579/112232260-a4f6ca80-8c0e-11eb-8315-3dbbff00fc6e.mp4
https://user-images.githubusercontent.com/72760579/112232261-a4f6ca80-8c0e-11eb-9530-d8bc27c64b15.mp4
> [Highlight currently executing blocks]: Better highlighting

- addons/image-uploader/userscript.js
> Fix image uploader making reply box white in dark mode

- webpages/settings/index.html
**Resolves**
Resolves #2062
**Changes**
**Tests**
> Fix regression

- addons/dark-www/experimental_statistics.css
Try on https://scratch.mit.edu/statistics/
> Add dark mode to statics graphs

- addons/cat-blocks/userscript.js
Before:
After:
Fixes https://github.com/TurboWarp/scratch-gui/issues/105
> Fix cat ears in Firefox and Safari

- addons/60fps/userscript.js
**Resolves**
Resolves #2153
**Changes**
Reduce timeout time from 2500 -> 250
Temp fix, see comments.
**Tests**
sure
> 60FPS - temp fix - reduce timeout time

- addon-api/content-script/Tab.js
- addon-api/content-script/blocks.js
- addons/a11y/userscript.js
- addons/pause/userscript.js
- content-scripts/prototype-handler.js
> For GrahamSH to merge

- addons/scratchr2/studio.css
**Resolves**
Resolves #2130
**Changes**
Fixes the studio scrollbar not working with 2.0 → 3.0 enabled.
> Fix studio scrollbar not working with 2.0 → 3.0

- addons/variable-manager/userscript.js
**Changes**
- Fixes #2029 
- Fixes rename misbehaving when a variable already exists with the new name
> variable-manager: bug fixes

- addons/dark-www/experimental_profile.css
**Resolves**
Resolves #2166
**Changes**
Makes the text white
**Tests**
not tested
> "Become a Scratcher" modal in own profile unreadble with dark-www

- addons/debugger/addon.json
- addons/debugger/style.css
- addons/debugger/userscript.js
**Resolves**
None
**Changes**
Adds error block
Graham Asked me to pr 
**Tests**
Yes
> add error block

- webpages/settings/index.html
- webpages/settings/index.js
Tempfixes #2090 
We should look for a better long term solution for next release
> Temporarily load color pickers only when needed

- addons/editor-stepping/userscript.js
- Improve performance drastically by not calling querySelectorAll 30 times per second
- ~~Fix https://discord.com/channels/751206349614088204/755131743136383107/832279223224762441~~ Already fixed
- Step VM before displaying running scripts, otherwise everything is 1 frame outdated
> editor-stepping: fix bugs and improve performance

- addons/studio-tools/userscript.js
> Fix managers can't use "leave studio" button

- content-scripts/inject/module.js
> Fix opening editor from My Stuff causes a crash

- addons/cat-blocks/userscript.js
Fixes compatibility with editor devtools, colored context menus, highlight executing blocks
> Fix cat blocks compatibility with other addons

- addon-api/content-script/Tab.js
- content-scripts/inject/module.js
This PR implements new waitForElement spec. Please ignore the branch name.
> Implement new waitForElement spec

- _locales/en/messages.json
- content-scripts/cs.js
- content-scripts/inject/module.js
- popups/scratch-messaging/popup.js
> Prevent users from mentioning "scratch addons" in comments

- content-scripts/cs.js
- content-scripts/inject/module.js
I did it. No more mutation observer, no more web browser.
> Use "versions" in user agent modifier

- addons/editor-stage-left/stageleft.css
**Resolves**
None
**Changes**
Fixes rounded corners in the editor-stage-left addon. Tested in both LTR and RTL languages.
> Fix editor-stage-left rounded corners

- addons/editor-dark-mode/addon.json
- addons/editor-dark-mode/experimental_editor.css
**Resolves**
Resolves #2239
**Changes**
* Makes ask prompts and stage monitors not affect the stage
* Renames two settings for clarity
Feedback
> Make editor dark mode not affect the stage

- webpages/popup/index.html
- webpages/popup/index.js
- webpages/popup/style.css
**Resolves**
Resolves #634
**Changes**
Improves the code that handles popup resizing.
> Improve popup size detection

- addons/custom-zoom/userscript.js
**Resolves**
Resolves #2270
**Changes**
Changes formula to one sent by mxmou
Fixes bug
**Tests**
No
> Fix formula

- .github/workflows/format-code.yml
**Resolves**
none
**Changes**
removed "check format"
it's annoying that it says it failed when it actually worked just fine. it spams my emails
**Tests**
i have this action on my own repos and it works
> remove "check format" from format code action

- webpages/settings/index.html
Resolves #2201
**Changes**
Changes code
Because
**Tests**
No
> Close color picker after reclicking input (settings page)

- libraries/CREDITS.md
- libraries/color-picker.js
**Resolves**
Resolves #2086
**Changes**
Upgrades lib
Because @mxmou and I made changes
**Tests**
> Upgrade color-picker-web-component

- webpages/settings/index.js
**Resolves**
Resolves #2177
**Changes**
Changes preset loading to update all settings at once.
> Update all settings at once when loading presets

- addons/scratchstats/userscript.js
> Calculate stepSize

- addons/confirm-actions/userscript.js
> confirm-actions: fix "Confirm joining studios"

- webpages/settings/index.html
temp fix: always open color picker, when it's button, is pressed (which has the color picker in it
> clicking on color picker closes it

- webpages/settings/index.js
Regression by #2258
We probably want to do this in a prettier way after release, but it works for now
> Fix color picker cooldown not working

- addons/60fps/userscript.js
- addons/animated-thumb/userscript.js
- addons/clones/userscript.js
- addons/disable-auto-save/userscript.js
- addons/editor-messages/userscript.js
- addons/gamepad/userscript.js
- addons/hide-flyout/userscript.js
- addons/last-edit-tooltip/userscript.js
- addons/mediarecorder/userscript.js
- addons/mouse-pos/userscript.js
- addons/mute-project/userscript.js
- addons/pause/userscript.js
- addons/project-info/blockcount.js
- addons/project-info/projectstats.js
- addons/variable-manager/userscript.js
- maybe fix race condition on page load (please test)
- fix addons not running in response to language change
This API really needs to be cleaned up to get rid of all this code repetition.
> Fix reduxEvents regressions

- addon-api/content-script/Tab.js
- addons/2d-color-picker/paint-editor.js
- addons/animated-thumb/userscript.js
- addons/clones/userscript.js
- addons/color-picker/paint-editor.js
- addons/copy-message-link/project.js
- addons/disable-auto-save/userscript.js
- addons/discuss-button/userscript.js
- addons/editor-messages/userscript.js
- addons/editor-searchable-dropdowns/userscript.js
- addons/folders/userscript.js
- addons/hide-flyout/userscript.js
- addons/last-edit-tooltip/userscript.js
- addons/onion-skinning/userscript.js
- addons/project-info/blockcount.js
- addons/project-info/projectstats.js
- addons/project-notes-tabs/userscript.js
- addons/variable-manager/userscript.js
- content-scripts/load-redux.js
> Don't run reduxCondition when redux is unavailable

- addons/resizable-comment-input/addon.json
> Run resizable-comment-input in studios_www

- content-scripts/cs.js
Untested, but should work
Important diff is third commit https://github.com/ScratchAddons/ScratchAddons/pull/2486/commits/a9f3eaac32f89fb5bbb2adbe3f4ba29e50e6c0d2 as well as https://github.com/ScratchAddons/ScratchAddons/pull/2486/commits/d921807de93544ff542f2901fac8979b8d632b63
> Support extension policy filter in upcoming scratch-www studios

- .github/ISSUE_TEMPLATE/---bug.md
- .github/ISSUE_TEMPLATE/--feature.md
- .github/ISSUE_TEMPLATE/--new-addon.md
- .github/ISSUE_TEMPLATE/blank.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/dangerfile.js
- .github/labeler.yml
- .github/pull_request_template.md
- .github/workflows/danger.yml
- .github/workflows/format-code.yml
- .github/workflows/labeler.yml
- .github/workflows/schema-validation.yml
- .github/workflows/update-addons-data.yml
- .github/workflows/update-changelog.yml
- README.md
Reverts ScratchAddons/ScratchAddons#2478
This causes CI failure, needs more investigation
> Revert "Multiple meta updates"

- addons/better-emojis/userscript.js
- addons/comments-linebreaks/userscript.js
- addons/copy-message-link/project.js
- addons/infinite-scroll/buttonScroll.js
- addons/more-links/userscript.js
- addons/remix-tree-button/main.js
- addons/true-youtube-links/userscript.js
**Changes**
I missed some addons in #2268
This adds reduxCondition and similar optimizations to:
- comments-linebreaks
- remix-tree-button
- more-links
- infinite-scroll
- copy-message-link
- true-youtube-links
- better-emojis
Has been at least briefly tested
> Add reduxCondition to more addons

- addons/data-category-tweaks-v2/userscript.js
Because https://discord.com/channels/751206349614088204/755131743136383107/844247332361994240
> data-category-tweaks-v2: use real blockly

- addons/msg-count-badge/addon.json
- addons/msg-count-badge/background.js
> Change default msg-count-badge color, make it customizable

- addons/material-forum-editor-buttons/icons.css
**Resolves**
Resolves #2383 
**Changes**
TESTED. This is not spam, I found what was causing emojis to disappear. The rest works fine.
**Tests**
Yes, tested.
> Fix forum emojis disappearing with material-forum-editor-buttons

- addons/gamepad/addon.json
- addons/gamepad/gamepadlib.js
- addons/gamepad/userscript.js
- Full dynamic enable/disable support
- Fix virtual mouse cursor bugs on high DPI/retina displays
- New setting: Hide settings button when no controllers detected (disabled by default)
- Add WASD option to joysticks (still no per-axis configuration)
- Remove beta tag
> gamepad: bug fixes, improvements

- webpages/settings/index.html
- webpages/settings/index.js
- webpages/settings/light.css
- webpages/settings/style.css
- webpages/styles/components/modal.css
> Some light mode changes

- addons/more-links/userscript.js
Upstream merged my PR to bring back scratchr2 linkifying, so this is possible now.
> more-links: support migrated studio descriptions

- _locales/en/messages.json
- content-scripts/cs.js
> Add v1.15.0 update notification

- addons/debugger/addon.json
graham said to PR my name back in bc it got removed *somehow*
Resolves my name being removed
Adds my name
I asked graham why my name got removed and he said to re PR it
N/A
> my name got removed from credits

- addons/dark-www/addon.json
- addons/dark-www/experimental_scratchr2.css
- addons/dark-www/experimental_scratchwww.css
- addons/discuss-button/userscript.js
- addons/scratchr2/addon.json
- addons/scratchr2/lightprimary_scratchwww_compatibility.css
- addons/scratchr2/scratchwww.css
- addons/studio-tools/userstyle.css
Changes to `dark-www` and `scratchr2` to improve compatibility with the new studio page, and to `studio-tools` for compatibility with these addons.
Also makes `discuss-button` work correctly in development versions of `scratch-www`.
> Improve compatibility with new studios

- addons/studio-tools/migrated.js
> studio-tools: remove section when in other tabs

- manifest.json
> Bump to version 1.16.0-prerelease

- addon-api/content-script/Tab.js
> Implement addon.tab.direction

- addons/dark-www/experimental_scratchwww.css
- addons/exact-count/studio.js
- addons/scratchr2/addon.json
- addons/scratchr2/lightprimary_scratchwww_compatibility.css
- addons/scratchr2/scratchwww.css
Changes to `exact-count`, `dark-www` and `scratchr2` for the scratch-www studio page.
> More new studio page compatibility

- addons/blocks2image/userscript.js
- addons/editor-devtools/DevTools.js
- addons/editor-devtools/userscript.js
- addons/mediarecorder/userscript.js
Cherry picked from TurboWarp
You will probably want to make sure that addon.tab.direction is implemented in the DevtoolsExtension at some point as well
> Use addon.tab.direction in addons

- popups/scratch-messaging/popup.css
Resolves #2663
One-line tested change; self-merging
> scratch-messaging: apply min-height instead of height

- webpages/settings/index.html
- webpages/styles/components/modal.css
Fixes unintentional changes made to More settings in #2526 and #2688. Now the modal looks the same as in the screenshot in #1418.
> Fix unintentional changes to More settings in #2526 and #2688

- addons/discuss-button/addon.json
- webpages/settings/components/addon-setting.html
- webpages/settings/components/addon-setting.js
Resolves #2679 
Resolves #2639 
Schema already updated
> Allow string min/max length to be specified by addons

- addons/forum-search/userscript.js
Defense in depth; not actual vulnerability.
> SECURITY: Sanitize HTML returned from ScratchDB

- addons/clones/style.css
- addons/clones/userscript.js
Resolves https://github.com/ScratchAddons/ScratchAddons/issues/2181
Uses the same method as clone count for appending and changing some code.
> Fix clone count not showing when going out of editor

- webpages/styles/components/badges.css
https://github.com/ScratchAddons/ScratchAddons/pull/2688#issuecomment-855434063
> Fix tag tooltips not wrapping

- addons/dark-www/dark-www.css
- addons/dark-www/experimental_scratchwww.css
Same as #1570, but actually works.
To fix a bug.
Tested by forcing a crash in the navigation component.
> Actually fix unreadable crash message

- _locales/en/messages.json
> Use singular "a bug" for string "report *it* here"

- addons/editor-devtools/DevTools.js
> editor-devtools: ignore Ctrl+Shift+F

- addons/feature-unshared/addon.json
- addons/feature-unshared/userscript.js
Resolves #984
Resolves #2734 
My addon is, and has always been pollution-based. Here it is, feature-unshared addon with much shorter code.
(at least better than the original plan, which is `defineProperty writable: false` ing the whole thing. Half worked, half didn't work. Also better than another plan which was racy.)
> feature-unshared: pollute XHR.open

- _locales/en/messages.json
- content-scripts/cs.js
> Add v1.16.0 update notification

- webpages/settings/index.js
> Fix addon search sorting backwards sometimes

- addons/scratch-messaging/background.js
- background/handle-messages.js
- popups/scratch-messaging/popup.js
> Handle various errors from message fetching

- addons/dark-www/addon.json
- addons/editor-dark-mode/addon.json
- addons/resizable-comment-input/addon.json
- addons/scratchr2/addon.json
- addons/scratchstats/addon.json
- addons/show-bbcode/addon.json
- addons/youtube-fullscreen/addon.json
Changes most mentions of my Scratch username in addon credits to link to my Scratch profile
> Addon credits change

- manifest.json
> Bump to Scratch Addons version 1.17.0-prerelease

- addons/my-ocular/reactions.css
- addons/my-ocular/reactions.js
Fixes two minor bugs related to the changes in #2704.
> Fix new reactions UI bugs

- addons/scratch-messaging/background.js
> [v1.16.2] Fix scratch messaging saying "Please login" when comment reply is deleted

- addons/2d-color-picker/paint-editor.js
- addons/block-switching/userscript.js
- addons/clones/userscript.js
- addons/custom-zoom/userscript.js
- addons/editor-devtools/DevTools.js
- addons/editor-devtools/DomHelpers.js
- addons/editor-devtools/userscript.js
- addons/hide-flyout/userscript.js
- addons/mute-project/userscript.js
>  Bring addon changes from TurboWarp

- addons/material-forum-editor-buttons/icons.css
> material-forum-editor-buttons: show posted images

- addons/scratch-messaging/background.js
Resolves #2815 
Tested, self-merging.
> scratch-messaging: use raw href for relative path rewriting

- addons/copy-message-link/profile.js
> copy-messaging-link: add button when the report button gets re-rendered

- addons-l10n/en/studio-tools.json
- addons/studio-tools/migrated.js
Please make sure to run the userscript after merging.
Untested because the API change that backs the manager limit isn't available yet.
> studio-tools: add errors related to manager limit

- addons/my-ocular/reactions.css
- addons/my-ocular/reactions.js
Allows ocular reactions to be navigated to and toggled using the keyboard.
Accessibility
> Make reacting to posts using the keyboard possible

- popups/scratch-messaging/popup.html
- popups/scratch-messaging/popup.js
Resolves #2743
Resolves https://github.com/ScratchAddons/ScratchAddons/issues/799#issuecomment-731756883
Maybe can go into 1.16.2, no strings
> scratch-messaging: make links an actual link

- addons/copy-message-link/profile.js
Reverts ScratchAddons/ScratchAddons#2811
> Revert "copy-messaging-link: add button when the report button gets re-rendered"

- addons/dark-www/addon.json
- addons/dark-www/experimental_remixtree.css
> Fix remix tree dark mode

- addons/debugger/userscript.js
https://github.com/ScratchAddons/ScratchAddons/pull/2804/files/6f0c421f67c23daa31470636cc6a51cc1bbd5464
> debugger: fix things I broke

- popups/scratch-messaging/light.css
very sad
Resolves https://github.com/ScratchAddons/ScratchAddons/pull/2837#issuecomment-864426295
> Fix Scratch Messaging light mode

- manifest.json
> Bump to v1.16.3 stable

- README.md
> [Readme] Fix broken link

- addons-l10n/en/editor-searchable-dropdowns.json
- addons/editor-searchable-dropdowns/userscript.css
- addons/editor-searchable-dropdowns/userscript.js
> Rewrite `editor-searchable-dropdowns` and add new options in dropdowns

- addons/infinite-scroll/buttonScroll.js
Note: this only works after tomorrow's release.
> infinite-scroll: use new class names

- addon-api/popup/Popup.js
- content-scripts/cs.js
Implements a new API that can be used by popups like cloud-games.
> Add Popup.getSelectedTabUrl

- addon-api/content-script/Tab.js
- addons/clones/userscript.js
- addons/debugger/style.css
- addons/debugger/userscript.js
- addons/gamepad/style.css
- addons/gamepad/userscript.js
- addons/mouse-pos/style.css
- addons/mouse-pos/userscript.js
- addons/mute-project/userscript.js
- addons/my-ocular/reactions.js
- addons/pause/userscript.js
- addons/project-info/projectstats.js
- addons/remix-tree-button/main.js
- addons/show-bbcode/userscript.js
- addons/variable-manager/userscript.js
Resolves #2846
- Add API (see docs below)
- Hide debugger in small stage mode
- Support RTL margin in gamepad & debugger buttons
- mouse-pos static width to avoid clone count moving around costantly when moving cursor
Docs: https://scratchaddons.com/docs/reference/addon-api/addon.tab/addon.tab.appendtosharedspace/
> New API: addon.tab.appendToSharedSpace

- popups/scratch-messaging/popup.js
> Fix crash when stMessages is an object due to error

- addon-api/content-script/Tab.js
- addons/studio-tools/migrated.js
Creates shared space, uses it in studio-tools
This space should also be used by #2975 when merged, order 0 is reserved for it
> Create studioCuratorsTab shared space

- addon-api/content-script/Tab.js
- addons/copy-message-link/project.js
- content-scripts/inject/module.js
Also adds a new API solely for this purpose - for now.
> Fix crash when copy-message-link loads sooner than the website

- addons/infinite-scroll/buttonScroll.js
Previously infinite-scroll continued to request and request and request... and you'll end up with hundreds of duplicate entries.
> infinite-scroll: request on rising edge

- addon-api/content-script/ReduxHandler.js
- addons/studio-tools/migrated.js
> Add new API to wait for redux state

- _locales/en/messages.json
- content-scripts/cs.js
Image TODO, merging to get strings into translation
> v1.17 update notification

- .github/workflows/packer.yml
> Revert "Unzip and pack"

- background/get-addon-settings.js
Resolves https://github.com/ScratchAddons/ScratchAddons/pull/2988#issuecomment-878670575
> Enable scratchr2 version of old-studio-layout for addon users

- webpages/settings/components/addon-body.html
- webpages/settings/light.css
Resolves #2948
Changes the colors used for warnings and notices.
> Improve warning and notice colors

- addons/studio-tools/mystuff.js
Resolves #3011
Temporary fix but works.
> studio-tools: use leave-new string

- addons/editor-devtools/DevTools.js
Fixes https://discord.com/channels/751206349614088204/755131743136383107/865230225323458580
> Fix editor-devtools and editor-searchable-dropdowns compatibility

- addons/old-studio-layout/style.css
> old-studio-layout: fix title overflow

- addons/forum-search/userscript.js
> forum-search: stop scratchblocks from rendering again in posts

- addons/editor-searchable-dropdowns/userscript.js
- Fixes broken dropdowns when no menu item is selected (for example, when the selected costume was deleted) https://discord.com/channels/806602307750985799/806602307750985803/867883445517942795
- Fix selecting "Create variable xyz" menu items requiring 2 ctrl+z to be fully undone (now only 1)
> editor-searchable-dropdowns: fix a couple bugs

- addons/editor-devtools/DevTools.js
> Fix devtools search disappearing when changing language

- addons/pause/addon.json
Resolves part of https://github.com/ScratchAddons/ScratchAddons/issues/3015#issuecomment-879933837
Removed notice
@WorldLanguages said it could be removed
works
> Remove unneccesary notice

- addons/editor-dark-mode/bubbles.js
Makes the dark bubbles userscript not crash if the renderer is not available yet.
Not tested yet because I don't know how to make the problem happen consistently.
> Fix dark bubbles crashing when renderer is not available

- addons-l10n/en/editor-devtools.json
- addons/editor-devtools/DevTools.js
Resolves #3103
Added a new confirmation message the unused variable one variables asking to delete unused lists. Also added unused-list translation. 
Do I need to do something to add translations for other languages?
Tested manually, with many used and unused lists, private and public and ensuring it doesn't delete lists with uses.
> Clean up in DevTools remove unused lists.

- webpages/settings/index.html
Seemingly fixes a syntax error
Syntax Highlighting is important
Should **still** work
> Seemingly fix syntax highlighting in settings page

- addons-l10n/en/debugger.json
- addons/debugger/style.css
- addons/debugger/userscript.js
> Add feedback link to debugger

- background/handle-unsupported-version.js
- background/transition.js
- content-scripts/cs.js
- webpages/popup/index.js
- webpages/settings/index.html
- webpages/settings/index.js
Resolves #3123
Localized URLs in farewells, transition and welcome.
Untested as i dont know how to test this sort of thing
> Localized ScratchAddons.com URLs and UTM tags

- content-scripts/cs.js
- content-scripts/inject/module.js
- content-scripts/inject/run-userscript.js
Resolves #597
Add better console log for addons, and make the "big red letter 'debug addon' thingies" ([Quote source](https://canary.discord.com/channels/751206349614088204/819307061493760031/870041209597472808)) less obnoxious.
To solve #597, also make a consistent design for logs.
Chrome stable:
Firefox Developer Edition 91.0:
> Better console

- addons/editor-colored-context-menus/addon.json
Resolves https://github.com/ScratchAddons/ScratchAddons/pull/2799#issuecomment-888571492
> Colored context menus: clearer description

- _locales/en/messages.json
- content-scripts/cs.js
- webpages/settings/index.js
Merging today before 22:00 UTC+0
Video still TODO
New addon order: (hardcoded)
> v1.18 update notification

- addons/forum-search/addon.json
> forum-search: grammatically correct addon description

- addons-l10n/en/studio-tools.json
- addons/studio-tools/mystuff.js
> studio-tools: add back leave string

- webpages/styles/components/filter.css
Fixes select setting overflow being cut off.
> Fix only first row of select setting options being visible in the popup

- background/handle-auth.js
- content-scripts/inject/run-userscript.js
1st and 3rd commit fix `/session` being fired too many times; 2nd fixes dynamicEnable'd addon not getting auth
> Fix some auth issues

- addons/forum-search/userscript.js
Fixes forum-search from not working in signature page
forum-search doesnt work
Tested locally
> forum-search: stop erroring in signature page

- webpages/settings/components/picker-component.html
- webpages/settings/style.css
Resolves #2201
Related to #3036
Makes color pickers look and behave very similarly to reset dropdowns.
> Make color pickers similar to reset dropdowns

- addons/infinite-scroll/buttonScroll.js
Resolves #3169 probably, maybe not. I dont know what this does tbh
> infinite-scroll: fix compat with items-per-row

- addons/better-img-uploads/userscript.js
Fix issue where HD uploads button shows up in sounds tab when using non-English locale
> better-img-uploads: fix button showing up in sounds tab

- addons/better-featured-project/addon.json
Resolves none
Changed credits from Ezlambry to Wicycool for better-featured-project.
Rebranding from Ezlambry to Wicycool
N/A
> Fix credits for Wicycool after rebrand

- addons/turbowarp-player/userscript.js
> turbowarp-player: set label after button click

- background/get-userscripts.js
Resolves #3288 
@mxmou This was probably it...
> Fix addons sometimes not loading

- addons/default-project/addon.json
- addons/default-project/userscript.js
Many users said it was broken, and they were right in the most part, too racy
@apple502j Tell me there's a better way :P
> Run default-project on runAtComplete:false

- addons/addons.json
Reverts ScratchAddons/ScratchAddons#3306
> Revert "Do not load scratchblocks addon"

- addons/hide-delete-button/addon.json
> hide-delete-button: add featured tag

- addons/better-img-uploads/userscript.js
> better-img-uploads: un-hardcode HTML

- _locales/en/messages.json
- addons/debugger/userscript.js
- content-scripts/cs.js
New YouTube video ID coming in a few days
> v1.19 update notification

- addons/scratch-messaging/background.js
- popups/scratch-messaging/popup.css
> scratch-messaging: support multiline comments

- addon-api/content-script/Tab.js
- addons/addons.json
- addons/remix-button/addon.json
- addons/remix-button/userscript.js
Resolves #1816
Adds `remix-button` addon, that allows you to remix your own projects.
Tested locally
> Remix your own projects

- addons/exact-count/forum.js
Stops erroring in console if scratchdb is down
> Dont update post count if number on scratch is higher than scratchdb's count

- addons/variable-manager/userscript.js
Resolves #3419
~~To be tested~~ Tested
> variable-manager: avoid crash if Redux unavailable

- content-scripts/cs.js
Resolves #3361
This part of the code is ugly, but it works for now. We should refactor at some point
> Remove variables from dynamically disabled addons

- addon-api/content-script/Tab.js
- addon-api/content-script/Trap.js
- addon-api/content-script/contextmenu.js
- addons-l10n/en/editor-devtools.json
- addons-l10n/en/move-to-top-bottom.json
- addons/addons.json
- addons/editor-devtools/DevTools.js
- addons/editor-devtools/userscript.js
- addons/folders/userscript.js
- addons/move-to-top-bottom/addon.json
- addons/move-to-top-bottom/userscript.js
- background/get-addon-settings.js
Closes #3406 
Closes #3418 
Resolves #3439 
Also adds new addon "Move costume to top or bottom" (move-to-top-bottom) - a testing addon but this can be kept.
> Implement Tab.createEditorContextMenu

- addons/default-project/userscript.js
this addon's code is terrible but it's beta and i don't have time to make it pretty
Resolves #3441
> Fix default-project replacing file uploads

- addons/studio-tools/migrated.js
> Revert "studio-tools: actually update redux instead of reloading"

- addons/comments-linebreaks/addon.json
- addons/comments-linebreaks/break-spaces.css
- addons/comments-linebreaks/userscript.js
> comments-linebreak: fix style during profile load

- addons-l10n/en/debugger.json
- addons/debugger/style.css
- addons/debugger/userscript.js
Reverts #3099
We had enough feedback already
> Stop asking for feedback on debugger logs window

- webpages/settings/components/category-selector.html
> Fix semicolon instead of comma on settings page CSS

- addon-api/content-script/blocks.js
https://discord.com/channels/751206349614088204/751207339545198682/889660355159134258
It can still slightly impact performance, but not nearly as much as before
> Fix addBlock performance issue

- addons/dark-www/experimental_scratchr2.css
Resolves #3569
Makes the empty trash modal dark.
> Fix empty trash modal dark mode

- addons/editor-colored-context-menus/userscript.css
- addons/editor-colored-context-menus/userscript.js
Fixes https://discord.com/channels/806602307750985799/826250884279173162/892395546323615764 "the colored menus addon doesnt work when a block input is active"
> Rewrite editor-colored-context-menus with getBlockly

- addon-api/content-script/contextmenu.js
- addons/folders/style.css
- addons/folders/userscript.js
> folders: use context menu API

- addons-l10n/en/mediarecorder.json
- addons/mediarecorder/style.css
- addons/mediarecorder/userscript.js
Resolves https://discord.com/channels/806602307750985799/806609030935740477/892989006927773726
Add a delay option to mediarecorder
bc
yes
> Add a delay option to mediarecorder

- webpages/popup/index.html
- webpages/popup/index.js
> Make changelog link in the popup into a `href` link

- addon-api/content-script/Tab.js
- Never show a separator on the top item:
- Minor performance improvement by removing an unnecessary querySelector
> createBlockContextMenu bug fix and optimization

- addons/fix-editor-comments/addon.json
W_L gave permission https://discord.com/channels/751206349614088204/751207339545198682/905929105814458388
> fix-editor-comments: add recommended tag

- addon-api/content-script/Tab.js
- addons-l10n/en/_general.json
- addons-l10n/en/animated-thumb.json
- addons/animated-thumb/addon.json
- addons/animated-thumb/persistent-thumb.js
- addons/animated-thumb/rectangle.svg
- addons/animated-thumb/userscript.css
- addons/animated-thumb/userscript.js
- libraries/common/cs/thumb-setter.js
Resolves #2334
https://user-images.githubusercontent.com/33279053/136035391-02c14822-5740-44c1-9ecb-7b32ef039a40.mp4
> animated-thumb: add modal

- addons/swap-local-global/userscript.js
A couple bug fixes for #3722
- Do not let New Scratchers and signed out users try to make cloud variables
- Do not let people try to make more than 10 cloud variables
> swap-local-global: a couple bug fixes

- addons/columns/addon.json
> Add tags and versionAdded to new "columns" addon

- _locales/en/messages.json
- content-scripts/cs.js
> Add update notification for v1.22

- addons/columns/userscript.js
I didn't test going inside and outside the editor with dynamicEnable and dynamicDisable existing, so this fixes it, but also...
This should probably make things faster and also stop using some yucky VM stuff.
Also I added comments just for you @WorldLanguages
> [columns]: Fix see inside bug

- addons/editor-extra-keys/addon.json
- addons/editor-extra-keys/userscript.js
editor-extra-keys now handles dynamic enable, disable, and settings changes
> editor-extra-keys: support dynamic enable, disable, settings change

- addons/better-emojis/addon.json
> better-emojis: change manifest

- addons/animated-thumb/rectangle.svg
this svg comes from scratch's "add backdrop button"
> cooler svg for animated-thumb button

- manifest.json
> Bump to v1.22.0 stable

- webpages/settings/index.js
> Fix duplicate items in addon search

- addons/search-my-stuff/addon.json
- addons/search-my-stuff/userscript.js
Resolves #3784
Fixes errors when switching pages, etc
> search-my-stuff: fix bugs

- manifest.json
> Bump to v1.22.1 stable

- addons/msg-count-badge/addon.json
I added credits for msg-count-badge
To give me and WL credit
> Add credits for msg-count-badge

- addons/editor-comment-previews/addon.json
Once upon a time, there was a lush, green land with a kingdom named Scratch Addons, ruled by the noble and mighty World_Languages and his wise advisor, Apple, from the comfort of the lavish GitHub Castle. The land was blessed with a rich and mysterious resource, known to mortals as "addons." World_Languages distributed the addons to the people, which brought joy to all the land. Some addons were very fine in quality, bringing greater joy and therefore the most popular choices, and some had lesser importance, bringing lesser joy and therefore often picked over.
One day, it was a bright and sunny day in the kingdom. The birds were chirping, and the air was fresher than ever. The kingdom was in a golden age, with the land plentiful in new and rich addons. The people were happy. The council …
> editor-comment-previews: re-add featured tag

- addons/hi-res-thumbnails/addon.json
> Fix typo in hi-res-thumbnails description

- addons/block-count/blockcount.js
Fixes block count not resetting on project load
> block-count: handle project load

- _locales/en/messages.json
- content-scripts/cs.js
> Add v1.23 update notification

- addons-l10n/en/animated-thumb.json
- addons/animated-thumb/userscript.js
> animated-thumb: remove tooltip

- background/get-addon-settings.js
> Update existing settings that use presets

- manifest.json
whoops i forgot to bump the main version property on #3954
> Bump to v1.23.1 stable

- addons/dark-www/experimental_scratchwww.css
> Fix website dark mode changing text color in editor

- addons/forum-quote-code-beautifier/main.css
See https://github.com/ScratchAddons/ScratchAddons/issues/3946#issuecomment-998325469
> Fix code blocks inside quotes

- addons/my-ocular/discuss.js
Resolves #3814
Creates an object that acts as a cache for the statuses.
> Implement status cache in ocular addon

- addons/editor-theme3/addon.json
- addons/editor-theme3/forums/base.css
- addons/editor-theme3/forums/black_text.css
- addons/editor-theme3/forums/color_on_black.css
- addons/editor-theme3/forums/color_on_white.css
- addons/editor-theme3/forums/colored_text.css
Resolves #3993
[(Testing post)](https://scratch.mit.edu/discuss/post/5335829/)
> Setting to change forum scratchblocks colors

- addons/60fps/userscript.js
> Fix 60FPS losing track of state when changing from project page to editor.

- addons/dark-www/addon.json
- addons/editor-dark-mode/addon.json
- addons/forum-quote-code-beautifier/addon.json
- addons/forum-toolbar/addon.json
- addons/live-featured-project/addon.json
- addons/material-forum-editor-buttons/addon.json
- addons/scratch-notifier/addon.json
- background/load-addon-manifests.js
- webpages/settings/components/addon-body.html
Resolves #2172
Also, moves the Silk credits from forum-toolbar from the description to the addon credits.
> Manifest: new credits.note property, intended to be localized

- addons/editor-devtools/userscript.js
> editor-devtools: dispatch event if addon is enabled and DevtoolsExtension is running

- addons/gamepad/gamepadlib.js
- addons/gamepad/userscript.js
Fixes https://github.com/TurboWarp/scratch-gui/issues/420
> gamepad: Reset controls when new project loaded

- _locales/en/messages.json
Some addons can update without adding new options.
> Change updated message to "New features"

- webpages/settings/components/addon-setting.html
wl thought it would make things slower for some reason :shrug:
> Undo removing `<template>`s from <addon-settings> component

- _locales/en/messages.json
- content-scripts/cs.js
> v1.24 update notification text

- background/get-addon-settings.js
Fixes https://discord.com/channels/751206349614088204/751207339545198682/934590630930292746
> Fix discuss-button migration

- _locales/en/messages.json
- webpages/settings/data/tags.js
- webpages/settings/index.js
> Add new tag for updated addons with new settings

- addons/discuss-button/userscript.js
Resolves #4135
Tested.... merging
> fix scratchr2 erroring

- addons/editor-devtools/DevTools.js
> editor-devtools: allow "stop other scripts in sprite" to stack

- addons/debugger/threads.js
> Fix recursion breaking debugger threads display.

- addons/scratchr2/profile.css
> Fix featured project title overflow

- addons/scratchr2/mystuff.css
- addons/scratchr2/v_tabs.css
Resolves #4158
Resolves #4160
Makes the My Stuff tab list wider, adds padding to the right and increases the indentation of subcategories slightly.
> Fix My Stuff tab problems

- addons/scratch-notifier/notifier.js
> scratch-notifier: do not play ping sound for disabled notifications

- libraries/common/message-cache.js
- popups/scratch-messaging/api.js
- popups/scratch-messaging/popup.html
- popups/scratch-messaging/popup.js
- webpages/popup-loader.js
- webpages/popup/index.html
- More detailed error message to help debug issues
- Remove some raw HTML usage
- Add favicon to popups
> More messaging refactor

- content-scripts/cs.js
> Fix null color handling

- addons/dark-www/experimental_scratchr2.css
- addons/scratchr2/profile.css
> Add class-reporting styles to dark-www and scratchr2

- addons/debugger/module.js
Resolves #4281
Resolves #4210
Tested manually, fixes both bugs and shouldn't mess with other behavior.
> Debugger debugging

- addons/forum-toolbar/userscript.js
Resolves #4301
Fixes a bug in the forum-toolbar addon.
> Fix forum-toolbar not working on change signature page

- addons/custom-zoom/addon.json
Resolves https://discord.com/channels/806602307750985799/945402551094894632/945404083777470524
> Fix minimum being different then what it said it is

- addons/scratchstats/userscript.js
> scratchstats: fix graph rendering issues

- addons/custom-zoom/addon.json
so min can't be more than max
Reverts #4307
> custom-zoom: revert minimum fix, change setting name instead

- addons/discuss-button/userscript.js
> discuss-button: convert to absolute URL

- addons/scratchr2/forums_bubbles.css
Fixes a bug.
https://github.com/ScratchAddons/ScratchAddons/pull/4332#issuecomment-1053660214
> Fix username "weird background" when using bubble post style

- _locales/en/messages.json
- webpages/settings/index.html
- webpages/settings/index.js
- webpages/settings/style.css
- Show "No results found. Perhaps try different keywords?" when there is no search result
- Show "Explore all 130+ addons" when all addons are disabled in popup
> Settings: fix display when there are no results to show

- addons/scratchr2/forums.css
> Add missing moz-fit-content

- background/get-userscripts.js
Resolves #4364
Does not contain any addon changes. Addons that do want to run on these pages need to add the page URL explicitly.
> Exclude 500 and 503 errors from isNotScratchWWW

- _locales/en/messages.json
- content-scripts/cs.js
> Add v1.25 update notification

- webpages/settings/index.html
- webpages/settings/index.js
Related to https://github.com/ScratchAddons/website-v2/pull/151
> Link to scratchaddons.com/credits instead of /contributors

- libraries/common/global-theme.js
- webpages/popup/index.js
- webpages/settings/components/category-selector.html
- webpages/settings/index.html
- webpages/settings/index.js
> Revert "Scratch Avocados (April Fools)"

- addon-api/content-script/Tab.js
- addon-api/content-script/Trap.js
- addons/cat-blocks/userscript.js
- addons/columns/style.css
- addons/columns/userscript.js
- addons/data-category-tweaks-v2/userscript.js
- addons/hide-flyout/userscript.js
- content-scripts/load-redux.js
> Revert "Compatibility with Scratch April Fools (totally-normal-2022)"

- addons/better-featured-project/userstyle.css
- addons/dark-www/scrollbar.css
- addons/scratchr2/profile.css
- addons/scratchr2/scratchr2.css
Resolves #1076
Makes the scrollbars on the profile page usable on Firefox and slightly more 3.0-like.
> Scratch 2.0 → 3.0: profile page scrollbars

- addons/addons.json
- addons/default-costume-editor-color/addon.json
- addons/default-costume-editor-color/userscript.js
It changes the default colors and outlline size used by the paint editor
> New addon: default-costume-editor-color

- addons/forum-search/userscript.js
- addons/scratchr2/forums.css
- addons/scratchr2/forums_bubbles.css
Resolves #4424
Fixes a bug that caused the forum search addon to not work at all, except on topic pages if the scratchblocks addon was enabled. Also fixes a compatibility issue with 2.0 → 3.0.
> Fix forum search

- addons/compact-messages/addon.json
- addons/user-id/addon.json
Fix 2 broken credit links & add the new username instead of the old (invalid) one.
Because no proper credit was given.
No tests.
> Fix broken credits

- _locales/en/messages.json
- webpages/settings/components/modal.html
- webpages/settings/components/modal.js
- webpages/settings/index.html
- webpages/settings/index.js
- webpages/styles/components/modal.css
Moves the implementation of the More Settings modal into a separate component. This doesn't change anything, but it allows other modals to be added, specifically for preset switching.
> Add a modal component

- libraries/common/cs/fast-linkify.js
> Fix linkifyTag doing wrong instanceof check

- _locales/en/messages.json
- content-scripts/cs.js
> Add v1.26 update notification

- libraries/common/cs/l10n.js
Also use ScratchAddons console when available
Supersedes #4559
> Fix l10n log spam when fallback is provided

- webpages/settings/index.html
Resolves #4558 
(Regressed by #4510)
> Fix settings modal showing on load

- webpages/settings/components/addon-body.html
- webpages/settings/components/addon-body.js
- webpages/styles/colors-light.css
- webpages/styles/colors.css
- webpages/styles/components/badges.css
Resolves #4606
Hides updates from previous versions and makes their appearance more similar to normal notices.
> Improve addon update notices

- addons/default-project/default.json
- addons/default-project/userscript.js
Part of project token stuff. Should also act as a minor performance improvement.
> default-project: bundle empty project json

- addons/turbowarp-player/userscript.js
Resolves #4603
See also: https://discord.com/channels/751206349614088204/751207339545198682/981968933819154463
> turbowarp-player: send project token

- addons/addons.json
- addons/editor-buttons-reverse-order/addon.json
- addons/editor-buttons-reverse-order/userstyle.css
Resolves #3937
Updates this PR: #2010
Moves feature that [TheColaber](https://github.com/ScratchAddons/ScratchAddons/pull/2010#issuecomment-821754505) proposed to new addon.
Everything works great - Firefox 95.
Apparently Github closes PR on fast forward, so I need to create second PR (previous #4621)
Also, if anyone has better suggestions to name/description, please suggest!
> New Addon - Fullscreen button on left

- addon-api/content-script/modal.js
- addons-l10n/en/confirm-actions.json
- addons/confirm-actions/addon.json
- addons/confirm-actions/userscript.js
- addons/editor-unshare-button/userscript.js
Resolves #4637
Adds confirm cancelling comments options
firefox developer
> confirm-actions: Confirm cancelling comments

- addons/forum-search/userscript.css
- addons/forum-search/userscript.js
> Fix forum search layout

- addons/columns/style.css
- addons/hide-flyout/style.css
- addons/hide-flyout/userscript.js
Resolves #4736
* Fixes palette area hover mode
* Changing workspace metrics is now consistent
* Improves compatibility with columns and editor-stage-left
> hide-flyout: bug fixes

- addons/hide-flyout/addon.json
- addons/hide-flyout/style.css
- addons/hide-flyout/userscript.js
Adds dynamic enable/disable and setting change to the "auto-hiding block palette" addon.
> hide-flyout: dynamic enable/disable

- addons/cloud-games/addon.json
Resolves https://github.com/ScratchAddons/ScratchAddons/issues/4668#issuecomment-1176941697
> Add info note to cloud-games

- _locales/en/messages.json
- content-scripts/cs.js
> Add v1.27 update notification

- .eslintignore
- .eslintrc.json
Resolves lots of files in root
updates the eslint ignore patterns, move them out of root, add root: true
too many files in root
it works
> Move eslint ignores into .eslintrc

- addons/hide-flyout/style.css
> hide-flyout: fix full screen

- addons/hide-stage/style.css
- addons/hide-stage/userscript.js
https://github.com/ScratchAddons/ScratchAddons/pull/4609#issuecomment-1179601058
> hide-stage: bug fixes

- addons/progress-bar/userscript.js
> Fix progress bar

- addons/hide-flyout/userscript.js
> Fix editor crash in hide-flyout

- addons/ctrl-enter-post/addon.json
- addons/default-project/addon.json
- addons/editor-unshare-button/addon.json
- addons/hide-project-stats/addon.json
- addons/hide-signatures/addon.json
- addons/last-edit-tooltip/addon.json
- addons/redirect-mobile-forums/addon.json
- addons/remix-button/addon.json
- addons/scratchblocks/addon.json
- addons/studio-followers/addon.json
I don't know why I moved to Verixion in the first place,
I'm sorry for making this PR, but I'm probably deleting that account soon, and I don't want users to click on a dead link
> Addon credits: Verixion -> Weredime

- manifest.json
In favor of https://github.com/ScratchAddons/ScratchAddons/issues/4857
Thank you @Coolguy236gg
> Bump version to v1.27.2

- manifest.json
so apparently garbo found out that hiding the stage and then seeing outside keeps the stage hidden. \:P
> Bump version to 1.27.3-prerelease

- addons/editor-dark-mode/paper.js
- addons/onion-skinning/userscript.js
Resolves #4829
Fixes two bugs that would happen when changing the language:
* the costume editor would lose its dark background if dark mode was enabled
* the onion skin settings would disappear
> Fix missing `reduxEvents`

- addons/cloud-games/addon.json
https://github.com/ScratchAddons/ScratchAddons/pull/4516/commits/defe5dd4383e0ab130361217dc0c753a3554989d
https://github.com/ScratchAddons/ScratchAddons/pull/4516#discussion_r922283147
https://scratch.mit.edu/projects/612229554/
> Add MMP Project back to cloud game's presets, fix preset name

- addons/search-profile/addon.json
- addons/search-profile/style.css
- addons/search-profile/userscript.js
Makes the tab added by "search profile" gray instead of red if it isn't available.
Red is scary.
> Change the appearance of profile tab when disabled

- webpages/popup/index.js
Resolves #4809
Saves the current popup tab on reload.
Firefox
> popup: save tab on reload

- addons-l10n/en/gamepad.json
- addons/gamepad/gamepadlib.js
- addons/gamepad/style.css
- addons/gamepad/userscript.js
Resolves https://github.com/ScratchAddons/ScratchAddons/issues/4878
> gamepad: Add reset button and clear button

- addons/exact-count/addon.json
- addons/exact-count/forum.js
- addons/exact-count/studio.js
- addons/exact-count/user.js
dynamicEnable/disable for all three
users.js refactor (it was messy)
> exact-count: refactor users.js and dynamic enable/disable

- libraries/common/global-theme.js
- webpages/popup-loader.js
- webpages/popup/index.html
- webpages/settings/components/addon-body.html
- webpages/settings/components/category-selector.html
- webpages/settings/components/previews/editor-dark-mode.html
- webpages/settings/index.html
- webpages/settings/licenses.html
- webpages/settings/permissions.html
- webpages/settings/style.css
- webpages/styles/colors.css
- webpages/styles/components/buttons.css
plus the toggle thingy, it can stay
Also, re-adds favicon to fix Firefox missing favicons. Also fixed favicon on fullscreen messaging
> Fix issues from the pre-release color PR

- addons/variable-manager/userscript.js
Resolves #4941
Validate cloud variables names
> variable-manager: Validate variable names

- libraries/common/global-theme.js
- webpages/settings/components/addon-setting.html
- webpages/settings/index.html
- webpages/styles/colors.css
Fixes https://github.com/ScratchAddons/ScratchAddons/pull/4930#issuecomment-1200446217 and incorrect icon preload path. Tested on Chromium 103.
> Fix a couple bugs from #4810

- addons/cloud-games/addon.json
- addons/emoji-picker/emojis.js
Resolves #3368
added fullscreen to cloud-games
#4448
none
> add fullscreen for cloud-games

- addons/customize-avatar-border/addon.json
I don't think translation is that much of a problem. If translators are active, they will, and if they aren't, there are far more untranslated strings that changing just one makes little to no difference.
> customize-avatar-border: rename "Outline colour"

- _locales/en/messages.json
- content-scripts/cs.js
> Add 1.28 update notification text

- addons/jump-to-def/addon.json
Consistency with other addon descriptions
> Change `Shift + Click` to `Shift+Click` (consistency)

- addons/studio-followers/modal.css
- addons/studio-followers/userscript.js
Actually close properly when disabled
Don't let text be highlighted, because it looks bad
> studio-followers: fixes

- addons/block-cherry-picking/userscript.js
fixes https://github.com/ScratchAddons/ScratchAddons/issues/5033
> block-cherry-picking: do not cherry pick shadow blocks

- addons/editor-dark-mode/experimental_editor.css
My absolute bad. I hate the current system of how we style when darkmode is enabled tbh.
> Fix dark mode and find-bar... again :/

- addons/cloud-games/addon.json
- addons/msg-count-badge/addon.json
- addons/scratch-messaging/addon.json
- addons/scratch-notifier/addon.json
It resolves nothing, it's just good to know that these are dynamic enable and disable already since they have persistent scripts/popups
> Add dynamic enable and disable to popup addons

- addons/editor-dark-mode/experimental_editor.css
Resolves #5056
Fixes a regression.
> Fix text on primary color

- addons/pick-colors-from-stage/addon.json
Adds featured tag to new addon #5002
> Add featured tag to pick-colors-from-stage

- CONTRIBUTING.md
Resolves #5075
Added step-by-step instructions to show everyone how to finish their PR. (And a few other changes)
To help those who are new to contributing.
Looks fine.
> Add step-by-step instructions for making a PR

- addons/block-palette-icons/addon.json
- addons/full-signature/addon.json
- addons/longer-wiwo/addon.json
Resolves N/A
Changes my links from my old website to my GitHub
those pages have been moved, and they're very outdated anyway
uh...the link works
> Update RedGuy7 credit links

- _locales/en/messages.json
See #5205
This PR is separate because strings close today
> New strings from unmerged PR #5202

- _locales/en/messages.json
- content-scripts/cs.js
Update video is still pending
This PR should be merged today
> Add v1.29 update notification string

- _locales/en/messages.json
- background/load-addon-manifests.js
- webpages/settings/index.html
- webpages/settings/index.js
- webpages/settings/style.css
> New setting: "display addon names in English"

- addons/hide-flyout/addon.json
- addons/hide-flyout/userscript.js
Reverts ScratchAddons/ScratchAddons#5245
> Revert "`hide-flyout` animation speed changes"

- .github/gen-manifest.mjs
> Fix permission removal in genManifest

- manifest.json
> Bump version to 1.29.0 stable

- manifest.json
> Bump version to 1.30.0-prerelease

- popups/scratch-messaging/popup.css
- webpages/settings/components/addon-setting.html
- webpages/settings/index.html
Fixes incorrect RTL styles.
The Arabic translation might be added soon. (#5254)
Tested by adding English to `rtl-list.js`.
> Fix some RTL bugs in webpages

- addons/comments-linebreaks/addon.json
As suggested by @mxmou on https://github.com/ScratchAddons/ScratchAddons/pull/5352#issuecomment-1328186882
> comments-linebreaks: add notice "linebreaks only visible to you"

- addons/curator-link/script.js
Resolves #5374
Fixes a bug where `curator-link` doesn't work when signed out.
Tested on Chromium 108.
> Fix curator-link not working when signed out

- addons/debugger/addon.json
- addons/editor-extra-keys/addon.json
- addons/remove-curved-stage-border/addon.json
I changed my username to Tacodiva, if you would I'd be nice to change my credits in SA too :)
Really wish 7 year old me had picked a more gender-neutral username lmao
> Remove dead (user)name

- addon-api/content-script/Trap.js
- content-scripts/inject/module.js
- content-scripts/prototype-handler.js
- manifest.json
Reverts ScratchAddons/ScratchAddons#5430
See #5517
> Revert "Better vm trapping"

- manifest.json
> Bump version to v1.30.0 stable

- manifest.json
> Bump version to 1.31.0-prerelease

- addons/vol-slider/userscript.js
Resolves #5558
Tested on Firefox 108
> Fix volume slider value

- .github/CONTRIBUTING.md
- README.md
> Fix broken links

- .github/workflows/stale-issues.yml
Resolves error logs from https://github.com/ScratchAddons/ScratchAddons/actions/runs/3897982638
> Fix GitHub action stale-issues

- addons/fullscreen/userscript.js
Reverts ScratchAddons/ScratchAddons#5498
Resolves #5567
> Revert "fullscreen: resize stage canvas"

- addons/fullscreen/userscript.js
Resolves #3815
Same as the previous PR (#5498), except that it checks if the width or height is zero.
> fullscreen: resize stage canvas (attempt 2)

- manifest.json
> Bump version to v1.30.1 stable

- manifest.json
Bumps manifest version correctly
> Bump version to v1.31.0-prerelease

- _locales/en/messages.json
- content-scripts/cs.js
YT thumbnail and video still pending
> Add v1.31 update notification

- addons/copy-reporter/addon.json
> Clarify copy-reporter addon description

- addons/middle-click-popup/addon.json
Continuing the development of the revamped "Insert blocks by name" addon.
> Update middle-click-popup addon manifest

- addons/middle-click-popup/addon.json
> Add isMajor:true to middle-click-popup latestUpdate

- manifest.json
> Bump version to v1.31.0 stable

- addon-api/content-script/Tab.js
- addons/cat-blocks/userscript.js
- addons/columns/style.css
- addons/columns/userscript.js
- addons/data-category-tweaks-v2/userscript.js
- addons/hide-flyout/userscript.js
- content-scripts/load-redux.js
Reverts most of ScratchAddons/ScratchAddons#5848
A single change is kept, as part of the efforts towards #5281: commit https://github.com/ScratchAddons/ScratchAddons/pull/5873/commits/906125c90fd8adb9b327284e2bfa4cffee462109
> Revert most of "Handle Scratch totally-normal mode (April Fools 2023)"

- manifest.json
Release v1.31.2 to fix non-ideal isAprilFools23 check
> Bump version to v1.31.2 stable

- manifest.json
> Bump version to v1.32.0-prerelease

- addons-l10n/en/disable-auto-save.json
Reworded the message that appears on the saving and leaving confirmation popup (when clicking "See Project Page").
To make it clearer that you are saving your changes.
Not tested.
> `disable-auto-save`: Update string

- addons/number-pad/addon.json
Resolves #5906
Updated the description and info message in the `number-pad` addon.
To make it less confusing.
Tested.
> Update `number-pad` description

- addons/color-inputs/addon.json
- addons/hide-flyout/addon.json
- addons/hide-new-variables/addon.json
- addons/pause/addon.json
- addons/pick-colors-from-stage/addon.json
Check `Files changed` for the changes.
These changes are meant to make a few of the addons easier to find, understand, and use.
Should work.
> Edit descriptions/names of 5 addons

- addons-l10n/en/necropost-highlighter.json
Fixes small typo I made 15 minutes ago
> Fix typo in translation file (developer_comment)

- addons/better-featured-project/userstyle.css
Resolves #5950
* Fixes the position of the "About me" placeholder
* Makes icons in "What I've been doing" appear correctly on Firefox
> better-featured-project: CSS fixes

- addons/editor-extra-keys/addon.json
Resolves #5996
This PR took me so many hours of tweaking to perfection but I'm pretty happy with the results.
> Remove beta tag from editor-extra-keys

- manifest.json
> Bump version to 1.33.0-prerelease

- addons/cat-blocks/addon.json
I changed the cat-blocks json file to state that the cat blocks were from 2020-2023, not just 2020
i do not know how to make a pull request
> Added that the cat blocks were from 2020-2023

- addons/discuss-button/r2.js
- addons/discuss-button/www.js
Resolves #6057
Checks for the existing username element before making one
To fix a bug
I tested in Chrome 113 with SA v1.32.0-prerelease
> Fix `discuss-button` duplicating username when changing settings

- manifest.json
Bumps version to v1.32.1 stable (`v1.32.x` branch)
> Bump version to v1.32.1 stable

- addons/debugger/addon.json
Made some minor edits to the names of some settings and the update message in the Debugger addon.
Tested.
> Rename some settings in Debugger addon

- _locales/en/messages.json
- content-scripts/cs.js
> Add v1.33.0 update notification

- addon-api/content-script/Tab.js
- content-scripts/inject/module.js
- content-scripts/inject/run-userscript.js
Resolves #6136
Resolves #6153
Fixes multiple very stupid mistakes.
> Fix `addon.tab.scratchClass` bugs after refactor

- background/handle-fetch.js
Resolves #6167
- Use `initiatorDomains` instead of `domains` in Firefox. We can also do this in Chrome if we decide to support only Chrome 101 and newer.
- Use `new URL(chrome.runtime.getURL("")).host` instead of `chrome.runtime.id` for Firefox support. Firefox considers `griffpatch@griffpatch.co.uk` to be the extension ID, and all we care about here is the hostname when looking at the URL of our background page. 
Everything appears to work fine in both Chrome and Firefox after this change: posting comments from Scratch Messaging, deleting comments, etc.
Be careful when testing: browsers may use old rulesets if there was an error while adding new ones. Run `chrome.declarativeNetRequest.updateDynamicRules({removeRuleIds: [1]})` to be sure.
> Properly support declarativeNetRequest in Firefox

- addon-api/content-script/Tab.js
- background/get-userscripts.js
- content-scripts/inject/module.js
- content-scripts/prototype-handler.js
- manifest.json
Reverts ScratchAddons/ScratchAddons#6053
Resolves #6084
> Revert "Run addons on `scratchfoundation.github.io` for testing"

- manifest.json
> Bump version to 1.33.0 stable

- addons/op-badge/forums.js
Resolves #6213
Adds an additional pair of brackets (and also uses location.pathname instead of splitting the location.href because that's also error prone).
To fix a bug.
> Fix op-badge not getting the actual OP in forums

- manifest.json
> Bump version to 1.33.1 stable

- manifest.json
> Bump version to 1.33.2-prerelease

- manifest.json
> Bump version to v1.33.2 stable

- manifest.json
> Bump version to 1.33.3-prerelease

- addons/debugger/userscript.js
- addons/editor-dark-mode/addon.json
- addons/editor-dark-mode/experimental_editor.css
- addons/editor-theme3/theme3.js
- addons/gamepad/userscript.js
- addons/hide-stage/style.css
- addons/hide-stage/userscript.js
- addons/onion-skinning/style.css
- addons/paint-snap/userstyle.css
Removes code that became unnecessary after the Scratch update.
> Remove outdated code

- addons/tutorials-button/userstyle.css
> tutorials-button: fix compat with block-count

- manifest.json
> Bump version to 1.33.3 stable

- manifest.json
> Bump version to 1.34.0-prerelease

- content-scripts/cs.js
- webpages/settings/index.js
Reverts part of #6256 and part of #6257
> Revert v1.33.x exclusive changes

- addons/dark-www/experimental_forums_preview.js
> dark-www: fix forum preview link color

- addons/hide-stage/userscript.js
Resolves #6380
Removes the hide stage button from the DOM instead of just hiding it when the addon is disabled. The small stage button becomes the `:first-child`, so Scratch's CSS makes it rounded.
> hide-stage: fix square corners when dynamically disabled

- addons/better-img-uploads/userscript.js
Fixes regression in #6242 (not released yet).
> better-img-uploads: handle capitalized file extension

- addon-api/content-script/Tab.js
- background/get-userscripts.js
- content-scripts/inject/module.js
- content-scripts/prototype-handler.js
- manifest.json
Resolves (the technical aspect of) #5281
Most changes aren't new and they were part of #6053
Since #6205 was merged, we can keep all of these changes on the codebase. The `manifest.json` changes will not be released to extension store users.
> Run addons locally on scratch-gui & `scratchfoundation.github.io`

- _locales/en/messages.json
- content-scripts/cs.js
We might still merge more PRs, but I think we can all agree that these 2 new addons deserve to be mentioned
Screenshot:
> Add v1.34.0 update notification

- manifest.json
Will merge all other PRs in the milestone first
> Bump version to v1.34.0 stable

- manifest.json
> Bump version to v1.34.1-prerelease

- manifest.json
Waiting for #6569 to be merged first.
> Bump version to v1.34.1 stable

- manifest.json
> Bump version to 1.35.0-prerelease

- addons-l10n/en/search-profile.json
- addons/search-profile/addon.json
- addons/search-profile/style.css
- addons/search-profile/userscript.js
responds to this pull request #6254
Added a new setting in the Username search addon that allows the user to show icon of searched user.
This modification enhance the user experience by providing better visual recognition of searched users. This enables users to navigate more efficiently.
Google Chrome	114.0.5735.198
Microsoft Edge	114.0.1823.58
> "Username search" addon: show profile picture of searched user

- addons/editor-dark-mode/paint_icons.js
Fixes the bug described in https://github.com/ScratchAddons/ScratchAddons/pull/6337#issuecomment-1637120905.
Tested in Edge and Firefox.
> editor-dark-mode: fix incorrect icons in paint editor

- addons/preview-project-description/userscript.js
Adds missing dynamicDisable support to new addon added recently by PR #6489
> preview-project-description: Support dynamicDisable properly

- addons/custom-block-text/addon.json
- addons/mediarecorder/addon.json
> Highlight mediarecorder update and feature new text-size setting

- _locales/en/messages.json
- content-scripts/cs.js
> Add v1.35 update notification

- addons/project-notes-tabs/userscript.js
Resolves portions of #6698
Resolves #6714
> Fix bugs in project-notes-tabs

- addons/editor-number-arrow-keys/addon.json
- addons/editor-number-arrow-keys/userscript.js
- background/get-addon-settings.js
- webpages/settings/components/addon-setting.html
See also ScratchAddons/manifest-schema#65
Please, at least use `untranslated`...
> Add and use decimal setting type

- manifest.json
> Bump version to 1.35.0 stable

- addons/editor-number-arrow-keys/addon.json
- addons/editor-number-arrow-keys/userscript.js
- background/get-addon-settings.js
- webpages/settings/components/addon-setting.html
Reverts ScratchAddons/ScratchAddons#6744
> Revert "Add and use decimal setting type"

- manifest.json
> Bump version to 1.35.0 stable release

- addons/my-ocular/addon.json
- addons/my-ocular/status-dot-forums.css
- Resolves bug I just found (see comment https://github.com/ScratchAddons/ScratchAddons/pull/5089/files#r1361312540)
- Resolves regression #6773
- In forum topics, 100% of the JS/CSS is identical to v1.34.1
Scripts/styles in profiles stay untouched.
- Fixes an incorrect setting.if
> Fix my-ocular regression in forum posts

- addons/dark-www/experimental_scratchwww.css
- addons/search-profile/style.css
- addons/search-profile/userscript.js
Resolves #6772
A class name gets added to the image once the profile picture loaded
> Fix white profile picture (search-profile & dark-www)

- manifest.json
> Bump version to 1.35.1 stable

- addons/better-img-uploads/addon.json
It's a minor string update
Changed setting from stage to canvas cuz yes
its the canvas not the stage
if this breaks anything I will eat my hat
> better-img-uploads: clarify setting names

- addons/custom-block-text/addon.json
Tiny grammar fix to make it sound more fluent.
Fluency
> Adjust "custom block text style" addon description

- addon-api/content-script/Tab.js
- addons/editor-number-arrow-keys/userscript.js
- addons/find-bar/userscript.js
- background/get-addon-settings.js
- libraries/common/cs/text-color.js
- popups/scratch-messaging/popup.js
- webpages/settings/components/addon-body.js
- webpages/settings/index.js
It looks like Prettier has made some changes again and is formatting some things that were fine before. I just opened this pull request so those changes can happen.
I recommend all contributors merge `upstream/master` into their branches once this pull request has been merged to avoid headaches.
> Format code

- background/get-addon-settings.js
Adds comments in a couple of places in `get-addon-settings`.
This script is a little difficult to understand due to mostly but not entirely comprising of migration logic.
N/A
> Add code comments to certain addon-setting procedures

- _locales/en/messages.json
- content-scripts/cs.js
> Add 1.36 update notification

- addons/middle-click-popup/WorkspaceQuerier.js
Before, when a query hit a hard-coded limit of too many results, it would immediately stop looking for any other possible results. This is a problem when we have yet to search for the "best" result, as stopping means that that result wouldn't show. Now, when the limit is hit it instead only stops searching for blocks inside of blocks but continues searching all the "simple" blocks.
This is a strange one, because it's very difficult to reproduce this in SA alone. It is, however, causing problems in TurboWarp where extensions can create a large number of blocks. In this screenshot the "and" block should show up first it doesn't show up at all. This is because the "More Events" TurboWarp extension is creating a large number of blocks like "broadcast () and ...." and the algorithm bails …
> "Insert blocks by name": smarter algorithm to handle lots of results (middle-click-popup)

- addons/forum-time-zones/addon.json
- addons/image-uploader/addon.json
Not the ideal solution, but works for now
> Add beta tag to deprecated/broken forum addons

- manifest.json
> Bump version to 1.36.0 stable

- manifest.json
> Bump version to 1.37.0-prerelease

- addons/progress-bar/userstyle.css
Fixes https://github.com/ScratchAddons/ScratchAddons/issues/7166
> progress-bar: make bar at top of screen non-interactive

- addons/dark-www/experimental_forums_preview.js
Resolves #7114
Makes the forum post preview dark even if it's removed (by alt-clicking the preview icon) and shown again.
> dark-www: change post preview consistently

- _locales/en/messages.json
- content-scripts/cs.js
> Update notification for v1.37

- addons/cat-blocks/userscript.js
- addons/columns/style.css
- addons/columns/userscript.js
- addons/data-category-tweaks-v2/userscript.js
- addons/hide-flyout/april-fools.js
- addons/hide-flyout/userscript.js
> Disable some addons for April Fools

- manifest.json
> Bump version to 1.37.0 stable

- libraries/common/global-theme.js
- webpages/popup/index.js
Reverts ScratchAddons/ScratchAddons#7299
> Revert "April Fools 2024 easter egg: Scratch Haddocks"

- manifest.json
> Bump version to v1.37.1 stable

- manifest.json
> Bump version to 1.38.0-prerelease

- .github/gen-manifest.mjs
> Fix bug in gen-manifest.mjs action workflow

- manifest.json
Bumps version
See https://github.com/ScratchAddons/ScratchAddons/issues/6876#issuecomment-2106002109
> Bump version to 1.38.0 stable

- manifest.json
> Bump version to 1.38.1-prerelease

- manifest.json
Bumps version
Rough changelog: faster userstyle injection (#7417) and Firefox for Android fix
> Bump version to 1.38.1 stable

- manifest.json
> Bump version to 1.38.2

- manifest.json
> Bump version to 1.39.0-prerelease

- addons/search-my-stuff/addon.json
- addons/search-sprites/addon.json
> Rename "search" addons for consistency

- addons/delete-others/addon.json
Based off:
https://github.com/ScratchAddons/ScratchAddons/blob/d0daf6be4c3018695036655fbf6fab11b14d362c/addons/move-to-top-bottom/addon.json#L2-L3
and the feedback left from a transifex reviewer: https://github.com/ScratchAddons/ScratchAddons/pull/7030/files#r1639627849
> Change `delete-others` addon name + description

- addons/forum-search/addon.json
- addons/scratchstats/addon.json
Resolves https://discord.com/channels/806602307750985799/1253390754483535945
(it doesn't actually resolve it, it makes it a known issue)
Add a warning, like in `image-uploader`, to tell users that Forum search and ScratchStats might not work. Also add the *Beta* tag to both addons.
https://scratchdb.lefty.one
> Warn users that `forum-search` and `scratchstats` might not work

- addons/find-bar/userscript.js
Resolves #3534
Adds something very similar to the "terrible bug fix" suggested by W_L in the linked issue.
> find-bar: fix Ctrl+Z

- addons/columns/userscript.js
Resolves #4727
Fixes a bug that caused the flyout scrollbar to behave incorrectly when columns was enabled.
> columns: fix scrollbar

- background/get-addon-settings.js
> Add setting transition code for new workspace-dots addon

- addons/faster-project-loading/module.js
- addons/faster-project-loading/userscript.js
- addons/progress-bar/userscript.js
See https://github.com/ScratchAddons/ScratchAddons/issues/6665#issuecomment-1947595991 for the problems these changes solve and the idea behind fixing them.
Tested manually, fixes the issues with and without faster-project-loading enabled, and works as normal on things unaffected but the bug.
> Improve progress-bar compatibility with faster-project-loading

- addons/exact-count/addon.json
https://github.com/ScratchAddons/ScratchAddons/pull/7617#issuecomment-2207005464
> Add notice to `exact-count` about removed setting

- addons/editor-theme3/addon.json
- Remove credits to unreachable developer.
- Add info note clarifying what an "insertion marker" is.
> Changes to `editor-theme3/addon.json`

- addon-api/common/FetchableAuth.js
- addons/exact-count/user.js
- addons/forum-post-countdown/userscript.js
- background/handle-auth.js
- background/message-cache.js
- content-scripts/inject/module.js
- content-scripts/prototype-handler.js
- webpages/popup-loader.js
> Commits from `v1.38.x` branch (multiple opts to send less requests)

- addons/collapse-footer/addon.json
- addons/vol-slider/addon.json
Link to GitHub instead of Scratch.
> Update Samq64 addon credit links

- addons/delete-others/addon.json
Resolves comment https://github.com/ScratchAddons/ScratchAddons/pull/7030#discussion_r1721002842
> `delete-others`: featured tag instead of recommended

- _locales/en/messages.json
- content-scripts/cs.js
> Add update notification for v1.39

- manifest.json
> Bump version to 1.39.0 stable

- addons/exact-count/addon.json
> Remove forums tag from exact-count

- manifest.json
> Bump version to 1.39.1 stable

- manifest.json
> Bump version to 1.40.0-prerelease

- addons/blocks2image/userscript.js
- addons/custom-block-text/userscript.js
Resolves #7804
Makes `blocks2image` and `custom-block-text` compatible with each other.
> blocks2image and custom-block-text compatibility

- README.md
Adds the user count to the readme
> `README.md`: add user count

- webpages/popup/index.js
- webpages/popup/style.css
Resolves #7842
Addons is the default tab, so it makes sense to make it the first one. The visual changes make the tabs more similar to the settings page categories. Another reason to change the design is that users will be less likely not to notice that the order is different.
> Change the order and appearance of popup tabs

- addon-api/content-script/Tab.js
Resolves #6452
Tested on Chromium on the website and localhost.
> addon.tab.editorMode: Use Redux on /projects/editor/

- addons/folders/userscript.js
Resolves https://github.com/ScratchAddons/ScratchAddons/issues/7911
> folders: fix compatibility with sprite delete confirmation

- addons/editor-number-arrow-keys/userscript.js
Updates "arrow key incrementation" to work with the new version of Blockly.
> editor-number-arrow-keys: new Blockly

- .github/gen-manifest.mjs
- background/background.js
- background/firefox-localhost-support.js
- content-scripts/cs.js
- manifest.json
https://github.com/ScratchAddons/ScratchAddons/pull/7939#issuecomment-2495537972
> Revert "Remove firefox-localhost-support.js (#7939)"

- .github/workflows/format-code.yml
- addon-api/content-script/blocks.js
- addons/editor-stepping/highlighter.js
- addons/editor-theme3/theme3.js
- addons/find-bar/userscript.js
- addons/middle-click-popup/userscript.js
#7134 changed the version of Prettier used by the GitHub action, but only in one of the two places where it's specified.
> Use the same Prettier version in PRs and on master

- addons/data-category-tweaks-v2/userscript.js
Updates data category tweaks to support new Blockly.
> data-category-tweaks-v2: new Blockly

- _locales/en/messages.json
- content-scripts/cs.js
(Technically the mp4 update was 1.39.2 but I think it still deserves attention)
> 1.40 update notification

- manifest.json
> Bump version to 1.40.0 stable

- manifest.json
> Bump version to 1.41.0-prerelease

- webpages/settings/index.js
Forgot to remove this for v1.40
> Remove v1.39 code from settings page

- addons/workspace-dots/userscript.js
Updates "customizable workspace grid" to make it compatible with modern Blockly.
> workspace-dots: new Blockly

- addons/block-cherry-picking/addon.json
> Add one setting description for testing

- background/load-addon-manifests.js
See #8062 and https://github.com/ScratchAddons/l10n-script/pull/16.
Untested
> Use translated setting descriptions

- _locales/en/messages.json
- content-scripts/cs.js
Quite redundant, not gonna lie
> Add 1.41 update notification

- manifest.json
> Bump version to 1.41.0 stable

- manifest.json
> Bump version to 1.42.0-prerelease

- addons/hide-new-variables/userscript.js
Updates hide-new-variables to make it compatible with modern Blockly.
> hide-new-variables: new Blockly

- addons/folders/userscript.js
Resolves #8184
Fixes a bug caused by the React 18 PR.
> folders: fix regression

- manifest.json
> Bump version to 1.42.0 stable

- manifest.json
> Bump version to 1.43.0-prerelease

- addons/dark-www/experimental_scratchwww.css
- addons/scratch3to2/main.css
> Support feedback and Terms of Use popups

- addons-l10n/en/forum-post-countdown.json
- addons/editor-theme3/theme3.js
- addons/forum-post-countdown/addon.json
- addons/forum-post-countdown/userscript.js
Resolves #6926
Resolves #7269 
1. Make the addon check for the "reply saved" message instead of clicking the post button (#6926)
2. Add a checkbox that automatically posts when the countdown is done
3. Add a setting for the addon that, when getting the 60-second (or 120-second) warning, it automatically checks the checkbox mentioned above.
The addon does not currently work great, and these changes make it much better.
Tested on Firefox, Windows 11. No gotchas or other issues that I found.
I still need to figure out the localization thing, but someone on here might be able to help with that. Also suggestions are welcome for a better, shorter name for the setting it adds.
Thanks for reading!
> Improvements to `forum-post-countdown`

- addons/editor-devtools/DevTools.js
- addons/editor-devtools/DomHelpers.js
- libraries/common/cs/UndoGroup.js
Updates "developer tools" to work with modern Blockly.
> editor-devtools: new Blockly

- addons/forum-post-countdown/addon.json
See https://github.com/ScratchAddons/ScratchAddons/pull/8199#discussion_r2049678061
> Change default of recently added forum-post-countdown setting

- addons/last-edit-tooltip/addon.json
#7986 set it to 1.42 instead of 1.43.
> last-edit-tooltip: Fix latestUpdate

- addons/vol-slider/hover.css
> Fix volume slider overlapping fps

- addons/dark-www/addon.json
- addons/dark-www/experimental_scratchwww.css
- addons/old-studio-layout/scratch3to2.css
- addons/old-studio-layout/style.css
- addons/scratch3to2/studio.css
> dark-www: style studio page's loading state

- addons/my-ocular/reactions.js
> my-ocular: fix reaction popup not being centered

- addons/default-project/userscript.js
Resolves #8304
Updates the "customizable default project" addon, which was broken by a recent Scratch update.
> default-project: update setProjectToken call

- addons/editor-cleanup-plus/userscript.js
- libraries/common/cs/devtools-utils.js
Updates "enhanced clean up tool" to work with modern Blockly.
> editor-cleanup-plus: new Blockly

- addons/custom-zoom/userscript.js
> custom-zoom: Fix initial zoom

- addons/animated-thumb/userscript.css
- addons/animated-thumb/userscript.js
- Shows the upload error messages that were already in the code but weren't displayed
- Dims the buttons while loading and adds a spinner to the clicked one
- Adds a border to the thumbnail
It makes it easier to understand what's going on.
When there is no internet connection:
Tested on Brave.
> animated-thumb: Better status indicators

- addons/custom-menu-bar/username.css
- addons/custom-menu-bar/username.js
- addons/discuss-button/compact-nav.css
- addons/discuss-button/www.js
Resolves #8067
- Renamed `custom-menu-bar`'s class to prevent collisions
- Set the username's `line-height` to 0 on the website
- Fixed the username from disappearing when re-opening the project page
- Use a more specific menu item selector even though it's not really necessary
> Compact user dropdown adjustments

- addons/custom-block-text/userscript.js
- libraries/common/cs/update-all-blocks.js
Updates "customizable block text style" to work with modern Blockly.
> custom-block-text: new Blockly

- addons/discuss-button/www.js
Resolves https://github.com/ScratchAddons/ScratchAddons/pull/8346#discussion_r2214358222
> discuss-button: Add redux condition for compact user dropdown

- addons/blocks2image/userscript.js
- addons/cat-blocks/userscript.js
<p><img width="305" height="576" alt="image" src="https://github.com/user-attachments/assets/00cc74ac-cb70-4dfe-9f2f-2ebb068ad70e" /></p>
Also includes a tiny improvement to blocks2image's code.
> cat-blocks: new Blockly

- addons/full-signature/addon.json
- addons/infinite-scroll/addon.json
Corrects `full-signature`'s `latestUpdate` version and adds a two-way relation with `infinite-scroll`.
> Add relation between infinite scrolling and full areas

- addons/better-img-uploads/userscript.js
- addons/hide-delete-button/costumes.css
- addons/hide-delete-button/sounds.css
Fixes some CSS selectors after Scratch's face sensing extension update.
Tested on Chromium
> Fix better-img-uploads and hide-delete-button CSS selectors

- manifest.json
> Bump version to 1.44.0 stable
