.github/workflows/format-code.yml

I think it is better to use prettier's built-in checker.

ci: Use prettier's built-in checker instead of git diff

---

background/get-userscripts.js

**Resolves**
Resolves #24
**Changes**
Adds an implicit hash to the URL path, so that, for example, `https://scratch.mit.edu/users/kaj` matches `https://scratch.mit.edu/users/*/`.
Now, only the URL origin and paths are checked. We don't allow matches for other parts of the URL.
**Tests**
Latest Chromium

Fix url matches

---

manifest.json

**Changes**
The options page can now be accessed by right clicking the extension icon and clicking "options".
**Tests**
Latest Chromium

Add options page to manifest

---

addon-api/background/Addon.js
addon-api/background/Badge.js
addon-api/common/Settings.js
addon-api/content-script/Addon.js
addon-api/content-script/Tab.js
addons/addons.json
addons/discuss-button/addon.json
addons/discuss-button/userscript.js
addons/msg-count-badge/addon.json
addons/msg-count-badge/background.js
addons/scratch-notifier/addon.json
addons/scratch-notifier/background.js
addons/scratch-notifier/background2.js
background/background.html
background/declare-scratchaddons-object.js
background/get-background-scripts.js
background/get-userscripts.js
background/handle-addon-settings.js
background/handle-fetch.js
background/handle-local-state.js
background/handle-settings-page.js
background/load-addon-manifests.js
content-scripts/inject/module.js
libraries/Sora.css
libraries/vue.js
manifest.json
webpages/settings/index.html
webpages/settings/index.js

**Resolves**
Resolves #22
Resolves #11
**Changes**
- Splits Scratch Notifier into 2 addon, to avoid the complexity of `child_boolean` and settings that require permissions. Now, permissions are linked directly to an addon.
- Adds discuss button addon, with an option to remove the "ideas" button as well.
- Implements `addon.settings` API and saving settings in `chrome.storage.sync`.
- Implements enabling and disabling addons.
- Loaded vue into the settings page, now it dynamically loads the addon names. There's lots of work to do there tho.
- Moved the Google Fonts stylesheet to libraries, because Chrome classifies third party CSS as RCE...

Implement settings, enabling/disabling, dynamic settings page, addon.tab API, new addon

---

manifest.json

**Resolves**
`chrome.storage.sync` did not fully work because there was no specified ID.
**Changes**
Specify ID `firefox@scratchaddons` in the manifest.

Add extension ID for Firefox

---

addons/scratch-notifier/addon.json
addons/scratch-notifier/background.js
addons/scratch-notifier/userscript.js

- Resolves #62
- Removed useless userscript
- Remove useless use of `global`
- Automatically remove `close` events to avoid memory leaks
- Rename `newMessage` function for clarity
- Change addon description

Scratch Notifier addon

---

addon-api/common/Settings.js

**Resolves**
Resolves #63
**Changes**
Now throws instead of returning `undefined`.
It also throws this error if the addon has no options object in the manifest.

Throw if setting ID doesn't exist (addon.settings.get)

---

addon-api/content-script/Tab.js

**Resolves**
Resolves #96
**Changes**
Adds addon.tab.waitForElement
This function allows addons to wait for elements to appear in the DOM. For example, `await addon.tab.waitForElement("#navigation span.message-count")` will wait for the message-count element to load. If the element already exists, it will resolve instantly.
**Tests**
I haven't tested it with the rest of the extention, but it works on it's own.

Add addon.tab.waitForElement

---

background/declare-scratchaddons-object.js
background/get-background-scripts.js
background/get-userscripts.js
background/handle-addon-settings.js
background/handle-local-state.js
background/handle-settings-page.js
background/load-addon-manifests.js
webpages/settings/index.html
webpages/settings/index.js
webpages/settings/list.svg
webpages/settings/style.css

You can now:
- Enable and disable addons
- Change addon settings (for now, only boolean and positive_integer)
- Filter addons by category and tags
- Search addons by typing keywords found in title/description
Other changes:
- Standardized the way `_target` works between global state and local state.
- Changed `scratchAddons.manifest` to be an array of objects, with keys `"id"` and  `"manifest"`.

Functional settings page

---

addons/addons.json
addons/editor-colored-context-menus/addon.json
addons/editor-colored-context-menus/userscript.css
addons/editor-colored-context-menus/userscript.js

**Resolves**
Part of #70
**Changes**
Adds an addon that makes the color of context menus in the editor match the block that was clicked:
It looks cool and Scratch 2 did it. That's about the only reason.
**Tests**
It works in Chrome and Firefox.
It might break if the addon runs before the body is setup but I'm not sure if that's possible in this extension.

Add colored context menus addon

---

background/declare-scratchaddons-object.js
background/handle-auth.js

Resolves #134 
- Cleaned up `handle-auth.js`
- Fixes bug
- Now, a change in `scratchLang` won't trigger a `"change"` event on `addon.auth`.

Fix addon.auth.scratchLang being null while logged out #134

---

addons/addons.json
addons/true-youtube-links/addon.json
addons/true-youtube-links/userscript.js

The extension replaces every https://scratch.mit.edu/discuss/youtube/ link with a youtu.be link.
I think that it's okay that it's enabled by default since it is more or less a fix.
I guess seeing Rick's face in a YT tab is nicer then doing it in a Scratch tab. 
I can remove the default tag but I see no reason why.
Also, should I add the tag "forum"?

True YouTube links

---

addons/true-youtube-links/userscript.js

**Changes**
This pull request introduces this request.
- Change CSS selector so tagging with class is not needed
- Use the direct YouTube link (https://www.youtube.com/watch?v=) instead of the shortened format (https://youtu.be/)
Why not? Is that acceptable?
**Tests**
In theory, it should have worked. I'm not sure how to test it because I don't know any page that has a YouTube link, so please help with testing it.

Update "True YouTube links" addon (05/09/2020)

---

addons/external-player-button/addon.json
addons/image-uploader/userscript.js

**Resolves**
It automatically switches the stage from Scratch to forkphorus or turbowarp when it's recommended. That's neat I think.
Resolves #191 
**Changes**
I added code for searching in the instructions and notes for links to fork and warp. 
I also added some code that adds a button that adds ?ignoreplayerlinks=true to the URL that adds the possibility to view projects with Scratch in case you want to that adds 5 points to the awesomeness of this addon.
Because
> it's never bad to have features
**Tests**
Well, it works. I tested it and didn't run into problems.
**Other stuff I want to talk about**
It would be nice to have #190 so the last two options are only there when you have enabled "replace stage".

Replacing the stage automatically when it's recommended

---

addons/editor-dark-mode/styles.css

**Resolves**
(Doesn't look like there's an issue for this but I was told about it by @WorldLanguages!)
**Changes**
Fixes the fullscreen button getting styled dark while on the editor page (when the dark editor addon is enabled).
It looks better! This was a bug in the dark editor addon. (I'm the original author of the CSS used in it.) In my userstyle I dealt with this by only applying the styles to `*/editor` and `*/fullscreen` pages, which is arguably more robust than this is, but this gets the bug fixed with only a single CSS change.
**Tests**
Tested manually.

Fix dark fullscreen button on editor page

---

addons/discuss-button/addon.json
addons/discuss-button/userscript.js
webpages/settings/index.html
webpages/settings/index.js

String: works exactly like `positive_integer` but for strings.
Select: requires a `potential_values` array of strings (and a default value as well, that should exactly match one of those values).
Bonus: with this addition, now the discuss button addon lets the user rename the button. This is useful for internationalization.

New option types: select & string

---

addon-api/content-script/Trap.js
content-scripts/prototype-handler.js

**Resolves**
Resolves #243.
**Changes**
Implements two new API functions for low-level interaction with prototype traps/overrides, as outlined in #243:
* `addon.tab.traps.addPrototypeListener`: Adds an event listener for when overridden prototype functions (e.g. on `Function`, `Array`, `Object`) are called. This follows the same details as other `add...Listeners` functions in the `addon.tab.traps` API; the event details are `args` and (optionally) `trapName`. The value of `args` is an array which contains the arguments passed to that function, and this array can be mutated to change the values which will be passed to the trapped prototype function once all listeners have been called.
* `addon.tab.traps.removePrototypeListener`: Corresponding interface for removing an existing event …

Add API for low-level prototype trap interaction

---

README.md
addon-api/content-script/Trap.js
addons/addons.json
addons/list-category/addon.json
addons/list-category/userscript.js
content-scripts/prototype-handler.js

**Resolves**
Resolves #245. **Depends on #244**, so that should be merged before this. (This is a fork of that PR - commit f06b636d4d07cbf44d3d155a1d3e9e6608039212 contains the addon code.)
**Changes**
Implements a "Separate List Category" addon, which does what it says: it breaks the "Variables" category into two, one for (scalar/ordinary) variable blocks and one for list blocks.
Implementing a (self- :P) requested addon; rationale for the request is in LLK/scratch-blocks#1874.
**Tests**
Tested manually by enabling the extension and running it!

Separate List Category addon

---

addons/bitmap-copy/addon.json
addons/data-category-tweaks/addon.json
addons/deleted-comments/addon.json
addons/editor-colored-context-menus/addon.json
addons/editor-devtools/addon.json
addons/editor-searchable-dropdowns/addon.json
addons/editor-stepping/addon.json
addons/fix-buttons/addon.json
addons/forum-time-zones/addon.json
addons/image-uploader/addon.json
addons/msg-count-badge/addon.json
addons/progress-bar/addon.json
addons/remove-sprite-confirm/addon.json
addons/scratch-messaging/addon.json
addons/scratch-notifier/addon.json
addons/true-youtube-links/addon.json
addons/youtube-fullscreen/addon.json
webpages/settings/index.html
webpages/settings/index.js
webpages/settings/style.css

- Resolves #180 (standardize naming - most addons shouldn't have Names Like This)
- Changed the name of some addons to make it more clear what their job is.
- Add credits to some addons when the author did credit themselves in other addons.
- Added `recommended` tags to some addons I believed deserved the tag. My main judging point was that these addons were either related to messaging, or added functionality without removing/replacing any original Scratch functionality. Please tell me if you disagree with any tag choice I made!
- Fixed ordering in the settings page. Messaging addons go first, then enabled addons alphabetically , then recommended disabled addons alphabetically, then other addons alphabetically.
- Allow searching by author in the settings page. Already supported were name …

Standardize naming, add some credits, recommended tags, settings page bug fixes

---

.github/workflows/schema-validation.yml

This PR adds a schema validation workflow for addon manifests, based on the schema that I made on [Hans5958/ScratchAddons-Schema](https://github.com/Hans5958/ScratchAddons-Schemas/blob/master/addon/1.0.json), with some actions that I have modified so it works properly.
The workflow have been tested rigorously by myself and it seems that it is working properly.
This pull request partially resolves #229 as there will be future PRs for updating all addon manifest for the schema, which will be done after this PR. 
Some notes:
- There is still a need to get the descriptions done on [the schema](https://github.com/Hans5958/ScratchAddons-Schemas/blob/master/addon/1.0.json). I have filled some of the description based on the wiki, but there still some field missing, indicated by the TODO …

Add schema validation workflow

---

addons/scratch-messaging/background.js

Limit the amount of saved messages over time to 1000 (not just for the first check).
Remove comment that could be misinterpreted.

Scratch Messaging little fixes

---

.github/workflows/schema-validation.yml

This PR is created because [Hans5958/ScratchAddons-Schemas](https://github.com/Hans5958/ScratchAddons-Schemas) has been changed to [ScratchAddons/manifest-schema](https://github.com/ScratchAddons/manifest-schema).
#229

Schema Validation workflow changes in accordance with the new name

---

webpages/settings/index.html
webpages/settings/style.css

Makes the search bar the same size everywhere. Chrome's default is 16px but not all browsers follow.
Removes HTML comments that aren't needed anymore

Little styling fix on settings page

---

addons/full-signature/addon.json

(－‸ლ)
(－‸ლ)
I used two userstyle keys. Wow, I'm stupid. Well, it's fixed now.

Fix For Full Signature Addon

---

content-scripts/inject/module.js

- Avoids `dispatchEvent` from being called on non-existent `addon.settings` event targets.
- Removes the `data-fire-event` from the DOM after being read by the injected script.

Small bug fix: avoid HTML attribute memory leak and console errors

---

background/get-userscripts.js

Resolves #332 
Adds an implicit "/" at the end of the pattern. This was already done with the URL, but not with the pattern.
This implicit slash is only added if the last character of the pattern isn't a wildcard - `https://scratch.mit.edu/discuss/*` would match any URL inside discuss, but `https://scratch.mit.edu/discuss/*/` would only match those that have a single "sub-folder" after "discuss".

Fix #322: bug in URL/pattern matcher 

---

.prettierrc.json
addons/addons.json
addons/forum-search/addon.json
addons/forum-search/userscript.css
addons/forum-search/userscript.js

**Changes**
Added an addon that adds a search bar to search through forum posts using ScratchDB
There isn't any current site forum search so this implements what some external sites do directly inline on the forums
**Tests**
Addon is able to search and appears in the addon list properly
**Notes**
I am planning on improving some styling as well as adding sort options such as sorting by newest and oldest in future updates, as well as possibly searching in the category you are currently viewing. I also plan on adding more information about a post instead of just having the username on the left. There is also a few remnants from me debugging still in the code, I will get those removed soon.

Add base for Forum Search integration

---

webpages/settings/style.css

**Resolves**
Resolves #377
**Changes**
Changed 100px to 150px width for search box
You couldn't see multiple words.
**Tests**

Changed search to 150px

---

addon-api/content-script/Addon.js
addon-api/content-script/Tab.js
addon-api/content-script/Trap.js
addons/60fps/addon.json
addons/data-category-tweaks/addon.json
addons/editor-stepping/addon.json
addons/editor-stepping/userscript.js
addons/remove-sprite-confirm/addon.json
background/get-userscripts.js
background/handle-settings-page.js
content-scripts/inject/module.js
content-scripts/inject/run-userscript.js
content-scripts/prototype-handler.js
content-scripts/sa-embed.js
manifest.json

Resolves #345
With this change, if you have none of these addons enabled, Scratch projects performance goes back to normal:
- 60fps
- Data category tweaks
- Editor stepping
- Remove sprite confirm
This introduces a `traps` property in the manifest, with the default value of `false`. If truthy, addon.tab.traps is available to that addon. In the future, we expect to make this an object that specifies which objects it wants to trap, instead of doing that at runtime.
This removes `addon.tabs.getScratchVM()` - please use the `addon.tab.traps` API for consistency.

Do not load traps unless addons that use them are enabled (performance concerns)

---

addons/addons.json
addons/cloud-games/addon.json
webpages/popup/index.html
webpages/popup/index.js
webpages/popup/style.css

Resolves #339 
Shown projects are retrieved from griffpatch's multiplayer games studios.
There's no "favorite project" functionality yet.
The fact there are 2 popups does not mean popup functionality exists yet, they're still hardcoded. Disabling the "cloud games" addon has no real effect.

Add cloud games addon

---

content-scripts/cs.js

Resolves #401
Most times the head loaded before userstyles were injected - however, sometimes, they didn't, causing issues were the Scratch styles were more relevant than Scratch Addons'. This fixes this issue, and I've noticed no flickering of any kind so far.

Make sure the head loaded before injecting userstyles

---

addons/editor-dark-mode/3dark.css
addons/editor-dark-mode/3darker.css
addons/editor-dark-mode/addon.json
addons/editor-dark-mode/dark-editor.css

Resolves #389
I thought I was going to throw a bunch of CSS `:not()`s so that dark mode wouldn't apply to the search input, but then I realized I could just change the single pattern to these 4, where the editor is reachable without a redirect or new navigation: `"https://scratch.mit.edu/projects/*/", "https://scratch.mit.edu/projects/*/editor", "https://scratch.mit.edu/projects/*/fullscreen", "https://scratch.mit.edu/projects/editor"`
I also fixed some slight changes to the search bar by the dark modes in the normal project page search bar (not the remix tree one)

Don't inject dark mode into remixtree, do not style scratch 3.0 search bar

---

addons/addons.json
addons/forum-search/userscript.css
addons/scratchr2/forums.css

**Resolves**
Resolves #416
**Changes**
Makes forum search and Scratch 2.0 → 3.0 compatible.
Previously, when Scratch 2.0 → 3.0 was enabled, forum search looked terrible.
**Tests**

Forum search and 2.0 → 3.0 compatibility

---

addons/editor-stage-left/addon.json
addons/forum-search/addon.json
addons/scratchr2/addon.json

- I don't like adding themes as "recommended", but the Scratch 2.0 → 3.0 addon deserves it.
- Renamed "Forum Search" to "Forums search", since other addons also use "forums" instead of "forum". It's also not really beta anymore.
- The warning for `editor-stage-left` is outdated.

Update tags and addon names

---

addons/editor-dark-mode/3dark.css
addons/editor-dark-mode/3darker.css
addons/editor-dark-mode/dark-editor.css
popups/cloud-games/popup.css
popups/scratch-messaging/popup.css
webpages/popup/index.js

(Forgot to make a new branch, stayed in the old one. Sorry!)
- This is fairly subjective I admit, but the font-weight of 800 in dark-editor.css is a bit extreme. I lowered it into 700 until we provide more customization options.
- Remove a border that shouldn't be in 3.Dark and 3.Darker
- Change var(--text) to white on 3.Darker so that text is more readable. In the future, we should provide the past color back if the user decides to use Scratch 2.0 colors: https://github.com/infinitytec/2.0-Colors

Dark mode little changes

---

addons/editor-stage-left/addon.json

If it's enabled/disabled and the editor isn't refreshed, it will be very buggy because the userscript keeps running. This should be fixed in the next update, providing a way for userscripts to know when their userstyles have been removed.

Add warning to editor-stage-left

---

addons/forum-search/userscript.js

Resolves: if you are logged out, the search forums addon sticks the searchbar at the bottom

Forum search styling bugfix when logged out

---

addons/bitmap-copy/addon.json

We've received through feedback that someone tried to copy the <canvas> so this note should clear up the confusion.

Add note to bitmap images copying addon

---

addons/60fps/addon.json
addons/60fps/userscript.js

- Normalize addon name.
- "Fixes" #425. It might not work, but it's my best attempt. If this does not solve it, I don't think anything else will. The logic I used is: when you do alt+click, the website should get notified about alt getting clicked. When you then click, it triggers a right click, so it should fire a `contextmenu` event on the green flag. If alt has been pressed for the last 2.5 and you right click the green flag, it interprets that the same way as a normal click with alt pressed (and of course, tells the browser not to open the right click context menu).

60fps addon enhancements

---

addon-api/content-script/Tab.js
content-scripts/inject/module.js

Resolves #442, not exactly as I described however. This event triggers after any URL change (not navigations, of course). Right now, as far as I know, this can only happen inside projects, when editor mode changes. However in the future this might happen for something else, who knows! So let's try to cover as many use cases as possible.

Add "urlChanged" event to addon.tab

---

addons/better-emojis/userscript.js

Oh, good old JavaScript. The className can be truthy and not be a string, who knew...

Fix #511: make sure className is a string

---

addons/better-emojis/userscript.js

**Resolves**
Just realized that the link to emojis on 2.0-styled pages are apparently not static. I have accounted for this now, to ensure that they will always be properly detected
**Changes**
The code now checks for telling parts of the image SRC, rather than the entire thing

Fix emoji appearance on Scratch 2.0 Pages

---

addons/addons.json
addons/infinite-scroll/addon.json
addons/infinite-scroll/buttonScroll.js
addons/infinite-scroll/forumScroll.js
addons/infinite-scroll/userscript.css

**Resolves**
Adds infinite scrolling on multiple parts of the site
**Changes**
On the forums, topic listings will scroll without having to use pagination. (Forum topics themselves don't have infinite scrolling since you're most likely going to the last page anyway)
Otherwise, infinite scrolling was added to studios, profiles, projects, and messages
Hitting buttons is hard
**Tests**
Self, using Chrome/Brave
I did my tests using 2.0 to 3.0 styling, and a little bit with normal 2.0 testing. Should work fine, but may require some CSS tweaks for the footer

add infinite scroll addon

---

addons/addons.json
addons/exact-count/addon.json
addons/exact-count/studio.js
addons/exact-count/user.js

**Resolves**
Resolves #66 
Resolves #68
**Changes**
Added the exact count of user info on profiles and the exact count of a studio's project count.
It's convenient. Please lmk if you want something in the setting to be changed or anything else.
**Tests**
Works on chrome. I noticed that @mxmou's studio script will throw errors for 404s so if anyone knows what causes this lmk.
**Credit**
@mxmou for the studio script and @WorldLanguages for the base of the profile script. I then changed it up a bit so it is useful for all box heads.

Exact Count Addon

---

background/handle-notifications.js

Stupid bug, I wrote 1 hour had 480 minutes instead of 60 minutes. Thanks @TheColaber!

Fix duration of 1 hour

---

addons/addons.json
background/transition.js
manifest.json
popups/cloud-games/popup.css
popups/scratch-messaging/light.css
popups/scratch-messaging/popup.css

- Disable `dark-www` by commenting it out from addons.json
- Add install page /welcome
- Remove `prerelease` from version name
- Make titles in both popups unselectable, so that a double click extends and reduces the category without selecting the text.

Details before submitting v1.2.0

---

background/get-addon-settings.js
manifest.json
webpages/popup/index.html
webpages/popup/index.js

v1.2.0 was only released on Firefox, for less than 100 users.
Bug fixed on #571 is important (addon warnings not showing) so version v1.2.0 will never reach Chrome users.

v1.2.1 hotfix

---

addons/remix-tree-button/addon.json
addons/remix-tree-button/button.css
addons/remix-tree-button/main.js

**Changes**
The remix tree button was wildly inconsistent when trying to open the link. This fixes that with some better code to grab the project id
The remix icon was also reimplemented to be identical to the other project buttons, and the custom color has been set to automatically update

Remix Tree Button Fixes

---

content-scripts/fix-console.js
content-scripts/inject/run-userscript.js
manifest.json

Resolves #618 
Note: this issue is not caused by Scratch Addons. It's caused by Sentry, the service Scratch uses to get information about JavaScript errors, and it's only used in projects. This patch allows addons to use the native `console` object through the `console` argument of the default exported function in the modules.
Related: #566 (discussion)

Fix console.log memory leak caused by Scratch projects

---

content-scripts/cs.js

**Resolves**
Resolves #552
**Changes**
I've added this warning to the forum when posting:
It's pretty common...
**Tests**
Well it works on chrome. 
Btw Please someone tell me how to run prettier. I need to know...

Add a warning on the Scratch forums to avoid posts about Scratch Addons

---

addons/60fps/addon.json
addons/clones/addon.json
addons/editor-colored-context-menus/addon.json
addons/editor-stage-left/addon.json
addons/editor-stage-left/fix-share-the-love.js
addons/editor-stage-left/stageleft.css
addons/editor-stepping/addon.json
addons/editor-stepping/userscript.js
addons/editor-theme3/addon.json
addons/editor-theme3/theme3.css
addons/editor-theme3/theme3.js
addons/mouse-pos/addon.json
addons/pause/addon.json
addons/remove-sprite-confirm/addon.json
background/handle-settings-page.js
content-scripts/cs.js
content-scripts/prototype-handler.js
content-scripts/sa-embed.js
manifest.json

A pretty big PR
- Resolves #431. The only 2 traps used by addons nowadays are vm and workspace - and workspace can actually be obtained from the accidentally global object `window.Blockly`. So, sorry @apple502j, but at least for now, we're returning to the old "prototype handler" that only traps the VM, and nothing else.
- Because of the former, all performance warnings were removed, and the "traps" property was removed from all manifests.
- Code that handled whether to inject traps or not was removed - now, traps are always injected, as long as it's a project.
- Resolves #336, returns to previous non-trap code for editor-stepping, using a setInterval of 500ms. Beta tag removed - no addons have it as of now.
- Adds `/* sa-autoupdate-theme-ignore */`, a way for themes to ask for their …

Remove prototype handler, add /* sa-autoupdate-theme-ignore */

---

addon-api/content-script/Tab.js
addons/60fps/addon.json
addons/animated-thumb/addon.json
addons/exact-count/addon.json
addons/forum-time-zones/addon.json
addons/full-signature/addon.json
addons/infinite-scroll/addon.json
addons/pause/addon.json
addons/resizable-comment-input/addon.json
addons/studio-tools/addon.json

Resolves #487 
- With the removal of the prototype handler, `60fps` is now recommended and turned on by default.
- The new `resizable-comments` addon will be turned on for all users.
- The new `animated-thumb` addon will be turned on for all users.
- Made `exact-count` recommended.
- `full-signature` is now recommended and will be turned on for new users.
- `forum-time-zones` and `infinite-scroll` are now beta.
- `studio-tools` will be turned on for new users.
- The new `pause` addon is beta.

Update addon tags, make some addons recommended

---

background/get-addon-settings.js

This enables 60fps, studio tools and full signature for all users. Since it's been a while since Scratch Addons was Scratch Messaging, it seems to be a good time to do it.
It's possible some users did try out these new addons and then disabled them, but that should be a minority. Sadly, because of the way I coded this, it's not possible to know if a user disabled an addon themselves, or if they never enabled a non-enabled-by-default addon.

Enable some old addons for all users on v1.3.0

---

addons/live-featured-project/addon.json

This PR set the `enabledByDefault` value of the "Live featured project" addon to false.
I thought a post-merge PR is enough. Turns out it isn't, and the damage was done. On the bright side, at least I got some inquiries about it.
P/S: I am really pissed off rn

Live featured project: Disable addon by default

---

background/get-userscripts.js
content-scripts/cs.js

**Resolves**
Resolves #700
**Changes**
Theme userstyles now load in the same order as they are listed in `addon.json`.
This makes them predictable.
**Tests**
I opened the editor with editor dark mode enabled and the styles were in correct order.

Make theme userstyles ordered

---

addons/infinite-scroll/userscript.css

**Resolves**
Resolves #689 
**Changes**
Makes the *Fix footer* feature of the infinite scrolling addon work on https://scratch.mit.edu/annual-report
#689
**Tests**
Tested, works.

Fix fixed footer on annual report

---

addons/full-signature/working.js

It seems that the capitalization of the "Load more" button is not the same as the other "Load more" button on the bottom of the comments. (pictured below)
This PR fixes it.

Show full areas: Fix capitalization on "Load more"

---

addons/addons.json
addons/search-load-more-fix/addon.json
addons/search-load-more-fix/userstyle.css

A Load more fix is needed again, for search results this time: LLK/scratch-www#4624
I thinks it's OK to have it enabled by default.

Another Load more fix

---

webpages/settings/index.html
webpages/settings/licenses.html

There is no icon on the extension web pages. This PR adds it. Oh, and I also moved the "Scratch Addons" portion of text to the right, since it is already described on the icon.

Add favicon on the web pages

---

webpages/settings/index.html

In this PR, I remove the word "theme" from the "Dark Theme" and the "Light Theme" phrase as it is unnecessary because it is already described that the settings are for themes.
This might be too minor and subjective, so it is open for discussion.
If this got rejected, how about we talk about the capitalization?

Remove unnecessary word "theme"

---

addons/live-featured-project/addon.json
addons/live-featured-project/script.js
addons/live-featured-project/style.css

This PR updates the "Live featured project" addon, in response of few of the user's suggestions, and to fix here and there.
- Add option "none" to disable alternative player (iframe removed if failed, thumbnail appears after that)
- Make "none" as default option for alternative player
- Fix styling of forkphorus player
- Prepend iframe instead of append
- Tidy up code

Live featured project: Add option to disable alt player, fix style, etc

---

addon-api/content-script/Tab.js
addons/mouse-pos/style.css
addons/mouse-pos/userscript.js

A user reported through feedback that they experienced lag while using Scratch Addons. I then noticed this was obviously the mutation observers for all calls to `addon.tab.waitForElement` reacting to something. I ended up finding that dragging a block triggers attribute changes in the DOM, and the mutation observers were listening to attribute changes. There might be valid reasons for `waitForElement` that might require to listen for attribute changes, but it's not worth the performance cost.
This fixed the performance issues (using 4x slowdown simulation on Chrome devtools), except when having the "mouse position" addon by @JeffaloBob enabled. I think it's safe to guess why; moving the cursor causes a change to the DOM, which then causes all mutation observers to trigger - but not when …

Fix performance when dragging blocks in the editor

---

addons/scratchr2/addon.json

This adds more pages to scratchr2.
Resolves #774 
Adds:   
"https://scratch.mit.edu/login",
"https://scratch.mit.edu/login_retry",
"https://scratch.mit.edu/cloudmonitor/*",
"https://scratch.mit.edu/accounts/login"

Add more pages to scratchr2

---

addons/scratchr2/assets/caret.svg
addons/scratchr2/assets/caret_hover.svg
addons/scratchr2/experimental_dark_compatibility.css
addons/scratchr2/mystuff.css
addons/scratchr2/scratchr2.css
content-scripts/cs.js

Resolves #741 
Any instance of the string `%addon-self-dir%` in a CSS file of a theme will be replaced with the value of `addon.self.dir` for that addon.

Add support for %addon-self-dir% in themes CSS

---

addons/editor-stage-left/stageleft.css

**Changes**
change
to
on left stage with;
```css
[dir="ltr"] .backpack_backpack-header_6ltCS {
border-top-right-radius: 0rem;
border-top-left-radius: 0.5rem;
}
```
I looks a little better now :)
Idk why, but this just makes the backpack div not look pointy on the left stage mode.
**Tests**
Yup, it works

add radius to backpack

---

.github/workflows/transifex.yml

I don't know, this change is quite small, and I think it is better to use ScratchAddons-Bot so checks and workflows work (if that's an issue), and for, you know, uniformity.

Use SAB as the placeholder author on the Transifex workflow

---

addons/scratchr2/profile.css

**Resolves**
Resolves #
**Changes**
Change
to
on the 3.0 styled pages
Changed "change's" radius on the top left to match the profile pic radius
This is done by:
```css
.portrait [data-control="edit"] {
border-top-left-radius: 5px;
}
```
Change radius to match the profile image
**Tests**
Yup, inspected

Radius for change button on profile

---

security.md

Instead of updating it every vulnerability (and causing that pop-up appear every time), how about just link it to [this page](https://github.com/ScratchAddons/ScratchAddons/security/advisories?state=published)? The page is used to list our advisories, so why another list?
Reminder that people can click our Security tab and check either our policy or the advisories list.

Link advisories page instead of updating it every vuln

---

content-scripts/cs.js

Theme CSS is not injected as <link rel="stylesheet">, but as <style>, to improve speed. This means the original URL for the style is lost in devtools.
Used to look like this:
Now looks like this:

Add source URL to theme CSS

---

webpages/settings/index.html
webpages/settings/index.js
webpages/settings/style.css

Resolves #726 - ctrl+click any addon name in the settings page (while on prerelease), and all addon names will be replaced with addon IDs.
Minor CSS change to tags - use default cursor when hovering them, instead of the text cursor.

Ctrl+click addon name to show IDs instead of names

---

background/get-addon-settings.js
manifest.json

Removes a ` TODO: remove on v1.4.0`, bumps to non-prerelease v1.4.0

Bump to v1.4.0

---

background/get-userscripts.js
background/handle-messages.js
background/imports/global-state.js
content-scripts/cs.js
manifest.json

Resolves #702
Caveats:
- `about:blank` iframes not supported (at least for now)
- No theme autoupdate in iframes (at least for now)
- Only first party iframes run addons. If example.com embeds a Scratch project, it won't run addons on it.
This means, pause button & 60fps and live featured project now work together:

Run addons in iframes

---

addons/dark-www/experimental_scratchwww.css
content-scripts/inject/module.js

Resolves #846 
- `module.js` is now in charge of adding or removing a `sa-body-editor` class to the `<body>` element. This class is then used by "dark website" to only style the body, and also used by some very generic selectors (like `h1`) to avoid styling when the page is in either editor mode or full screen mode.
- Remove styles that affect full screen mode. We're considering full screen mode part of the editor.

Dark website: don't affect editor and fullscreen

---

addons-l10n/en/better-featured-project.json
addons/addons.json
addons/better-featured-project/addon.json
addons/better-featured-project/userscript.js
addons/better-featured-project/userstyle.css

**Resolves**
None
**Changes**
Adds an addon that changes the featured project into a nice-looking banner.
I showed this off in the Discord server, and everyone thought it was pretty cool!
**Tests**
I have tested this with the 2.0 to 3.0 style, the dark mode style, and the Live Featured Project addon (which I had to move the embedded project that it creates with some very hacky CSS). :P I have also tested this with Firefox and Brave, which both seem to work exactly the same.

Created Profile Page Banner addon

---

addons/editor-theme3/addon.json
addons/editor-theme3/theme3.css
addons/editor-theme3/theme3.js

Partially reverts #669
- Removes duplicate CSS
- Revert changes to addon settings ID so that settings are not lost during updates.

Partially revert #669

---

webpages/settings/index.html
webpages/settings/index.js

Before this PR, color settings would update every time the inputs fired oninput, which meant multiple times per second. This might cause memory leaks because the setting themselves are changing multiple times per second. It could also cause significant hard drive write activity (to be honest, I could hear it while testing on Firefox - drive go brr when changing color settings)
With this PR, color settings are only updated after 250ms without changes. RAM usage might temporarily appear to skyrocket, but it's used by the settings page, not the background page, so after the settings page is closed all that can be cleared.

Color setting input: 250ms cooldown on change

---

addons/more-links/addon.json

Me and others have experienced some lag while browsing the website, likely Linkify blocking the main thread. As a first measure we should likely mark this addon as beta.
cc @Hans5958

Add beta tag to "more links"

---

addons/dark-www/experimental_scratchr2.css

Resolves #1088 
The proper way to do this might be darkifying the modal, but this is OK for now.
cc @mxmou

Fix can't read report pop up text with website dark mode

---

addons/editor-devtools/userscript.css
addons/editor-devtools/userscript.js

**Changes**
- The addon previously used an interesting method to hide the context menu when a button is clicked: hide the entire workspace and show it again. This is horribly slow on large projects because all the styles have to get recomputed. It now uses fake events to trick it into hiding (without access to the real Blockly and without using Blockly's builtin context menu handling, this seems to be the most consistent way to do this) which makes any context menu operation (copy, cut, paste, swap variable, show senders/receivers...) significantly faster.
- "Copy block" before & after: [2.37 seconds](https://user-images.githubusercontent.com/33787854/103255960-fca7d180-4950-11eb-9e75-e6a5ce523d02.png) to [~200ms](https://user-images.githubusercontent.com/33787854/103256058-5e683b80-4951-1 …

Optimizations and bug fixes for editor-devtools

---

addons/project-notes-tabs/addon.json
addons/project-notes-tabs/style.css
addons/project-notes-tabs/userscript.js

**Changes**
Here's the bugs in project-notes-tabs that this fixes:
- the tab buttons did not work at all in Firefox
- instructions would not fill empty space in Firefox
- it would throw errors and stop working after the initial page load when there is only one section
- if the project only had instructions, the tab would be called "Notes and credits"
- the tab buttons could occasionally appear above the remix credit box
- there was a brief period of time (before onload) where the unmodified instructions and n&c are shown without tabs.
**Tests**
Tested on these projects (just found from trending) in Chrome and Firefox:
- https://scratch.mit.edu/projects/467543815/
- https://scratch.mit.edu/projects/455720538/
- https://scratch.mit.edu/projects/455488994/
Editing descriptions still works. …

Fix some bugs in project-notes-tabs

---

addons/color-picker/paint-editor.js
addons/color-picker/style.css

**Resolves**
Resolves #1126
**Changes**
Improves the styling of the hex color picker addon. Now it looks good in all dark mode variants.
#1126, and consistency with Scratch's design.
**Tests**
See screenshot above.

Improve hex color picker CSS

---

popups/scratch-messaging/popup.css
webpages/popup/index.js
webpages/popup/style.css

**Resolves**
Resolves #600 (finally)
**Changes**
Removes the double scrollbar in the popup when browser zoom is set to more than 100%. I don't like the solution because it uses JavaScript, but I don't know how else I could fix it. I also changed the height of the messaging tab so there is no scrollbar unless there are many messages.
#600
**Tests**
I was able to zoom up to 175% before the second scrollbar appeared.

Fix double scrollbar in popup

---

addons/scratchr2/scratchwww.css

Resolves #1186. Username links in messages are now black.

Fix blue usernames in messages

---

addons/mute-project/addon.json

This was a 2.0 feature so it should be recommended.
It's close to being enabled by default, but I don't think we're going to turn any new addons by default.

Make "mute project" addon recommended

---

webpages/settings/index.js

It's been a while since the Scratch Messaging transition, and these 2 addons are now in the "popup features" category

Settings page: remove messaging related addons should go first

---

webpages/settings/index.js

Data category tweaks is still more relevant, and is the one mentioned in the update notification.
Also tweaked the `NEW_ADDONS` sorting logic to maintain the order - data category tweaks will always go first, then mute project player.

Mark mute-project as relevant new addon

---

_locales/en/messages.json
background/handle-site-access.js

- changes "skip" to "cancel"
- fix: site access screen no longer opens when revoking optional permissions on Firefox
DO NOT MERGE YET

WIP: bugfixes

---

addons/remix-tree-button/button.css
addons/scratchr2/lightprimary_scratchwww_compatibility.css
addons/scratchr2/scratchwww.css

**Resolves**
Resolves #1268
**Changes**
- Fixed blue share button
- Fixed incorrectly styled remix tree button

Fix Scratch 2.0 → 3.0 button styling on scratch-www pages

---

addons/better-featured-project/userstyle.css

**Resolves**
Resolves #1076
**Changes**
Fixes an incorrectly placed scrollbar in Firefox when the profile page banner addon is enabled.

Fix incorrectly placed scrollbar in Firefox with profile banner addon

---

addons/scratchr2/lightprimary_scratchwww_compatibility.css

**Resolves**
Fixes a bug caused by #1273
**Changes**
Makes the text color on the remix tree button independent of the primary color.
**Tests**
Tested by changing the primary color to different values, the button always had white text.

Fix bug caused by #1273

---

addons/data-category-tweaks-v2/addon.json
addons/data-category-tweaks-v2/userscript.js

**Changes**
- Remove beta tag under the (perhaps incorrect) assumption that no one has encountered issues with the addon
- Resolve #1296 - Add new option: "Move Reporters Under Operations" (name not final) that moves the reporter blocks below the other blocks: https://user-images.githubusercontent.com/33787854/104348402-4f43ca80-54c7-11eb-98b2-37a446d20f0d.png
- Update in response to settings updates immediately (previously only when switching sprites or creating a new variable, depending on the setting): https://user-images.githubusercontent.com/33787854/104348890-ddb84c00-54c7-11eb-8e7d-869840f808c9.mp4

Data category tweaks update

---

content-scripts/inject/run-userscript.js

editor-devtools has been using `scratchAddons.l10n.locale` to get the locale code. In order to make devtools its own independent extension, we're moving this to `msg.locale` so that the extension does not need to access `window.scratchAddons` in order to work.
I'm not modifying editor-devtools in this PR in order to avoid conflicts.

Add msg.locale property

---

addons/editor-stepping/addon.json

The addon was misnamed anyway so had no effect for a while... if you go to the current version or the released version of SA you won't see it anyway... The message is for 1.3.0 and we are on 1.8.0... it's time.

Remove notice for editor stepping addon

---

addon-api/content-script/Tab.js
addon-api/content-script/Trap.js
addons/60fps/userscript.js
addons/clones/userscript.js
addons/data-category-tweaks-v2/userscript.js
addons/editor-devtools/show-broadcast.js
addons/editor-stepping/userscript.js
addons/mediarecorder/userscript.js
addons/mouse-pos/userscript.js
addons/mute-project/userscript.js
addons/onion-skinning/userscript.js
addons/pause/userscript.js
addons/project-info/blockcount.js
addons/project-info/projectstats.js
addons/remove-sprite-confirm/userscript.js
background/get-userscripts.js
content-scripts/prototype-handler.js

- Removes unused APIs
- Adds an async function `traps.getBlockly` which can be used to obtain real Blockly used by Scratch (not `globalThis.Blockly`)

Refactor traps

---

addons/disable-auto-save/addon.json
webpages/settings/index.html
webpages/settings/index.js
webpages/settings/style.css

1. Shows "beta" tag in settings popup, but hides its tooltip when hovered
2. Expands enabled addons through the settings popup if addon has any warnings, so that users can read them
3. Remove "beta" tag in disable-auto-save, add warning to make sure users don't enable accidentally

Show "beta" tag & expand if addon has warnings in settings popup

---

addons-l10n/en/a11y.json
addons/a11y/addon.json
addons/a11y/style.css
addons/a11y/userscript.js
addons/addons.json

**Changes**
Add a11y addon that adds a category to the toolbox with blocks to allow people to add WAI-ARIA roles and labels to their sprites.
Scratch projects aren't accessible to people using assistive technologies. I think that is an issue.
**Tests**
I have tested it and fixed all bugs I've found.

Add a11y addon

---

addons/dark-www/experimental_forums.css
addons/dark-www/experimental_scratchr2.css

**Resolves**
Resolves #1353
**Changes**
Fixes incorrect styling of the search bar and forum search when webside dark mode is enabled without Scratch 2.0 → 3.0.
Text in the search bar was unreadable.
**Tests**

Fix unreadable search bar

---

addons/scratchr2/lightprimary_compatibility.css
addons/scratchr2/lightprimary_scratchwww_compatibility.css
addons/scratchr2/scratchr2.css

**Resolves**
Resolves #1320
**Changes**
Makes the message count readable when the primary color is set to a bright color in Scratch 2.0 → 3.0.

Fix unreadable message count on bright primary color

---

addons/a11y/userscript.js

We got rid of `onceValues` so that addon is broken right now

HOT FIX AHHHHHHHHH

---

addons/infinite-scroll/userscript.css

**Resolves**
Resolves #1325
**Changes**
Removes the blank space above the fixed footer when you scroll to the bottom on a scratchr2 page.

Fix infinite scrolling layout

---

addons-l10n/en/editor-devtools.json
addons/editor-devtools/DevTools.js
addons/editor-devtools/userscript.js

- Credit Scratch Addons in help popup
- Add extension description (not addon description) to locales so that we can translate it
- Show old style "help" and "tutorials" links if extension and not addon
- Bump date and version to v1.9.0, but help popup still needs update
- Use `msg.locale` instead of `scratchAddons.l10n.locale`

Editor devtools: get ready for extension

---

README.md

Now that TurboWarp borrows some of our addons, and because of the upcoming editor devtools v1.9.0 extension directly mirrored from Scratch Addons, it's now worth mentioning in the readme that addons can be used outside of Scratch Addons.

Mention addons being used outside of SA in readme

---

addons/mute-project/userscript.js

**Resolves**
Resolves #1362
**Changes**
Adds an icon shown when a project is muted.

Show icon when project is muted

---

addons/scratchr2/addon.json
addons/scratchr2/set-default-var-value.css

For obvious reasons, there's a little bit of time until JavaScript runs (lightprimary.js), until then the CSS variable `--scratchr2-primaryColor-isLight` resolves to an empty string, and the `calc()` functions that determine the color of the text in the navbar end up showing gray-ish text, instead of white, for half a second, on default addon settings.
This PR changes the default value of the variable to 0 until JS can actually calculate it, which is going to be the final result for most users that do not change the color of the navbar. The "problem" still persists but would affect less users, only the ones that change the color of the navbar to colors that do not contrast properly with white.

scratchr2: use white text until JS can calculate contrast

---

addons/editor-devtools/userscript.css

Slightly reverts part of #1433 - it's good to keep our styles consistent with Scratch's, but this differed too much from devtools' original design (specially with a way bigger border radius, and a box shadow on focus)

Devtools UI: change Scratch default <input> styles

---

addon-api/content-script/Tab.js
addons/animated-thumb/userscript.js
addons/editor-devtools/DevTools.js
addons/editor-devtools/userscript.css
addons/editor-devtools/userscript.js
addons/live-featured-project/script.js
addons/mediarecorder/userscript.js
content-scripts/inject/module.js

`addon.tab.scratchClass` is a handy function that should make it easier for us to be consistent with Scratch UI.
It accepts multiple arguments, for example 
```js
addon.tab.scratchClass("modal_header-item", "modal_header-item-title")
```
returns `modal_header-item_2zQTd modal_header-item-title_tLOU5`.
It also accepts an option object, that allows us to merge Scratch and non-Scratch classes automatically, for example: 
```js
addon.tab.scratchClass("modal_modal-content", { others: "mediaRecorderPopup" })
```
returns `modal_modal-content_1h3ll mediaRecorderPopup`. (`others` can be either a string or array)
If an addon calls this function before the classes are available, they temporarily fallback to `scratchAddonsScratchClass/[classNameToFind]`, and after the classes load, all elements with …

Introduce addon.tab.scratchClass

---

_locales/en/messages.json

Adds description to _locales asking translators this, to avoid keyword spam rejection on Chrome Web Store.

Make sure translators don't repeat word "Scratch"

---

addons/editor-devtools/userscript.js

The extension will set window.initGUI to make sure Scratch Addons <v1.9 doesn't run the editor-devtools addon

Editor devtools extension: run even if window.initGUI is truthy

---

addons/dark-www/addon.json

**Resolves**
Resolves #1480
**Changes**
Makes the preview when editing a forum post dark when website dark mode is enabled.

Dark preview when editing forum post

---

webpages/settings/index.js

**Changes**
Creates a check to see if shift is being held down, if so... do not expand the addon.
Makes it easier to enable multiple addons quick.
**Tests**
I promise I won't have to change a single line of code.

Settings page: do not extend disabled addon on shift + click enable

---

_locales/sq/messages.json
addons-l10n/sq/_general.json
addons-l10n/sq/data-category-tweaks-v2.json
addons-l10n/sq/onion-skinning.json
addons-l10n/sq/scratch-messaging.json

It was added by error. The language is already removed from Transifex.

Remove albanian translations

---

popups/scratch-messaging/popup.css
popups/scratch-messaging/popup.html
webpages/styles/components/tooltips.css

- Bottom bar should always be on top of lovers & favers tooltip, as well as project titles
- It's now easier to move your cursor above the tooltip in order to click in a username - previously you had to move your cursor fast or just at the right height.

Scratch Messaging: z-index fixes, tooltip hover fixes

---

addons-l10n/en/editor-devtools.json
addons/editor-devtools/userscript.js

Fixes #1435 kinda - not sure how and where to advertise Scratch Addons properly, might do it on next release.
Removes now unused strings from outdated show sender/receiver functionality. This functionality has been moved to the search bar.
It would be cool to have a better feature list for v1.10.

Editor devtools: remove outdated strings & 0.x change list

---

background/get-userscripts.js
background/l10n.js

pt (which is now lowercase) falls back to pt-br, then en. We use `pt` as `pt-pt` for Scratch compatibility.

Add fallback for pt translations

---

libraries/fast-linkify.js

Numbers and hyphens are no longer permitted in non-IDN TLDs. For example, `-.-3` will no longer match.

Update regex for URL matching (again)

---

background/handle-notifications.js

**Resolves**
Resolves #1523
**Changes**
one line of code. it was doing this previous action because `scratchAddons.muted` was undefined leading to the badge showing. This line of code sets it to deal with that problem.
**Tests**
Works.

Muted extension shows badge on refresh

---

addon-api/content-script/Tab.js

Resolves #1554 
Add locale fallback mechanism to `Tab.scratchMessage`.

Fix crash on Tab.scratchMessage

---

addons/editor-devtools/blockly/BlockFlasher.js

**Resolves**
Resolves #1545
**Changes**
The Blockly method just edited the `fill` attribute, which is overridden by the stylesheet. This way edits the `style` attribute, which overrides everything.
it's a bug
**Tests**
it works

Fix "custom Colors addon makes devtools highlighting not work"

---

addons/dark-www/dark-www.css

sometimes scratch crashes and it shows a error message
with dark-www, it looks like this: 
unreadable
**Changes**
update dark-www.css, now it looks like this:
it's a bug
**Tests**
works

fix unreadable crash message with dark-www

---

addons/dark-www/experimental_studio.css

**Resolves**
Resolves #1576
**Changes**
Fixes the studio follower count being invisible when website dark mode is enabled without Scratch 2.0 → 3.0.

Fix invisible studio follower count

---

addons/scratch-messaging/background.js
popups/scratch-messaging/popup.html

Links to Scratch Team users' profiles on Scratch Messaging no longer includes an asterisk. Asterisks are still visible; they are just not inside the URL.

scratch-messaging: correct handling of Scratch Team comments

---

webpages/settings/style.css

**Resolves**
None
**Changes**
Fixes the licenses page not having a scrollbar (which is a bug I made in #1187). Can be tested on the `scratch-blocks` license.

Fix missing scrollbar on licenses page

---

addons-l10n/en/cloud-games.json
popups/cloud-games/popup.css
popups/cloud-games/popup.html
popups/cloud-games/popup.js

1. Adds loading indicator
2. Shows incomplete data after more than 50% of projects loaded, but keeps the loading indicator until 100% loads
3. Instead of starting each request in parallel, request every 125ms

cloud-games: add loading indicator, do not request data in parallel

---

addons/full-signature/happen.js
addons/scratch-messaging/background.js
addons/studio-tools/mystuff.js
background/handle-fetch.js
background/handle-messages.js

1. Removes the single use of `addon.fetch` in userscripts. Instead of using this magic function, userscripts should manually add corresponding headers manually, with the help of `addon.auth.csrfToken` if needed.
2. `addon.fetch` was used in the background page in order to add an artificial `Referer` header in some POST requests to Scratch 2.0 API endpoints that require it. This is a problem that is obviously only present in background requests - userscript requests send the Referer header just fine because they're running under a scratch.mit.edu tab. The old `X-ScratchAddons-Uses-Fetch` header was removed in favor of adding `?sareferer` or `&sareferer` at the end of the URL. This new approach is compatible with the new `chrome.declarativeNetRequest` API we will have to use after we …

Remove addon.fetch, introduce ?sareferer URL parameter for background requests

---

addons/60fps/addon.json

1. Rename addon to `Alt+GreenFlag 60FPS player mode`
2. Rename `FPS` setting to `Alt+GreenFlag FPS`
3. Set setting min to 31, and max to 240 (good luck finding a monitor with a higher refresh rate than that)

Rename "60FPS player mode" addon for clarity

---

background/handle-notifications.js

Inline `onclick` won't be supported in manifest v3, so worth changing now

chrome.contextMenus API: use onClicked listener instead of inline onclick

---

README.md

I think it is inappropriate to add the translation badges on the README. The focus of the repository is for the development in code, not localization/translation. I think it is better to put it on the wiki or some kind.
By the way, I did this on my Android phone, because my computer is still in use. Probably better than some of you guys copying and pasting code from your local enviroment to the GitHub editor.

Revert "Add translation badges"

---

addons/dark-www/experimental_scratchr2.css
addons/dark-www/experimental_scratchwww.css

**Resolves**
https://github.com/ScratchAddons/ScratchAddons/pull/1712#issuecomment-790707723
**Changes**
Makes the border added by the "fixed footer" feature of the infinite scrolling addon dark when website dark mode is enabled.

Make fixed footer border dark in dark mode

---

addons/infinite-scroll/userscript.css

**Resolves**
None
**Changes**
Changes the fixed footer border color to `#d9d9d9` for consistency with similar elements on Scratch and removes empty space above it.
**Screenshots**
Before:
Now:

Change fixed footer border color and remove empty space above it

---

addons/block-switching/userscript.js

**Changes**
Previously, converting a `change variable by` block to a `set variable to` block would result in a set variable block that only let you type numbers. Going the other way would result in a change variable block that let you type things that aren't numbers.
This is now fixed.

Fix block switching bug with change and set variable blocks

---

addons/load-extensions/addon.json

**Resolves**
**Changes**
Make the load extension addon doesn’t load the video sensing by default
Video sensing automatically turns on the camera but the user doesn’t notice and it can make scratch lag
**Tests**
Yes. I try  it on chrome and Firefox

Remove video sensing from loading by default

---

addons-l10n/en/folders.json
addons/folders/userscript.js

**Changes**
- Fix #1732 - the item will be renamed to something like `_mouse_2`
- This addon does a lot of terrible things to Scratch internals, so some checks were added to ensure that if Scratch ever refactors this, the addon should (hopefully) gracefully abort instead of leaving things in a half-broken state
- Fix some issues when creating costume/sound folders with items that are already in folders
- Fix dragging closed costume/sound folders causing folders to open
- Fix new items being able to automatically move into closed folders
- Do not allow `//` to be used in folder names when creating and renaming folders

Fix some bugs in folders addon

---

addons/disable-auto-save/userscript.js

**Resolves**
Resolves #1709 
**Changes**
Simplify disable-auto-save to use redux. Too simple that I hate to test this.
NOTE: this does remove disabling "save when going to project page", but the cost of accidental saving is significantly smaller than the cost of losing projects. Note that this behavior is not "autosave" per se; maybe we can rename the button to "Save and See Project Page"?

Simplify disable-auto-save

---

background/background.html
background/transition.js

This change forcibly disables video sensing on load-extensions settings for users from 1.10/1.11. It is likely that a lot of 1.10 users who enabled this new addon via the popup have been annoyed by video sensing being added on all projects - and this is also a performance concern.
We did this before, we can do it again.
TODO: should we add some sort of notes (e.g. page to show) for those who are affected, telling them they can re-enable it (with some performance downsides)?

Forcibly disable video sensing auto-loading

---

addons/longer-wiwo/userscript.js

Minor thing, there's an error in the console on others' profiles becuase `status[0]` is undefined, as there is no `textarea#status`. 
<details><summary>`?.` is pretty new (but also great browser support, see https://caniuse.com/mdn-javascript_operators_optional_chaining) so here is a explimation</summary>
```javascript
object = null
console.log(object?.key)
console.log(object?.["key"])
```
will log `undefined` twice. without the `?` it would throw errors both times.
```javascript
object = {"key":"hi"}
console.log(object?.key)
console.log(object?.["key"])
```
will log `"hi"` twice. without the `?` it would do the same. 
So the `?` protects against `object is undefined` errors
</details>

fix longer-wiwo error on others' profiles

---

addons/editor-dark-mode/3dark.css
addons/editor-dark-mode/3darker.css
addons/editor-dark-mode/dark-editor.css

**Resolves**
Resolves #1834
**Changes**
Fixed a bug that made scrolling with the mouse wheel impossible in Chrome in all editor dark modes except Experimental Dark.

Make scrolling possible in dark mode again

---

addons/scratchstats/userscript.js

**Resolves**
Resolves #1890
**Changes**
Adds a missing `.toLocaleString()` to the profile statistics addon.

Fix missing comma in profile statistics

---

addons/mute-project/userscript.js

Reverts ScratchAddons/ScratchAddons#1923
This wasn't reviewed by W_L, and also, metakey might match more than Cmd. This requires more testing.

Revert "support Mac command key in mute project player"

---

popups/scratch-messaging/popup.css

**Resolves**
N/A
**Changes**
Removed the ineffective `overflow: hidden` and added `clip-path: inset(0 0 0 0)`
Z̴̧̨̯̥̙̼̙͓͇͉̲̫̤͗̅̎̽̽̑̂͌̀͜͝a̷̙̩̫̿͗͑̓l̸̨̢̢̛̝̖̿̌̑͂̓͑͒̎̃̉̑̂̄̀̆̈́g̸͕͙̖̩̯͐̃̓̂̀̑͛͒͛̍͜͝o̸̧̨͎̯̤͎̜̝̘̪̰͙͍͎͇͛͂͛͝ͅ ̵̛̝͛͑̎͑͗̊́̓̕͘͘͝͠m̸͍̃̉̓̈́͗̀ú̸͍̫̺̖̤̬͕̭̱̦̣̾̏̈́͒́̔͠s̸͚͈͎̭̝͂͊͗͂̓́̽̅͐̀̂́̿̿̍t̷̳̊̆̌́̏̐̿͂̒̎͋͑͐̇͠ ̶̢̯̳͇̝̥̭̙͔͒͑͊̓̏̍̆͒̋̔̓̀̉͠ͅb̷̦̳̉͑̇̌̚͜͝͝ȇ̶̻̹͙̜̞̲̥̖ ̸̡̧̖̦̰̳̯̌̃̀͗͂̍͐̐̋̅̇́̕͝s̶̡̼̝̘͖͚̜̲͍̥̓͗̉͗͆̓ͅͅt̴̢̧̞̩̤̱̜̗̮̭̯͖̖̗̳͐͐̏̈́͋̿́̈́̉̒́̋̈́̚̕͘ớ̶̪́̓͊̂̈͌̅̓̚p̷̡̥̞͔̯̝̙̂p̷̛͍͌̏̾̈́̍̿̾̃̿̂͑̇́͘͘͜ḙ̵̡̧͔̮̬͈͎̼̬̰̞̹̖̈́̊̎͛̓̄͜d̴̡̙̊̍͑͒̽̂̽̍̇̀̈̆̚͠ ̵͓̞̈́̽̎̆͛͆̓̏́̀b̶̟̭̠̀̊́̐̒̈́̋́̌̊̚͝ĕ̷̡̨̧̛͉̬̞͉̝̯͙̞͈͋͌̂͛̎͑̅̕͝͠f̸͈̫̀͆̾o̴̢̩͎͎̪̜̣̖͔̰̥̪͚̜͍͔̎̔̃͗̌̍̏ṟ̶̝̤̲͎͒̿̓̃͆͑̐͒ȩ̶̛̬͍̫̤̹̞̦̩̈́̒̄͌͝ ̶̻̜̽̎͂̀̈́̈́̍̀̓̋̃͜ͅi̷̖̘͈̼̮̻̫̘̺̠̹̘̱̠̲͚̝̐t̷͚̻̮͍̖̱̺̙̘͈͍̲̜̝̫͒̐̂̅͘͝ ̴̥͗͂̉̊į̵͍̭̪̦̰͎͖̺̭͎͎̯͚͎͖̓̾̆̋̑̽̍̇̏̒̀̀̓́͜͠͝͝ś̶̻̼̟̮͖͚͙̹͔̅̄͑ …

Fix anti-zalgo code

---

addons/addons.json
addons/drag-drop/addon.json
addons/drag-drop/dragged-over.css
addons/drag-drop/userscript.js

**Resolves**
Resolves #1227 
**Changes**
I added the ability to drag files into the costume/sound list, the sprites pane, and the stage sidebar thing. This inserts the dropped files into the same file input that is used by the "Upload Xyz" option in the slidey "Choose a Xyz" menu.
Some people, especially those not super versed with computers, prefer dragging files in from their file explorer instead of having to hunt through folders in a file selection window.
**Tests**
I dragged in various files into the drop areas I listed above. If you drag in a file that isn't supported, nothing happens. I'm not sure whether this will be incompatible with other addons, though.

Drag and drop files into the editor

---

addon-api/content-script/Addon.js
addon-api/content-script/Tab.js
background/get-userscripts.js
background/handle-messages.js
content-scripts/cs.js
content-scripts/inject/module.js
content-scripts/inject/run-userscript.js
libraries/CREDITS.md
libraries/comlink.js
libraries/license-info.json
manifest.json
webpages/settings/index.html

Resolves #1659 
- Adds Comlink for CS <> page communication. For it to work properly I had to use 4 about:blank iframes, not ideal but not a big deal either. Good part of using 4 iframes is that they message each other, so no message goes through the main Scratch frame, which should help avoid conflicts with other extensions.
- Previously, neither module.js nor theme CSS were injected until there was a `<head>`. That limitation was now removed, but userscripts should still be executed after the `<head>` is created.
- Use `import.meta.url` instead of `template#scratch-addons[data-path]`
- Introduce `scratchAddons.methods.copyImage` for copying images on Firefox without needing Tab.js to use the template element
- I could list every change, but TL;DR is that everything that previously used …

Use Comlink instead of `template#scratch-addons`, stop spamming contentScriptInfo

---

addons/hide-flyout/style.css
addons/hide-flyout/userscript.js

**Resolves**
Fixes #1876
**Changes**
I've replaced the CSS animation with a transition. This removes the need to have to define an animation for each thing animated, and CSS transitions are also capable of stopping and going in a different direction midway through a transition if, say, the user wiggles their mouse around a lot.
I've noticed that the hide animation didn't seem to work for me; the palette just disappears with the lock trailing behind.
**Tests**
This is the current animation on `master`:
This is the animation introduced by the PR:
I tried the various animation durations and toggle behaviours, and they seem to work the same as before.

Fix auto-hide block palette closing animation

---

addons/2d-color-picker/paint-editor.js

**Changes**
2d color picker addon [did not work properly in Firefox](https://user-images.githubusercontent.com/33787854/112880401-021bd180-9090-11eb-81e2-769684dd4f38.mp4) because of https://bugzilla.mozilla.org/show_bug.cgi?id=1376369, this fixes that

Fix 2d-color-picker in Firefox

---

.github/ISSUE_TEMPLATE/--new-addon.md

This changes the issue template. I think new-addon and addon are duplicative

Change new-addon issue template

---

addons/scratchstats/userscript.js

**Resolves**
Resolves #2005
**Changes**
* Changes `segment` to 6 (for some reason 7 is actually 8 days) and `range` to 364 (so that it's a multiple of 7) in the call to the graph API
* Removes the last point from the graph so that there aren't two points for the same day
@WorldLanguages These changes should probably also be made on scratchstats.com.

Fix profile statistics graph issues

---

addons/hide-flyout/style.css
addons/hide-flyout/userscript.js

**Changes**
Fixes some bugs in the hide-flyout addon:
1. v1.12.0 regression: When `positionElements` was run while the flyout was in the middle of a transition, the lock image and the placeholder element would be displayed in the wrong position. This could make parts of the editor temporarily unusable. The easiest way to reproduce this is scrolling the workspace while the transition is happening https://user-images.githubusercontent.com/33787854/112885042-dd2a5d00-9095-11eb-9810-6c8dead50e5e.mp4 In general the positioning logic should be much better now as it's now entirely CSS.
4. Category click mode would break after leave editor -> go back into editor
5. Lock button would display the wrong icon when locked -> leave editor -> go back into editor
3. If the "Toggle On..." setting changed …

Fix some bugs in hide-flyout

---

.github/ISSUE_TEMPLATE/--new-addon.md

Reverts ScratchAddons/ScratchAddons#2022
Someone clearly didn't read my annoucement. The `new addon` is for backwards compability/general category for new addons. This is NOT a duplicate!

Revert "Change new-addon issue template"

---

addons/folders/userscript.js

Fixes folders still causing crashes when trying to backpack a folder specifically when the backpack is empty

Fix crash when dragging folder into empty backpack

---

addons/folders/userscript.js

**Changes**
- Trick react into not rendering as much whenever something updates, fixes a performance regression caused by the addon
- Don't emit unnecessary workspace update when reordering targets when nothing needs to be updated
- Fix backpacking sound folders

folders: performance improvements and bug fixes

---

addons/mute-project/userscript.js

**Changes**
Previously, whenever you pressed and released the control key, *all* clicks on the green flag for the next couple seconds would toggle mute instead of clicking on the flag. Also, on macOS, if you were to hold the control key down for several seconds before clicking the green flag, it would open the context menu instead of muting.
This fixes all of that. Tested in Firefox on Windows and macOS.

mute-project: fix control key detection

---

addons/dark-www/addon.json
addons/dark-www/experimental_contact.css
addons/dark-www/experimental_project_embed.css

**Resolves**
Resolves #2039
**Changes**
Adds dark mode to embedded projects. This is intentionally part of website dark mode, not editor dark mode, because the place where most users see embeds are profile pages (live featured project).
Also removes a few lines of unused CSS.

Dark embedded projects

---

addons/dark-www/experimental_mystuff.css
addons/dark-www/experimental_profile.css
addons/dark-www/experimental_scratchr2.css
addons/dark-www/experimental_scratchr2_comments.css
addons/dark-www/experimental_scratchwww.css
addons/scratchr2/profile.css
addons/scratchr2/scratchr2.css
addons/scratchr2/studio.css

**Resolves**
Resolves #2049
**Changes**
Multiple changes to website dark mode:
* Fixes white textarea placeholders on profile pages (unfinished)
* Now a consistent color, `rgba(255, 255, 255, 0.4)`, is used for all gray text (preparation for #645)
* Fixes the border color of textareas on scratchr2 pages being different from other borders

Fix white profile placeholders and inconsistent gray text colors

---

addon-api/content-script/Tab.js
content-scripts/inject/module.js

Most of waitForElement logic is now moved to core, and one MutationObserver is reused for all calls of waitForElement.

Move waitForElement logic from addon-api to core

---

addons/live-featured-project/script.js

**Resolves**
Resolves an issue where the live featured project embed scrolls when it's not supposed to.
**Changes**
I added a single line of code. It adds the "scrolling, no" attributes to the iframe.
Scrolling is not supposed to happen, according to TheColaber.
**Tests**
Yes, I tested it by simply reloading the page when I make a new change.

Disable scrolling

---

addons/addons.json
background/load-addon-manifests.js

Whoops, while resolving conflicts `wrap-lists` ended up being twice, and the settings page listed the addon twice hehe
Easy fix to avoid problems, do not run extension if there's duplicates, good investment even tho it takes a few hundred CPU cycles :P

Throw if addons.json has duplicated addon ID

---

webpages/settings/index.html
webpages/settings/index.js

Resolves #2196 
Resolves #2097
Do not call `._valueChanged()` in the color picker if it doesn't exist
Doesn't cause any bugs because when created, the color picker will grab the updated color from `this.value` through the `v-bind:value` HTML attribute

Fix loading presets for colors & allowTransparency:false not working

---

addons/60fps/userscript.js

Resolves #2153 properly
In most devices, it checks whether `e.altKey` is true when clicking the green flag
In chromebooks, it instead assumes a right click in the green flag is an alt+click

Better handle key/mouse events in 60fps

---

content-scripts/inject/module.js

The waitForElement MutationObserver used to specify `attributes: false`, but it seems it was accidentally changed to `attributes: true` in #2061 which is *very bad* for performance, especially in the editor.
This shouldn't cause any addons to misbehave as this was the old behavior.

Fix waitForElement MutationObserver options

---

addons/addons.json
addons/editor-sounds/addon.json
addons/editor-sounds/userscript.js

**Resolves**
Resolves #993
**Changes**
It adds sounds to the editor by enabling the disabled-by-default sound support in Blockly/scratch-blocks
Here's what they sound like: https://user-images.githubusercontent.com/33787854/115614282-22b40180-a2b3-11eb-93c6-9960109ace98.mp4

New addon: Editor sound effects

---

addons/drag-drop/addon.json

**Changes**
The addon is now properly described with the new 1.13.0 text file features.
New description:
> Lets you drag image, sound, and text files from your file explorer into the sprites pane, costume/sound list, ask and wait prompt, and list panes.
Because nobody reads old changelogs and future users may miss out on this feature.
**Tests**
I just changed the text in a JSON string so that shouldn't break anything

Update drag-and-drop addon description

---

_locales/en/messages.json

Regressed by #2259 
Turns out it's used.

Fix undefined message

---

content-scripts/cs.js

**Resolves**
this bug
**Changes**
added a fallback in case it's null
i'm seeing this
i want this
**Tests**
yes

css variables aren't being set bug

---

background/get-userscripts.js
background/load-addon-manifests.js

Resolves #23 
Resolves #646
Closes #2257 
New syntax is:
- `*`: allow any URL on Scratch origin.
- string starting with `^https:`: treat as regex that matches origin+pathname, aka absolute regex
- string starting with `^` but not `^https:`: treat as regex that matches pathname, aka relative regex
- Array of:
- absolute or relative regexes (mentioned above)
- shortcut: `projects` (excl. embeds), `projectEmbeds`, `studios`, `studioComments`, `profiles`, `topics`, `newPostScreens` (topics + new topic), `editingScreens` (newPostScreens + signature setting), `forums` (excl. mobile forums)), `scratchWWWNoProject` (all scratch-www pages, except project page and embeds)
- shortcut matchers: `isNotScratchWWW`, which can be used like "is scratchr2?"
- legacy match (aka current match) is kept …

Add improved userscript matching

---

addons/2d-color-picker/paint-editor.js
addons/60fps/userscript.js
addons/animated-thumb/userscript.js
addons/blocks2image/userscript.js
addons/clones/userscript.js
addons/color-picker/code-editor.js
addons/color-picker/paint-editor.js
addons/confirm-actions/userscript.js
addons/copy-message-link/project.js
addons/disable-auto-save/userscript.js
addons/discuss-button/userscript.js
addons/drag-drop/dragged-over.css
addons/drag-drop/userscript.js
addons/editor-messages/userscript.js
addons/editor-searchable-dropdowns/userscript.js
addons/folders/userscript.js
addons/hide-flyout/userscript.js
addons/last-edit-tooltip/userscript.js
addons/mediarecorder/userscript.js
addons/mouse-pos/userscript.js
addons/mute-project/userscript.js
addons/onion-skinning/userscript.js
addons/pause/userscript.js
addons/project-info/blockcount.js
addons/project-info/projectstats.js
addons/project-notes-tabs/userscript.js
addons/variable-manager/userscript.js

- Makes a lot of addons use the new waitForElement spec (#2182) to reduce the amount of querySelectorAlls that are run in response to any DOM change. This can significantly reduce Scratch Addons' impact on performance in large projects.
- Removes unnecessary waitForElement usages
I did a test where I dragged some blocks around in the player sprite of https://scratch.mit.edu/projects/60917032/editor/ with a bunch of addons enabled:
Before: 30+ querySelectorAll / 134ms per DOM change (https://share.firefox.dev/3ayMSgu)
After: 2 querySelectorAll / 10ms per DOM change (https://share.firefox.dev/2QHjgXx)
The difference is immediately noticeable. The remaining two querySelectorAlls are in hide-flyout (only when mode is category click or category hover) and addon.tab.scratchClass.
The likelihood …

Use the new waitForElement spec and remove unnecesary waitForElement calls to improve performance

---

content-scripts/cs.js

To repro, disable an addon without userscripts (e.g. website dark mode), and see how another addon disappeared from the "currently running list"
Dumb bug, easy fix

Fix wrong addons being listed as dynamically disabled

---

background/get-userscripts.js

Resolves bug with no issue number. Repro:
1. Open anything else but a project
2. Go to settings page
3. Enable 60fps addon (or any other project addon)
4. Come back to tab you opened in step 1
5. Open addons popup
6. It says 60fps is running on tab, when it has no userscripts nor userstyles running on the page

Do not send dynamicAddonEnabled message with no userscripts/styles

---

addons/cat-blocks/addon.json
webpages/settings/index.js

This also makes cat-blocks a new addon, which is kinda a lie, but worth doing :P

Settings: ignore patch when checking if addon is new

---

addons/forum-time-zones/userscript.js

`getDate()` in the code clearly was intended to be used in the code of this addon to calculate how many days have have happened since the post, but that method only returns the day of the month, not number of days since a specific date.
Fixes wrong dates when posts were older than a month. Example: https://scratch.mit.edu/discuss/topic/217432/ (showed "today", was posted in 2016)

forum-time-zones: use days since epoch instead of day of month

---

addons/my-ocular/reactions.css

**Resolves**
https://scratch.mit.edu/discuss/post/5199993/
**Changes**
Reactions are no longer overlapped or split into two when there are too many of them to fit on a single line.
**Tests**
Tested with this post: https://scratch.mit.edu/discuss/post/5199335/
Before:
Now:

Fix ocular reaction wrapping

---

webpages/popup/style.css

**Resolves**
Resolves #2394
**Changes**
Makes the popup arrow on Firefox orange and removes unused CSS.
It looks better.
**Tests**

Make Firefox popup arrow orange

---

addons/scratchr2/addon.json
background/get-userscripts.js
content-scripts/cs.js

This is an easy implementation of #1976 (Resolves #1976)
If the status code of the page is not 2xx, instead of userscripts and userstyles being matched to the real url (e.g. `scratch.mit.edu/nope`) they are matched against slash + status code (`scratch.mit.edu/404`).
Some details about this implementation:
- Does not work on iframes to avoid complexity
- Addons aren't able to target specific URLs if they don't return 2xx. Not sure why an addon would want to do that, tho
- This implementation does not try its best to run the userscripts and userstyles as fast as if the page returned a 2xx status code, not because we need to wait to get the status code, but because **the content script is in charge** of requesting contentScriptInfo again if the original getContentScriptInfo request …

Match userscripts/styles to scratch.mit.edu/[statusCode] if not 2xx

---

addons-l10n/en/my-ocular.json

swaps the link from my-ocular.jeffalo.net to ocular.jeffalo.net in the l10n
**Resolves**
Resolves #2404
**Changes**
Switches the link from my-ocular.jeffalo.net to ocular.jeffalo.net/dashboard
everything from my-ocular.jeffalo.net is now in ocular.jeffalo.net

Switch my-ocular to ocular

---

addons/last-edit-tooltip/userscript.js

Resolves own unshared projects 404ing
Weird timing & cache issue in Scratch's side. We request API info without x-token, which will 404 for unshared projects because we're not authorized. Real request by Scratch to get project info will hit the cache and also get 404, even tho that request does have valid x-token header.
To solve this issue, we simply make sure to send x-token header from the addon as well. This fixes the issue and also makes the addon work in unshared projects.

Modify last-edit-tooltip to avoid Scratch 404ing own unshared projects

---

addons/folders/userscript.js

PR #2420 switched `condition` functions that only consisted of Redux state to `reduxCondition`s. All changes kept the same behavior, except this one, where a `!` was forgotten.
See https://github.com/ScratchAddons/ScratchAddons/pull/2420/files#r628910519

reduxCondition regression: missing !

---

webpages/settings/index.js

Better alternative to #2439. However requires one zip for Chrome and another for Firefox, since manifest.json is going to be different
Note that the builds released in stores do have different manifest.json contents anyway, since each store adds their own unique update_url URL

Make clipboardWrite a Firefox-only browserLevelPermission

---

.eslintrc.json
content-scripts/cs.js

Fixes a crash caused when clicking profile pages in Firefox.
New eslint rule disallows accessing `path` property of `e`, `ev` and `event`. This allows both false-negative and false-positive (e.g. SVG) but I expect people to follow conventions.

Disallow and remove use of Event.path

---

addons/editor-dark-mode/experimental_editor.css

**Resolves**
Resolves #2433
**Changes**
Makes the text of questions asked by the stage visible.

Fix unreadable ask prompts with editor-dark-mode

---

addons/exact-count/addon.json
addons/exact-count/studio.js

**Resolves**
Resolves #2491 
**Changes**
make it compatible with 3.0 studios and with 2.0 studios
because
also we should keep the count even tho it's not in vanilla scratch anymore because
1. we shouldn't remove features if we dont need to
2. we already have the code
3. it's a nice feature
**Tests**
on local scratch-www

Migrate `exact-count` to scratch-www

---

addons/scratch-messaging/background.js
popups/scratch-messaging/popup.js

Resolves #2046 
Caveats:
- Links aren't supported yet. No links will be clickeable, including scratch.mit.edu links

Use JSON API for retrieving/replying/deleting comments in projects and studios (scratch-messaging)

---

addons/editor-devtools/DevTools.js
addons/editor-devtools/blockly/BlockFlasher.js

Most of these are minor nitpicks that no one will notice, except the first one
1. Use the find bar to switch between broadcast receivers across sprites was not very reliable: https://user-images.githubusercontent.com/33787854/117884225-fa943e80-b271-11eb-9d3f-5e9fc372e9b9.mp4
2. On Linux systems, middle click is usually assigned to paste for some reason, which caused issues when middle click was used to open the floating block palette
3. Floating block palette would appear in wrong spot if user middle mouse clicked without first moving the mouse
4. Floating block palette did not work properly when opened immediately after leaving custom block menu sometimes
5. Floating block palette text input could not be interacted with using the mouse

editor-devtools: fix some bugs

---

addons/true-youtube-links/addon.json

Changing `https://scratch.mit.edu/*` match to matching only places where users can provide links (comments, about me in profiles, project notes, studio description, forums)

True YT link addon: stop using wildcard scratch.mit.edu/* match

---

webpages/settings/light.css

Resolves #2530
Faded the description color in light mode to match the contrast level with the background in dark mode.
Because readability before was bad:
And also consistency with dark mode:
Doesn't appear to recolor anything else unintentionally.

Fix addon descriptions in light mode

---

addons/addons.json
addons/ctrl-click-run-scripts/addon.json
addons/ctrl-click-run-scripts/userscript.js

This is a feature that was originally part of #2470.
When the addon is enabled, scripts will only run when they are clicked while holding down the Ctrl key.
W_L approved
Achieves its purpose without negative side effects.
Do your best to break it and let me know if you find anything.

New addon - Ctrl+Click to run scripts

---

popups/scratch-messaging/popup.js

Title, it would throw "cannot get property map of undefined" if res was `{"error": "notReady"}` for obvious reasons
Also removed a timeout from the days you could not remove popups, unused now
Bug introduced by #2431 when adding alerts feature

scratch-messaging: fix stMessages being null when error:notReady

---

background/get-userscripts.js
content-scripts/cs.js

Surprisingly, my usual test case of opening a Scratch tab on startup with focus by default stopped working.
It looks like the tab is loading before we register `chrome.runtime.onMessage`, which is weird, one would expect extensions would be able to run sync operations before any tabs loading but whatever :P
Fix is ugly but lets us avoid edge cases like opening "a Scratch tab with an iframe on it on startup with focus". (edit: redid properly, tested succesfully in edgecase)
@mxmou Maybe this is what was causing `Unchecked runtime.lastError: The message port closed before a response was received.` for you?

Fix addons not running on browser startup

---

background/get-userscripts.js

Doesn't actually fix any bugs
Not sure how it happened, but making sure we're not causing an memory leak by checking if `cacheEntry` is undefined and unregistering the event

Fix edge case TypeError in get-userscripts.js

---

addons/transparent-orphans/addon.json
addons/transparent-orphans/userstyle.css

Resolves https://github.com/ScratchAddons/ScratchAddons/discussions/2551#discussioncomment-767955
Adds 2 new setting options, plus the name change to support dragged blocks, and all other blocks in general.
> Snap (snap.berkeley.edu) solved on[e] of the more annoying Scratch problems, that is dragging a reporter block in the right argument, making the dragged block semitransparent.
I have tested it, it works great.

Make Transparent orphan blocks support more blocks

---

addons/transparent-orphans/addon.json

~~Resolves W_L's issues~~
Old:
> Adjust the transparency for all blocks in general, orphaned blocks (those without a hat block at the top) and blocks that are being dragged.
New:
> Adjust the transparency for blocks in the editor, with separate options for orphaned blocks (those without a hat block at the top) and blocks that are being dragged.
It's now more clear that there are separate color options for each of the three block "types" described.

Update description for the "Block transparency" addon

---

addons-l10n/en/scratch-messaging.json

Resolves #2583 
Currently we use "post" as verb and "comment" as noun

Change "posts" to "comments"

---

content-scripts/cs.js

From feedback:
> issue: even with no addons well, on. for some reason posting blank it says. You can't post an empty comment, like usual, then try to post it again it crashes scratch. without the extension, it just says You can't post an empty comment
Apparently React doesn't like when you remove an element it owns from the DOM
So now, it only removes elements owned (created) by cs.js
Could also be workarounded with `display: none`, but the original code never intended to remove/hide vanilla Scratch comment warnings.
`try {} catch {}` wouldn't have avoided this issue, since its not our code throwing, but React's, after it not expecting the element to have been removed by us.
Also, added some safer code in last commit just in case Scratch changes the comment component

Fix project page crash in edge cases (caused by "avoid commenting SA" code)

---

addons/custom-block-shape/userscript.js

Fixes #2033
Tested on padding sizes ranging from 50-200. Text is centered (within a couple pixels) at all sizes
I've only tested on a strange Linux system. I see no reason why it wouldn't work on Windows, but do make a brief check (surely you do that anyways, right?)

custom-block-shape: fix #2033

---

addons/fix-pasted-scripts/userscript.js

If a duplicated reporter was dropped onto a field, the script could still run sometimes
Also changed how the addon tries to inject, should be more reliable

Fix Do not automatically run duplicated blocks edge cases

---

content-scripts/cs.js

Fixes potential double discuss button on browser startup
Any received `contentScriptInfo` response will be thrown if `receivedResponse` is `true`

Make sure to only run userscripts once

---

webpages/settings/components/addon-body.html
webpages/styles/components/badges.css

Resolves #2681
* Removes `max-width` from collapsed addon descriptions
* Tags no longer wrap
* Addon names no longer wrap until the window is so small that the description becomes invisible

Fix addon body CSS

---

addons-l10n/en/my-ocular.json
addons/dark-www/experimental_forums.css
addons/my-ocular/reactions.css
addons/my-ocular/reactions.js
addons/scratchr2/forums.css

Jeffalo recently updated the ocular UI for reactions to initially only show reactions with a non-zero reaction count and added a tooltip that lists the users who reacted.
Adds these changes to the ocular addon. The tooltips are limited to 5 usernames because the post container has `overflow: hidden` so part of the list could otherwise be cut off.

Update ocular reactions UI

---

addons/editor-dark-mode/addon.json
addons/editor-dark-mode/experimental_editor.css
addons/editor-dark-mode/stage.css
content-scripts/cs.js
libraries/common/cs/text-color.esm.js
libraries/common/cs/text-color.js

Resolves #2415
Adds a feature described in https://github.com/ScratchAddons/ScratchAddons/pull/1805#issuecomment-827611354
* Adds the Boolean setting described in #2415
* Adds a setting to change the color of blue text and icons (ideally the tool buttons in the paint editor would also be affected but those icons also use other colors and I'm not sure if there is an SVG filter that would only affect a specific color)
* Makes the selection background and handles in the sound editor affected by the highlight color setting
* Removes now unused camera modal styles
There is a new type for custom CSS variables, `"recolorFilter"`, which returns a filter function that can be used to change the color of monochrome icons.
To allow more customization.
Tested with different values of both settings.

Add two new settings to editor dark mode

---

addons/dark-www/addon.json
addons/dark-www/experimental_confirm_email_modal.css
addons/scratchr2/scratchwww.css

Resolves #2170 although I don't think this is actually what the issue was originally about
Makes the links in the confirm email banner and the modal opened by one of those links styled correctly.

Fix unreadable email confirmation modal

---

webpages/settings/components/category-selector.html
webpages/settings/index.html
webpages/settings/index.js

Thanks @Ascor8522
Uses `<a href="" target="_blank">` instead of `window.open()`
Adds popout icon

Make it clearer links on settings page go to scratchaddons.com

---

addons/dark-www/addon.json

This got outdated, we won't be supporting more "versions"
@mxmou Please approve
Before:
After:

Remove useless setting type:select from dark-www

---

addons/debugger/userscript.js
addons/editor-theme3/theme3.js

- Changes how the block "previews" are generated to not rely on an actual Blockly block existing.
- don't try to scroll a block in a flyout into view.
- make the button not disappear when entering and leaving fullscreen.

debugger: fix #2771 and some other bugs

---

webpages/settings/components/addon-setting.html
webpages/settings/components/addon-setting.js
webpages/settings/index.js

This improves speed of key inputs (when they are actually used) but also removes the querySelectorAll which can remove up to 0.5 seconds of load time!!
This should not change any functionality.
This also moves `updateOption` to the addon-settings component.

Move `handleKeySettings` to addon-settings component

---

addon-api/content-script/blocks.js

- Fixes https://scratch.mit.edu/users/GarboMuffin/#comments-146974453 or "can't delete procedure when addon blocks are used". Root cause is a bug in Scratch, this is a workaround
- Don't show "Edit" when right clicking on an addon block

Fix deleting procedures when debugger blocks exist and don't show "Edit" context menu item

---

webpages/settings/index.js

Easy fix: no addons group the `_iframeSearch` pseudogroup should match search if the search input is empty. Addons not from that pseudogroup continue to match search if the search input is empty for obvious reasons.
To reproduce:
1. Open "addons" tab in popup
2. Search for a disabled addon with the search bar
3. Clear the search term - all search results stay

Settings popup: fix disabled searched addons staying after clearing search

---

addons/copy-message-link/profile.js

Logic is simple:
1. Store number of comments on the page (initially 0).
2. Wait for a new comment element that doesn't match `[data-sa-copy-link-pass = currentPassNumber]`. This could match new comments (such as new posts or loading more comments pages), as well as comments we already added the button to before but we might need to add again.
3. Set the `data-sa-copy-link-pass` on the found comment to `currentPassNumber`.
4. Add the "copy link" button to the comment if it doesn't have it.
5. Check if amount of comments on the page has changed. If so, add 1 to the current pass number. This means all comments will be checked again.
6. Back to 2.
This works properly in all realistic situations, and there are no potential performance concerns unless the user posts a new comment.

Fix "copy link to comment" not working properly on profiles when loading more pages

---

addons/studio-tools/addon.json

Still enabled by default, but can change.

Mark studio-tools as beta addon

---

content-scripts/inject/module.js

Resolves #2885 
Fixes a bug where same-URL navigation added `/undefined` at the end of the `newUrl`

Fix bugs with urlChange event

---

addons/editor-theme3/addon.json

Unless I'm missing something, this addon does not require a reload after being enabled or disabled, so remove the notice that says it does.

editor-theme3: remove refresheditor notice

---

addons/scratchr2/profile.css

I changed the bottom border radius for banner add-on just to look more appealing to the eye. 
The two cornered radius borders look ugly in the 3.0 add-on with the banner add-on. I think it should be changed
Add this bit of code down below to the 3.0 add-on css file for the profile page
```css
.box#profile-data .box-head {
border-bottom-left-radius: 10px;
border-bottom-right-radius: 10px;
}
```
Much better
It works when a inspect the scratch website.
When i disable the banner and apply the code it looks normal. Nothing changed without the banner on.
@mxmou this is your add-on so I think i need approval from you first.

Change bottom border radius on banner add-on

---

addon-api/content-script/blocks.js
addons-l10n/en/debugger.json
addons/debugger/userscript.js

addon.tab.addBlock:
- API changed to accept an object for most arguments instead of passing four of them individually (cleaner when more and more arguments get added)
- Now accepts an optional displayName argument that allows the internal procedure code and the text that is displayed to be different when the addon is enabled.
Debugger addon:
- Debugger block names are now translatable and can be changed without compatibility concerns
- Fixes #2883
- Fixes block previews for procedure arguments: https://user-images.githubusercontent.com/33787854/123903560-86eae580-d934-11eb-8c38-11f7af2ea63d.png

debugger: translatable block names and some bug fixes

---

addons/addons.json
addons/disable-stage-drag-select/addon.json
addons/disable-stage-drag-select/userscript.js

Resolves #2709 
I've added a new addon called disable-stage-drag-select. All it does is redefine the dragStart and dragStop functions to return instantly, essentially deleting them.
This adds the functionality to drag sprites in the editor and not select that sprite or call the dragStart or dragStop functions in the virtual machine.
I tested it on one of my projects which I need it for: https://scratch.mit.edu/projects/524385137/. The result was that it did exactly what I needed it to do.
However, since I don't have access to the stage container and the methods contained within it, I couldn't remove the onDragStart or onDragStop methods, so the sprite will still go the top and be slightly offsetted when dragged. It will also still be selected on double click. This is only a minor …

Added disable-stage-drag-select addon

---

webpages/settings/index.js

Better fix than #2900, by avoiding giving Fuse an object owned by Vue
I'll clean up this later, I promise, it's pretty messy rn

Fix addons changing order after toggle on search

---

webpages/settings/components/addon-body.html
webpages/settings/style.css

Makes the area that can be clicked to expand or collapse an addon on the settings page larger. This makes using the Addons tab in the popup much easier.

Increase hitbox for expanding/collapsing addons

---

addons/expanding-search-bar/addon.json
addons/expanding-search-bar/expanding-search-bar.js

Adds dynamic enabling/disabling to Expandable search bar.
To add dynamic enable/disable to more addons.
Tested on Firefox. Also did some tests with switching in/out of editor, and on scratchr2 pages.

expanding-search-bar: add dynamic enable/disable

---

addons/addons.json
addons/dark-www/experimental_scratchwww.css
addons/old-studio-layout/addon.json
addons/old-studio-layout/classes.js
addons/old-studio-layout/default.css
addons/old-studio-layout/scratchr2.css
addons/old-studio-layout/style.css
addons/scratchr2/addon.json
addons/studio-tools/migrated.js

Resolves #2935
Adds an addon that reverts studios to either the old design or the 2.0 → 3.0 design. Adjusts studio-tools for compatibility with the added addon and attempts to fix a bug causing the leave button to not always appear.
Default:
Scratch 2.0 → 3.0:
Adding projects:

Add old studio layout addon

---

addons/editor-stepping/addon.json
addons/editor-stepping/userscript.js

Resolves #2957
Adds a color option to recolor the border in the editor-stepping (Highlight currently executing blocks) addon. Also slightly rewords the addon to not use the word blue. The default color is still #0000FF blue.
Some people may not like the blue or think it's too strong:
>**FunctionalMetatable wrote:**
>
>I don't want blue to be the only color available for the highlighting blocks addon.
Tested on Firefox, should work on Chrome.

editor-stepping: Allow changing highlight color

---

addons/infinite-scroll/addon.json

Resolves #2991
Adds a settingMatch for forumScroll to discuss.css in the `infinite-scroll` addon. This fixes a bug where the page navigation is always hidden even if the forums option is disabled.
Bugfixing.
Tested lightly on Firefox only, should work on other browsers.

infinite-scroll: add settingMatch to discuss.css

---

addons/studio-followers/lib.js
addons/studio-followers/modal.css

Changes to the Browse Followers modal:
- Makes profile pictures square and stretch to fit
- Removes unnecessary CSS and uses Scratch classes instead
- Makes the add icon smaller and closer to the edge so that it doesn't cover too much of the profile picture

Improve follower tiles and remove unnecessarily duplicated Scratch CSS

---

addons/infinite-scroll/buttonScroll.js
addons/studio-followers/modal.css
addons/studio-followers/userscript.js

- Changes the number of items loaded at once to 28 (four rows, two if old studio layout is enabled)
- Replaces infinite scrolling with a Load More button to match Scratch's add projects modal
- Remembers the scroll position when switching between Followers and Following tabs

Improve Browse Followers modal scrolling

---

popups/scratch-messaging/light.css
popups/scratch-messaging/popup.css
webpages/settings/light.css

- Fixes the recently changed expand button hover state not working in light mode
- Makes the same change in the messaging popup
- Fixes a small gap in the messaging popup (caused by a change in #2871 - an element can't have more than one `min-height`)
- Fixes part of the rounded corners of some message types being cut off

Small CSS fixes

---

addons/old-studio-layout/classes.js

Fixes "add projects" pseudobutton not being there after going to projects tab, then to another tab, then back.

old-studio-layout: properly keep "browse projects" button

---

addon-api/content-script/blocks.js

- More thoroughly validate proccode and displayName using the same logic as Scratch
- Automatically ensure all arguments in displayName are preceded by whitespace so Scratch will parse it correctly
- This fixes some debugger blocks missing text inputs in some languages and will ensure that cases like this are (almost) impossible moving forward:

Improve addon.tab.addBlock displayName

---

addons/better-img-uploads/userscript.js

Resolves #3027 
Reasons for this change:
- GIF files are already of poor resolution in most cases
- Most GIF files are animated and hard to deal with (do we see static GIF anywhere?)
- We can't add omggif (GIF parsing library used by Scratch) just for this small feature

better-img-uploads: remove gif from acceptable files

---

addons/2d-color-picker/paint-editor.js
addons/color-picker/paint-editor.js
addons/onion-skinning/userscript.js

See https://github.com/LLK/scratch-paint/pull/1698/files#diff-ba47b319faac03f59857691b06c8b1f8896c38c7c5bd0b28c230993d77eecc2aR4
The check uses Redux. For 2d-color-picker and color-picker this is fine because both addons are already powered by redux. For onion skinning this is not the case, so I just ignored any error that could come from lack of redux.

Stop addon execution when color picker update is detected

---

addons/last-edit-tooltip/userscript.js

Uses redux instead of fetching by itself in last-edit-tooltip to get the dates
Less requests
Tested locally (edge)

last-edit-tooltip: use redux instead of fetching

---

addons/dark-www/experimental_scratchr2.css
addons/dark-www/experimental_scratchwww.css
addons/semicolon/semicolon.css

Resolves #1604
Adds dark background to semicolon when both semicolon and dark-www addons are enabled.
Tested locally

dark-www: fix `semicolon` addon showing white background and incorrect font color

---

addons/editor-stage-left/fix-share-the-love.js

Just cleans up some old code and fixes some potential uncaught errors.
- replace urlChange, editorMode, and setInterval with getBlockly
- fixes dynamic enable/disable throwing error if workspace does not exist (don't think this actually broke anything)
- should work slightly more reliably

editor-stage-left: rewrite fix-share-the-love without urlChange

---

addons/editor-dark-mode/addon.json
addons/editor-dark-mode/bubbles.js

Changes editor dark mode to use the accent background for speech bubbles if the `affectStage` setting is enabled.

Dark speech bubbles

---

addons/exact-count/user.js

Omitting credentials makes it possible for Scratch to return a cached HTML source, because there's no login data.

exact-count: use fetch instead of XHR, omit credentials

---

addons/editor-stage-left/fix-share-the-love.js

- Fixes https://discord.com/channels/751206349614088204/819307061493760031/869286894578577479
>1. Load the editor with editor-stage-left off
>2. Drag any block from the block palette (not workspace) into another sprite
>3. Enable editor-stage-left (dynamicEnable)
>4. (Try to) drag any block from the block palette (not workspace) into another sprite
- Fixes mouse coordinate blocks reporting wrong values after dynamic enable/disable

editor-stage-left: fix a couple bugs

---

addons/60fps/addon.json
addons/mute-project/addon.json
addons/pause/addon.json

Makes 60fps, mute-projects, and pause addons run in embeds again, allowing them to be used together with live featured project.

Run 60fps, mute-project, and pause in embeds

---

addons/editor-dark-mode/addon.json

Resolves #2246
Adds TurboWarp's dark mode as a preset for the `editor-dark-mode` addon.
Because a lot of people like TurboWarp's dark theme and it's annoying having to set each colour manually.

Add TurboWarp dark mode as a preset for editor-dark-mode

---

webpages/settings/index.html

Adds the `v-cloak` attribute to the settings search toolbar.
To fix autofocus. https://github.com/ScratchAddons/ScratchAddons/pull/3036#issuecomment-888597549

Add `v-cloak` to search toolbar

---

addons/turbowarp-player/style.css
addons/turbowarp-player/userscript.js

See https://github.com/ScratchAddons/ScratchAddons/pull/2682#issuecomment-888570607
Makes the TurboWarp stage the same size as Scratch's stage and removes the now unnecessary background and border from the iframe.

We can keep the stage the exact same size

---

addons/infinite-scroll/addon.json
addons/infinite-scroll/footer.css
addons/infinite-scroll/moveDonor.js

Resolves #1600
In the `infintie-scroll` addon, this adds a simple userscript for the home page that simply moves the donor text (the "Scratch is available for free..." text) into the footer, allowing it to show when the footer is hovered over instead of being at the bottom of the page.
This also adds a CSS variable for the hovered footer's height so that the userscript can change it to make the text visible once it runs.
Not having the donor text be with the footer just looks weird.
Seems to work.
The donor text script moves the text about 1-2 secs after the footer style loads which is okay.

infinite-scroll: Fix donor text with "fix footer"

---

addons/editor-devtools/DevTools.js
addons/turbowarp-player/userscript.js

- An error that occers with the turbowarp addon when seeing inside
- The clean up message in the context menu when you change the setting for devtools.
Yep, self merging, these changes are only on master, not on stable.

Fix TurboWarp Addon Error and Devtools clean up msg being wrong

---

addons/editor-colored-context-menus/userscript.css
addons/editor-colored-context-menus/userscript.js
addons/editor-dark-mode/experimental_editor.css
addons/editor-theme3/theme3.css
addons/editor-theme3/theme3.js

Resolves #2553
Resolves #2644
Resolves #3002
Fixes some bugs in the customizable block colors addon:
* Improves compatibility with developer tools and colored context menus
* Fixes result bubbles and color pickers being affected
* Fixes white text on variable and list reporters in "colored on white background" and "colored on black background" modes
* Dropdown changes

editor-theme3 fixes

---

addons/compact-messages/addon.json

Am i doing this right?
Adds a "credits" category to addon.json
Because the credits paragraph doesn't show up when locally testing. every other addon has it.
I did download my fork and test it, and it looks like this:

Add credits to Compact Messages Addon

---

addons/scratchr2/forums.css

Resolves #3133
Makes the whole post visible when opening a link to it.

Fix post links with Scratch 2.0 → 3.0

---

addons-l10n/en/studio-tools.json
addons/studio-tools/migrated.js

Resolves #3013
Removes locale `username` and replaced by native scratch-www message
why are we wasting translators time :P
tested locally

studio-tools: remove locale `username` and replace with native message

---

addons/default-project/addon.json
addons/default-project/userscript.js

Resolves https://github.com/ScratchAddons/ScratchAddons/pull/3046#issuecomment-889397472
Note that there was never real data loss, this only happened if you never clicked "save now"
This also makes it work reliably while logged out

default-project addon: work while logged out, avoid corrupt empty projects

---

addons/ctrl-enter-post/forums.js

Stops errors in console when ctrl-enter-post in forums are enabled and topic is closed
Errors fill up the console
Tested locally

ctrl-enter-post: stop erroring in console when topic is closed

---

addons/forum-search/userscript.js

Bug fixed upstream months ago, no need to escape ourselves. If they do send a bad payload the check below knows.

forum-search: remove dead code in cleanPost

---

_locales/en/messages.json
webpages/settings/components/addon-setting.html
webpages/settings/components/reset-dropdown.html
webpages/settings/style.css

#3156 increased the number of reset buttons and dropdowns, which take up quite a bit of space. The icon is enough to make their purpose obvious, so this makes them smaller by removing the labels.

Remove labels from reset buttons

---

addons/editor-stage-left/fix-share-the-love.js

From feedback:
> When setting the scratch editor's language to Arabic and then enabling the (Display stage on left side), The Method of deleting blocks by throwing them in the Catagory Displayer becomes broken.
Hopefully this is the last time I have a reason to touch this file

editor-stage-left: fix fix-share-the-love in RTL languages

---

addons/addons.json
addons/paint-by-default/addon.json
addons/paint-by-default/userscript.js

Adds an addon that makes the "Choose a Sprite" and "Choose a Costume" buttons create an empty sprite/costume instead of opening the library. Does not change the "Choose a Sound" button.
Has been requested a couple times:  
https://discord.com/channels/806602307750985799/806609030935740477/871487795456249877  
https://discord.com/channels/806602307750985799/806602307750985803/871533280233664522

New addon: Create empty sprite/costume instead of opening library

---

addon-api/content-script/Tab.js

It's a very inconsistent, but sometimes this could happen:
fix is simple: s3devToolBar is an ID, not a class

Fix variable tab getting inserted after devtools find bar sometimes

---

addons/msg-count-badge/addon.json
addons/msg-count-badge/background.js

Resolves #1756.
Currently, it is impossible to tell the difference between not having any messages and not being signed in. Because Scratch sessions can expire without action on the user's behalf, a user may falsely believe that they have no messages under the notion that they're still logged in.
It's also useful to know when the Scratch website experiences downtime and/or if the network connection as a whole is down.
A new option has been added to "Message count on extension icon". It's disabled by default.
When the option is enabled, a special badge appears when the user is offline, signed out, or having other connection issues to Scratch.
Additional options are available to customize this offline badge.
The default red for the setting has also been added as a preset for the regular …

msg-count-badge: add indicator when signed out

---

addons/editor-dark-mode/addon.json
addons/editor-dark-mode/experimental_editor.css
addons/editor-dark-mode/paper.css
addons/editor-dark-mode/paper.js

Adds a setting (on by default) that controls if editor dark mode affects the costume editor.
Feedback: https://github.com/ScratchAddons/ScratchAddons/pull/3077#issuecomment-894536073

Make dark costume editor optional

---

addons/better-img-uploads/userscript.js
addons/drag-drop/addon.json
addons/drag-drop/userscript.js

Resolves a bug where all drag-drop uploads were HD when better-img-uploads is enabled. In case anyone wants old behavior, this is now a setting (off by default, only shows if someone is using HD upload addon).
This code should not break in most circumstances - if better-img-uploads is not available when the settings is true, then it'll just fallback to normal upload (aka existing code path). Dynamic enabling of better-img-uploads should also be fine. It might break when better-img-uploads was dynamically disabled (drag-drop would still upload as HD), but better-img-uploads isn't dynamically disableable yet, so who cares

drag-drop: do not HD-upload images

---

addons/editor-theme3/theme3.js

Resolves #3275
Fixes custom block parameters using the text color of their parent block in colored text modes. Apparently the `.blocklyDraggable` class is not set consistently.

Fix incorrect text color of custom block parameters

---

background/get-userscripts.js

See the code below for changes:  (do not cheat and read the comments in diff!)
```js
!((injectable.if.addonEnabled?.length && (Array.isArray(injectable.if.addonEnabled) ? injectable.if.addonEnabled : [injectable.if.addonEnabled]).every((addon) => !scratchAddons.localState.addonsEnabled[addon])) || (injectable.if.settings && Object.keys(injectable.if.settings).some((settingName) => (Array.isArray(injectable.if.settings[settingName]) ? injectable.if.settings[settingName] : [injectable.if.settings[settingName]]).every((possibleValue) => settings[settingName] !== possibleValue))))
```
Should not affect current addons, but might affect future addons.

Change logic of matchesIf

---

addons/debugger/userscript.js
content-scripts/cs.js
webpages/settings/index.js

Requires changes to website
Users can opt out of sending enabled addons list when sending feedback

Include list of enabled addons when sending feedback

---

addon-api/common/Self.js
addon-api/content-script/Addon.js
addons/live-featured-project/addon.json
addons/live-featured-project/script.js
addons/turbowarp-player/addon.json
addons/turbowarp-player/userscript.js
background/get-userscripts.js
content-scripts/cs.js
content-scripts/inject/module.js

Resolves #3285 
Of course, if people wants old behavior, they can toggle the settings.
Other stuff:
- New API: `addon.getEnabledAddons(tag)` (CS only) - get a promise of list of enabled addon IDs, optionally filtered with a tag. This must contact the background because project player might not be embedded on a project page and thus is not loaded on CS (i.e. live featured project)
- URLSearchParams to correctly pass multiple sometimes-missing params.
- Embed iframe now has a feature policy. Both will disable document-domain (to promote its deprecation, does not actually do anything). autoplay, camera, microphone are used by Scratch; fullscreen and gamepad by TurboWarp implementation.
- live featured project sets src attr, so `'src'` is enough.
- turbowarp-player's location.replace hack …

Run addons in TurboWarp embed

---

addons/block-switching/addon.json
addons/block-switching/userscript.js

Resolves #557
Adds an option to block-switching to replace custom block args. Options are off (no arg switching), only in custom block definitions, and all (every arg can be replaced with any other arg anywhere). Note that boolean and string/num args can't be switched between.
'Tis useful and easy.
Tested on chrome.
The settings probably need a change of wording.

Custom block arg switching

---

_locales/en/messages.json
content-scripts/cs.js
webpages/settings/data/addon-groups.js
webpages/settings/index.js

"New" group is now collapsed on page load, unless user comes from the update notification.
If an addon is either recommended or featured, it gets into "featured new" instead of "new".
How it looks with "new" expanded, as if user came from update notification:
With "new" collapsed:

Separate "featured new addons" and "other new addons" addon groups

---

addons/addons.json

scratchblocks addon will no longer be loaded, enabled or even recognized by the SA. Code will remain. If you can fix this mess, please make a PR. If nobody can before v1.19 releases, then the code will be removed as well.
We can't ship a broken addon.

Do not load scratchblocks addon

---

addons/comments-linebreaks/addon.json
addons/comments-linebreaks/break-spaces.css
addons/comments-linebreaks/userscript.js
addons/scratch-messaging/background.js
libraries/common/cs/format-profile-comments.js

Resolves #3340
Also refactors comments-linebreak; no longer uses userscript for WWW, and supports dynamicEnable. dynamicDisable-ing is currently impossible due to profile comment mess.

scratch-messaging: fix profile comments with linebreaks

---

addons/paint-by-default/userscript.js

Fixes a bug: The addon treated the "Add sound" button as if it was the "Add costume" button if the current sprite had no sounds

paint-by-default: fix sound setting when no sounds exist

---

background/get-userscripts.js

Makes the `scratchWWWNoProject` regex match `/explore/*/*/popular`.
To fix themes not working on those URLs. Bug reported by Scratch user VRPS.

Fix `scratchWWWNoProject` not matching explore page popular mode

---

addons/drag-drop/userscript.js

This provides slightly better feedback to the user about what will happen if they drop a file. On Windows, this changes the tooltip from "Move" to "Copy". Similar changes happen on other operating systems.

drag-drop: set dropEffect to "copy"

---

addons-l10n/en/block-switching.json

Block is called "start sound" since 3.0

Block switching: "play sound" → "start sound"

---

addons/editor-searchable-dropdowns/userscript.js

Items now get sorted in this order:
1. Exact matches
2. Items that start with the query
3. Items that contain the query
https://discord.com/channels/806602307750985799/806609030935740477/865200426861199362
Tried using Fusejs for a little bit and it didn't seem to work particularly well, so I'll just leave it like this

editor-searchable-dropdowns: smarter searching

---

addons/remix-tree-button/addon.json
addons/remix-tree-button/main.js

Resolves #1262
Discussion happened in the issue, but in a nutshell, this level of customization is not suitable for a settings page GUI. If users really want to style specific buttons, they should create their own CSS userstyle.

Remove "button color" setting from remix-tree-button

---

_locales/en/messages.json
addons/hide-new-variables/addon.json
addons/remix-button/addon.json
content-scripts/cs.js

I also made remix-button not be featured anymore, and hide-new-variables be featured. Which makes more sense. hide-new-variables is very useful, and remix-button is just a funny hack which rarely is useful by itself.
Youtube video TODO, will be replaced in the notification in a few days.

Add v1.20 update notification

---

addons/infinite-scroll/buttonScroll.js

Related to #3238
Some users couldn't load more followers, so it's better to remove infinite-scroll support until we find a solution.
Weirdly enough, infinite scrolling works differently for the vanilla "browse projects" modal and our own "browse followers" modal? Strangely, what we do is make infinite-scroll tell browse-followers to handle the infinite scrolling by itself:
https://github.com/ScratchAddons/ScratchAddons/blob/master/addons/studio-followers/userscript.js#L139

Disable infinite-scroll for studio-followers

---

addons/block-cherry-picking/userscript.js

This fixes https://discord.com/channels/751206349614088204/755131743136383107/887443591931244574 and many more bugs

block-cherry-picking: only modify opt_healStack if called from startBlockDrag

---

addons/block-cherry-picking/userscript.js
addons/ctrl-click-run-scripts/userscript.js

block-cherry-picking and ctrl-click-run-scripts now detect the control key more reliably. Notably, devtool's paste context menu item will no longer cause issues. It will also avoid issues when alt+tabbing while holding control.

More reliable ctrl key detection

---

addons/editor-dark-mode/addon.json
addons/editor-dark-mode/experimental_editor.css

Adds a preset to editor dark mode that uses colors from Scratch 1.4.
If `affectStage` is enabled:

Scratch 1.x preset

---

webpages/settings/components/addon-setting.html

Related to #257
Makes checkboxes on the setting page look like this:
To make it obvious that the label is on the left side.
Works on Chrome and Firefox.

Blue switches

---

addons/block-cherry-picking/addon.json
addons/block-cherry-picking/userscript.js

Previously, dragging the top block of a script would always drag the entire script regardless of control being pressed or not. Now it's possible to drag just the top block.
The "flip controls" setting is always disabled when dragging the top block. This matches the current behavior which allows people to easily move scripts around without pressing control when that setting is enabled. They can still drag just the top block by pressing control, which is weird, but I'm not aware of a better solution. Adding another setting seems unnecessary.

block-cherry-picking: allow cherry-picking the top block of a script

---

addons-l10n/en/confirm-actions.json
addons/confirm-actions/addon.json
addons/confirm-actions/userscript.js

Parity with the editor unshare button which already has confirmation.
Suggested by CreativeCat at https://discord.com/channels/806602307750985799/806609030935740477/891940176845217812

confirm-actions: confirm project unshare

---

manifest.json

Resolves #3476 
There's no issues with addon.auth because we already support Firefox containers. That means, Scratch Messaging and Notifier will continue to make use of the account that's logged into the main session, not incognito.
Related: #203

Allow extension usage on incognito

---

addons/my-ocular/reactions.js

I've added support for ocular easter egg emojis, this is in preparation for an update to ocular, see https://github.com/jeffalo/ocular/pull/109
Any reaction that starts and ends with a colon, will load an image from ocular.jeffalo.net/emojis/, these can only be set by admins currently, however it will be extended in the future. 
This PR just makes sure that they don't look funny when the changes to ocular launch.
Compatibility between ocular.jeffalo.net and the addon.
I've tested this locally.

show ocular easter egg emojis

---

addons/editor-theme3/theme3.css

Resolves #3702 
Changed line 18 of theme3.css from `fill: none` to `fill: #0000`
To fix the bug that was in #3702
I haven't actually tested it, but @awesome-llama did. See https://github.com/ScratchAddons/ScratchAddons/issues/3702#issuecomment-950198535

Fix "editor-theme3 reduces size of clickable area in block dropdowns "

---

webpages/settings/components/addon-body.html
webpages/settings/components/addon-body.js
webpages/settings/components/addon-setting.html
webpages/settings/components/addon-setting.js
webpages/settings/components/picker-component.js
webpages/settings/components/reset-dropdown.js

Changes
https://github.com/ScratchAddons/ScratchAddons/blob/d6f41737c8162e6feeb98f6a9f5b479378e8b813/webpages/settings/components/addon-body.js#L30-L32 to
https://github.com/ScratchAddons/ScratchAddons/blob/7cdda720df1b3392951616a189984828706aac8c/webpages/settings/components/addon-body.js#L30-L32
Which basically changes all other stuff that uses addonSettings (addon-body, addon-settings, picker, etc.) to change something like this:
```js
this.addonSettings[this.addon._addonId][property] = "hi"
```
to something like
```js
this.addonSettings[property] = "hi"
```
addon-body and addon-settings don't need to include the same thing 1000 times (and also this is something I did for my table pr for nested addon-settings).
Tested.

[addon-body]: make `addonSettings` also include the addon id

---

addons-l10n/en/editor-devtools.json
addons/editor-devtools/DevTools.js
addons/editor-devtools/DomHelpers.js
addons/editor-devtools/userscript.css

If ~~Ctrl~~ Shift is held while clicking on the workspace or dragging a block from the middle-click find bar, it will not  be closed. The layer of the floating find bar is also lowered so that it appears below dragged blocks.
A little quality-of-life feature to allow rapid creation of scripts.
Tested.
~~This might have some issues combined with block cherry picking, but hopefully it should be fine.~~

`editor-devtools`: Shortcut to not close the floating find bar

---

addons/addons.json
addons/fix-editor-comments/addon.json
addons/fix-editor-comments/fix-drag.js
addons/fix-editor-comments/scroll.css
addons/fix-editor-comments/standalone-edit.css

Resolves #2475 (https://github.com/LLK/scratch-blocks/issues/1566 with duplicates https://github.com/LLK/scratch-gui/issues/4776 and https://github.com/LLK/scratch-gui/issues/5948)
In vanilla Scratch, when dragging a block with a comment attached to it, the position of the comment is not saved correctly, causing it to jump back to its original position when the sprite or project is reloaded. This addon fixes this bug.
Also, when the contents of comments are clipped due to the comment bubble's size, a scroll bar does not appear on the comment. This addon implements this scroll bar.
In addition, comments not attached to blocks cannot be edited directly -- the user must click the comment for it to gain focus, and only then can it be directly edited. This addon makes it so that the cursor can …

New addon: better editor comments

---

addons/disable-stage-drag-select/userscript.js

Alt+tabbing while holding shift will no longer cause problems
Very similar to #3513

disable-stage-drag-select: more reliable shift key detection

---

addons/block-switching/userscript.js

- Fixes custom block arg switching misbehaving after deleting and adding arguments of varying types (root cause appears to have been a Scratch bug where argumentdefaults is not updated properly)
Should resolve https://discord.com/channels/751206349614088204/755131743136383107/907390137330176000
- Show each unique argument name at most once
- Clean up some old code
Compare with & without patch on https://scratch.mit.edu/projects/597673801/

block-switching: fix custom block arg switching bugs

---

addons/animated-thumb/addon.json

Resolves #2334 (makes `animated-thumb` a community addon)
Adds the `community` & `projectPage` tags and removes the `editor` & `menuBar` tags from `animated-thumb`.
> This should be a "community" addon, not an "editor" addon - editor addons are about the project itself, and thumbnails are only a concept as part of the community site.
_Originally posted by @WorldLanguages in #2334._
Even though the set thumbnail button moved to the project page, it was still found under the editor category on the settings page. If this was done for a reason, just close the PR.
None.

animated-thumb: add community tag

---

addons/editor-devtools/DevTools.js

Very minor optimization.
The standalone devtools extension doesn't support these, but that's fine. It's not particularly important.

editor-devtools: add missing reduxEvents and reduxCondition

---

addons/swap-local-global/userscript.js

The old canUserUseCloudVariables() was unreliable in certain situations, although as far as I'm aware Scratch Addons itself wasn't affected (not entirely sure, there might be some weird edge case). This makes it work reliably everywhere and should be more resistant to any Scratch changes.

swap-local-global: theoretical bug fix

---

addons/editor-comment-previews/addon.json
addons/editor-comment-previews/userscript.js
addons/editor-comment-previews/userstyle.css

- Don't needlessy force the flyout to completely rerender
- Various other minor optimizations
- Fix comment previews in the flyout not working after leaving & entering editor
- Don't show preview for comments that only contain whitespace
- Right clicking should hide preview as left clicking already did
- Improve preview readability in browsers that don't support backdrop-filter (Firefox)
- Hovering over a text input will now show the comment attached to the block that the input is in (previously it would show nothing, don't know if that was intentional)
- Fix various other bugs

editor-comment-previews: fix some bugs

---

addons/hide-flyout/userscript.js

Resolves #3736
In hover mode, when the workspace is dragged and the mouse enters the flyout area, the flyout no longer opens.
The flyout still opens when a block is being dragged for deletion.
When the mouse is released while still hovering over the flyout area, the flyout will reappear.
The category hover and category click modes are unaffected.
The user does not intend for the flyout to open when the workspace is being dragged.
Tested in browser w/ Chromium 95 and Firefox 94.0.1.

`hide-flyout`: suppress flyout on workspace drag

---

addons/editor-searchable-dropdowns/userscript.css

Resolves #3806
Makes the searchable drop-down borders solid instead of dashed.
Tested briefly on Edge.

Use solid border in editor-searchable-dropdowns

---

addons/progress-bar/addon.json

Resolves #2412.
- Sets the minimum progress bar height to 3.
- Sets the maximum progress bar height to 25.
Any progress bar height lower than 3 causes it to be unreadable because of the 1px border and any height higher than about 26 pixels causes it to overflow the menu bar when saving the project.
Tested on Edge 96.

progress-bar: Set height limits

---

addons/my-ocular/reactions.css

Chromium recently started using outlined emojis in bold text (I'm not sure if that happens everywhere or just on Windows). The ocular reaction menu button icon isn't meant to be outlined, so this fixes it:
I'm not sure if the ocular icon should be changed or not because it's part of a link.

Fix outlined reaction menu button icon in Chromium

---

addons/swap-local-global/userscript.js

Accidentally left hardcoded class hashes in some selectors. They shouldn't be there.
Old code works fine in Scratch but can break in modified environments or if/when Scratch changes prompts.

swap-local-global: remove hardcoded class hashes

---

addons/emoji-picker/userscript.js
addons/emoji-picker/userstyle.css

Resolves #3843
Related to #3840
Makes the font of the emoji picker button and its Unicode emojis normal-weight.
Google made an amazing new ""feature"" in Chrome where bold emojs are outlined for absolutely zero reason.
Tested in Chrome. Should work in Firefox.

`emoji-picker`: fix Unicode emojis and button in Chrome

---

addons/block-cherry-picking/userscript.js

- Don't drag comments attached to blocks underneath the cherry-picked block
https://user-images.githubusercontent.com/33787854/143664568-b8ebdfb8-c597-4392-989f-b2e00fdc7ace.mp4
- Fix editor breaking when you start cherry-picking the top block of a script, drag it away from where it started, then drop it in the same place where it started

block-cherry-picking: bug fixes

---

addons/scratchr2/scratchr2.css

Currently, the 2.0 --> 3.0 addon breaks project selection in the `featured-project-modal` modal on profile pages. This fixes that.
**Steps to Reproduce:**
1) Enable the 2.0 --> 3.0 addon
2) Go to your profile page
3) Try changing the featured project
Current:
After:
Tested on Firefox 95 and Edge 97

Fix featured project selection

---

addons/account-settings-capitalize/addon.json
addons/account-settings-capitalize/style.css

Resolves #3808
Makes the "Capitalized Account Settings" addon work in the editor.

Capitalize "Account Settings" in editor

---

addons/customize-avatar-border/addon.json

https://cdn.discordapp.com/attachments/819307061493760031/913834834156199976/unknown.png

fix(addon): `customize-avatar-border` - hide `Outline color` when `Hide outline` is off

---

addons/hi-res-thumbnails/userscript.js

Fixes hi-res-thumbnails freezing the page when going into the editor.

hi-res-thumbnails: fix editor crash freeze

---

addons/onion-skinning/userscript.js

- Fixes #1661 by converting vector onion layers to bitmap internally, which improves performance and fixes crashes. They're dynamically rendered up to 4096px wide/tall, so quality doesn't suffer unless you zoom in very far.
- Fixes #3872. All onion layers will be displayed at the same time. Bitmap onion layers also load faster now because they're loaded in parallel.
- Other performance improvements

onion-skinning: Improve performance and fix bugs

---

addons/scratchr2/forums.css

Text on ocular reaction buttons was unreadable when website dark mode and Scratch 2.0 → 3.0 were enabled. This fixes it.

Fix ocular reaction buttons when both dark mode and 2.0 → 3.0 are enabled

---

addons/editor-comment-previews/userscript.js

- Don't display comment preview when hovering over the thin line that connects comments to their block. It was too small to be useful for actually wanting to read a preview but it was possible to accidentally trigger.
- Fixed uncaught errors when resizing comments (didn't actually break anything)

editor-comment-previews: Fix a couple small bugs

---

addons/onion-skinning/userscript.js

Further testing shows some browsers have a significant performance issue when dealing with images larger than 3840px that can make the costume editor unusably slow, so lower the maximum size of rasterized vector layers to be under that.

onion-skinning: Lower max size of rasterized vectors to improve performance

---

addons/better-img-uploads/userscript.js

Resolves [this suggestion](https://discord.com/channels/806602307750985799/806609030935740477/901762244633825330)
In the HD image upload addon, sets the transform property to scale the image instead of setting the width and height parameters (which cause Scratch to pixelate the image, which we don't want).
This makes HD image uploads actually HD in the `Stretch to fill stage` and `Shrink to fit stage` modes.
Tested 5 different test images in all 3 modes in Firefox. The image wasn't pixelated in any of them.
Test images used in case you want to test yourself:
* [Image 1](https://user-images.githubusercontent.com/68464103/145687920-54933d17-3ef3-4759-ad50-aa37d589fcf8.png) (1000x1000)
* [Image 2](https://user-images.githubusercontent.com/68464103/145687922-6084ff49-87ed-430e-8343-a916bbf0214 …

fix(addon): `better-img-uploads` - scale image properly

---

addons/customize-avatar-border/addon.json

Response to #3866
In the "Customizable profile picture border" addon, also shows the "Outline color" option when the "Fill transparent profile pictures" option is on.
The "Fill transparent profile pictures" option also uses the "Outline color" option for its color, so it doesn't make sense to hide it when that option's on.
Works.

fix(addon): `customize-avatar-border` - don't hide `Outline color` when `Fill transparent profile pictures` is on

---

addons/hi-res-thumbnails/userscript.js

Resolves #3893.
**Not a blocker for release,** but would be nice to have!
Two major tweaks:
1. Downscale images when the default resolution is larger than it's actually displayed at.
2. Use arbitrarily determined dimensions as the basis for images which may dynamically be displayed larger than they currently are (only current case: studio project thumbnails).
~~**Still need to do this third change before worth merging:**~~ Done!
3. Auto-replace `projects.scratch.mit.edu` images with cdn2 480x360 images as a preprocessing step—this will generally be downscaled to whatever size the image is actually displayed at (e.g. on the homepage 145x110).
Save people's network data by not loading higher resolutions than needed! But also, in doing that, don't accidentally make images look bad (when …

High res thumbnails: Downscaling + Special cases for larger-than-rendered dimensions

---

addons/dark-www/darker_banners.css
addons/dark-www/desaturated_banners.css
addons/dark-www/experimental_scratchwww.css
addons/dark-www/experimental_scratchwww_white_bg.css
addons/dark-www/experimental_search.css
addons/dark-www/scrollbar.css

Resolves #3939
Makes scrollbars on Firefox gray instead of blue. This also affects overscroll background on Edge and background of the window while a Scratch page is loading on all browsers.

Fix blue scrollbars on Firefox

---

addons/dark-www/experimental_scratchr2.css

Resolves #3941
Makes Material icons smaller when dark mode is enabled. This could be a temporary solution to #3941, but it will need to be reverted before merging #3940.

Temporary fix for Material icons and dark mode compatibility

---

libraries/common/cs/text-color.js

Fixes part of #3938
Firefox and Chromium use different default color spaces for SVG filters (Chromium doesn't follow the specification for some reason). This defines the color space explicitly to produce the same result on both browsers.

Fix incorrect icon color on Firefox

---

addons/editor-searchable-dropdowns/userscript.js

Fixes https://github.com/ScratchAddons/ScratchAddons/issues/4095
There is no "bigger bug" as hinted by above issue. Creating a local variable in the stage set isLocal=true in the editor's version of the variables, which caused swap-local-globals to misbehave. The problem would've been fixed after saving and loading the project.

editor-searchable-dropdowns: do not allow creating local variables in the stage

---

addons/swap-local-global/addon.json

This addon is pretty robust and we haven't found a bug for months. Great job garbo!

Remove beta tag from swap-local-global

---

background/load-addon-manifests.js

Code could use logical nullish assignment (`??=`) but Chrome 84 and below would break

Fix `(addon-id/@credits-undefined)` in non-English

---

addons/scratch-notifier/addon.json

My bad, ids shouldn't have spaces

Avoid using spaces in manifest credit.id

---

addons/editor-theme3/addon.json

Resolves https://github.com/ScratchAddons/ScratchAddons/pull/3995#issuecomment-1015796175 (thanks redguy!)
I added a `temporaryNotice` because users might not notice that the last setting is what's new.

Add latestUpdate to editor-theme3 (forum scratchblocks)

---

addons/better-img-uploads/userscript.js
addons/hide-delete-button/costumes.css
addons/hide-delete-button/sounds.css
addons/variable-manager/userscript.js

Resolves #4102 
Note that variable-manager one is not causing issues from what I know; it's just to fix duplicate IDs which should never happen in HTML. The id itself is meaningless.
Changelog:
- hide-delete-button does not hide the buttons after leaving and re-entering the editor.
- better-img-uploads button disappears after leaving and re-entering the editor.

Fix editor tab ID immutability issues

---

background/load-addon-manifests.js

Fix crash while loading manifest

---

background/get-addon-settings.js

Who approved this code 🤔 (yes, this is the one bug we can solve by typechecking. Or maybe not. We don't want an enum of addon IDs just for this, and it still wouldn't solve this issue because it can be partially initialized. But we don't want to mark every usage of addonSettings as potentially fallible. Hmmm)

Fix crash on initial install

---

addons/editor-searchable-dropdowns/userscript.js

vm.editingTarget can be null while the project is still loading. This adds a check to fix an error introduced by #4096

editor-searchable-dropdowns: check that editingTarget isn't null

---

addons/onion-skinning/userscript.js

Remove unnecessary rounding so that vector onion layers aren't shifted a pixel or two from their true position. Most noticeable when zoomed in on small costumes.

onion-skinning: fix vector layers being a couple pixels off

---

addons/block-palette-icons/userstyle.css

Resolves https://discord.com/channels/806602307750985799/806602307750985803/936692119454744666
changed `backgound-size: 17px 17px;` to `background: cover;`
the icons were offcenter
inspect element

Fix uncentered block-pallate-icons

---

libraries/common/message-cache.js

because `id` can be arbitrary and does not have to be in order

Compare datetime_created when checking for new messages

---

addons/scratchr2/scratchr2_comments.css

Resolves #4161
Adds `z-index: 1;` to `.actions-wrap` so that it is over the commenter name (but below the modals)

scratchr2: fix z-index

---

addons/better-featured-project/userstyle.css
addons/scratchr2/profile.css

Resolves #4154
This should fix an issue on profile pages that happens consistently on macOS and on specific zoom levels on Windows when both Scratch 2.0 → 3.0 and profile page banner are enabled.
Tested in Edge on Windows. Someone who uses macOS would need to check if this fixes the problem there as well.

Attempt to fix broken profile layout on macOS

---

addons/clones/userscript.js
addons/variable-manager/userscript.js

Some addons trapped `vm.runtime._step` while some other addons trapped `vm.runtime.constructor.prototype._step`. If an addon that used the first approach ran first, any addons that used the second approach would not work. This converts everything to use the first approach.
Fixes #4184 and another instance of the same issue in variable-manager

Fix _step trap race affecting clones and variable-manager

---

addons/debugger/userscript.js

This makes debugger's go to block feature work again. Previously it would silently error.

debugger: fix go to block

---

addons/editor-stepping/highlighter.js

Fixes editor-stepping spewing errors when the editor hasn't been opened. I don't think this actually broke anything. It could've broken some other editor addons, but the error wouldn't happen when the editor is open anyways.
https://discord.com/channels/751206349614088204/758464349768515604/939767789902762014
https://scratch.mit.edu/projects/579616012/#comments-249378616

editor-stepping: Don't spew errors if workspace is null

---

addons/dark-www/addon.json
addons/forum-quote-code-beautifier/main.css
content-scripts/cs.js

Resolves #4209
Makes the background of code blocks inside quotes use either the gray background or default code block background color, depending on which is more appropriate, when forum-quote-code-beautifier.
`"type": "ternary"` value providers for `customCssVariables` now accept other value providers as `true` and `false` values.
The color in the example screenshot still produces the same result because it is quite dark, but lighter colors now behave as expected.

Fix code blocks inside quotes again

---

addons/dark-www/blue_banners_scratchr2.css
addons/scratchr2/addon.json
addons/scratchr2/mystuff.css
addons/scratchr2/v_tabs.css

Resolves #4211
Makes the delete account confirmation page look not broken (which doesn't mean good, but it isn't a page people would use very often) if Scratch 2.0 → 3.0 is enabled.

2.0 → 3.0: fix delete account confirmation page

---

popups/scratch-messaging/popup.js

Resolves #4215
`After the messaging refactor, the "Loading messages..." text no longer appears when opening the messaging popup, which makes loading seem much slower. `
So now it works 😄

Error with not showing loading message

---

README.md

Changes the wording for step 1 a bit, and changes `right-hand` to `left-hand` in step 2.
The instructions for Firefox in the [README](https://github.com/ScratchAddons/ScratchAddons#from-source) tells users to click a button the the right-hand menu, but it actually is in the left now. 
Improving instructions to install the addon from source.
This doesn't change any file except `README.md`, so I haven't tested it.

Improve install from source for Firefox

---

addon-api/content-script/Tab.js
addon-api/content-script/Trap.js

Mitigates #4212
Note: commit name is inaccurate, every addon will compute clientVersion when requested for the first time, and it will be cached only for the addon that requested it.

Compute addon.tab.clientVersion only when the addon needs it

---

addons/dark-www/experimental_forums_preview.js

Removes a reference to a file that no longer exist.
It was showing errors in the console.

Remove reference to `experimental_forums.css` from dark-www userscript

---

popups/scratch-messaging/api.js
popups/scratch-messaging/popup.html
popups/scratch-messaging/popup.js

Hides Delete button for comments in others' profile/project. Not doing this for studio comments, since that'll require an additional API request just for that.

scratch-messaging: hide Delete when inapplicable

---

addons/msg-count-badge/addon.json

Resolves the issue of the message count badge looking wrong. 
Added "Orange" preset to message count badge
- The badge doesn't match the extension logo 
- Other extensions with badges on my device use colors similar to their logos(/icons).
- This adds an SA-color orange preset to make the logo and badge look good together.
It works. ☑️

New "orange" color preset for msg count badge

---

popups/scratch-messaging/api.js

This doesn't fix the underlying bug, it just means it will show the message without other replies when it fails.

scratch-messaging: fail soft when missing replies

---

addons/addons.json
addons/forum-live-preview/addon.json
addons/forum-live-preview/style.css
addons/forum-live-preview/userscript.js

Resolves #2395
Adds an addon that removes the preview button in the forums and instead automatically shows the preview when the user stops typing for a second (exactly a second right now, but that delay could be changed or made configurable).

Live forum post preview addon

---

content-scripts/cs.js
popups/scratch-messaging/popup.js

This message now appears when linking to the Chrome Web Store link for scratch addons, now that the regex is more strict:

Change regex for comments that mention "scratch addons"

---

addons/mute-project/userscript.js

Resolves #4299
basically just used what was in /addons/ctrl-enter-post/forums.js
So Mac users can use the CMD key.
can't test since I don't have a Mac

add cmd key support

---

addons/fix-pasted-scripts/userscript.js

This should be safer and faster; it won't trigger a workspace update
Fixes https://discord.com/channels/751206349614088204/751207339545198682/946687781265113119
Fixes https://discord.com/channels/806602307750985799/944919791477620746/945042894849474562
>repro steps:
>1) be logged out and use Chrome, go to /projects/editor/ with fix-pasted-scripts enabled
>2) create new variable
>3) neither toolbox block nor monitor appears
>4) refresh workspace (e.g. by switching tabs or sprites)
>5) toolbox updated, monitor still missing

 fix-pasted-scripts: don't break the flyout 

---

addons/mute-project/addon.json

Resolves [issuecomment-1050049569](https://github.com/ScratchAddons/ScratchAddons/pull/4320#issuecomment-1050049569)
Added notice to use CMD key on Mac.
So Mac users can know they use CMD
Tested on Windows 10, Firefox 97.0.1

Add Cmd Key notice to mute-project

---

addons/folders/userscript.js

On large projects, removing unused cache entries can be quite slow (>50ms for 2000 costume sprite). Converting an array to a Set makes it take only around 5ms at most on the same sprite.

 folders: Optimize cache 

---

background/declare-scratchaddons-object.js
background/get-userscripts.js
background/imports/change-addon-state.js
background/load-addon-manifests.js
content-scripts/cs.js

Resolves #4188
Took 3 hours to implement and 30 minutes to write this.
- `scratchAddons.dependents`: `object<Set<string>>` - set of addon IDs that declare the addon as `addonEnabled` dependency for userstyles.
- `getAddonData` and other places that handle an array of userstyles now receive an array of objects instead of strings. The object always has `href` (absolute URL to the style) and `index` (index in manifest, does not change if userstyle gets enabled/disabled), and additional `text` for `injectAsStyleElt` addons.
- Due to internal code changes, there's a maximum limit of userstyles per addon. Exceeding this won't throw error, but may cause unreliable style priority on some situations. Currently this is 100. If this is ever reached, a warning will be logged to the page console.
- …

Add partial dynamicEnable/dynamicDisable for userstyles

---

webpages/settings/components/category-selector.js

When you click the the accordion category that is already opened, the category is closed and the main / default category is then opened / selected.
I know this has been debated when I originally submitted the proposal, but hear me out.
Many accordion menus behave this way.
This commit just adds a behavior that is to be expected from such kind of menu.
It doesn't change anything for the users used to the menu's current behavior,
but it's still a nice quality of life improvement for those expecting it to behave that way.

Settings page - Allows closing an addon category by re-clicking on it.

---

addon-api/popup/Popup.js
background/get-userscripts.js
background/handle-unsupported-version.js
background/imports/global-state.js
content-scripts/cs.js

Resolves #4334 
Firefox 86 gives us access to the URL of tabs we already have a host permission for, so we can avoid sending messages to all tabs in Firefox, and instead do the same thing we've always done in Chrome, which is only messaging scratch.mit.edu tabs.

Change minimum supported Firefox version, remove unused code

---

webpages/popup/style.css
webpages/settings/style.css
webpages/styles/components/filter.css

It adds more consistency and better accessibility to the controls used in the settings page.
All the controls (buttons, reset input buttons, open color picker button, etc.) now show a pointer mouse cursor (pointing hand) when hovered.
It's now clearer that those controls are clickable.
It is basically the point of that cursor, so we might as well use it.
Suggested those changes back in August this year.
Didn't get a lot of feedback, but was mainly positive overall.
Even if this was never really requested, it's still a nice quality of life addition and doesn't hurt.

Settings page - CSS tweaks - Clickable controls now use pointer cursor

---

background/get-userscripts.js

Fixes a bug caused by #4346 that broke any scratch-www URL with a slash at the end, for example `/about/`.

Fix `scratchWWWNoProject` regex

---

addon-api/common/Self.js
libraries/common/notification-util.js

An intent-to-deprecate was issued, replacing them with general User-Agent detection.

Remove use of InstallTrigger for UA detection

---

libraries/common/global-theme.js
webpages/popup/index.js
webpages/settings/components/category-selector.html
webpages/settings/index.html
webpages/settings/index.js

Our April Fools, from March 31st 12:00:00 UTC+0 to April 2nd 12:00:00 UTC+0.
Took avocado hex color from [Wikipedia](https://en.wikipedia.org/wiki/List_of_colors:_A%E2%80%93F).
Popup changes: brand color, extension name (note that real extension name does not change, only this header). "Scratch Avocados" is not localized.
Settings page changes: brand color, avocado emoji on header next to "settings"

Scratch Avocados (April Fools)

---

content-scripts/prototype-handler.js

"All the world's a stage" mode, which would clear the `style` attribute of the `<html>` element, was removed: https://github.com/LLK/scratch-gui/commit/9a0200e0bb1e6d1b034cabf514db6fee588fc01d
So we can also remove our own fix that restored CSS variables to avoid issues with editor-dark-mode and other addons.

Revert now unnecessary April Fools fix

---

_locales/en/messages.json
webpages/settings/index.html
webpages/settings/index.js

Resolves #4360
Adds a button to view the raw settings file in the Settings page.
#4360
Like this
https://user-images.githubusercontent.com/97374054/157168220-b648ad40-b6ff-4cb1-9710-55684647f64a.mov
Well this is currently using `window.open()` so it counts as a pop-up, according to the user's browser settings, they may or may not see this message when they click the button
In vanilla JS, under a user event, pop-ups are allowed to be made (like when a button is clicked), but since this is using Vue, I don't think it works that way.

"View settings" button on settings page

---

addons/ctrl-enter-post/comments.js
addons/ctrl-enter-post/forums.js

Resolves #4451
Changes event listener to listen on `keydown` instead of `keyup`
`keyup` doesn't seem to work for the command key on Macs
Command key now seems to work on Firefox, macOS Big Sur, on both the forums  (posting a new post and editing)  and comments (scratchr2 + scratch-www). Also tested ctrl key on the forums and comments, works fine.

Fix command key not working on `ctrl-enter-post`

---

addons/animated-thumb/userscript.js

Resolves #4049
Changes the width of the image preview in the animated-thumb modal to make sure the aspect ratio is 4:3.

Fix thumbnail setter preview aspect ratio

---

addons/scratchstats/userscript.js

For example, it would display 
https://ibb.co/y4vkxHW
but now it shows
https://ibb.co/VNprHNH
Add .toLocaleString() 
Everything else is comma-separated so this just makes it consistent
I tested this with my browser

Most loves by country is comma sepperated

---

libraries/common/message-cache.js
popups/scratch-messaging/api.js
popups/scratch-messaging/popup.js
webpages/popup-loader.js

Referer is unnecessary when fetching from migrated API. Still required for r2 or proxy APIs. Also fixes a potential crash when a comment could not be sent.

Remove sareferer when unnecessary

---

libraries/common/cs/l10n.js

Support loading Structured JSON translations. Note that this PR does not introduce the new format. Structured JSON is specified at https://docs.transifex.com/formats/json/structured-json.
Future plans:
- `addons-l10n/en` will use a mix of key-value json and structured json; current syntax works fine, but you can also specify an object that meets the structured json spec.
- Since key-value json is not a valid structure json syntax, the script will convert that to actual structured json.
- After pulling the translated strings as structured json, the script will convert them to key-value json to save some bytes. Translations on this repository do not need developer comments, etc.

Support loading Structured JSON translations

---

webpages/settings/index.js

Resolves #4465
Code doesn't check for manifests length, but it filters if addon doesn't contains `easterEgg` tag.
Now you can't see it, because it is rounded to 5, but I removed it for test and it excluded all easter eggs correctly.

Exclude easter eggs from addon count

---

addons/scratchr2/scratchr2.css

Resolves #4497
Adds styles for alerts to the Scratch 2.0 → 3.0 addon. They're compatible with dark mode.
Alerts without text look exactly as broken as before:

Scratch 3.0-style alerts

---

_locales/en/messages.json
webpages/settings/index.html
webpages/settings/index.js

Resolves #4442
Adds a new "no results" message that is displayed when searching in a category other than "All". This doesn't work in the `easterEgg` category because it doesn't have a name.

Add selected category name to no results message

---

addons/60fps/userscript.js

Resolves #4523
Makes monitors update consistently when 60 FPS mode (Alt + green flag) is enabled. This is similar to TurboWarp's solution mentioned by @apple502j.
Tested by following the reproduction steps described in #4523.

Fix monitor updates in 60 FPS mode

---

addons/folders/userscript.js

DOM API is very slow when dealing with very large attributes like inline image sources. Manually generating a string is much faster.
On a test project, generating a very large folder preview used to take 20ms, now takes 3ms. Could be further reduced to almost zero if escaping is removed which doesn't sound like a great idea (even though I'm pretty sure it would be completely safe).

folders: optimize folder preview generation 

---

addons-l10n/en/folders.json

These are used by #3208 
Adding them separately to close string addition/modifications early

Add 2 new strings to folders addon

---

addons/scratchstats/userscript.js

Resolves #4543
The workaround added in #2016 is no longer necessary and is now causing issues. Remove that code, and make it work properly if the API somehow returned no results (by not rendering the graph at all).

scratchstats: fix graph rendering

---

addons/dark-www/experimental_scratchwww.css
addons/editor-dark-mode/experimental_editor.css

Resolves #4560 
Sadly there is no CSS keyword that reverts to previously defined non-inherited style. Also this is not a prio-2.

dark-www: fix stage monitor colors

---

addons/default-project/userscript.js
addons/progress-bar/userscript.js

Resolves part of #4603
TurboWarp integration pending Garbo opinions. Tested and found no regressions. Note that project token fetching logs an error but does not stop the loading of the specified project.
TODO:

Add support for project tokens

---

addons-l10n/en/cloud-games.json
popups/cloud-games/popup.css
popups/cloud-games/popup.html
popups/cloud-games/popup.js
popups/scratch-messaging/popup.css
popups/scratch-messaging/popup.html

* Changes the spacing around "Loading messages..." to match "No unread messages". It currently moves slightly when the loading is complete.
* Doesn't wait until messages are loaded before showing the bottom bar.
* Shows a placeholder similar to that on the settings page while cloud games are loading.
* Changes to the loading message for cloud games:
* It's now in front of the project list (not above it) to avoid layout shift
* Replaces numbers with a progress bar to make it easier to see the progress

Improve popup loading

---

addons/block-cherry-picking/userscript.js

Bug from feedback: https://youtu.be/EWxghIDN2xM - holding ctrl when pressing right click > duplicate causes buggy behavior
To fix this, I made it so ctrl clicking on right click > duplicate will now duplicate just that one block. This currently ignores the "Flip controls" option.

block-cherry-picking: Implement ctrl clicking on duplicate to duplicate just one block

---

_locales/en/messages.json

Resolves #4520
* Changes the title "Export and Import Settings" to "Export and import settings" to match "Scratch Addons theme" above
* Changes "Export Settings" and "Import Settings" to "Export/Import settings" to match all other buttons.

Change the capitalization of Export/Import Settings

---

addons/debugger/logs.js
addons/debugger/threads.js
addons/debugger/userscript.js

- Fix logs tab breaking when trying to generate a block preview for a deleted sprite or clone.
- The logs tab now records the name of the sprite when the log happens, not when it's displayed. This makes block links not display "(unknown sprite)" when a sprite or clone is deleted. This also makes links not update when a sprite is renamed which didn't happen reliably before anyways.
- Fix threads tab for blocks in flyout
Part of https://github.com/TurboWarp/scratch-gui/issues/537
Can be tested in https://scratch.mit.edu/projects/703936251/

debugger: Fix some bugs

---

addons/debugger/module.js

- Fix performance regression where pausing a project will make Scratch's sequencer do 25ms of unnecessary work every frame.
- Fix some bugs where breakpoints and single stepping could affect script execution order
- Fix error when you pause project with no threads -> start new thread -> try to single step
I've tested this on quite a few projects and haven't found any regressions so far (but have found many bug fixes), but with how complex the debugger is I wouldn't be surprised if there's something. I have verified that #4210 and #4281 are still fixed.

Fix some bugs in the pause and debugger shared module

---

addons/debugger/module.js

Further testing of https://github.com/ScratchAddons/ScratchAddons/pull/4674 reveals that it introduced a performance regression in some projects where some internal Scratch functions will be permanently slower (until reload) after pausing once, seemingly related to JS JITs not being able to optimize the getter/setter on thread.status very well.
https://scratch.mit.edu/users/GarboMuffin/#comments-212097554

Fix a performance regression in the pause and debugger shared module

---

background/get-userscripts.js
background/handle-settings-page.js
background/load-addon-manifests.js
content-scripts/cs.js

Resolves #4665
Addon state (whether addon was enabled or disabled) was previously only changed by enabling or disabling an addon directly. #4289 changed this by introducing partial dynamic enable and disable. However, there existed another way for userstyle addons to get enabled, involving a setting condition. Due to implementation quirks this actually added the style previously as well, but other effects normally achieved by (dynamically-)enabling addons weren't applied; this included addonsWithUserstyles array and custom CSS variables. This also applied to disabling.
The change consists of four parts:
- Warn if updateUserstylesOnSettingsChange was used without either dynamicEnable or dynamicDisable, and if a userstyle had a settings condition. This causes the described bug.
- If …

Handle settings change effectively changing addon state

---

addons/editor-dark-mode/experimental_editor.css
addons/editor-devtools/DevTools.js
addons/editor-devtools/userscript.css

- Fixes #1881
- Fixes "Find" moving vertically when you resize the window so that "(?)" toggles visibility
When the find bar is focused, it will always grow to a minimum size to make sure that it's actually usable. It may still cover up the controls when that happens, but that's okay because you're interacting with the input when that happens.
Tested in LTR and RTL languages.

editor-devtools: Fix find bar style bugs

---

popups/scratch-messaging/popup.css

Adds `font-variant: tabular-nums` to the number of remaining characters when replying to a comment in the Messaging popup. This prevents the width of the number from changing.
Before: ![chars_left_old](https://user-images.githubusercontent.com/51849865/177115005-9aee62e5-7e57-4dd3-8a7d-7ed4ac6286a4.gif)
After: ![chars_left_new](https://user-images.githubusercontent.com/51849865/177115351-28b28a78-9cc2-4004-b0d6-eda1e522d9e4.gif)

Add `font-variant: tabular-nums` to the number of remaining characters

---

addons/dark-www/experimental_scratchwww.css
addons/project-info/addon.json
addons/project-info/projectstats.js
addons/project-info/text-only.css
addons/project-info/userscript.css
background/get-addon-settings.js

Resolves #3378
Adds an option to add icons next to the `project-info` labels or remove the labels entirely.
It looks a little better with the icons and they were already available on Scratch's servers.
Tested on Chromium 103.

Add icons to project-info

---

addons/hide-flyout/addon.json

Resolves #4668
- Adds latestUpdate to addon:
- Credit Maximouse for the addon
- Change default mode to category hover. There's no migration, so it will only affect new Scratch Addons users - old SA users that had this enabled will still have category hover as the default. For this reason, I'm keeping the info hoverExplanation.

Add latestUpdate to hide-flyout, change default mode

---

background/get-addon-settings.js
background/handle-settings-page.js
libraries/common/minify-settings.js
webpages/settings/index.js

Resolves #4721
Removes unnecessary addon settings (missing, empty, etc) from the stored settings. Missing addon/setting check is not performed in development environment.
This reduces the storage size, hopefully allowing storage errors while I work on more permanent solution.

Minify stored settings data

---

addons/editor-unshare-button/userscript.js

Resolves the bug that @Norbiros commented over here: https://github.com/ScratchAddons/ScratchAddons/pull/4639#discussion_r906731593
To repro the bug on master:
1. Go to a shared project you own
2. Click the unshare button
3. Confirm the action
4. Click the share button
5. The editor-unshare-button addon thinks the "unshare" button was clicked, and asks to confirm
6. If the confirmations addon is set up to confirm sharing projects, it will also ask to confirm.
Bug was fixed by removing the confirmation described on number 5 - this addon shouldn't do anything if the "share" button was clicked after using the "unshared" button.

Fix editor-unshare-button bug

---

addons/data-category-tweaks-v2/userscript.js
addons/full-signature/addon.json
addons/full-signature/happen.css
addons/full-signature/happen.js
addons/full-signature/working.css
addons/full-signature/working.js
webpages/popup/index.js

Bug fixes:
* Data category tweaks: dynamic enable/disable didn't work correctly if any setting other than separate list category was enabled.
* Full areas: disabling the addon when the What's Happening load more button hasn't been clicked yet removed all items.
* An outdated comment in `webpages/popup/index.js`.
Other changes:
* Full areas now has dynamic setting changes. Interacting with an addon that has dynamic enable/disable but requires a reload to change settings can be confusing.
* Reenabling full areas now shows all items that were previously loaded so that the user doesn't have to click "Load more" again if they accidentally disable the addon.
Tested all changed addons.

Fix some bugs from #4627

---

addons/addons.json
addons/hide-stage/style.css
addons/hide-stage/userscript.js

The `addon.json` sets `"dynamicEnable"` and `"dynamicDisable"` to true but apparently I forgot to actually make dynamic enable/disable work. (This is probably what caused the button to not work in the changelog video - the addon was disabled so the userstyle was not loaded but the button was still there.)

hide-stage: implement dynamic enable/disable

---

addons/dark-www/experimental_scratchr2.css

Resolves #2106
Makes the ban message readable.
See screenshots below.

dark-www: fix banned response page

---

addons/better-quoter/userscript.js

Resolves #2018
Uses `#reply` instead of `scrollIntoView()` in `better-quoter`: 
It allows navigating back to the post being quoted and is consistent with Scratch.
Tested on Chromium 103

better-quoter: #reply instead of scrollIntoView()

---

addons/editor-stage-left/stageleft.css
addons/hide-stage/style.css
addons/hide-stage/userscript.js

A hidden stage is interpreted as 0x0 in some parts of the renderer which can cause infinite loops or crashes.
- Fixes https://github.com/ScratchAddons/ScratchAddons/issues/4857 (infinite loop in "touching mouse pointer" block)
- Hides code editor eye droppers when the stage is hidden because the user has no way to hover over the stage anyways. Previously attempting to use these would crash the editor.

hide-stage: Fix renderer crashes

---

addons/hide-flyout/userscript.js

Calls `Blockly.svgResize()` when a setting is changed or hide-flyout is disabled/reenabled.
If auto-hide block palette is enabled and the mode is set to category hover or category click, the amount of usable space in the code area is increased. This affects the horizontal scrollbar and the placement of blocks. Previously the workspace metrics were only updated when enabling the addon. When it was disabled or the mode was changed, a reload was necessary to update them.

hide-flyout: update workspace metrics when changing settings

---

addons/editor-stage-left/stageleft.css
addons/hide-stage/style.css
addons/hide-stage/userscript.js

- Fixes https://github.com/ScratchAddons/ScratchAddons/issues/4866. sa-stage-hidden is now once again applied to the body wrapper, not the root element. A different class is now applied to the root element to style something that isn't inside the body wrapper.
- Fixes an editor crash when rendering a text bubble after entering and leaving fullscreen with the stage hidden

hide-stage: Fix hidden stage on project page regression and other errors

---

webpages/settings/components/addon-setting.html

Makes settings inside table rows vertically centered.
Before:
After:
Rows with more than one setting aren't changed.

Improve layout of table rows with only one field

---

addons/editor-stage-left/addon.json

* The addon now appears when searching for "scratch 2" or "scratch 2.0".
* People who enable this addon probably also want the old button order.

Add notice to `editor-stage-left` and change description

---

addons/forum-live-preview/addon.json
addons/forum-live-preview/userscript.js

Resolves #4782
Adds a setting to `forum-live-preview` for adjusting the refresh rate.
Some people might want to configure the refresh rate.
Tested on Chromium 103.

Refresh setting for forum-live-preview

---

addons/initialise-sprite-position/addon.json
addons/initialise-sprite-position/userscript.js

Resolves #4786
- adds a setting for how to handle duplication: either randomise (scratch's default), go to custom x/y values, or stay in the same position as the original sprite; setting & option names & orders should probably be reconsidered
- uses `const` instead of `let` in a few places
- it's a bug, and users should choose the behaviour they want
- `const` is love, `const` is life
tested on chromium (kiwi) 101 with all 3 settings + dynamic enable/disable

initialise-sprite-position: run on sprite duplication

---

addons/columns/style.css

When both editor-stage-left and columns were enabled, the add extension button's bottom left corner (or bottom right in RTL) would be more rounded than the other corners.
Before
After

Fix incorrect add extension button corner when using editor-stage-left and columns

---

addons/columns/style.css
addons/editor-stage-left/stageleft.css
addons/hide-flyout/style.css
addons/hide-flyout/userscript.js

- The lock button is now inside the flyout SVG instead of being "above" it, simplifying some things
- Fixes #4896
- Removed unnecessary .gui from selectors as some Scratch mods don't have an element with that class
- Added redux events (minor performance optimization)
- Fix incorrect placeholder element location using RTL language and columns addon
- Fix left border still being partially transparent so you could still see the flyout through the border while dragging blocks; now it's completely opaque
- Fix right border of code editor not working in RTL with editor-stage-left
- Fix dragged sprites getting covered by target pane and columns category list

hide-flyout: Fix some bugs and some internal cleanup

---

addons-l10n/en/confirm-actions.json
addons/confirm-actions/addon.json
addons/confirm-actions/userscript.js

Resolves #4884
- Fix bug with showing "unshare project" when leaving/deleting studio in mystuff
- Show new delete confirmation when user is deleting project in mystuff (in trash, and in projects tab)
Firefox 95.

Confirm removing project in mystuff

---

.github/gen-manifest.mjs
background/handle-fetch.js
manifest.json

Progress on #3615
Uses declarativeNetRequestWithHostAccess when possible. Users running Chrome 95 and below, plus Firefox users, will still use webRequestBlocking. Packer script now automatically removes DNR permission from Firefox build.
Note that `domains` condition was renamed to `initiatorDomains`, but this is not shipped yet.
Tested that requests using sareferer still works in Chrome and Firefox.
Next step would be to drop all Chrome versions without DNR support and implement a way to ask for non-WHA DNR permission in browsers that require those. Not sure how to test that though.

Use declarativeNetRequestWithHostAccess when possible

---

addons/full-signature/blocks.css

Resolves #3684
Continues #4217 (I forgot about that PR...)
Full areas addon now adds scrollbar to `scratch blocks 3` (from `scratchblocks` addon).

Add support for scratchblocks to full-signature

---

addons/forum-time-zones/addon.json
addons/forum-time-zones/userscript.js

Leaves the ScratchDB deprecated v2 APIs and get UTC dates using the mobile forums
Also fixes bug when you're on a big topic and you're on the first page (we don't specify a "page" to scratchdb)
And dynamic enable/disable
Less bytes sent to client
Firefox

forum-time-zones: use mobile forums instead of scratchdb

---

addon-api/content-script/Tab.js
content-scripts/inject/module.js

Stop duplicate scripts from running, e.g color-picker and 2d-color-picker use tinycolor, and if you use both at the same time it loads the same script two times

Don't reload already-loaded scripts

---

addons/default-costume-editor-color/addon.json

This addon was marked as beta by garbomuffin when released, see commit https://github.com/ScratchAddons/ScratchAddons/pull/4267/commits/aaeee39d3655d042369418c55bee043f4cbcfc4e
No relevant bugs were reported, so we should remove the beta tag

Remove beta tag from default-costume-editor-color

---

addons/forum-search/userscript.js

Resolves bug from feedback:
> There's a new forum now ( https://scratch.mit.edu/discuss/60/ ) called "Project Save & Level Codes", which has an ampersand in it.
When the forum search addon is enabled and you visit this page, then the placeholder text says "Project Save \&amp; Level Codes" instead of the expected "Project Save & Level Codes".

Get textContent instead of innerHTML (forum-search)

---

addons/emoji-picker/userscript.js

Resolves #4842
Closes the emoji picker when the button is pressed
Firefox 105

emoji-picker: close picker when button pressed

---

addons/variable-manager/addon.json
addons/variable-manager/userscript.js

Resolves #3235
Replaces the `variable-manager` shift key check with an element type check.
The shift key doesn't have to be held while creating list items anymore.
Tested on Chromium 103. Pressing enter on a variable input still unfocuses it.

Allow adding list items through variable-manager by pressing enter

---

background/load-addon-manifests.js

Resolves #4947
Stops crashing the manifest loader if an addon manifest is invalid, and error in background page
Firefox

Show error message if an addon.json is invalid

---

addons/confirm-actions/addon.json
addons/confirm-actions/userscript.js

Does not resolve any open issues.
Changed "cancelling" to "canceling" in the `confirm-actions` addon.
"Canceling" is usually favored by Americans, whereas "cancelling" is usually used in other dialects. Source: https://www.grammarly.com/blog/canceled-vs-cancelled
Nobody will notice this, but I think this change is still worth it.
Didn't test, but the changes should work just fine. It's just language.

Change spelling: "cancelling" to "canceling"

---

addons/find-bar/userscript.js
addons/jump-to-def/userscript.js

This uses the code from the devtools files. This also fixes a bug where the items in the sounds tab were not appropriately styled.

Dont let `find-bar` and `jump-to-def` run when devtools extension installed

---

addons/editor-devtools/addon.json

See #4817
Removes the now unused `enableMiddleClickFinder` `ditor-devtools` setting. Also removes the `costumeEditor` tag since there (probably) aren't any costume editor devtools features left.

Remove unused devtools setting

---

addon-api/content-script/Tab.js
addons/find-bar/userscript.js
addons/find-bar/userstyle.css

Fixes the element used in the Tab.js API and renames all created elements to have the `sa-` prefix as requested by WL.

Fix variable manager order conflict with find-bar

---

addons/editor-dark-mode/experimental_editor.css

I know this isn't the place to put this, but at some point, we should not have dark mode be styling elements created by other addons like this. Instead, we would have a scratch class that you would add to elements that just set their background to #fff or similar and the darkmode addon would change that class' background. The code would be cleaner and shorter in the long run. This would work for addons such as devtools (middle click menu), find-bar, hide-flyout, gamepad (which currently does not have darkmode support in the editor, but I think that was on purpose?), onion skinning, and a lot more but I won't list them all.

Fix editor-devtools not styling properly in darkmode

---

content-scripts/cs.js

So apparently an if statement was too long. Previously, nothing would happen if you tried to enable, disable, or change settings. But this is really hard to repro. To repro, you can add a timeout promise before the listeners are made.

Fix one in a million race condition

---

.github/ISSUE_TEMPLATE/---bug.yml

Mentioned the security policy in the bug report form under the READ BEFORE CERATING! section.
To help remind people that security issues should NOT be reported publicly.
Yes, the change shows up.

Link to security policy in bug report form

---

webpages/settings/components/previews/editor-dark-mode.html
webpages/settings/components/previews/editor-dark-mode.js

Updates the setting preview to match what actually appears in the editor after #4916.

Correct block palette opacity in preview

---

addons/last-edit-tooltip/userscript.js

The last-edit-tooltip addon currently waits for a Redux action named `"SET_INFO"`, which doesn't exist. This means that it only works if the info has already been loaded when it runs.

Fix last-edit-tooltip race condition

---

addons/block-cherry-picking/userscript.js
addons/block-duplicate/module.js
addons/block-duplicate/userscript.js

Fixes https://discord.com/channels/806602307750985799/1015981428472811520/1016169173514211421
> Has anyone noticed the Ctrl + Alt drag to duplicate a single block is bugged? It is currently leaving the original block detached from the script after duplicating
> https://cdn.discordapp.com/attachments/1015981428472811520/1015982258844356679/2022-09-04_14-50-06.mp4
The addons trapped the same method and would break if they ran in the wrong order (regression from https://github.com/ScratchAddons/ScratchAddons/pull/4682). They now use a shared module to ensure consistent order.

Fix block-cherry-picking and block-duplicate race

---

addons/infinite-scroll/forumScroll.js

Resolves #5014
Fixed a broken iteration that skipped inserting/appending every other post, and fixed the insertion location on some pages.
Full details in Issue #5014 
Bug fixes.
Tested on Firefox and Chrome, with Scratch Addons v1.28.0-pre

Fix forum infinite scrolling

---

addons/better-quoter/addon.json
addons/default-costume-editor-color/addon.json
addons/editor-colored-context-menus/addon.json
addons/move-to-top-bottom/addon.json

Resolves #5074
Changes the setting name "Use previous color instead of default when switching tools" → "Recall previous color instead of resetting after switching tools", plus a few other edits ranging from corrections to clarifications.
To make it clearer what that option does.
No, but it should work - it's just text.

Clarify some strings

---

popups/scratch-messaging/popup.html
popups/scratch-messaging/popup.js

Suggested by micahlt on discord
https://discord.com/channels/806602307750985799/1024110625070272613
> At the moment, you can use Ctrl+Enter to submit comments on users, studios, and projects without clicking the Post button.  I'd love to see the same feature in SA's Scratch Messaging addon that appears in the extension popup.

scratch messaging: Ctrl + Enter to post message

---

addons-l10n/en/scratchstats.json
addons/dark-www/addon.json
addons/dark-www/scratchstats.js
addons/scratchr2/forums.css
addons/scratchr2/mystuff.css
addons/scratchr2/scratchr2.css
addons/scratchr2/scratchr2_comments.css
addons/scratchstats/addon.json
addons/scratchstats/style.css
addons/scratchstats/userscript.js
libraries/common/cs/spinner.css

Resolves #4968
Resolves #5022
* Fixes the layout shift by disabling `runAtComplete` and showing the div containing the chart before the chart loads.
* Shows a loading spinner instead of the "Loading..." text.
* Loads the chart even if the user info is not available.
* Shows question marks if only some user info is available.
* Makes the chart look better in dark mode.

Improve scratchstats addon

---

addons/my-ocular/addon.json

PR #5089 broke the unwritten rule. Setting names, as well as possible values, use `Sentence case`.

Change setting name capitalization (my-ocular)

---

addons-l10n/en/rename-broadcasts.json
addons/addons.json
addons/rename-broadcasts/addon.json
addons/rename-broadcasts/userscript.js

Requested in the discord server https://discord.com/channels/806602307750985799/1024221040961929266
Currently, you can rename by clicking on the dropdown and choosing "Rename broadcast" which will open a model. This addon is consistent with scratch's method to rename variables. I did not create the option to rename the broadcast by right-clicking on the block to stay consistent.

New addon: Rename broadcasts

---

addons/turbowarp-player/userscript.js

Always enable the settings button when using turbowarp-player in replace mode. Lets people enable things like high quality pen if they want to. For people who don't want to use those features, they can simply not click on the button.
This directly or indirectly addresses:
- https://github.com/ScratchAddons/ScratchAddons/discussions/5213
- https://github.com/ScratchAddons/ScratchAddons/issues/4005
- #1439 
but does not necessarily resolve them
There are other PRs that touch this addon but they are stalled. This is a small one-line change to implement a feature that people want.

turbowarp-player: enable settings button

---

addons/editor-devtools/userscript.css

Resolves #5228
Imports `compatibility.css` from `editor-theme3` to allow blocks in the Shift+Click popup to have colored backgrounds regardless of whether or not other addons using this stylesheet are enabled.
Regression caused by https://github.com/ScratchAddons/ScratchAddons/pull/4817
Tested to work in browsers with Chromium 106.

`editor-devtools`: import `compatibility.css` from `editor-theme3`

---

.github/CODEOWNERS

Since we allow any org member to merge PRs after 2 approvals, the current CODEOWNERS file makes little sense.
@Hans5958 Do you want to keep your entry, what do you think?
Does any org member want CODEOWNER of a specific folder/addon? It's a good moment to add it
Personally, I'd like to self-request review when appropiate, instead of getting it automatically in every single PR.

[GitHub meta] Change CODEOWNERS entries

---

addons-l10n/en/rename-broadcasts.json
addons/editor-searchable-dropdowns/userscript.js
addons/rename-broadcasts/addon.json
addons/rename-broadcasts/userscript.js

- The addon actually works now
- Undo/redo works
- When a broadcast with the new name already exists, the old broadcast is "merged" into the new one instead of silently doing nothing
- ~~I changed some strings to use the same words that Scratch itself uses. If it's too late for string updates then just revert 8424f49696072bcaadbcf4bf55d5d8a059f41a76 before merging.~~ ~~Still think this change is correct but it seems to be too late for string updates~~ moved to https://github.com/ScratchAddons/ScratchAddons/pull/5231
- editor-searchable-dropdowns now treats the rename message option the same as it does the rename variable option (hide during search)
I've been able to open up Appel and rename broadcasts while the project is running without issues, and those new names are saved when the …

Fix a lot of issues in rename-broadcast

---

popups/scratch-messaging/popup.js

Resolves plausible showing `vundefined`
fixes typo
it's a bug

Fix typo in constructing a /feedback link

---

addons/hide-project-stats/addon.json

Marks the "Hide broken (always 0) studio count" setting on `hide-project-stats` as a new setting for v1.29.0.

hide-project-stats: "new" tag for `studios` setting

---

addons/vol-slider/userscript.js
addons/vol-slider/userstyle.css

Resolves #5200
- Adds some visual margin (internally padding) between the volslider container and any elements next to it. These elements may be the green flag if `editor-buttons-reverse-order` is enabled. It may also be the containers from `mouse-pos` or `clones`.
- Small stage detection fixes. 1. Fix dynamically enabling this addon when small stage enabled 2. Fix enabling small stage mode, going to the project page, then back

Fix vol-slider bugs

---

addons/hide-flyout/addon.json
addons/hide-flyout/userscript.js

- I changed the setting title from "Animation duration" to "Animation speed".
- I changed the option names from _None/Short/Default/Long_ to _Instant/Quick/Default/Slow_.
- I made each setting faster.
1. The Long setting was honestly _too_ slow.
2. Even on the Short setting, it still felt a little slower than I'd like.
Changes tested in Edge 106. No problems found.

`hide-flyout` animation speed changes

---

README.md

It's the same as Google Chrome except it's `edge://extensions` instead of `chrome://extensions`.
Resolves #
Add Microsoft Edge to "From Source".
To help lost Edge users I guess.
Um, I don't think I need to?

Add Microsoft Edge to "From Source"

---

addons/opacity-slider/style.css
addons/opacity-slider/userscript.js

Resolves #5205
- Fixes shadow for the opacity slider drag point only shows within the slider itself
- Fixes bug: https://user-images.githubusercontent.com/17484114/195955656-5ee628ae-2e96-45ad-992b-aa93447499ab.png
- Disable opacity slider completely in bitmap (requested by apple502j)

Fix opacity slider bugs

---

addons-l10n/en/rename-broadcasts.json
addons/rename-broadcasts/addon.json

Extracted from https://github.com/ScratchAddons/ScratchAddons/pull/5215
Scratch uses strings like "New Message" or "New message name:", so the addon should too
Maybe the addon's name should also be changed. I have no particularly strong feelings on that.
Took this out to a separate one because I don't know what the plan is for merging these this close to release

rename-broadcasts: Update some strings

---

addons/dark-www/experimental_scratchr2.css

Resolves #5298
Sets `color-scheme` on iframes to light. The explanation is in a code comment.
To make text in certain modals readable.
The profile report modal is now readable:

Fix unreadable text in jQueryUI modals in dark mode

---

.github/gen-manifest.mjs
manifest.json

Resolves #5273 
Removed properties from manifest.json that are equal to their defaults.
Redundancy and this wasn't localized
Tested locally, this does still display properly with the proper tooltip.

Remove unlocalized instance of "Scratch Addons"

---

CONTRIBUTING.md

- Clone Scratch Addons now heads to instructions on how to download AND add the extension to your browser.
- Rephrased the part at the bottom that tells you other ways to commit changes.
I felt that those details were a little vague for new contributors.

Update Clone Scratch Addons link and more
