addons/my-ocular/discuss.js

Resolves #5286
Removes `display: inline-block` from ocular statuses in the forums.
To fix a bug.
Tested [this post](https://scratch.mit.edu/discuss/post/6682478/). Nothing changed on Firefox - this was a Chrome-only bug. On Chrome, the bug is fixed - the status doesn't cover the post.

Fix long status regression

---

addons/turbowarp-player/userscript.js

With the Turbowarp button addon, the current method of getting the project token does not update, even though the token itself does. This can cause the Turbowarp button to crash when the token hasn't been fetched after a little while. This makes it fetch the token each time the Turbowarp button is pressed (which, in most scenarios, would only be once).
Because we don't want to crash the addon...
I tested between the production version from the Chrome Web Store (v1.29) and the version with my changes.

fix old tokens being used for turbowarp button

---

addons/editor-extra-keys/addon.json

Resolves #4862
Renamed `editor-extra-keys`, plus edited its description and setting names.
_Extra key "support"_ seems a little misleading - this addon actually just adds more keys to the drop-menus of key-pressed blocks, but after you add them to a project, they work fine for all users, even those who do not have Scratch Addons installed.
Should work fine.

Rename the Extra key support addon, plus its settings and description

---

addons/comments-linebreaks/addon.json

Changed “Maximum number of lines” to “Maximum number of lines visible at once”.
- To make the addon easier to understand
Didn’t test the changes, but there weren’t any code changes.

Rename the setting “Maximum number of lines” in Line breaks in comments

---

addons/cat-blocks/addon.json

Previously, the message on the `cat-blocks` addon that the "Watch mouse cursor" option may affect performance was a red warning. I changed it to a yellow notice.
The warning message is pretty bright for a minor warning that only applies if you turn on a setting that I don't think everyone will use.
Change tested.

`cat-blocks`: Change info type from warning to notice

---

addons/material-forum-editor-buttons/icons.css

Resolves #5337
Adds the new class name for the image uploader button to the `material-forum-editor-buttons` userstyle. I didn't remove the old one because some people might still be using Jeffalo's extension.
Is the `#ibbBtn` selector still needed? It was apparently added for compatibility with an ImgBB userscript made by easrng. Event if that userscript still exists, it probably doesn't work because the Wikimedia open redirect bug was fixed.
To fix a bug.
Before:
After:

Fix image uploader Material icon

---

addons/more-links/addon.json

Resolves #4882
Changed the name of the "More links" addon to "Clickable external links" and edited the description.
The new name makes more sense.
Changes should work fine.

Rename the "more links" addon

---

popups/scratch-messaging/api.js

Resolves #5318
This changes `popups/scratch-messaging/api.js` to be prepared for 403 errors when fetching comments or replies, as well as 404 errors.
The Scratch Messaging popup would error whenever it tried fetching comments/replies from banned profiles. It's only ready for 404 errors when fetching, not 403.
I did test:
Browser: Chrome 106
Scratch Addons version: v1.29 (tested on multiple other beta versions though)
Operating system: MacOS

Fix comment replies on deleted profiles cause messaging to fail

---

_locales/en/messages.json

Are you sure you want to load this preset? → Load this preset and overwrite current settings?
Someone may not realize that loading a preset is going to permanently overwrite their custom settings.
Shouldn't need a test.

Change preset loading confirmation message to say that settings will be overwritten

---

content-scripts/cs.js

Resolves #4380
Throws at the top of `cs.js` if being ran on an iframe when `iframe.getAttribute("src") === null`
Other content script files will still run on Firefox, but I don't think that is causing any trouble.
Tested on Firefox 106
Checked website dark mode should not apply to the contact us form
Checked addons should still run in iframes (pause+live-featured-project in profile)

Fix addons running on iframes without src (Firefox)

---

addons/editor-theme3/addon.json
addons/scratchblocks/addon.json
addons/scratchblocks/userscript.js

Resolves #5290
Makes the `editor-theme3` and `scratchblocks` addons take effect on all forum pages, not just topic pages.
Scratch blocks can appear on the forums in places other than forum topics, such as [post listing pages](https://scratch.mit.edu/discuss/search/?page=1&action=show_user&show_as=posts) and search results from the `forum-search` addon.
The only downside is unnecessary userstyle injection (on pages where there are never any Scratch blocks), which might impact performance, but it probably won't be noticeable.
Tested on Edge 107. There was an issue but mxmou fixed it for me. Other than that, I didn’t find any problems.

Apply Scratch block-affecting addons to all forum pages

---

addons/block-duplicate/module.js

Resolves https://discord.com/channels/806602307750985799/1034089671984169030
Previously, if you had block-cherry-picking enabled in invert mode, normal block drags would only drag one block but alt+dragging would duplicate the entire stack. Now alt+dragging will just duplicate the one block unless ctrl is being held. This is what users would expect to happen.

block-duplicate: respect block-cherry-picking's invert setting 

---

addons/debugger/module.js

In some browsers (Chrome), calling resume() and suspend() simultaneously or very closely together results in the resume() call winning in the end, so wait for the previous resume/suspend call to finish before starting a new one.
Closes https://github.com/ScratchAddons/ScratchAddons/issues/5361
Tested by running this in the JS console:
```js
var btn = document.querySelector('.pause-btn')
for (let i = 0; i < 33; i++) btn.click()
```

Wait for previous suspend/resume to complete when pausing

---

addons/custom-zoom/addon.json
addons/custom-zoom/userscript.js

Resolves no open issues. Related to #5260.
Applies the same animation speed changes I made to `hide-flyout` last month (PR linked above) to `custom-zoom`'s autohide zoom controls feature.
1. I don't think anyone was going to use the Long setting.
2. Even on the Short setting, it still felt just a _little_ slower than I'd like.
Tested on Edge 107. Everything seems fine.

Change `custom-zoom` animation speeds

---

popups/scratch-messaging/popup.css

Fixes a reference to a CSS variable that doesn't exist.
To fix a bug.

Fix reference to `--danger-orange`

---

addons/pick-colors-from-stage/userscript.js

Resolves https://discord.com/channels/806602307750985799/1035494962193772604
> When I set the opacity in the sprite editor for some reason when I hover over stage it thinks that I am going to select a colour to use for sprite editing.
Probably also affects the other addons that use the color picker.

pick-colors-from-stage: only process user-initiated clicks

---

content-scripts/load-redux.js

Shuffled the `inject-redux` script around a little so that it does not break when redux devtools is enabled. If the `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__` variable is already set, it replaces the function and instead of using it's own ducktyped compose function uses the old `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__` and only edits middleware. If `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__` is set *after* sa updates it, same thing happens with the new value.
It's annoying not being able to use Redux DevTools to develop addons.
No conflicts on my end, but i need some other people to test too.

Fix redux devtools conflict

---

addons/turbowarp-player/style.css

Resolves #5445
Adds `color-scheme: light` to the TurboWarp iframe.
To fix the white background in dark mode.

Fix TurboWarp player white background

---

.gitignore

Added `node_modules/` to `.gitignore`.
I've been working on a development feature that uses node, and am unable to switch between branches because this is not present. If my bundling pr gets merged, this will need to be present anyways. It's only a single line.

Add `node_modules` to gitignore

---

addons/sprite-properties/addon.json

Changes the names of the speed settings from None/Short/Default/Long to Instant/Quick/Default/Slow.
Since I’ve changed the names of the different speed settings on two other addons, I wanted to apply that change to this addon, too.
Should be fine.

Update `sprite-properties` speed setting names

---

.github/ISSUE_TEMPLATE/--feature.yml
.github/ISSUE_TEMPLATE/--new-addon.yml

Resolves #5436
Various wording changes/revisions in the suggestion-type issue forms:
- Some headings (like "What this change does") changed
- Some form descriptions changed
- New step in `Read before creating` section on New Addon form: _"If your new addon is similar to another existing addon, consider mentioning merging them in the Possible alternatives field or suggesting a [new feature](https://github.com/ScratchAddons/ScratchAddons/issues/new?assignees=&labels=status%3A+needs+triage%2Ctype%3A+enhancement&template=--feature.yml) for it."_
To allow for more flexibility in suggestions and to make writing suggestions easier.
Took a look at the changes on [my fork](https://github.com/DNin01/ScratchAddons/tree/5d9855ba8c42b38fa2b9f5c14955e3e8a55b1704/.github/ISSUE_TEMPLATE).

Suggestion form changes

---

addons/addons.json
addons/number-pad/addon.json
addons/number-pad/userscript.js

https://github.com/ScratchAddons/ScratchAddons/discussions/5396
Apparently on touchscreen devices, Scratch shows this menu on number inputs:
This addon makes it always appear on  all devices.

New addon: number-pad

---

addons/turbowarp-player/userscript.js

Resolves #4430
Code is self explanatory.
We might want to discuss whether we should try to be consistent with the vanilla Scratch fullscreen, which remains unchanged even if `dark-www` is enabled.
Note that users that had system-level dark mode enabled already had dark mode here. This only applies for users that don't have that.

Apply dark mode to TurboWarp iframe fullscreen background

---

content-scripts/cs.js

Code should be easier to understand now, and more consistent.
Idea for `window.top.location.origin !== window.location.origin` is by mxmou (https://github.com/ScratchAddons/ScratchAddons/issues/5281#issuecomment-1321149772)

cs.js checks at top of the file: clean up & small changes

---

addons/sprite-properties/userscript.js
addons/sprite-properties/userstyle.css

See https://github.com/ScratchAddons/ScratchAddons/pull/5158#issuecomment-1345303499
The "collapsing sprite properties" addon adds an arrow to close the properties panel when it's expanded. It looks like this:
This PR changes it to look like this instead:
A large area around it is clickable.
To make it more visible.

Move the icon for closing sprite properties

---

addons/disable-paste-offset/addon.json

From feedback:
> just figured out there's a SA feature allowing to duplicate an object at the same place on costume editor but we could already do this by holding option/alt and click on the item
Add an info note to the addon to make users aware of this. The phrasing can be changed and probably should.

Add info note to disable-paste-offset

---

addons-l10n/en/find-bar.json
addons/find-bar/userscript.js

These no longer cause issues:
- Broadcasts with complex inputs will be treated as if they are named ~~"(complex)"~~ "(expression)" instead of throwing errors. The reasoning for this behavior is: generating a meaningful text description for complex blocks is not trivial, very few projects use this anyways, but skipping them entirely seems like a bad idea
- Broadcasts named after Object.prototype builtins will work reliably now.
- Closes https://github.com/TurboWarp/scratch-gui/issues/669

find-bar: Fix some errors searching for broadcasts

---

_locales/en/messages.json
content-scripts/cs.js

> New addon: "costume editor snapping", which lets you snap objects in the costume editor to bounding boxes and vector nodes. Go to [Scratch Addons settings](https://scratch.mit.edu/scratch-addons-extension/settings?source=updatenotif) to enable it.
> Other new addons added this update are "collapsing sprite properties", "insert blocks by name", and "always show number pad".
YouTube video thumbnail and link are still pending.

Add v1.30 update notification

---

addons/hide-flyout/style.css
addons/hide-flyout/userscript.js

Slightly tweaked the `z-index` change on the stage wrapper to prevent sprite context menus from being cut off with the folders addon enabled.

Fix hide-flyout and sprite-folders conflicts

---

addons/editor-stage-left/stageleft.css

Resolves #2851
Fixes a bug in `editor-stage-left` that caused gamepad and debugger icons to be flipped. Large stage, small stage and hide stage icons are still flipped, as expected.
LTR:
RTL:

editor-stage-left: fix flipped stage button icons

---

addons/fullscreen/userscript.js

Resolves #3815
Calls `renderer.resize()` when the window size changes.
To fix a bug.

fullscreen: resize stage canvas

---

addons/fullscreen/removeBorder.css

Fixes a bug in the enhanced full screen addon that caused the answer input to be positioned incorrectly (slightly too low and not centered).
Before:
After:

fullscreen: fix incorrect position of answer input

---

background/get-userscripts.js

Resolves #4513
Excludes paths starting with `/emails/` from the `isNotScratchWWW` match pattern.
There's no reason for addons to affect emails. Website dark mode currently makes them unreadable.
Tested on Edge and Firefox. The following link can be used for testing: https://scratch.mit.edu/emails/welcome/LakeMackay/1/

Exclude emails from `isNotScratchWWW` match

---

addons/editor-dark-mode/addon.json
addons/editor-dark-mode/experimental_editor.css
addons/editor-dark-mode/paper.css

Resolves #5502
Fixes #5502 by setting the text color to `#575e75` unless the dark paint editor setting is enabled.
Also changes something unrelated that I forgot to do in #5077.

editor-dark-mode: fix invisible caret in paint editor

---

addons/find-bar/userscript.js

Resolves #4899
Calls `scrollIntoView()` when the selection in the find bar dropdown is changed using arrow keys.
To make navigating long dropdowns using the keyboard easier.

find-bar: scroll dropdown when using arrow keys to navigate

---

addons/editor-dark-mode/experimental_editor.css

Resolves #4685
Sets the text color of the project title and remix button in the editor correctly.
To make sure that text is readable.

editor-dark-mode: fix color of project title and remix button

---

addons/middle-click-popup/userscript.js

Fixes this bug from feedback https://discord.com/channels/751206349614088204/758464349768515604/1058040403468750898
> if u search b r b when adding a block with middle click it will suggest you broadcast ( rename broadcast ) which isn't supposed to happen as its a custom option to rename a broadcast and not a broadcast you have used and if u click on it, it creates the broadcast "rename broadcast"
> very minor bug but its a bug sooo :P

middle-click-popup: fix rename-broadcasts compatibility

---

.github/CONTRIBUTING.md

Step 4 on **Creating pull requests** in the contributing guidelines now links to instructions on GitHub Docs that show you how to clone a fork and part of the README that shows you how to add it to your browser.
Users should know how to clone their fork, otherwise they may clone the origin repository instead.

Show how to clone a fork

---

addons/hi-res-thumbnails/userscript.js

Resolves #3987
* Ignores images in forum posts and signatures.
* Fixes dynamic disable (it currently breaks all images that don't have lazy loading).
The addon can't handle forum images correctly because they don't have width/height attributes or CSS properties. If it runs before the image loads, it tries to resize it to 0x0. If the image loads first, the addon will make it larger instead of increasing the resolution.

hi-res-thumbnails: fix bugs

---

addons/hide-delete-button/sounds.css

hide-delete-button's option to hide the delete button in the sounds list was not working previously.
Tested in Firefox and Chromium on Linux

hide-delete-button: Fix sounds option

---

addons/hide-stage/style.css

I broke this in https://github.com/ScratchAddons/ScratchAddons/pull/5424. The stage would still use some space on the right:
Tested fix in RTL and LTR in Firefox

Unbreak hide-flyout and hide-stage compatibility

---

addons/onion-skinning/style.css
addons/paint-snap/userstyle.css

This is a partial follow-up to https://github.com/ScratchAddons/ScratchAddons/pull/5069, primarily regarding changes to onion-skinning
- Fix onion skinning setting labels wrapping unexpectedly
- Restore previous input background color change when an onion skinning settings input was focused so the user can easily tell what input they're editing, reverting https://github.com/ErrorGamer2000/ScratchAddons/commit/7afb158dcfd9e2d3f36e75415059b31f61ed4a68. I feel that the browser's native text caret that is invisible half the time is not sufficient for indicating focus. If that commit was intended to fix a different "visual bug", I can't tell what it was.
- Use a smaller motion when opening the onion skinning settings menu (similar to the animation pre-paint-snap). I feel that the animation was …

Fix some onion-skinning and paint-snap visual issues

---

addons/variable-manager/userscript.js

This prevents variable-manager from getting the project into a broken state:
1. Create a variable "For this sprite only" in sprite A (eg. "local")
2. In another sprite, create a global variable (eg. "global")
3. Using variable-manager, rename "global" to "local"
4. Go back to the original sprite. Using variable-manager you will see both a local and global variable with the same name, and in the editor you will only see one of these and blocks that interact with these variables may not work as expected.
Tested in Firefox on Linux

variable-manager: Prevent creating conflicting variable names

---

addons/editor-theme3/theme3.js

Fixes this bug: https://discord.com/channels/751206349614088204/755131743136383107/1060029229900775465
1. Disable editor-theme3
2. Open the editor in a new tab
3. Dynamically enable editor-theme3
4. Create a variable. The variable will not appear in the toolbox until you force the editor to reload (switching sprites, editor tabs, etc.)
This can also probably happen on normal page loads with the addon enabled if you get unlucky with when the addon loads.
The fix used here is based on similar code that already exists in custom-block-shape.
Historical context that led to the code being the way it is: https://github.com/ScratchAddons/ScratchAddons/pull/3805/commits/2f80e2c396554e9597f2be8da84d95ba5e65c73f https://github.com/ScratchAddons/ScratchAddons/pull/3805/commits/426a8d7e8fe111975b10268b …

editor-theme3: Enable toolbox refresh after reloading flyout

---

addons/middle-click-popup/userscript.js
addons/middle-click-popup/userstyle.css

- Fix the middle click popup issue described in https://github.com/TurboWarp/scratch-gui/issues/680. The find bar issue described there is an unrelated downstream bug.
- Fix placeholder text of the input. The string already exists; it just wasn't used
- Fix color of blocks like "backdrop # of stage" and "when backdrop switches to"
- Disable ctrl+space outside of the editor
<table>
<tr>
<th>git master</th>
<th>this PR</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/33787854/210157000-7de60309-c43d-446a-8d5c-732848b8e367.png"></td>
<td><img src="https://user-images.githubusercontent.com/33787854/210156989-adeb2777-1492-4d37-8372-79d808fda2e6.png"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/33787854/210158177-e237f39d-3a8d-4a61-a39b-378bd5f …

middle-click-popup: Fix editor-theme3 compatibility and placeholder text

---

addons/gamepad/gamepadlib.js
addons/gamepad/userscript.js

This fixes an issue from my Scratch comments:
>  Problem with Turbowarp. I'm using the desktop client, so I don't know if that's the issue. Basically, when I try to change the gamepad controls using the gamepad support addon, it resets the controls when I unplug the controller, even after saving the project. Am I doing something wrong? 
1. Plug in a controller
2. Customize settings
3. Save them to the project
4. Unplug controller
5. Plug controller in again
6. It should have the settings that were customized, not the default ones
Controllers are not plugged and unplugged often enough to justify have a fragile cache here

gamepad: Remove hints cache

---

webpages/settings/components/addon-body.js
webpages/settings/index.js

The notification that pops up when you try to enable the Scratch Notifier addon from the extension popup. It needs you to open the full screen settings page because I guess the extension popup cannot request permissions.
Made the drop-down duration of this popup 0.35s and the dismiss duration 0.6s. Basically, I just sped up the animation. It may seem like a lot, but it was pretty slow to begin with.
With the previous, slower animation speed, it would take a second for it to come onscreen. This change makes it snappier and more responsive, which can help make it easier to notice.
Tested on Microsoft Edge.

Speed up open full screen settings popup glide-in

---

addons/zebra-striping/userscript.js

Resolves #5194
Enables zebra striping when two blocks have the same color, even if the category is different. This only works if the two colors are exactly the same.
It's possible to choose the same color for two categories.
Tested on Edge and Firefox, using Appel as an example project. In the first screenshot, variables and lists have the same color. In the second screenshot, operators and variables have the same color.

zebra-striping: compare colors instead of categories

---

addon-api/content-script/blocks.js

Before, the insertion marker for addon blocks was given color:
Now, it looks the same as every other block:

Don't color addon block insertion markers

---

addons/copy-message-link/addon.json
addons/customize-avatar-border/addon.json
addons/hide-flyout/addon.json
addons/infinite-scroll/addon.json
addons/more-links/addon.json
addons/resizable-comment-input/addon.json
background/get-userscripts.js

Resolves #5575
* Adds `/projects` to the `scratchWWWNoProjects` regex (not `projects` because it isn't a functional project page).
* Changes some addons to use the `"projects"` match instead of `/projects/*` to prevent them from running on this page.
To fix a bug with website dark mode and prevent potential bugs in the future.

Fix bugs related to the `/projects` error page

---

webpages/settings/style.css

Resolves #5549
Moves the "presets" label in the popup above the list of presets.
It was previously next to the first preset, with no spacing around it, which didn't look very good.

Fix "presets" label in the Addons popup

---

.github/workflows/stale-issues.yml

Messages from me on Discord:
> Is there a way to get a reminder if a specific GitHub issue hasn't had discussion for a specific period of time?
I sometimes expect someone to reply so I can remember about the issue, but if no one does, the issue falls into oblivion
This new GitHub action will not close any issues/PRs automatically.
It will not affect any issues/PRs, unless they have the `status: awaiting answer/followup` label. Only in issues/PRs that have that label, the bot will send a message after 7 days of inactivity.
**Example imaginary situation where I would use this:**
1. I comment on the issue/PR
2. I add the `status: awaiting answer/followup` label to the issue/PR.
3. In case mxmou (example) doesn't reply for 7 days, the bot will post a new comment. At that point, I can ping …

New repo action: send comment on stale issues

---

addons/middle-click-popup/addon.json

This has been wrong for a while, but it should have been Shift+Click, not Shift+Space.

Fix middle click popup description

---

addons-l10n/en/variable-manager.json
addons/variable-manager/style.css
addons/variable-manager/userscript.js

When variables exceed around 1,000,000 characters in length, they cause excessive performance issues and sometimes cause the whole tab to crash. (there was an issue in TW/scratch-gui about this, but I can't find it anymore)
Instead of that, this PR shows a warning:
The thresholds are set high enough that most people will never see this message.
An earlier version of this PR with similar thresholds has been in TurboWarp for a very long time with the message "Too big to safely display. If this limit is too low, use the feedback button at the top of the screen." No one has submitted feedback about this.

variable-manager: Require a click to display variables that are way too big

---

popups/scratch-messaging/popup.css

Resolves #5360
Adds `overflow-wrap: break-word` to forum and studio titles in the Messaging popup.
To prevent long titles from overflowing.
Tested by changing the title using the inspector.

scratch-messaging: break long words in topic and studio titles

---

addons/editor-searchable-dropdowns/userscript.js

Previously the options would always be shown, but using them do the wrong thing. For example, when creating a global variable whose name conflicts with a local variable, it would seem like a variable was created, but in reality one was not.
Additionally, variable names will now always be trimmed. This matches Scratch's behavior.

editor-searchable-dropdowns: Preventing creating existing variables and trim names

---

background/handle-l10n.js
popups/scratch-messaging/popup.js

Resolves bug reported by a translator.
> why are there no translations for these strings?
TODOs:

Use local language RelativeTimeFormat in scratch-messaging

---

addons/clones/userscript.js

Resolves #4635
Calculates the correct clone count when `clones` is dynamically enabled.
To prevent the counter from showing a negative number.

clones: correct count when dynamically enabled

---

addons/opacity-slider/userscript.js

Resolves #5312
Fixes a bug in the opacity slider code that made it impossible to move the slider by clicking.
To make the addon easier to use.

Allow opacity slider to be moved by clicking

---

addons/progress-bar/addon.json
addons/progress-bar/userstyle.css

The progress bar in the `progress-bar` addon is now rounded. It previously had disgusting square edges that stuck out, so this helps it look better.
I also set the default `Progress bar height (px)` value to ~~10~~ 8 (previously 5), since 5 is very small and hides away.
The square edges were aesthetically unpleasing, and the small size made it appear as if the addon was trying to hide as opposed to being useful, so I improved it.
Working on Chrome 109 (beta, 32-bit) on a Chromebook. I would appreciate it if someone could test this on Firefox.

`progress-bar`: Round the progress bar and set default height to 8px

---

webpages/settings/components/addon-setting.js

Fixes the condition for showing a reset dropdown next to a setting.
The dropdown should be hidden if the setting isn't changed by any preset.
Tested by copying the `addon.json` change from #5602.

Fix condition for showing reset dropdown

---

addons/editor-dark-mode/experimental_editor.css
addons/progress-bar/addon.json
addons/progress-bar/userscript.js
addons/progress-bar/userstyle.css

* Removes the border from the progress bar and adds a transparent background instead
* Uses the `currentColor` keyword to make specific styles for the alert progress bar unnecessary
* Improves the placement of save and remix progress bars
https://github.com/ScratchAddons/ScratchAddons/pull/5583#issuecomment-1376901183

progress-bar: improve rounded design

---

addons/drag-drop/dragged-over.css
addons/sprite-properties/addon.json
addons/sprite-properties/userscript.js
addons/sprite-properties/userstyle.css

- Fixes https://github.com/ScratchAddons/ScratchAddons/issues/5561
- Fixes https://github.com/ScratchAddons/ScratchAddons/issues/5572 / https://discord.com/channels/751206349614088204/758464349768515604/1061135466251943946 - properties panel now works in ["wide" languages](https://github.com/LLK/scratch-gui/blob/e15b2dfa3a2e58e80fae8d1586c7f56aa0cc0ede/src/lib/locale-utils.js#L6-L18) such as Japanese and Italian
- Fixes collapse icon being draggable
- Fixes RTL support
- Fixes properties panel after entering editor momentarily being hidden when auto-collapse is disabled
- Whether the panel is collapsed or not is now preserved through leaving the editor and going back in rather than resetting to the default from settings
- Fixes info button disappearing after renaming sprite
- Fixes …

sprite-properties: Fix some bugs

---

addons/disable-auto-save/addon.json

Change was requested via email to me.

Remove link to Scratch profile from disable-auto-save credits

---

addons/sprite-properties/userscript.js

Fixes https://github.com/ScratchAddons/ScratchAddons/issues/5658
I believe I broke this in https://github.com/ScratchAddons/ScratchAddons/pull/5563

sprite-properties: fix compatibility with search-sprites

---

addons/paint-snap/updateSelectTool.js

Resolves #5573
Made `paint-snap` revert to vanilla when disabled either dynamically or with the button.
Addons should go back to vanilla behavior when disabled.
https://user-images.githubusercontent.com/70162741/213511009-f44592ba-7fd6-423c-a3d2-2daf289b800f.mp4

Use vanilla snapping when `paint-snap` is disabled

---

_locales/en/messages.json
addons/msg-count-badge/addon.json
addons/scratch-notifier/addon.json

Resolves #4955
When right clicking the Scratch Addons extension icon, there was a Mute option, which silenced and hid notifications from the Scratch Notifier addon and hid the messages badge. I renamed this setting to "Do not disturb" and added a note to notification-related addons to tell the user that enabling this feature will hide the message count.
It described the feature better.
Changes tested.

Rename "Mute" to "Do not disturb"

---

addons/editor-dark-mode/addon.json
addons/editor-dark-mode/extension_icons.js
addons/editor-theme3/theme3.js

Updates editor dark mode and customizable block colors addons to change the colors of extension icons in the category menu. The affected icons are debugger, music, video sensing, and text to speech.

Change colors of extension icons based on background and block color

---

addons/find-bar/userscript.js

Fixes a regression from https://github.com/ScratchAddons/ScratchAddons/pull/5638 where navigating to a block using the find bar would incorrectly navigate so the block was either in the top right corner of the workspace or offscreen.

find-bar: fix block scrolling regression

---

addons/editor-dark-mode/addon.json
addons/editor-dark-mode/experimental_editor.css

Makes the block insertion marker white in dark mode.
To make it more visible.

editor-dark-mode: white insertion marker

---

addons/dark-www/experimental_scratchr2.css
addons/scratchr2/forums.css

Fixes a bug in `dark-www` and `scratchr2` that changed the color of the gray pin icons next to closed sticky topics to blue.
1.30.1:
With this change:

Fix blue icon next to closed stickies

---

addons/scratchr2/profile.css

Changes to Scratch 2.0 → 3.0:
* Reduces vertical spacing around profile comment inputs to match scratch-www again (it was changed in LLK/scratch-www#6646)
* Aligns the left edge of the "commenting off" message with comment bubbles
* Makes the color of the "commenting off" message the same as in scratch-www when website dark mode is enabled
Consistency with scratch-www.

scratchr2: adjust spacing around comment input

---

addons/items-per-row/classes.js
addons/items-per-row/search.css
addons/items-per-row/studio.css

Resolves #3293
Modifies the CSS of the `items-per-row` addon to avoid changing the height of rows on Explore, search, and studio pages.
If the selected number of items is the same as Scratch's default, the addon shouldn't make any changes.

items-per-row: avoid changing layout with default settings

---

addons/clones/addon.json
addons/clones/userscript.js

Inspired by https://github.com/ScratchAddons/ScratchAddons/issues/5486#issuecomment-1364735331
Added an option to change whether the clone counter also shows on the project page. The previous behavior was only in the editor. Now, this can be changed.
Viewers and creators might want to see it outside the editor in some cases.
Tested (including the latest changes) on Edge with SA v1.30.0-pre.

`clones`: Setting to show on project page

---

webpages/popup/index.js

Do adjustments to the changelog link so it goes directly to the version, instead stuck on the top.
So the link would stick to the current extension version that is used, even if it is not latest.
Negligble to be tested, but I haven't done it.

Link changelog link directly to version

---

addons/dark-www/experimental_scratchwww.css

Resolves #5709
Links that are visited no longer turn blue on the messages page when dark-www is enabled.
What's happening currently is inconsistent with the behavior of vanilla Scratch.
Tested on a chromium browser.

Prevent visited links from turning blue on messages page

---

addons/dark-www/addon.json
addons/dark-www/experimental_scratchwww.css

Makes website dark mode compatible with the recent change to the design of tabs on the Explore page.
To make text on the tabs readable.
Tested locally (this change isn't on scratch.mit.edu yet).
Without the addon:
Before this change:
After this change:

dark-www: support updated Explore page tabs

---

addons/one-click-studio-invites/addon.json
addons/one-click-studio-invites/userscript.js
addons/one-click-studio-invites/userstyle.css

A step towards #1673
Made the "Accept Invite" button show when you enable the addon and hide when you disable it, all without a refresh.
We're trying to add dynamic enable/disable support to all addons at some point.
Tested on Edge with SA v1.30.0-pre.

Dynamic enable/disable for `one-click-studio-invites`

---

addons/dark-www/addon.json

Added a slider to the color picker for the navbar in the `dark-www` addon which allows the user to change the transparency.
The feature was already in the Scratch 2.0 -> 3.0 addon. The transparency slider disappeared when the settings were moved to the dark-www addon. This had the consequence that people who changed the transparency in the old version could not change or disable it anymore. Another reason is that a transparent navbar looks good to some users.
Tested by changing the transparency and using it for a while, and I've never noticed any issues.

Transparent navbar

---

addons/better-quoter/module.js

Resolves #5766 
Fixes a regression caused by #5240 that made the link added by `forum-id` with the 'auto add post link to quotes' setting enabled large and without brackets.
Keeps the behaviour consistent with the current release.
Tested on chromium 107 - the standalone 'quote post number' button works as it always has and auto-adding the link doea format it as before #5240.

forum-id: auto-add post number small & in brackets

---

addons/progress-bar/addon.json

Adds the update tag to the progress bar addon with a temporary notice about the changes from 1.30.1.
A lot of users might have missed it since there was no update tag on the settings page.
Tested on Chromium 110.

Add `latestUpdate` to `progress-bar`

---

manifest.json

Bumps version.
See [v1.31.1 milestone](https://github.com/ScratchAddons/ScratchAddons/milestone/46).

Bump version v1.31.1-prerelase

---

addons/search-my-stuff/userscript.js

Resolves bug from Discord server feedback:
> Minor annoyance where the my stuff page scrolls to the very top when it loads the share buttons
https://user-images.githubusercontent.com/17484114/225464455-3fc83973-7de2-4844-b8bb-4a98d774911d.mp4
Adds `{preventScroll: true}` to the `element.focus()` call that focuses the search bar. Pretty nice that this toggle is built-in into the browser APIs!
I don't believe the intention of the original call was to scroll the page, it was probably just to let the user begin typing to search.
Not tested yet

search-my-stuff: prevent input autofocus from scrolling page

---

addons/editor-theme3/theme3.js

Resolves #5803
`editor-theme3` currently uses a CSS filter to change the color of dropdown arrows, which recently stopped working in Chromium-based browsers. This PR replaces the image with two SVG paths and changes the fill attribute instead.

editor-theme3: fix invisible dropdown arrows

---

addons/discuss-button/compact-nav.css
addons/scratchr2/scratchr2.css

Adds `white-space: normal;` to the `#topnav ul.account-nav ul.user-nav li a` style rule in `addons/scratchr2/scratchr2.css`
To resolve #5715
After:
Tested on Edge 111.

Fix user dropdown text overflowing

---

addons/scratchr2/mystuff.css
addons/share-through-mystuff/addon.json
addons/share-through-mystuff/scratchr2.css
addons/share-through-mystuff/userscript.js
addons/share-through-mystuff/userstyle.css

* Moves 2.0 → 3.0 compatibility code to `addons/scratchr2/mystuff.css`.
* Replaces a workaround for a Scratch bug with a much simpler one that doesn't need CSS.
* The addon currently tries to align the Delete and Share buttons on unshared projects with the Unshare button on shared projects. This is implemented in a way that doesn't work in languages other than English. I removed it in this PR because I don't think visual changes belong in this addon.

share-through-mystuff: simplify CSS

---

addons/debugger/userscript.js
addons/variable-manager/userscript.js

Resolves bug report from feedback:
> When I'm in the variable tab and I click on a link to a block in the deguger a poster bug happens.
[scrnli_04_03_2023_12-33-48.webm](https://user-images.githubusercontent.com/17484114/222927479-0826c6fa-df7c-4393-858e-7328d6ddd1c4.webm)
`variable-manager` now dispatches a "resize" event if it detects that the user (or an addon) navigated away from the varmanager tab into a different tab.
~~Dispatch a "resize" event on the window object after the redux dispatch that changes the tab.~~
~~**It's possible that we're also missing this in other parts where we dispatch ACTIVATE_TAB**. I still have to check this.
I'm also wondering if maybe dispatching ACTIVATE_TAB is the right way to change the selected tab. Does vanilla Scratch also have this bug?~~
Fixes …

"Variable manager" addon: trigger resize event after switching to another tab

---

addons/dark-www/addon.json
addons/dark-www/experimental_scratchwww.css
addons/horizontal-mystuff-tabs/scratchr2.css
addons/old-studio-layout/scratchr2.css
addons/scratchr2/forums.css

Makes Scratch Addons' aqua color match the new aqua color from Scratch.
`#0fbd8c` → `#328554`
To improve text contrast.
Tested on Edge 110.
If we can:

Update aqua (same as remix button) color

---

addons-l10n/en/featured-dangos.json
addons/addons.json
addons/featured-dangos/addon.json
addons/featured-dangos/style.css
addons/featured-dangos/userscript.js
webpages/settings/index.js

Resolves #5807
New addon that adds a "Featured Dangos" row to the front page. It includes 5 hand-picked projects.
It will be enabled by default, but it won't be visible in the settings page unless it's April Fools.
TODOs:
This idea appeared to receive positive feedback in the April Fools discussion issue.
Works correctly in Chromium
The layout doesn't work very well in mobile portrait view.

Add AprilFools2023 addon: "featured dangos"

---

content-scripts/cs.js
content-scripts/inject/module.js

Resolves #5753
Converts comlink.js to a module dependency. It will now be impossible for our own code in module.js to run if comlink.js hasn't executed fully yet.
We need to ensure module.js code has access to `window.Comlink` when executing. The previous approach to load comlink.js did not ensure that in 100% of cases.
If you've experienced that userstyles run but userscripts don't, and it gets fixed after a reload, this was probably the root cause.
Needs some more testing, since we're changing the execution environment of comlink.js to strict mode.

Fix Comlink not defined in module.js (race condition)

---

webpages/settings/index.js

Use `eventObject.key` instead of `eventObject.code`.
On non qwerty keyboards, the konami code to activate the easter egg addons did not work.
[Video of the fix](https://clipchamp.com/watch/k6Ytjiw9atA/embed)

Fix konami-code in settings page not working properly on non-qwerty layouts

---

addons/scratchr2/scratchr2_comments.css

Resolves #5912
Add `text-transform: lowercase` to the reply button in the scratchr2 addon.
To make the button more similar to the scratch-www button.
Tested on 113.0.1774.3 (Official build) dev (64-bit). I do not have the ability to test more.

Lowercase reply button in scratchr2 addon

---

addons/user-id/addon.json
addons/user-id/hover.css

Resolves #5329
Added an option to the `user-id` addon that makes the user ID only appear when you're hovering over the username.
Having the user ID next to the username is useful whenever you want to use it, but what if you don't always like it to show up?
Tested on Edge 108 with SA v1.30.0-pre and it works.

`user-id`: Option to show only on hover

---

addons/dark-www/experimental_scratchwww.css
addons/search-profile/style.css
addons/search-profile/userscript.js

Resolves #5925
Makes `dark-www` and `search-profile` compatible with Scratch's recent changes to tabs in search results and on the Explore page.
Scratch changed the implementation of tabs to improve accessibility, which caused bugs in these addons.

Support updated tabs on search and Explore pages

---

addons/turbowarp-player/addon.json

Small string change for https://github.com/ScratchAddons/ScratchAddons/pull/5738
Clarified support for Cmd+Click on button for macOS users.
Mac users might think the Ctrl+Click for new tab feature won't work for them.

Clarify support for Cmd key in turbowarp-player info

---

addons/dark-www/experimental_forums_preview.js

See https://github.com/ScratchAddons/ScratchAddons/pull/5077#issuecomment-1528897383
Removes outdated code related to the "dark scrollbars" setting from `experimental_forums_preview.js`.
* On Firefox, it works the same as before.
* On Edge, the scrollbar is now dark if the background is dark.

dark-www: remove references to dark scrollbars setting

---

addons/message-filters/userscript.js

Resolves #5697
Closes #5783
Fixes incorrect logic in the `message-filters` userscript. The previous code used an infinite loop with `waitForElement`, which caused the button to be clicked for every message until there were at least 40. This PR uses Redux to detect messages being loaded instead.
Tested on Edge and Firefox. Verified that every request is sent only once using the network log.

message-filters: fix load more spam

---

addons-l10n/en/move-to-top-layer.json
addons/addons.json
addons/move-to-top-layer/addon.json
addons/move-to-top-layer/userscript.js

New addon "Move to Top Layer" to move a sprite to the top layer when shift-clicking its thumbnail in the sprite list. I extracted the code for this addon from a larger addon created by Norbiros that wasn't fully accepted by ScratchAddons.
Resolves #4231
Created new addon "move-to-top-layer"
When a sprite is covered by other sprites on the Stage so that it is not visible, to make it visible you have to go to the palette and run a "go to front layer" block. By enabling this extension it can be quickly brought to the front layer by simply shift-clicking its thumbnail in the sprite list
I tested this extension locally as an unpacked extension.

New addon: "Move sprite to front layer"

---

webpages/settings/components/addon-body.html
webpages/settings/style.css

- The `addon-blink` animation now has a drop-shadow to make the addon glow orange
- The animation's timing has been modified 
I feel like the animation is more noticeable with these changes.
To see the animation for yourself:
1. Search for "Scratch Notifier" in the popup.
2. Disable the addon if it's already enabled, then enable the addon, then on the following prompt, choose "Open full screen settings".
3. Observe the animation. Refresh the page or use developer tools to replay it.
Tested on Edge 109.

New addon-blink animation

---

addons/dark-www/experimental_scratchwww.css
background/get-userscripts.js

The ST is working on an updated privacy policy that will include a new "Cookies" page. There will also be a notification banner about the update.
Tested by running scratch-www locally.

Support new cookie policy page

---

background/get-addon-settings.js

Resolves #5992
See https://github.com/ScratchAddons/ScratchAddons/pull/5896#discussion_r1181981293 for more information about the bug this fixes.
Converts all colors (in memory) to `#{rr}{gg}{bb}{aa}` format before comparing them.
Adds preset migrations for #5896 and #5931
TODOs:
See above.
All cases tested in Chromium.

Fix preset migration logic edge-cases and migrate `editor-theme3` & `editor-dark-mode`

---

addons/faster-project-loading/userscript.js

Resolves #6062
`faster-project-loading` blocks requests to insert sprites from the backpack. To my understanding, these requests always look like this: `https://backpack.scratch.mit.edu/*.zip`. Because they begin with backpack.scratch.mit.edu, this addon blocks them, but that was not the intended behavior. This change should fix that but not affect project load speed.
Tested in Edge 113.

Fix unable to insert sprites from backpack

---

addons/editor-buttons-reverse-order/userstyle.css

Changes the order of elements when "reverse order of project controls" is enabled.
https://github.com/ScratchAddons/ScratchAddons/pull/6061#issuecomment-1551769458
> ... it would prevent the clone counter, which doesn't have a fixed width, from causing the mouse position to move.

editor-buttons-reverse-order: change order

---

addons-l10n/en/gamepad.json

Resolves #5458
Changed the description of the checkbox for storing the gamepad configuration inside the project.
For clarification.
Tested.

Change string `gamepad/store-in-project`

---

addon-api/content-script/Tab.js
background/get-userscripts.js
content-scripts/inject/module.js
content-scripts/prototype-handler.js
manifest.json

Runs addons on https://scratchfoundation.github.io/scratch-gui/beta/ and https://scratchfoundation.github.io/scratch-gui/develop/
Related: #5281
Makes it easier to test the upcoming changes.
This will be reverted before v1.33.0 release.
Most things work normally in Chromium and Firefox. This includes dynamic enable, dynamic disable and dynamic setting changes.
There's some problems with `addon.tab.scratchClass` but a reload often fixes it. If, for example, the find bar lacks CSS, a reload will often fix it. It's not a bug that will happen this often in real scratch.mit.edu.

Run addons on `scratchfoundation.github.io` for testing

---

addons/editor-dark-mode/addon.json
addons/editor-dark-mode/experimental_editor.css

When Scratch adds the high contrast theme, there will be a theme picker in the menu bar. There will also be an updated design for toggle buttons. This PR adds support for these new components to editor dark mode.
To make sure that things don't look weird when the update is released.
Tested locally (using the beta version of scratch-gui) and on `scratch.mit.edu`.

editor-dark-mode: add styles for theme picker and toggle buttons

---

addons/initialise-sprite-position/addon.json

Reworded the description and some settings in the `initialise-sprite-position` addon.
To make it easier to understand it.
Should work fine.

Reword sentences in `initialise-sprite-position`

---

addons/sprite-properties/userscript.js

Resolves #5898
The sprite properties won't hide if the mouse left them as a result of the user changing the direction of a sprite by dragging the dial.
The sprite properties will stay visible until the cursor leaves the sprite properties again (excluding the direction dial). I don't think it makes sense to try to do better in this case.
Fixes an important bug.
Tested in Chromium in scratch.mit.edu and https://scratchfoundation.github.io/scratch-gui/beta/

Fix "collapse when mouse leaves sprite panel" bug (sprite-properties)

---

addon-api/content-script/Tab.js
content-scripts/inject/module.js
content-scripts/inject/run-userscript.js

Resolves #4106
- Userscripts that don't specify runAtComplete (or that explicitly set runAtComplete:true) won't run until `addon.tab.scratchClass()` is guaranteed to work properly.
- A persistent mutation observer that made a somehow expensive (haven't measured) document.querySelector call in the callback has been removed as a consequence of the above.
- Previously, `addon.tab.scratchClass()` failed often (depending on computer and internet speeds) when running scratch-gui locally or visiting https://scratchfoundation.github.io/scratch-gui/beta/ or https://scratchfoundation.github.io/scratch-gui/develop/. Now, it should always work properly. Exceptionally, some users suffered from this bug on scratch.mit.edu too in the release version (not 100% confirmed whether this PR should fix those …

Enhance `addon.tab.scratchClass` performance and consistency

---

background/get-addon-settings.js
background/handle-settings-page.js
libraries/common/minify-settings.js
webpages/settings/index.js

Resolves #5849
For new users, it creates three different storage items for addon settings: addonSettings1, addonSettings2 and addonSettings3.
For existing users, it splits the addonSettings storage item in three parts (using the first character of the addon ID) and reloads the extension.
The structure of settings JSON files (which can be exported/imported) remains untouched.
See #5849. There's a very low size per-key limit.
Still a draft, so not tested yet.
Will need deep testing in both Chromium and Firefox.

Split "addonSettings" storage item into 3 different items

---

addon-api/content-script/Tab.js
content-scripts/inject/module.js

Fixes bug introduced here: https://github.com/ScratchAddons/ScratchAddons/pull/6105/files#r1208669440
Considers URLs such as https://scratch.mit.edu/projects/104/remixes/ and https://scratch.mit.edu/projects/104/studios/ not to be project pages. Project embeds were already excluded.

Fix `isProject` (is project page) logic

---

addons/editor-theme3/addon.json

Moves the "High contrast" preset in `editor-theme3` up to the top of the list for easier access. This will become a much more important preset after Scratch's update that we already know about. Also removes a reference to Scratch Lab from the preset tooltip.
Tested.

Move high contrast blocks preset up

---

content-scripts/cs.js
popups/scratch-messaging/popup.js

Resolves #6028
Removes the use of a MutationObserver in projects and studios, in favor of `window.addEventListener("click", ...)`.
This might have fixed some bugs, and should be generally better for performance.
Tested successfully in Chromium and Firefox. This includes making sure the "post anyway" feature works properly.

Fix bugs with extension policy comment censoring (commenting "Scratch Addons")

---

addons/data-category-tweaks-v2/userscript.js

The "data category tweaks" addon uses Scratch's extension category system to replace the data category with separate categories for variables and lists. That didn't work in high contrast mode because Scratch tries to change the color of all extension categories and the code responsible for that only expects one category per item.
This PR fixes the issue.
To make the feature work after the Scratch update.
Tested on https://scratchfoundation.github.io/scratch-gui/beta/ and on the Scratch website.

data-category-tweaks-v2: high contrast mode fix

---

addons/hide-flyout/userscript.js
addons/zebra-striping/userscript.js

Fixes two bugs that happened when switching theme:
* `hide-flyout` stopped working.
* The `zebra-striping` bug happened when a reporter inside another block from the same category was being replaced:
When doing this after changing the theme, the replacement glow wouldn't appear.
Tested on https://scratchfoundation.github.io/scratch-gui/beta/ and on the Scratch website.

Add `SET_THEME` to `reduxEvents` list in some addons

---

addons/sounds-duration/addon.json
addons/sounds-duration/userscript.js

A step towards https://github.com/ScratchAddons/ScratchAddons/issues/1673
Added dynamic enable and disable support to `sounds-duration`. The addon actually continues running in the background but is invisible while disabled.
We're trying to add dynamic enable/disable support to all addons at some point.
Tested on Edge 113.

Dynamic enable and disable for sounds-duration

---

addons/editor-comment-previews/userscript.js

Resolves #6000
Fixes a bug in `editor-comment-previews` that caused the `sa-comment-preview-outer` element to stay visible after the addon was dynamically disabled.
Tested in Edge 114.

editor-comment-previews: Fix dynamic disable

---

addons/folders/userscript.js

Resolves https://github.com/ScratchAddons/ScratchAddons/pull/6137#issuecomment-1584936150
Userscripts that call `addon.tab.createEditorContextMenu()` and that run before complete need to wait until scratchClass is ready.
It was reported that `move-to-top-bottom` was broken, but it was a byproduct of the "sprite folders" addon breaking.
Hopefully adding this `await` doesn't break anything (it's now the first one in the file). We can use `.then()` instead in that case.

Fix `addon.tab.scratchClass` regression breaking folders addon

---

addons/vol-slider/hover.css

Resolves #6184
Made it so that the Turbo Mode label that appears next to the stop sign when Turbo Mode is enabled hides when hovering over the volume slider, just like the clone counter and mouse position display.
Tested in Edge 114. Code modified using browser developer tools during testing.

Hide Turbo Mode label when volume slider hovered

---

addons/custom-zoom/userscript.js

Resolves #6191
Fixes bugs in `custom-zoom` that happened when changing the Scratch language or theme.
Tested on the Scratch website and in the GUI playground.

custom-zoom: respond to theme and language changes

---

addons/confirm-actions/userscript.js

Resolves #6219
Tested in Chromium:
- Share confirmation works inside the editor.
- Share confirmation works in the project page.
- Share confirmation continues to work outside projects, such as the follow/unfollow confirmation (note that this type of confirmation is disabled by default in the settings)

Fix "confirmations" addon project sharing confirmation not working

---

webpages/settings/permissions.html

Fixes the styling of the Enable button on the permissions page. I think it was broken by #4516.
Tested on Edge and Firefox. v1.33.1:
After this change:

Fix unstyled button on permissions page

---

addons-l10n/en/studio-tools.json

Removes the string `studio-tools/owner-error`.
Before the studio update, this error appeared if the owner of a studio tried to use the "Leave Studio" button. In the current version of the addon, the button doesn't appear if you're the owner, so this string isn't used anywhere.

studio-tools: remove unused string

---

content-scripts/cs.js

Resolves #4746
Extended the "scratch addons" warning to new forum posts, new forum topics, editing existing topics and (probably, haven't tested) the signature changing screen.
Appears to work in Chromium. See comment: https://github.com/ScratchAddons/ScratchAddons/pull/6232#issuecomment-1599656292

Warn users before posting "scratch addons" on forums

---

addons/hide-stage/userscript.js
addons/search-profile/userscript.js

Changes code that sets `role` and `aria-*` attributes to use `setAttribute()` because `.role` and `.aria*` don't work on Firefox.
Some things didn't work correctly on Firefox:
* The tab added by `search-profile` was read as "button" instead of "tab, not selected" by screen readers.
* In the beta version of scratch-gui, the hide stage button didn't appear selected when the stage was hidden.
Tested on Edge and Firefox. The `hide-stage` change was tested by running scratch-www locally.

Use setAttribute to set ARIA attributes

---

addons/dark-www/addon.json
addons/editor-dark-mode/addon.json
addons/editor-theme3/addon.json
webpages/settings/index.js

I don't see any reason not to do this (see screenshot).
Also, `op-badge` has been moved to the "other new addons and updates" group,

Feature color-related addons at the top of settings (1.32.2)

---

addons/editor-dark-mode/experimental_editor.css

Fixes a bug in the beta version of scratch-gui: when the mouse is moved over the code area scrollbar but not over the thumb, the scrollbar reverts to the default color.
The Scratch change that caused this is explained here: https://github.com/scratchfoundation/scratch-blocks/pull/2962#discussion_r1108574249
The bug is annoying.
Tested locally and on scratch.mit.edu.

editor-dark-mode: fix scrollbar hover color

---

addons/dark-www/addon.json
addons/dark-www/banners/darker.css
addons/dark-www/banners/darker_explore.css
addons/dark-www/banners/darker_join.css
addons/dark-www/banners/darker_search.css
addons/dark-www/banners/desaturated.css
addons/dark-www/banners/desaturated_join.css
addons/dark-www/experimental_forums_preview.js
addons/dark-www/experimental_project_embed.css
addons/dark-www/experimental_scratchr2.css
addons/dark-www/experimental_scratchwww.css
addons/dark-www/join.css
addons/horizontal-mystuff-tabs/scratchr2.css
addons/old-studio-layout/scratchr2.css
addons/scratchr2/scratchr2.css

Makes `dark-www` work better with Scratch's color contrast update. I didn't make changes to other addons in this PR unless they were referencing CSS variables I renamed or removed.
We don't know what changes, if any, will be made to scratchr2. I decided to use the same colors on scratch-www and scratchr2 (see screenshots below). If the ST does something different, we can change it in a future update.
I used the updated Experimental Dark preset proposed in #6128 in the screenshots.
Tested by running scratch-www locally.

dark-www: compatibility with Scratch color changes

---

addon-api/content-script/modal.js
addons/editor-dark-mode/experimental_editor.css
addons/op-badge/forums.css
addons/op-badge/projectpage.css
webpages/settings/components/previews/editor-dark-mode.html

Part of #6091
Updates the `op-badge` addon, `addon.tab.createModal`, and the editor dark mode preview to use the new purple color.

Update remaining uses of blue accent color

---

addons/customize-avatar-border/addon.json
addons/necropost-highlighter/style.css
addons/old-studio-layout/addon.json
addons/old-studio-layout/style.css
addons/scratchr2/addon.json
addons/scratchr2/forums.css
addons/scratchr2/mystuff.css
addons/scratchr2/remixtree.css
addons/scratchr2/scratchr2.css
addons/scratchr2/scratchr2_comments.css
addons/scratchr2/v_tabs.css
addons/scratchr2/view_all.css
addons/scratchstats/userscript.js

Progress on #6091
Switches to the new purple in website addons, except for `dark-www` which is handled in #6128 and #6268.
Scratch is changing it's blue colour (`#4d97ff`) to purple (`#855cd6`) and addons should stay consistent with Scratch. Scratch also changed some other colours, but those aren't handheld in this PR yet.
Untested. I'm probably missing something. I'm submitting this now because we're getting very close to the deadline and my local `scratch-www` instance isn't quite working.

Use new purple in website addons

---

addons/editor-dark-mode/addon.json
addons/editor-dark-mode/experimental_editor.css

Makes selected text, hovered block category names, and checkboxes in the block palette blue even if a different highlight color is chosen.
A blue loading screen would look very bright in a dark theme, so the page background is used in dark themes instead.
In Scratch, these things are still blue and not purple.
Tested by running scratch-www locally.

editor-dark-mode: use blue color for some elements

---

background/get-addon-settings.js

Store the list of setting migrations that were applied. Might be useful in the future, in case we want to distinguish users that have some settings because of the migration vs. they already had those settings before then. It's also possible that we'll never use this. It won't take a lot of space to store a few integer numbers.
To be tested

Store setting migrations that were applied

---

content-scripts/cs.js

Resolves #6304
Do not show update notification banner if running on an iframe.
This is quite difficult to test. But in non-iframes, the update notification works normally after this change.

Do not show update notification on iframes

---

addons/dark-www/addon.json
addons/dark-www/experimental_scratchr2.css
addons/op-badge/forums.css
content-scripts/cs.js

Resolves #6314
* Fixes the color of hovered usernames in profile comments (https://github.com/ScratchAddons/ScratchAddons/issues/6296#issuecomment-1612304865)
* Removes separators between menu bar items (#6314)
* Changes the blue color on scratchr2 pages if a blue preset is selected (https://github.com/ScratchAddons/ScratchAddons/pull/6268#issuecomment-1613487815)
* `customCssVariables` changes:
* New `default` property for `"type": "map"` value providers. It's a value provider that's used as a fallback if none of the options match.
* The `options` of a `"type": "map"` value provider can now also be value providers.
To make the "Scratch's default colors" preset more similar to Scratch's new design and the blue presets to the old one.

dark-www: old scratchr2 blue and other changes

---

content-scripts/cs.js

Resolves #6300
Changes the color of links in the update notification to `#1aa0d8` and makes the text size and line height the same on scratch-www and scratchr2 pages.
The purple color doesn't have enough contrast with the dark background.

Change link color in update notification

---

addons/dark-www/addon.json

Changes the IDs of the two "blue" website dark mode presets. They currently (in v1.33.2) have the same IDs as the purple versions.
If two presets have the same ID, only one string is uploaded to Transifex and their names and descriptions are the same in languages other than English.
The presets are still displayed correctly on the settings page.

dark-www: fix duplicate preset IDs

---

addons/paint-snap/genScalePoints.js
addons/paint-snap/genSnapPoints.js

Added an extra filter to the snapping algorithm that was using the costume mask, resulting in snapping to center even when snap to page center was disabled
(Below images run with only snap from selection center and snap to object center enabled)
Before:
After:

Don't snap to costume mask

---

addon-api/content-script/modal.js
images/cs/close-s3.svg

Resolves #6292
Looks like Scratch currently uses a data URL for its "X" icon. There may be a new URL that works now, but anyways I think it's better to include the close icon as part of the source.

Fix modal API "X" close icon not loading

---

addons/dark-www/addon.json
addons/dark-www/experimental_scratchr2.css
addons/user-id/userstyle.css

Resolves #6306
Changes the text color of About me and WIWO sections on profile pages to an opaque one.
The transparent color wasn't dark enough on Chromium-based browsers. It also made emojis transparent.

dark-www: fix text color in About me & WIWO

---

addons/editor-dark-mode/addon.json
addons/editor-dark-mode/paper.js

Resolves #6301
* Uses the page background instead of the highlight color to generate the background pattern of the costume editor canvas
* Makes the selection borders always blue
Consistency with Scratch.
Tested all presets on Edge and Firefox.

editor-dark-mode: blue paint editor

---

addons/clones/style.css
addons/clones/userscript.js
addons/debugger/style.css
addons/debugger/userscript.js
addons/gamepad/style.css
addons/gamepad/userscript.js
addons/mouse-pos/style.css
addons/mouse-pos/userscript.js
addons/vol-slider/userscript.js
addons/vol-slider/userstyle.css
libraries/common/cs/small-stage.js

Resolves #6275
Fixes a bug in `clones`, `mouse-pos` and `vol-slider`: switching to full screen or the project page while small stage mode was selected didn't show the addon's UI. `gamepad` doesn't seem to be affected.

Fix stage header addons not showing in full screen

---

addons/editor-dark-mode/addon.json
addons/editor-dark-mode/paint_icons.js

Resolves #6299
Changes paint editor icons based on editor dark mode settings.
This makes the icons blue in blue presets:
It also makes them look better in dark mode:

editor-dark-mode: change the color of icons in paint editor

---

webpages/settings/components/previews/editor-dark-mode.html
webpages/settings/components/previews/editor-dark-mode.js

Updates the setting preview for editor dark mode:
* Changes the menu bar and toggle button styles to match Scratch's new design
* Makes icons in the paint editor affected by highlight color
* Makes paint editor background based on page background instead of highlight color
The preview should be consistent with the actual addon.

Update editor dark mode preview

---

addons/editor-dark-mode/addon.json
addons/editor-dark-mode/experimental_editor.css
addons/scratchr2/assets/zoom_in.svg
addons/scratchr2/assets/zoom_out.svg
addons/scratchr2/assets/zoom_reset.svg
addons/scratchr2/remixtree.css

scratchfoundation/scratch-gui#8843 changed the way Scratch serves static files, which broke existing URLs and caused a few issues in SA (#6292 is already fixed). This PR fixes the following bugs:
* Zoom icons in remix tree were broken if 2.0 → 3.0 was enabled:
* Icons in the Sounds tab and library weren't white in dark mode:
* Play and Stop icons in the record modal weren't affected by the highlight color setting.

Fix references to Scratch asset URLs

---

addons/necropost-highlighter/userscript.js
addons/vol-slider/userscript.js

The other two stems from use of ES2022 feature. While static fields are supported by the lowest supported browsers (Chrome 80/Firefox 86) it is not in ES2020 (which eslint is configured to). Eslint config would be modified when we revisit supported version policy.

Fix two lint errors

---

addons/ctrl-enter-post/addon.json
addons/ctrl-enter-post/forums.js

Resolves #6262
Adds an `if` check to handle the different textbox on forum post report pages under `/discuss/misc/*
Reported a post and it seems to work, tested on Firefox, macOS (cmd+enter and ctrl+enter)

Apply "Ctrl+Enter to post" when reporting in the forums 

---

addons/pause/userscript.js

Resolves #6369
Fixes
>Usually, you aren't able to pause a project after dynamically disabling the Pause button addon because the button disappears. However, it is still possible to pause the project with the recently added Alt+X keyboard shortcut even after the addon is disabled.
No

Fix projects can be paused with Alt+X after disabling

---

popups/scratch-messaging/api.js

- Fixes bug: handle case where `getReplies` doesn't return an array and instead it returns an object or `null` (both are valid JSON)
- Small fix for consistency: `getReplies` now returns on 404 errors `null` instead of `undefined`, which is not valid JSON
Feedback:
> ''TypeError: Cannot read properties of undefined (reading 'forEach')'' Please fix it :'(
This appears to be the only place where forEach is used in scratch-messaging
Not really worth it to try to emulate the bug, as we can never be 100% certain this is what the user reported, but Scratch Messaging continues to work fine for me.

Fix Scratch Messaging popup "forEach of undefined"

---

addons/better-img-uploads/userscript.js

Resolves  #6238 
Added support for importing .sprite3 files (they are accepted but passed through with no changes), and changed 1 number in the logic for image sizing from 479 to 480 to stop it resizing certain things incorrectly.
Cuz they were annoying me and mxmou and WL said they were good 👍
Tested in Brave Version 1.52.126, Chromium version 114.0.5735.133

better-img-uploads (HD image uploads) bug fixes

---

addons/share-through-mystuff/userscript.js

Resolves #6280
Adds traps so that Scratch sends a request to the REST API instead of the deprecated one, which is never used by vanilla Scratch to share projects.
This means the addon continues to work exactly like before, but the request is going to the intended URL. Checking whether the request succeeded or failed is still handled by Scratch, just like before.

Use non-deprecated API on share-through-mystuff

---

addons/disable-stage-drag-select/addon.json
addons/disable-stage-drag-select/userscript.js

Added a new setting in the _Non-draggable sprites in editor_ addon that allows the user to enable dragging while the project is stopped.
Gives users more options for customization.
Tested in Chrome 114.0.5735.106

Add option to disable-stage-drag-select

---

.eslintrc.json
.github/gen-manifest.mjs
.prettierignore

Resolves #6084
Three changes:
- localhost and `scratchfoundation.github.io` permissions are now removed during gen-manifest execution, from both the permissions section and the CS section.
- In Firefox, DNRWHA permission is no longer removed. FF113+ supports DNRWHA, and development build (without this being removed) works fine.
- Linter configuration changes.

Strip localhost permission and include DNRWHA in generated manifest

---

addons/expanding-search-bar/expanding-search-bar.js

- When clicking the magnifying glass icon, which is actually a button to search, the search bar now stays expanded if it was expanded already. You still need to focus the search bar input for it to expand, to let you know when you can type into the search bar.
- A side effect of this change is that pressing Shift+Tab now moves to the Scratch logo instead of "About" on the navbar, so the way the links are hidden has been changed so pressing Shift+Tab (to move to the previous element) when navigating with a keyboard still moves focus to "About". Keyboard usability is useful not only for accessibility but also efficiency (I could imagine people Tabbing to the search bar all the time).
- Prevents accidents if someone decides to click the magnifying glass.
1. Click the search bar. Optionally …

Don't collapse search bar on icon click

---

addon-api/content-script/Account.js
addons/editor-messages/userscript.js

Resolves #5991
- The only userscript that used this API now uses fetch every 30 seconds (instead of using addon.account.getMsgCount every 5 seconds)
- Old addon.account.getMsgCount code was not removed but it was made inaccesible.
See #5991
Addon still works

editor-messages: use fetch instead of `addon.account.getMsgCount()`

---

addons/editor-compact/userstyle.css

Resolves #6435
Now `editor-compact` removes the margin-top and margin-bottom of the images that may appear on the stage header (at the moment, the turbo mode indicator and the clone counter).
The volume slider / muted indicator wasn't causing any style issues so they aren't affected.
Tested in editor mode and project fullscreen in Chromium

Fix editor-compact bug: stage header imgs overflow vertically

---

addons/echo-effect/userscript.js
addons/editor-compact/force-tooltip-update.js
addons/editor-compact/userscript.js

Resolves #6445
Addon `echo-effect` now calls `updateTooltips()` when adding the echo button
Bug fixed in Chromium

Fix editor-compact/echo-effect compatibility

---

addons/columns/userscript.js
addons/editor-compact/userstyle.css

Resolves #6444
Adds a class to the `<body>` element instead of adding it to the `gui_tab-panel`
Easiest way to make sure we're not missing any edge cases where the panel is re-created. The body element is always the same.

More robust solution for editor-compact/columns compat

---

addons/editor-theme3/theme3.js

Avoid `array.at(-1)`, specially inside a Blockly trap.
`Array.prototype.at` is only available in Chromium 92+ (released June 2021)
This was the root issue from a feedback report (Chromium 87).

Fix editor-theme3 browser support (array.prototype.at)

---

addons-l10n/en/pause.json
addons/pause/userscript.js

Currently, when hovering over the pause button, it shows a tooltip reading "Pause", but it also says "Pause" when hovering over the _resume_ button. Now, the resume button has its own tooltip - "Resume".
You know.
Tested in Edge 115.
Tested Dynamic Disable and in combination with `debugger`.

`pause`: Set title to "resume" for resume button

---

addons/true-youtube-links/addon.json
addons/true-youtube-links/userscript.js

Replaces #6166
- Adds dynamicDisable support to addon (disabled and reenabled events)
- Use `markAsSeen:true` to avoid potential infinite loops in case something goes wrong

true-youtube-links: add dynamicDisable support

---

webpages/styles/components/buttons.css

Resolves #6468
(Don't mind the branch name, I originally solved this using a different strategy which didn't actually work)
Change the way padding works on a .large-button to use actual padding.
So that buttons with more than one line look correct
Tested in Edge, it would surprise me if it didn't work everywhere

Fix long preset names not looking correct

---

addons/dark-www/addon.json

Resolves #6463
Adds a temporary notice to website dark mode mentioning the new presets.
Users might not notice them or not realize they're new.
Tested on Firefox 116.

Mention new website dark mode presets

---

addons/debugger/addon.json

We've been asked this question: #4412
Makes the meaning of the Threads tab in the Debugger window clearer by referring to a thread as a stack of blocks in the addon description.

Debugger addon description: clarify Threads tab

---

addons/dark-www/experimental_scratchwww.css

Resolves #6383
Makes messages from the Scratch Team affected by the highlight color setting in dark-www.
Before #6395, the addon didn't change the background color of admin messages at all. In #6395, I accidentally made them use the "blue background" setting.
Tested by running scratch-www locally and modifying the code to show a test alert.

dark-www: support admin messages

---

addons/dark-www/addon.json
addons/dark-www/experimental_scratchr2.css

Resolves #6475
Style forum error messages with the box color. Note that this changes the error message color with the default settings from `#f5f5f5` to `#f7f7f7`, but it's not that noticable.
So error messages aren't as bright in dark mode.

Style forum error messages in dark-www

---

addons/forum-post-countdown/addon.json

Shortens the  `forum-post-countdown` name and adds a bit more to the description.
Because shorter addon names are better in most cases and the location feels like it should be part of the description.
Tested on Chromium 115

Better forum-post-countdown name and description

---

addons/editor-compact/userstyle.css

Resolves #6563
The old CSS is left intact but it only affects inputs with type=text
Inputs with type=number get more room and only get reduced by `0.5rem` vs vanilla width,
Now, three digit numbers fit in Chromium and Firefox

editor-compact: fix narrow number inputs

---

addons/editor-compact/sprite-properties.css
addons/editor-compact/userstyle.css

Resolves #6545
Resolves #6551
Places labels next to inputs in all languages. There's enough space for them with the compact layout.
To fix the bug described in #6551 and use space more efficiently.
Tested on Edge and Firefox. Works as expected in all languages that normally use the wide layout ([list](https://github.com/scratchfoundation/scratch-gui/blob/953c39d85d7436bb43e894abdfbfe772e1fc86f7/src/lib/locale-utils.js)).

editor-compact: fix "wide" layout of sprite info

---

addons/expanding-search-bar/expanding-search-bar.js

Sets the overflow property of the navigation bar links to hidden to avoid them showing up on top of (technically, under) the search bar while the `scratchr2` addon is enabled.
To fix #6567
Tested in Edge 115.

Fix "expanding search bar" regression (with scratchr2 addon enabled)

---

addons/colorblind/bold-links.css
addons/colorblind/underline-links.css

Resolves #6536
Explicitly also style anchor tags without an `href` for specificity reasons.
Some links were unstyled.

Style non link links with `colorblind`

---

addons/project-notes-tabs/userscript.js

Resolves #6606 and resolves a pending compatibility task from unmerged PR #6258
We previously assumed `section.querySelector(".project-textlabel").innerText` to be the correct name for each section (either Instructions or Notes&Credits). It is also true in vanilla Scratch that the textContent of the first span child of that same element is the name of the section. So let's shrink the assumption as much as possible.

project-notes-tabs: More accurately get the name for each section

---

addons/project-notes-tabs/style.css

The `project-notes-tabs` addon adds `box-sizing: border-box` to the description, which changes the width. This PR adds `width: 100%` to fix that. It also removes unnecessary uses of `!important`.
This makes the right edge of the description aligned with the See inside button (and probably the preview toggle after #6489).

project-notes-tabs: don't change description width

---

addons-l10n/en/_general.json
addons/debugger/userscript.js
addons/editor-theme3/theme3.js
addons/middle-click-popup/BlockTypeInfo.js

Resolves #6579
Changes the `global/` string prefixes to `_general/`
To fix a bug where some tribulations were located in the wrong file.
Tested by moving another language's translations to the _general file locally. The find bar's flag label is still not translated and #6599 should be fixed with #6600

Fix global translation string IDs not prefixed with `_general`

---

background/handle-auth.js

Resolves (mitigates?) #6460
After 5 received events "in a row" (during 1500ms), `chrome.cookies.onChanged` events are added to a queue and only one is processed every 1500ms.
To emulate #6460 (requesting `/session/` itself setting cookies unexpectedly), add this to the top of handle-fetch.js:
```js
const extraInfoSpec = ["blocking", "responseHeaders"];
if (Object.prototype.hasOwnProperty.call(chrome.webRequest.OnBeforeSendHeadersOptions, "EXTRA_HEADERS"))
extraInfoSpec.push("extraHeaders");
chrome.webRequest.onHeadersReceived.addListener(
function (details) {
details.responseHeaders.push({
name: "Set-Cookie",
value: "scratchcsrftoken=abc; Domain=.scratch.mit.edu; expires=Fri, 30-Aug-2024 12:00:00 GMT; Max-Age=31449600; Path=/; secure",
});
return {
responseHeaders: …
```

chrome.cookies.onChanged: avoid infinite loops

---

addons/scratchr2/forums.css

Resolves #6534
Add `text-decoration: none` to the CSS in `scratchr2` responsible for styling the breadcrumbs. This is enough for `scratchr2` to override `colorblind`.
To make `colorblind` make more sense and only style links that are visible as such (rather than buttons).

Make forum breadcrumbs and page numbers styled by `scratchr2` not affected by `colorblind`

---

addons/sprite-properties/userstyle.css

Resolves #6602
Sprite pane not using all available space when both `editor-compact` and (collapsing)`sprite-properties` enabled
Increases the specificity of the selector with `height: 100%` inside so that it wins when the sprite properties are collapsed through the addon.
I will test this more thoroughly before merging. Send a review if you find a bug.
I will try to check all addons that target this element

Fix sprite pane not using all height (`editor-compact` & `sprite-properties`)

---

background/load-addon-manifests.js
webpages/error/check-chrome-storage.js
webpages/error/export.js
webpages/error/index.html
webpages/error/index.js
webpages/error/reset-settings.js
webpages/error/style.css
webpages/settings/index.html

Related to / mitigates #5306
Related to #6048
Related to #4949
I posted this idea a while ago: https://github.com/ScratchAddons/ScratchAddons/issues/5306#issuecomment-1299223233
This PR creates an error page and displays it in the following situations:
- Invalid addon.json file during development (already existed since #4949, now also supports Firefox)
- The settings page crashed or doesn't work because `chrome.storage` is unavailable/broken (#6048) which happens quite often in Chrome
This page also provides a link/button to reset all extension settings. It also recommends restarting the browser.
This page won't be localized for now. I'm open to adding more CSS, but it's not very important. Also, this page won't support dark mode.

Create error page, redirect to it on typical settings page crashes

---

addons/editor-number-arrow-keys/addon.json

Merges a duplicate `latestUpdate` key in `editor-number-arrow-keys`.

Fix duplicate latestUpdate key in addon manifest

---

addons/hide-delete-button/addon.json
addons/remove-sprite-confirm/addon.json

Considering `disable-paste-offset` has a bonus tip ("This behavior can also be achieved without this addon by Alt+Clicking the item."), I thought it'd be alright to add a bonus tip to the sprite deletion-related addons:
> Bonus tip: Accidentally deleted a sprite, costume, or sound? You can bring it back with Edit → Restore \<item> in the menu bar.
Tested.

Note that you can undo a sprite deletion

---

addons/confirm-actions/userscript.js

Resolves #6683
Make the `.banner-button` selector more specific by also requiring a `.banner-text` next to it, which the ideas button doesn't have.
To fix the share modal appearing on the ideas button.
Tested on Edge 116.

Fix share confirm modal appearing on ideas button

---

addons/dark-www/addon.json
addons/dark-www/experimental_scratchr2.css

Resolves #6710
Change the text color of the statistics items when on a dark background.
Contrast.

dark-www: better support for scratch.mit.edu/statistics

---

addons/old-studio-layout/style.css

From feedback:
> this has been a problem for a while but i didnt really realize how bad it actually was until now
i design my studio icons with the addon in mind, but for regular users it looks stretched
This PR preserves the aspect ratio of `1.53846153846` (😂) even when `old-studio-layout` is enabled. Technically this goes against the spirit of the addon, as studios previously used this aspect ratio, but it's still a weird decision to change it.
cc @mxmou

old-studio-layout: preserve thumbnail aspect ratio

---

addons/turbowarp-player/userscript.js
libraries/common/message-cache.js
popups/scratch-messaging/api.js
popups/scratch-messaging/popup.js

Resolves #6717
- Removes `nocache=${Date.now()}` and `timestamp=${Date.now()}` from Scratch Messaging code. These requests may now get cached by the browser (disk cache) or by the Scratch API.
- When an uncached version of the request is really needed, rename the URL paramater to be descriptive.
The "nocache" keyword is filtered by the Scratch API and is intentionally throttled.

Reconsider usage of timestamps in URLs to bypass cache

---

addons/cat-blocks/userscript.js
addons/custom-block-shape/update-all-blocks.js
addons/custom-block-shape/userscript.js
addons/custom-block-text/userscript.js
addons/editor-dark-mode/extension_icons.js
addons/editor-theme3/theme3.js

Resolves #6691
Disables workspace undo after reloading the workspace. The whole undo stack gets cleared.
There might be a way to keep the old "undo" actions available, but I'm not aware of them.
Fixes the bug in Chromium, addons custom-block-shape and custom-block-text
cc @DNin01 We probably need to check other addons that use `clearWorkspaceAndLoadFromXml`

Fix workspace undo bugs after workspace reload

---

addons/collapse-footer/userscript.js
addons/collapse-footer/userstyle.css

Resolves #6720
Fix footer appearing expanded at first on scratchr2 pages by lazily applying the transition on expand.
To make the experience feel less buggy.

`collapse-footer`: Fix footer appearing expanded at first on scratchr2 pages

---

addons/better-quoter/module.js

Resolves #6754
Automatically add `/get_image/.%2E` to assets.scratch.mit.edu links when quoting them with `better-quoter` to make quoted assets.scratch.mit.edu links work correctly.
~If there's any weird commits, it's probably new line encoding problems - currently trying to figure out how to set these up correctly with Git~ I've found the correct option lol
Better UX
Tested in Edge

`better-quoter`: Automatically add `/get_image/.%2E` to assets.scratch.mit.edu images

---

manifest.json

Reverts ScratchAddons/ScratchAddons#6763
What was the point of merging #6744 as part of this release?

Revert "Bump version to 1.35.0 stable"

---

background/message-cache.js
libraries/common/message-cache.js
popups/scratch-messaging/popup.js

Resolves #6777
- Continues to add URL parameters to the URL when bypassing the cache (after marking messages as read)
- Store last seen `X-Amz-Cf-Id` header in IDB, as an attempt to ignore server-side cached responses to the message count endpoint
- Do not send cookies to the message count endpoint, as it's not necessary

Fix ghost messages after marking as read (scratch-messaging)

---

webpages/popup/index.js

Resolves none (I think)
If there is no "lastSelectedPopup", for example when the extension was recently installed, default to the "Addons" tab instead of the "Messaging" tab.
The "Addons" tab is more useful for new users.

Default popup to "addons" tab (instead of "messaging")

---

addon-api/common/FetchableAuth.js
content-scripts/cs.js

When there's no `scratchlanguage` cookie, Scratch uses `navigator.language` as the language, and we want to match the language used by Scratch.
Remember that in modern browsers, `navigator.language = navigator.languages[0]` which doesn't necessarily match with the browser UI language, which is used for the popup and settings page through `chrome.i18n`.

Fix addon userscripts using wrong language for localized strings

---

webpages/settings/index.js
webpages/styles/components/enablepopup.css

A step towards #6705
The `enablepopup` component now uses an opacity-fade animation if the user prefers reduced motion.
https://github.com/ScratchAddons/ScratchAddons/assets/106490990/4e4200eb-a624-45a4-ab88-16ea27c429b4
To prevent vestibular motion triggers from the unexpected fly-in animation.
Tested in Edge 117.

Extension popup settings: support reduced motion for enablepopup component

---

addons/infinite-scroll/addon.json
addons/infinite-scroll/buttonScroll.js
addons/infinite-scroll/search-explore-module.js

Superseeds #5629
Resolves #2520
Included at #5419
Adds infinite scrolling support to project/studio search and project/studio explore.
PR #5629 also attempted this, but it sent too many requests. Scratch's "load more" button sends one request each time it's clicked, and we don't want to be sending more than one request concurrently. This is not the case in other infinite scrolling areas where the button is disabled/hidden while a new page of content is loading.

Infinite scrolling: support Explore and Search pages

---

addons/onion-skinning/userscript.js
addons/paint-snap/ui.js

Resolves #6840
#6801, in its final form, caused a regression which made it impossible to open the settings menus for the Onion skinning and Costume editor snapping addons. This change fixes that.
Tested in Edge 119. One side effect of this change is that clicking the toggle buttons next to the settings buttons doesn't close the menus, but that might be a good thing as they are kind of part of the settings, depending on how you think about them.

Fix `onion-skinning` and `paint-snap` settings menus not opening

---

README.md

GitHub seems to have updated the renderer and `> **Note**` no longer displays a styled note block (is that what it's called?). Not sure if that's intentional, but `> [!NOTE]` still works and is pretty standard so I've updated the syntax to use that.
To make it render correctly.
Tested on GitHub.com.

Update Markdown note block

---

addons/emoji-picker/userstyle.css

Fixes a bug where the "Report" and "Delete" buttons are displayed on top of the emoji picker on scratchr2 pages when the `scratchr2` addon is enabled. This happens because the `scratchr2` addon sets their `z-index` property to 1, causing them to be layered over the emoji picker.
This change increases the emoji picker's z-index to 2, fixing the problem.
Tested in Edge 119.

Layer emoji picker over Report and Delete buttons

---

addons/discuss-button/compact-nav.css
addons/discuss-button/r2.js

Resolves #6880
Uses CSS instead of JavaScript to hide the username when the "compact user dropdown" setting is enabled.
To fix a race condition and make the code simpler.

discuss-button: hide username using CSS

---

addons/editor-compact/userstyle.css

Resolves #6862
Only changes the paint editor tool selector to a single column if there's enough space.
To make space for the backpack on small screens.
Tested on Edge and Firefox with different zoom levels and window sizes.

editor-compact: fix backpack on costume tab

---

addons/preview-project-description/addon.json
addons/preview-project-description/userscript.js

Resolves #6884
Resolves #6782
Changes the way `preview-project-description` works. It now overrides the `render` function of the `Preview` component, which makes the code much simpler.
Forcing the whole page to rerender after each state change is bad for performance.

preview-project-description: simpler implementation

---

addons/custom-block-shape/userscript.js

Resolves #6692
* Moves a variable declaration to fix #6692
* Changes how the arrow position is calculated - now it's actually centered even if the padding isn't 100%.

custom-block-shape: fix dropdown arrow position

---

addons/custom-block-shape/userscript.js

Resolves #6667
Makes the padding setting of the `custom-block-shape` addon affect empty round inputs.
Some TurboWarp extensions use this type of input:
It currently looks like this with `custom-block-shape`:
Tested by opening [this project](https://scratch.mit.edu/projects/560198467/editor) on Edge and Firefox.

custom-block-shape: fix empty inputs

---

addons/blocks2image/userscript.js

Resolves #6663
Makes `blocks2image` use black text and icons when high contrast mode is enabled.
To make the text readable.

blocks2image: support high contrast mode

---

addons/better-quoter/module.js

Resolves #6815
Automatically escape open brackets `[` to `[[]` in forum posts.
This does escape more than necessary - for example, to make the text `[[]scratchblocks]` appear in a post, you only need to do `[[[]]scratchblocks]`, while this change would escape it to `[[][[]]scratchblocks]` - but it will still result in the same visual output, so it's fine.
To fix the bug.

`better-quoter`: Escape square brackets

---

addons/editor-theme3/black_text.css
addons/editor-theme3/theme3.css

Resolves #6806
Makes the HTML part of a focused block input invisible.

editor-theme3: fix transparent inputs

---

addons/ctrl-enter-post/addon.json

Resolves #6925
Add a match for `/discuss/*/topic/add/` so that it works when creating a new topic in s subforum.
<details>
<summary>Fun Fact</summary>
<br>
Weird this was found so late, I guess mostly because users create new topics a lot lesser than the amount they post.
This is #6927, about 660 pull requests before, #6267 fixed this exact same issue but when reporting a post, and even that was by me 😄
</details>

Fix `ctrl-enter-post` not working on topic creation

---

README.md

Resolves #6946
EDIT: Just realized the chrome docs one exists under a different name, committing
EDIT2: Commited, now uses the chrome docs one. Though if it's not the one it should be, please tell! I'm unsure if this and the one originally used in the `README.md` are really related or not.
This is a really minor change, so I think I don't really need to make an issue about this - Apologies if I am (EDIT: Just incase, I did)
Fixes broken URL.
The URL is outdated.
Tested with Firefox, the readme.md should work

[Readme] Fix broken URL to Chrome docs

---

addons/better-quoter/module.js
addons/show-bbcode/userscript.js

Resolves #6948
Add a data attribute to the element added by `show-bbcode`, so that `better-quoter` can see it and not escape brackets.
To make the interop make more sense and be useful.

Don't escape BBCode tags with `better-quoter` and `show-bbcode`

---

addons/scratchr2/scratchr2_comments.css

Resolves #6859
Styles comment warnings on profiles so they look as they do in scratchr2. This also makes the issue linked above no longer apply.
Making it more consistent, and fixing a bug.

`scratchr2`: Style comment warnings correctly

---

addons/2d-color-picker/paint-editor.js
addons/ctrl-enter-post/comments.js
addons/ctrl-enter-post/forums.js
addons/editor-devtools/DevTools.js
addons/editor-number-arrow-keys/userscript.js
addons/find-bar/userscript.js
addons/pause/userscript.js

Resolves #6455
Resolves #6456
Replaces most uses of `event.code` and `event.keyCode` with `event.key` (`event.key.toLowerCase()` for letters). Code that interacts with Blockly wasn't changed.
`event.code` represents the physical key, not the character associated with it. `event.keyCode` is deprecated and depends on the browser and platform.
Tested on Edge and Firefox. The find bar shortcut now works with Caps Lock. The pause shortcut now works on keyboard layouts other than QWERTY - I tested this by changing the layout to Dvorak in Windows settings.

Use `event.key` instead of `code` and `keyCode`

---

addons/folders/userscript.js

Resolves #6564
Makes duplicated sprites in folders appear at the end of the folders, not at the end of the sprite list. Duplicating costumes and sounds already works correctly.
In the current version, duplicating a sprite in a folder can create another copy of the folder.

folders: fix duplicated sprite order

---

.github/workflows/format-code.yml

Resolves #6882
Sets the version of Prettier to use to 3.1.0. This will keep us on the current version of Prettier even if it is updated. We can always update manually.
Currently, Prettier updates can cause our code formatting style to change unexpectedly, causing disruptions for contributors and us. This doesn't mean we'll never update, but if we do:
1. Currently open pull requests will still have status checks fail, but since the version will also be hardcoded on their branches, their code's formatting won't change automatically until their authors merge `upstream/master` into their branches, which updates the formatting anyway.
2. We might be able to take precautions (like notifying contributors) before updating the version to reduce the number of headaches.
Tested with GitHub Actions.

Specify version for Prettier action

---

addons/better-quoter/module.js

Resolves #6964
Adds a check for whether the user has actually selected anything, and in that case output the entire BBCode.
To fix a bug.
Tested, hopefully to full extent, in Edge

Fix `better-quoter` not quoting anything when not selecting anything with `show-bbcode`

---

addons/block-switching/addon.json

In the `block-switching` addon, changes occurrences of the word "argument" to "parameter". To my knowledge, the computer science terms "argument" and "parameter" are used interchangeably, but in Scratch, they are officially called parameters, according to the Scratch Team's latest [tutorial video](https://youtu.be/596LEqy6p7M). IMO, I also think "custom block parameter" might be understood by more users.
Consistency with the official terminology.
Not tested.

Change "argument" to "parameter"

---

addons/search-my-stuff/userscript.js

Checks if the addon is enabled before adding the search bar.
To reproduce the bug in the current version:
* Enable the addon and open My Stuff
* Disable the addon
* Switch to a different tab (Project/Studios/Trash)

search-my-stuff: don't show search bar when disabled

---

addons/hide-project-stats/addon.json
addons/horizontal-mystuff-tabs/addon.json
addons/scratchr2/addon.json
addons/search-my-stuff/addon.json
addons/share-through-mystuff/addon.json

Resolves #6945 
see there for more context, tl;dr: add whatever besides a section to mystuff and if you have addons that have a match related to mystuff then they won't load for the entire millenium
Also fixes these not loading:
- `share-through-mystuff`
- `scratchr2` (things related to this issue)
- `hide-project-stats`
- `search-my-stuff`
Adds wildcards after most MyStuff matches 
Make the addons load even if it's technically not really needed, not needed to merge.
Tested on LibreWolf v120.0-2 32 bit.

Multiple addons: Add wildcards to /mystuff URL matches

---

addons/collapse-footer/userstyle.css
addons/old-studio-layout/style.css

Resolves #6968
Instead of making "Browse Projects" and "Browse Followers" override `collapse-footer`, make the footer appear below the pane.
To make the footer still accessible in studio pages.

Fix z-index compat between `old-studio-layout`/`studio-followers` & `collapse-footer`

---

addons/middle-click-popup/userscript.js

middle-click-popup: only show popup in editor

---

addons/editor-theme3/addon.json
addons/editor-theme3/black_text.css
addons/editor-theme3/color_on_white.css
addons/editor-theme3/theme3.css
addons/editor-theme3/theme3.js

Resolves #7015
Changes the background of labels in the custom block modal:
Also fixes the text color in the "color on white" mode:
It looks like this on master:
To make the label text readable.

editor-theme3: fix labels in custom block editor

---

addons/editor-dark-mode/experimental_editor.css

Makes dangerous context menu items styled correctly when editor dark mode is enabled.
They were broken by #5595. The screenshot in https://github.com/ScratchAddons/ScratchAddons/pull/7030#issuecomment-1878020628 shows what they currently look like.

editor-dark-mode: fix dangerous context menu items

---

addons/confirm-actions/userscript.js

Resolves #7000
https://github.com/ScratchAddons/ScratchAddons/assets/106490990/ae2df17a-fc3f-4d0a-97a6-645e59fa00c2
Each comment on Scratch has a reply button that shows the comment box when clicked. If you click on the reply button again, the comment box is removed and your comment gets discarded. This update shows a confirmation before this action, if you've enabled "Confirm canceling comments", of course.
To prevent accidentally discarding comments.
Tested on profile pages, projects, and studios, only a little bit.

Confirm clicking Reply while writing a comment

---

addons-l10n/en/mediarecorder.json
addons/mediarecorder/userscript.js

Resolves https://github.com/ScratchAddons/ScratchAddons/issues/7055 (lots of discussion in there), based on changes in #7006
This logic is in this order:
1. Try to record as webm using VP9 (Chrome, best scenario)
2. Try to record as webm using whatever codec the browser gives us (Firefox will give us VP8)
3. Try to record as mp4 using whatever codec the browser gives us (Safari will give us H264)
Here is a video recorded by Chromium on Linux: https://github.com/ScratchAddons/ScratchAddons/assets/33787854/6e7ec5f3-aaab-4e25-94ec-5025bff8fc05 - mpv says this is vp9
Here is a video recorded by Firefox on Linux: https://github.com/ScratchAddons/ScratchAddons/assets/33787854/f4fb588a-08a0-4299-9dbd-0229c0686e57 - mpv says this is vp8
Here is a video recorded by Safari: …

mediarecorder: prefer VP9 when possible and add mp4 fallback

---

addons/find-bar/userscript.js

Fixes a part of #6579
#6623 made the string "flag" translatable in `debugger` and `middle-click-popup`, but not in `find-bar`.

find-bar: translate "flag"

---

addons/gamepad/gamepadlib.js

With https://bugzilla.mozilla.org/show_bug.cgi?id=1680982 being resolved in Firefox 123 (currently nightly), Firefox on Linux has a pretty good gamepad API implementation, so we can hide the warning that "This browser and operating system have known bugs that may make this addon difficult to use. Try another browser if you encounter problems"

gamepad: Mark Firefox 123 and later on Linux as not broken

---

addons/hide-flyout/addon.json
addons/hide-flyout/userscript.js

adds a new option to Auto-hiding block palette which makes the flyout lock when the page is loaded 
tested on chrome and firefox :)
(sorry for low framerate, for some reason obs decided to die)
https://github.com/ScratchAddons/ScratchAddons/assets/116295240/e93ebaf6-017d-46e5-8193-a5f20e165a07

hide-flyout: new setting "open by default" (auto-hide block pallete addon)

---

addons/emoji-picker/userstyle.css

Just adds a few `!important`s in the stylesheet to fix the margins below the show more emojis button on profile pages.
<sup>Weird margins</sup>
Tested in Edge 118.
---
<strike>Also since I've opened a PR for emoji-picker anyways, do you guys think it would be a good idea to replace the emoji on the button with one of the cat emojis?</strike> This is way too much work, I'm sure someone will get to it later.

Minor `emoji-picker` bugfix

---

addons/reorder-custom-inputs/addon.json

- Changes the addon description. It was previously just a rewording of the addon name. Thanks samq for the suggestion in the comment: https://github.com/ScratchAddons/ScratchAddons/pull/7020#issuecomment-1892957777
- I'm not sure if it's necessary, but I added a reminder on how to edit an existing custom block.

reorder-custom-inputs: change description

---

addons/better-quoter/module.js

Resolves #7120
adds a missing colon
~~its the biggest change in existance and should be considered as it restores balance in reality~~
bug fix - "rolleyes" has a colon skipped so it doesnt get rendered
https://github.com/ScratchAddons/ScratchAddons/blob/0fca0cedec08b27a101ec973e0434e684f739a97/addons/better-quoter/module.js#L81
firefox 122.0, works fine

better-quoter: fix typo in emoji data

---

addons/custom-menu-bar/addon.json

Chnages `custom-menu-bar`'s `versionAdded` from 1.35 to 1.36.

custom-menu-bar: Fix versionAdded

---

addons/account-settings-capitalize/style.css

Resolves #7148
Makes `account-settings-capitalize` select the menu item form the bottom instead of the top so it woks with teacher accounts.
To fix an incredibility niche bug.
No, I don't have a teacher account. @Open137 could you test this?

Fix capitalized account settings when using a teacher account

---

addons/pause/userscript.js

On macOS, option+x types ≈ and shift+option+x types ˛

pause: fix keyboard shortcut on macOS

---

addons/faster-project-loading/userscript.js

Resolves #7036
Never blocks URLs ending in `.json` (as suggested by the bug report issue). Not aware of any better alternatives. Searched on Discord where this issue was brought up with no luck.
Fixes a bug we have missed for months.
Can now drag backpack code into specific sprites in Chromium.

faster-project-loading: Fix dropping code into sprite-pane

---

addons/editor-dark-mode/experimental_editor.css

Resolves #7037
Add the classes from the WebGL not supported modal to some preexisting rules.
Consistency.

Style WebGL modal with `editor-dark-mode`

---

addons/image-uploader/addon.json

- The userscript is still in the source, but I removed references to it from addon.json
- Adds an (untranslated in the release) warning to the addon stating that it no longer works
cc @DNin01

Add deprecation warning to image-uploader

---

addons/mediarecorder/userscript.js

Resolves #
#7194 
added `${addon.tab.redux.state?.preview?.projectInfo?.title || "video"}` to the video download script
got the idea from a [discord suggestion](https://discord.com/channels/806602307750985799/1209113670681104424)
Tested on chrome

Project video recorder: Make filename the project title

---

addons/middle-click-popup/userstyle.css

Resolves #7107
Makes the selector that hides the middle click popup scrollbar more specific.
It was being overridden by `editor-compact`.

Fix double scrollbar in middle click popup

---

addons/fullscreen/userscript.js

Resolves #7191
Attaches a couple of event listeners to the body instead of document directly so the fullscreen toolbar is shown when when hovering above the page.
Tested on Firefox 122 and Brave (Chromium 121)

Fix hovering above fullscreen toolbar on Firefox

---

addons/pause/userscript.js

Resolves #7225
When the `pause` addon is enabled, pressing <kbd>Alt</kbd>+<kbd>X</kbd> will now stop immediate propagation, to avoid activating other shortcuts (specifically, cutting blocks).
The Scratch editor's Blockly workspace cuts the focused block (usually the last one that was touched) when pressing <kbd>Ctrl</kbd>+<kbd>X</kbd>, <kbd>Cmd</kbd>+<kbd>X</kbd> (Mac), <kbd>Alt</kbd>+<kbd>X</kbd>, or <kbd>Option</kbd>+<kbd>X</kbd> (Mac), two of which conflict with our pause keyboard shortcut.
I wonder why part of this shortcut was bound to the <kbd>Alt</kbd> key in the first place.
Tested with Edge 121.
Should probably check that this doesn't cause any other problems, like preventing other keyboard shortcuts from working.

Prevent Alt+X (pause) from cutting blocks

---

addons/editor-theme3/black_text.css
addons/editor-theme3/color_on_white.css
addons/editor-theme3/theme3.js

Resolves #7206
* Updates the displayed value when editing an input using the numpad.
* Fixes the text color of numpad buttons - it was previously always white, which is hard to see in high contrast mode and invisible if the text color is set to "colored on white background".

editor-theme3: fix number pad bugs

---

webpages/settings/index.js
webpages/settings/settings-utils.js

The `serializeSettings` and `deserializeSettings` functions were moved into its own module.
These functions are used in the settings page to import and export settings (the buttons inside More Settings).
The extension should continue to work the same after these changes.
In preparation for #6876.
Users will be able to export their settings from their unsupported-browser page soon, so the `serializeSettings` method will be imported from a second page.
Most likely, `deserializeSettings` will only ever be useful to the settings page, but it was modularized anyway.
Importing, exporting, and viewing settings as a file should continue to work normally from the settings page.

Move de- & serializeSettings into its own module

---

background/handle-unsupported-version.js
webpages/error/unsupported-browser.html
webpages/error/unsupported-browser.js
webpages/settings/index.js

Progress on #6876
Resolves #7125
The unsupported-browser page is now a full-screen iframe. The user can now export and view their settings if their browser is unsupported.
We will be increasing our minimum browser version requirements very soon, and we don't want existing users to permanently lose access to their settings, which technically wouldn't be gone, but only developers would know how to access them if we changed nothing.
You can emulate an unsupported browser by hardcoding `const checkIfUnsupported = () => true` on file background/handle-unsupported-version.js

Add "export settings" button to unsupported-browser page

---

addons/hide-flyout/userscript.js

There was some code in the Auto-hiding block palette (`hide-flyout`) addon that explicitly shrinks the width of the code workspace by 250 pixels if the toggle setting is "Category hover" or "Category click" (unless two-columns category menu addon is enabled). This causes problems on devices with smaller screens where the code palette blocks the user from easily accessing blocks underneath it by panning. This PR removes that code.
Video of **CURRENT BEHAVIOR** with an example work environment that triggers the problem below:
https://github.com/ScratchAddons/ScratchAddons/assets/61996651/4fc702a9-a79f-491a-a424-f08c755f6519
With the changes, the user can now actually pan to access the blocks underneath the block palette.
Video of **CHANGED BEHAVIOR** below: …

`hide-flyout`: Remove code that shrinks Scratch coding workspace

---

addons/custom-menu-bar/addon.json

Mentions the word editor in "Customizable menu bar".
Someone mentioned the navigation and meubar addons could be confused with each other without reading the description.

`custom-menu-bar`: change addon name, added word "editor"

---

addons/debugger/module.js
addons/debugger/userscript.js
addons/pause/userscript.js

Resolves #6847
Makes the sound library use a separate audio context if `debugger` or `pause` is enabled.
This allows the library to play sounds while the project is paused without resuming the project's audio.

Create a separate AudioContext for the sound library

---

addons/custom-menu-bar/addon.json
addons/custom-menu-bar/username.js
addons/editor-compact/addon.json

See the post-merge reviews on #6297.
Rewrites `custom-menu-bar`'s userscript to use the Redux as part of the `addon.tab.waitForElemet`.
To stop using a hashed selector and using Redux and `waitForElement` separately is unnecessary.
Tested on Firefox

custom-menu-bar: rewrite compact-dropdown userscript

---

addons/fullscreen/addon.json
addons/fullscreen/userscript.js
background/get-addon-settings.js

Suggested in this comment: https://github.com/ScratchAddons/ScratchAddons/issues/7147#issuecomment-1939420029
Merges the "Hide toolbar in full screen" and "Show toolbar when hovered" settings into one select setting.
To keep all 3 toolbar visibility options together and avoid hidden settings.
tested on Firefox and Brave.

Convert `fullscreen` toolbar toggles to a select setting

---

background/handle-unsupported-version.js

See #6876
Increases the minimum browser requirements.
- Chrome 96: released in November 2021, it supports `declarativeNetRequestWithHostAccess` and most MV3 features.
- Firefox 109: released in January 2023, it's the first stable Firefox version to support MV3.
Page https://scratchaddons.com/unsupported-browser will need to be updated.
See #6876 for the reasoning on increasing the requirements before the actual MV3 upgrade.
By the way, #7252 was recently merged, which allows users to export their extension settings even if their browser is unsupported.
Working on it

Change minimum browser requirements in preparation for MV3

---

addons/debugger/log-view.js
addons/debugger/threads.js

When single stepping, the addon's thread list now automatically scrolls so that you can see the thread and block that is being run instead of hoping you'll figure out where it is on your own.

debugger: Scroll to the running thread

---

addons/hide-backpack/button.css

Resolves #7286
Expand the `.sa-custom-zoom-area` when `hide-backpack` is active.
Note that this also makes hovering over the backpack icon show the zoom buttons.
Making zooming in possible while this addon is enabled

Make `hide-backpack` adjust for `custom-zoom`'s autohide

---

addons/dark-www/addon.json
addons/download-button/style.css

Resolves #7296 
just changes the logic so it goes dark when a light highlight colour is chosen
obvious
works on brave
@WorldLanguages this should be a quick merge, just need to know if setting this to inital instead of none is bad, doesnt seem to be

download-button: fix spinner not adapting to background contrast

---

libraries/common/global-theme.js
webpages/popup/index.js
webpages/popup/style.css

Right now only the top part of the popup has any changes at all
**(THIS SCREENSHOT IS NOW OUTDATED)**

April Fools 2024 easter egg: Scratch Haddocks

---

README.md

Resolves #7313
Move the image inside the `<h1>`, which causes it not to be affected by the border.
It looks a bit better.
Tested in Edge

[README change] Fix border appearing inside of logo

---

webpages/popup/index.html
webpages/popup/style.css
webpages/settings/index.html
webpages/settings/style.css

More clickable area of the theme button in the settings like the settings button in the popup as currently you need to click exactly on the image by:
- Enclosed it in a div with padding which has the on click event
So that it's more easy to click on the theme button and we don't need to click exactly on the image.
Microsoft Edge 122.0.2365.92 (Official build) (64-bit)

Expand the clickable area of the theme button like the settings button

---

background/handle-notifications.js

Changes a few relative URLs to absolute
To avoid problems in the future if we change the location of the background context

Use absolute URLs in background/core instead of relative URLs

---

background/background.html
background/background.js

For the extension background environment entrypoint, we import all JS code from JavaScript itself, instead of doing it through multiple HTML script tags.
Our manifest V3 Chrome extension will only be able to use a service_worker background environment.

Background: import JS from a single module instead of script tags

---

addons/big-save-button/userstyle.css

v1.37.1:
After this change:
Without the addon:
The extra padding is ugly and there's already very little space in the menu bar on small screens.

big-save-button: less space around the button

---

webpages/settings/permissions.js

On the `/webpages/settings/permissions.html` page, no longer checks if the extension already has the permissions we're about to request.
This means that, in some rare cases, we might unnecessarily reload the extension, instead of just closing the tab.
As a reminder, browsers won't show any UI to the user if the permissions we're requesting are already granted. Of course, users shouldn't be shown this page unless there are missing permissions, or type in the URL manually.
For manifest V3, Firefox will begin to allow users to revoke host permissions, so this page may show in Firefox.
Firefox does not allow any async operations between the click and the permission request, so it's less flexible than Chrome.
Tested in Chrome and Firefox

Remove unneeded async call (upcoming Firefox support)

---

addons-l10n/en/name-backpack-items.json
addons/name-backpack-items/userscript.js

Made `name-backpack-items` use `addon.tab.prompt` instead of `window.prompt`.
Makes the UX for it a lot better - it's really confusing to me when I try putting something into my backpack and nothing happens, and then I realize that it's because of this addon.
Tested in Edge

`name-backpack-items`: Use `addon.tab.prompt` instead of `window.prompt`

---

background/handle-permissions.js

The `/webpages/settings/permissions.html` page now opens if:
1. If the user has just revoked a host permission moments ago.
2. If the user has opened the popup and a permission is missing
3. If the user has opened the settings page and a permission is missing
4. NEW: if the user has just installed the extension, and the browser didn't grant host permissions by default.
It no longer opens that page on every extension startup. That means that if a permission is missing and the extension looks broken, the user is expected to interact with the extension in some way to know why it isn't working.
In manifest V3, it's not that straight forward to open the page once per extension session.
Also, we usually try to avoid opening new tabs unless there's user interaction. For example, we only show the …

Do not open "permissions" page on every startup

---

addon-api/common/Self.js
addon-api/content-script/Addon.js
addon-api/content-script/Tab.js
addons/2d-color-picker/userscript.js
addons/color-picker/userscript.js
addons/dark-www/scratchstats.js
addons/debugger/performance.js
addons/forum-search/userscript.js
addons/image-uploader/userscript.js
addons/opacity-slider/userscript.js
addons/scratchblocks/userscript.js
addons/scratchstats/userscript.js

- Removes `addon.self.lib` string, which was previously used to build relative URLs, similarly to `addon.self.dir`.
- New API: `addon.self.dynamicImport()` which works exactly like the `import()` keyword but it takes a relative URL.
- The existing `addon.tab.loadScript()` method now takes a relative URL.
The now removed `addon.self.lib` It was used in two ways:
1. Together with `addon.tab.loadScript()`, but as that API now takes relative URLs it is no longer needed.
2. For dynamic imports (`import()`) but this PR also adds `addon.tab.loadScript()` which should be useful for that case.
Manifest V3 extensions, when reviewed by the Chrome Web Store, are very strict about remote code execution. That is, we shouldn't execute any code (or even CSS) that isn't part of the extension package.
We …

Remove `addon.self.lib` in favor of relative URLs in other APIs

---

addons/scratchr2/forums.css

Fixes a typo in the `spinner.css` import path and removes `%addon-self-dir%`.
The typo caused `scratchr2` to fail to load load the spinner on the forums and `%addon-self-dir%` is unnecessary since CSS imports are already relative.
Untested.
Also my typo fix commit has a funny typo in its name.

Fix spinner.css path (typo in URL)

---

addons/fullscreen/userscript.js

Resolves #7389
Changes the code that measures the canvas size to exclude the stage border.
If the size is wrong, the canvas becomes blurry.

fullscreen: correct canvas size when not in full screen

---

addon-api/common/Self.js
addons/forum-search/userscript.js
addons/scratchblocks/userscript.js

Partially reverts #7376
Removed the `addon.tab.dynamicImport` API in favour of relative `import()`s
`dynamicImport` was only used in 2 places and relative imports don't need anything special.
Tested on Chromium 124.

Remove recently added `addon.self.dynamicImport` API

---

content-scripts/cs.js

Adds `?version=1.38.0` to the URL so that we can distinguish MV3 feedback.

Fix "send feedback" link in notification to include version number

---

.github/gen-manifest.mjs

The webRequestBlocking permission is meaningless in Chrome MV3.

Ignore permission webRequestBlocking in Chrome (gen-manifest.mjs)

---

addon-api/content-script/Tab.js
content-scripts/inject/run-userscript.js

- Resolves #7374. Tested by deleting the `scratchlanguage` cookie and making sure `addon.tab.direction === "ltr"` unless your browser language is RTL (for example Arabic)
- If at least one userscript is available, `window.__addon` can be used from the console, which may be the addon object from any addon, but should be useful for experimenting. Idea from #7368

Fix `addon.tab.direction` bugs and implement `__addon` global

---

background/handle-notifications.js
webpages/popup/index.html

Resolves #6976
Resolves #7461
Sets the viewport on the popup and checks if `chrome.contextMenus` is defined before using it since it errors on Firefox for Android now.
Also removes some weird icon handling I added back in #4810. Now it always uses the icons set in the extension's manifest.
The popup wasn't scaling correctly and after MV3 the extension completely broke. It's also nice to be able distinguish Git versions even if they're stable.
Tested on Andorid Firefox Beta, desktop Firefox and Chromium. The viewport doesn't seem to change the popup on Desktop and Firefox works on Android again including Scratch notifier.

Fix MV3 on Firefox for Android

---

background/load-addon-manifests.js

Resolves #7481
Resolves #7484
Performs a deep clone on each addon-manifest cache entry.
Since manifests are cached before they are processed and processing happens whether or not the manifests were loaded from disk or from the cache, it only makes sense that the cache is not modified during processing. As an example, this fixes an issue where values that couldn't be serialized to JSON were ending up in the cache and causing errors because the processing code didn't expect such data.
Tested.

Bug-fix: clone manifests before caching them

---

addons/dark-www/experimental_scratchr2.css
addons/my-ocular/reactions.css

Resolves #7428
Changes the default color of reaction buttons to purple and moves the code for dark mode support to the addon's userstyle (see #275).

my-ocular: purple reaction buttons

---

addons/reorder-custom-inputs/modified-funcs.js

Resolves  #7478
Solved by checking if label is empty and adding a space character instead
without this change the empty label would cause the %l to not get removed, causing all kinds of strange problems
Tested on chrome. See video of new functionality below:
https://github.com/ScratchAddons/ScratchAddons/assets/48254978/eb4a7f1b-82db-43b9-b21e-a2ad73bdf27f

Bug fix for empty labels not working with reorder-custom-inputs addon

---

addons/better-img-uploads/userscript.js

Resolves #7380
Draws the original image into a canvas before uploading it to the project
It should work

`better-img-uploads`: discard EXIF metadata before upload

---

addons/comments-linebreaks/addon.json

Temporary solution for #6995
Added an extra notice to tell users that linebreaks don't work on scratchr2 yet. This'll probably need a bit better wording.
The addon description suggests that it's supposed to work on the whole site.
Tested on Firefox 126.0.1 (32 bit)

`comments-linebreaks`: add notice about linebreaks not rendering on scratchr2 pages

---

addons/collapse-footer/addon.json

Resolves #7535
added a singular R:
grammer
tested on firefox 126.0.1

`collapse-footer`: fix grammar mistake in description

---

addons/editor-dark-mode/addon.json

Uses a non-transparent color for workspace dots even if editor dark mode is enabled.
See discussion on #7525
Tested on Edge and Firefox. The color of the dots is the same as in v1.38.2.

editor-dark-mode: opaque workspace dots

---

webpages/error/index.html
webpages/error/style.css
webpages/styles/colors-light.css

Adds some basic styles on the error page.
No styling looks ugly especially in the popup.
Tested on Chromium and Firefox.

Add some styles to the error  page

---

addons/editor-dark-mode/addon.json
addons/gamepad/dot.svg
addons/gamepad/gamepadlib.css
addons/gamepad/style.css

The light mode colors were also changed to be more consistent with Scratch's color palette.

gamepad: dark mode support

---

addons/old-studio-layout/style.css

Resolves #7440
Fixes an incorrect line height in the message that appears when trying to change the title of a studio while muted.
Tested on Edge - I used a local instance of scratch-www and modified the code in `src/views/studio/studio-title.jsx` to show the message even if the user is not muted. I don't recommend commenting automodmute to test this because that sends the comment to the Scratch moderators to review.

old-studio-layout: fix mute message line height

---

addons/editor-compact/sprite-properties.css

Resolves #7527
Sets the height of the sprite pane correctly when `editor-compact` and `sprite-properties` are both enabled and the properties are visible.

editor-compact: fix sprite-properties compatibility issue

---

addons/editor-dark-mode/paint_icons.js

Resolves #7066
Fixes a bug in the code that recolors paint editor icons.
The previous code would produce incorrect results for certain values of `highlightText` (white, `#575e75`) and `accent` (`#575e75`).
@OneShot-Niko Can you check if this fixes the issue for you?

editor-dark-mode: fix parts of paint icons disappearing if `highlightText` is white

---

addons/editor-compact/userstyle.css

editor-compact: add solid background to costume number

---

addon-api/content-script/modal.js

Resolves #7450
Calls `Blockly.hideChaff()` when a modal is opened in the editor.
Blockly inputs and dropdowns could appear above a modal.

Hide Blockly widgets when a modal is opened

---

addons/paint-snap/addon.json

Resolves https://github.com/ScratchAddons/ScratchAddons/pull/7550#issuecomment-2181066266
Makes `paint-snap` threshold setting use integer
See resolves

Set paint-snap to use integer

---

.github/CONTRIBUTING.md

I removed the mention of Prettier for VS Code as I think it always uses the latest version and you also need to change the settings for it to work with our code style, and I don't really want to take up space to explain how to configure it. The parser it uses also cannot format CSS, even though Prettier has an official CSS parser.
I was thinking of also linking to the [online Prettier playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAEzgDMBDAVwBt9SBnATyjD2PKZgEto8AKYPUgQLQANHkhRaESnDwBfAJR5gAHSh4BDJizZhO3WqXoAJOJUoQAKhACqtONh5LV6jeOhSZAOgsBzHiogpuYQYoF4ANQCAO6kHDRC0F4UMAAWXsRwMGCpdg5QpAC2cE4KANxqGnJqlTFx+IYmZhbWeY7ltRKecD4Q-oHGENEC2LL0EOR4MBAERgD8gR1Q1VAgIiAQGPqSyKCk2NhDAAr7CLTIIKSUsfTn6wBG2KRgANZZAMpFcAAyHFBwyDIlHsDyerw+GGef18yBg2HIcHW9kKHFh8MRqEwDg4xVgV0s+X2HDg5yQ …

Edits to the paragraph about Prettier

---

background/get-userscripts.js
background/handle-settings-page.js
background/imports/inactivity.js
background/message-cache.js

- Removed an unnecessary (since MV3) alarm that was previously named `cleanCsInfoCache`. See comment https://github.com/ScratchAddons/ScratchAddons/issues/7473#issuecomment-2138037284
- If the user is considered inactive, the background context of the extension should only wake up every 150 seconds (2.5 minutes). This is achieved by reducing the frequency of "the alarm that runs most often" (`updateBadge`)
.
After this PR, these are the events that may trigger the background context of the extension to wake up:
- The `updateBadge` alarm every 1 minute, **but every 2.5 minutes if user is considered inactive.**
- The `fetchMessages` alarm every 5 minutes.
- Opening the popup or settings page, changing settings, using the muting feature, etc.
- Navigating to a new Scratch page.
- Any …

Call background alarms less often (`msg-count-badge` affected)

---

addons/cat-blocks/userscript.js

Resolves #2391
Makes the "watch mouse cursor" setting in the cat blocks addon work more consistently.

cat-blocks: fix "watch mouse cursor" setting

---

addons-l10n/en/scratch-messaging.json
addons/message-filters/userscript.js
popups/scratch-messaging/popup.css
popups/scratch-messaging/popup.html
popups/scratch-messaging/popup.js

Resolves #2853
`message-filters` now never hides the "Welcome to Scratch" message. `scratch-messaging` now displays it properly:
I didn't change `scratch-notifier` because it already handles this message type appropriately - it shows a generic notification:

Support "Welcome to Scratch" message

---

addons/editor-theme3/theme3.js

To repro:
1. Create custom block
2. Edit addon's settings
3. Notice no changes to the toolbox.

`editor-theme3`: fix settings no longer dynamic after creating custom block

---

addons/find-bar/userscript.js

Resolves #3584
Adds `.toLowerCase()` to the code in `find-bar` that compares broadcast names.
Broadcasts aren't case-sensitive, so the previous code sometimes didn't find all instances. See https://github.com/ScratchAddons/ScratchAddons/issues/3584#issuecomment-943107668 for an example project and reproduction steps.
Tested in Edge and Firefox.

find-bar: ignore case when comparing broadcasts

---

addons/middle-click-popup/userscript.js

Resolves #4906
Hides Blockly dropdowns and context menus when Ctrl+Space is pressed.

middle-click-popup: hide Blockly widgets when opened

---

addons/dark-www/experimental_scratchwww.css
addons/editor-dark-mode/addon.json
addons/editor-dark-mode/stage.css

Resolves #5393
Chooses the `color-scheme` of stage monitors based on editor dark mode settings instead of website dark mode. This affects sliders and list scrollbars.

Fix monitor color scheme

---

.github/gen-manifest.mjs
addon-api/content-script/Tab.js
background/background.js
background/firefox-localhost-support.js
background/get-userscripts.js
content-scripts/cs.js
content-scripts/inject/module.js
content-scripts/prototype-handler.js
manifest.json

Resolves #7455
Resolves #7456
* Adds `localhost:8602` to `host_permissions` and updates other code that expects the GUI port to be 8601
* Replaces `localhost:8333` and `localhost:8601` content script matches with just `localhost` - Firefox doesn't like ports in match patterns for some reason
* Adds `localhost` and `scratchfoundation.github.io` to the `matches` field under `web_accessible_resources`
* **For up-to-date changes, see comment https://github.com/ScratchAddons/ScratchAddons/pull/7474#issuecomment-2197876142**
@WorldLanguages The `gen-manifest` script needs to be updated.
Tested on Edge and Firefox with the develop branch of scratch-gui and scratch-www.

`localhost` fixes

---

addons/dark-www/experimental_scratchwww.css

Adds `filter: none` to the "Choose a tutorial" icon on the Ideas page.
Currently, setting the highlight color to a lighter color makes the icon dark brown.

dark-www: fix "Choose a tutorial" icon

---

popups/scratch-messaging/api.js
popups/scratch-messaging/popup.js

Resolves #2466
Resolves #3916
If a comment can't be loaded, shows the fragment returned by the messages API instead, without context (note that the reply appears as a top-level comment in the screenshot below).
Tested on Edge and Firefox. I only tested comments on an unshared project, but this should fix old threads too because the root cause of the bug is the same.
Trying to reply to a comment on an unshared project shows an error message.

scratch-messaging: show fragment if fetching comment failed

---

addons/forum-toolbar/addon.json

Changes the link to Silk ions in `forum-toolbar`'s credits.
The old link now shows a 404 error.

forum-toolbar: update link to Silk icon set

---

addons/find-bar/userscript.js

Resolves #7627
Do not prevent the default behavior of pressing <kbd>Ctrl</kbd>+<kbd>F</kbd> when not in the editor.
The find bar can only be used in the editor, and <kbd>Ctrl</kbd>+<kbd>F</kbd> usually opens the browser's find bar.
Tested in Edge 126 on Windows.

`find-bar`: Don't prevent Ctrl+F outside editor

---

addons-l10n/en/exact-count.json
addons/exact-count/addon.json
addons/exact-count/studio.css
addons/exact-count/studio.js

Adds the "exact count for studios" option (recently removed in #7617) back, but instead of loading the count (which sends a large number of requests to Scratch) every time a studio page is opened, the user has to click the "100+" first:
Also replaces the `countProjects` function with the updated one from the exactcount website, which is much more readable - no callbacks, only loops with `await`. It doesn't actually reduce the average number of requests per studio though - I tested it on various studios.
Comparison with the previous version of the addon: https://github.com/ScratchAddons/ScratchAddons/compare/27ed288c2d823284616aabddc53e6ea380f88b7e...mxmou:ScratchAddons:studio-exact-count
This feature was quite useful because vanilla Scratch doesn't provide a way to see the exact number of …

exact-count: better exact count for studios

---

addons/download-button/addon.json

Replaces the `"projectPlayer"` tag in download-button's addon.json with `"projectPage"`.
This makes the addon appear in the "Project Pages" category on the settings page - it was previously under "Others". The `"projectPlayer"` tag is intended for editor addons.
Tested on Firefox.

download-button: fix wrong tag

---

addon-api/content-script/Tab.js
background/imports/util.js
content-scripts/cs.js
webpages/settings/index.js

Resolves #7625
This affects addons that request the "clipboardWrite" addon permission in order to copy PNG images into the clipboard. The extension then requests the "clipboardWrite" **extension permission** if necessary, after the user tries to enable an addon that requests it. This extension permission is deprecated in Chrome, but not in Firefox.
The only addon that uses this permission is currently `bitmap-copy`, and soon `blocks2image`.
Firefox 127+ will behave exactly like Chrome always had, in respect to this permission, in order to avoid unnecessary permission prompts.
- A permission prompt will not appear when enabling an addon that requires this permission.
- Existing addons that get this permission added with an update, won't get disabled automatically if the permission is …

Update clipboardWrite permission logic for Firefox 127+

---

addons-l10n/en/exact-count.json
addons/exact-count/addon.json
addons/exact-count/studio.css
addons/exact-count/studio.js
background/get-userscripts.js
background/handle-auth.js
background/handle-settings-page.js
background/imports/inactivity.js
background/message-cache.js
webpages/popup-loader.js

Resolves #7646
See PR description: #7646

[v1.38.x] Stop fetching scratch.mit.edu/csrf_token and more optimizations

---

popups/scratch-messaging/popup.html
popups/scratch-messaging/popup.js

If the user hasn't read messages for 20 days and they have received the same "there was activity in X studio" message multiple times, it is shown once, like it always has.
But the number of the "studio activity" row will reflect the actual number of messages that are "eaten" by the category:
This was also added to forum activity messages.
I've seen users more than once get confused on why we don't display all of their messages. But yes we were displaying all of them. This should help clarify the situation.
Tested but without identical messages.

Messaging: count identical studio-activity messages as many messages

---

addon-api/common/FetchableAuth.js
addons/animated-thumb/persistent-thumb.js
addons/exact-count/user.js
addons/forum-post-countdown/userscript.js
background/handle-auth.js
content-scripts/inject/module.js
content-scripts/prototype-handler.js

Resolves comment https://github.com/ScratchAddons/ScratchAddons/pull/7651#issuecomment-2239953482
Related: #7648
When viewing the diff, I recommend you enable "hide whitespace".
This PR intends to make very small changes/optimizations to reduce the load on Scratch servers. It should also slightly help with battery and data usage.
These are small code changes. Big restructurings are intentionally not made.
The changes are made in such a way that anyone can clearly see that, after the changes, it's impossible that the extension sends more than requests than before.
The amount of requests to `/session` will decrease significantly. This is strongly related to the Manifest V3 lifecycle and using `chrome.storage.session` to cache data.
- Previously, `/session` would be fetched each time the …

[v1.38.x] Send less requests to `scratch.mit.edu/session` etc.

---

README.md

Resolves #7676
Changes the static "chat on discord" badge to a dynamic badge that displays the number of users on our Discord server who are online.
It's a great opportunity to display the statistic.

README: Add badge for Discord online users

---

addons/blocks2image/userscript.js

Resolves #7681
Identical image URLs are only fetched once.
I used the new(ish) `Object.groupBy()` function to group icons by their image URLs.
I added logs when exporting blocks as image to facilitate testing this PR. See #7681 for repro steps and an example project and sprite. These logs will be removed before merging.
Tested in Chromium.
Make sure that `editor-theme3` is off when testing this. If it is on, everything will be a data: url anyway.

`blocks2image`: fix multiple reqs for same image

---

webpages/settings/style.css

Resolves #6844
Resolves https://github.com/ScratchAddons/ScratchAddons/pull/7464#issuecomment-2131309393
Makes the permissions page responsive, adds a scrollbar and fixes the button text.
The permissions page was not designed for phones or short screens.
Tested on Chromium. Since I didn't put the scrollbar on the body it won't necessarily be on the edge of the window. The image is also slightly too wide for the IPhone SE in devtools.

Responsive permissions page

---

addons/scratchblocks/userscript.js

Uses the built in option for scaling scratchblocks.
TBH pretty useless change
tested on chrome and FF

`scratchblocks`: use "scale" built-in option instead of scaleSVG()

---

addons/msg-count-badge/addon.json
background/get-addon-settings.js
webpages/settings/index.js

Resolves comment https://github.com/ScratchAddons/ScratchAddons/pull/7651#issuecomment-2254267589
- The addon `msg-count-badge` is no longer enabled by default.
- When updating to v1.39.0, existing users who do not have Scratch Addons pinned to their extension toolbar will have this addon automatically disabled.
- Users can easily reenable the addon as it will appear at the top of the settings page if disabled.
- Removes a historical default due to our Scratch Messaging roots that makes little sense now.
- Less data and battery usage wasted updating the extension badge when it is not visible to the user.
- Sending less requests to Scratch servers.

`msg-count-badge`: disable by default & some existing users

---

background/firefox-localhost-support.js

Tries to address #7761, not sure if this will fix it or not.
Checks for the `chrome.scripting` API being available before using it in firefox-local-support.js, as it does not exist on Firefox for release builds (which do not have the `scripting` permission).
Without this, the extension completely breaks on Firefox.
I think this is a Firefox-specific bug, so I only tested there. I tested by manually removing the `scripting` permission from manifest.json, and it seems to make the extension work.

Check if chrome.scripting exists before using it

---

addons/exact-count/addon.json

Adds the following info to the exact count addon:
https://github.com/ScratchAddons/ScratchAddons/issues/7577#issuecomment-2317063674

exact-count: explain that a click is required in studios

---

addons/dark-www/addon.json
addons/dark-www/experimental_scratchr2.css
addons/dark-www/experimental_scratchwww.css
libraries/common/cs/text-color.js

Resolves #5945
Website dark mode generates variants of the border color with different opacity. This change makes those generated colors fully transparent if the selected border color is fully transparent. It also makes certain elements, such as grid lines on the Statistics page and some separators, unaffected by the border color.
To make completely removing borders (by setting the border color opacity to zero) possible. This will allow the user to create a theme similar to #7722.

dark-www: fix fully transparent borders

---

addons/copy-message-link/profile.js

Resolves #7656 
Used `markAsSeen` and added a new class to comments that have already had the button added. This ensures that comments don't get used twice and also improves efficiency by not having the waitForElement API read over the comment again.
Lag can become pretty noticeable on profiles (as the project/studio one worked differently) when you have a lot of comments on the page.
macOS Sonoma 14.5
Chrome Version 126.0.6478.36 (Official Build) beta (arm64)

Improve efficiency in `copy-message-link` on profiles

---

addons/editor-theme3/addon.json

This does not resolve any issues, its just a change the editor-them3/addon.json, the link used in https://github.com/ScratchAddons/ScratchAddons/pull/7509/files#r1685494153 was dead because I changed my github account to what it is now so I am just adding a working link as it was in the original pr, nothing other than that :P

Add new item to `editor-theme3` credits

---

content-scripts/inject/module.js

Resolves #7786
Changes `addon.tab.scratchClass()` to handle classes containing a plus sign correctly.
The hashes at the end of some class names now contain a plus sign. This broke the `echo-effect` addon because it uses one of those classes.

Fix `addon.tab.scratchClass()` not supporting classes with "+"

---

addons/ctrl-enter-post/comments.js

Resolves #7585
Changes a `var` declaration to `let`. This fixes the bug because `let` has block scope, which means that a new variable is created in every iteration.
Tested on Edge and Firefox. This can be tested without posting anything - just click "reply" on two comment and press Ctrl+Enter in one of the text boxes. The error message should appear next to that text box.

ctrl-enter-post: submit the right comment

---

popups/cloud-games/popup.css

Resolves #7515
Makes the "Add this project" button in the cloud games popup centered.

cloud-games: fix add button position

---

addons/find-bar/userscript.js

Resolves #7717
Shows the index of the first result in the sprite when clicking an item in the find bar dropdown.
https://github.com/user-attachments/assets/2fedff68-7f26-493d-89e2-b0d0852bf125

find-bar: show correct index of first result

---

_locales/en/messages.json
background/handle-notifications.js

Changes the "Do not disturb" context submenu:
- Removes the "24 hours" option and replaces it with "until tomorrow", which lasts until midnight the next day.
- Also adds a "4 hours" option.
24 hours would most often be used to prevent distractions for an entire day, but that could have the potential to extend several hours into the following day.
Tested in Edge 128.

Mute for 4 hours and until tomorrow options

---

addons/mediarecorder/userscript.js

Resolves comment https://github.com/ScratchAddons/ScratchAddons/pull/7058#discussion_r1760364692
Downloads video files as mp4 on modern Chrome
It is a frequent request by users, and it's been supported since Chrome 126 (released June 2024)
Not tested

`mediarecorder`: prefer mp4 over webm

---

addons/better-img-uploads/style.css
addons/paint-by-default/addon.json
libraries/common/cs/react-tooltip.css

Resolves #7805
Fixes the CSS of tooltips added/changed by `better-img-uploads` and `paint-by-default`. #7808 fixes the HD upload button.

Fix tooltip CSS

---

addons/animated-thumb/addon.json
addons/disable-sprite-wobble/addon.json

Resolves #7708
Resolves #7830
Disables `animated-thumb` by default and enables `disable-sprite-wobble` by default keeping the number the same as before.

Tweak list of enabled by default addons

---

addons/editor-compact/userstyle.css

See https://github.com/ScratchAddons/ScratchAddons/pull/7822#discussion_r1789215426

editor-compact: fix sprite search bar in small stage mode

---

addons/editor-dark-mode/debugger.js

https://github.com/ScratchAddons/ScratchAddons/pull/7815#discussion_r1797843704
This fixes dynamically enabling dark mode when the performance tab is open.

editor-dark-mode: update debugger performance charts if they already exist

---

addons/download-button/style.css
addons/download-button/userscript.js
addons/last-edit-tooltip/userscript.js
addons/remix-tree-button/addon.json
addons/remix-tree-button/button.css
addons/remix-tree-button/main.js

Resolves #6956
The tooltip added by `last-edit-tooltip` now remains after resizing the window. The Download and Remix Tree buttons are still hidden when the window is narrow enough that the page switches to the vertical layout, but they now appear again when switching back to a larger window size.

Use new `resizeEvent` option in more addons

---

addons/disable-auto-save/userscript.js

See https://github.com/ScratchAddons/ScratchAddons/issues/6139#issuecomment-1964662287. The previous code would add two event listeners if the addon was enabled late, which caused the confirmation popup for leaving the editor to be shown twice.

disable-auto-save: don't show confirmation twice

---

addons/find-bar/userscript.js

Resolves #7635
Made `find-bar`'s CTRL+F shortcut only focus the find bar when it's not already focused.
Opens up easy access to the browser's own find bar.
Tested with Edge.

`find-bar`: Only override CTRL+F shortcut when find bar is not in focus

---

addons/scratch-notifier/addon.json

Replaces Scratch Notifier's recommended tag with the beta tag.
The addon has been unreliable  since the MV3 transition and it doesn't seem like it's going to be fixed soon.
- #3877
- #7839

Add beta tag to Scratch Notifier

---

addons/editor-theme3/theme3.js

Resolves #4036
Resolves [Scratch Addons Discord -> #bug-reports -> Custom block color not applied at make a block prompt buttons](https://discord.com/channels/806602307750985799/1213678804203995206)
This is a small change to the Customizable block colors (editor-theme3) addon. It applies custom block colors to the "Add a input/label" button block-like icons in the "Make a block" popup modal by editing the icon's vector svg data.
In the latest version of Scratch Addons as of writing, custom block colors do not affect these icons in the "Make a block" modal and they appear in Scratch's default pink custom block color which is inconsistent. This pull request changes the colors of the icons to make them match the actual rendered blocks.
| Make a block popup currently | Make a block popup with …

editor-theme3: Apply block colors to icons in "Make a block" popup

---

addons-l10n/en/confirm-actions.json
addons-l10n/en/scratch-messaging.json

```diff
- Are you sure you want to dismiss this message from the Scratch Team? It cannot be recovered.
+ Delete this message permanently?
```
This isn't as destructive as other actions.
```diff
- Are you sure you want to share?
+ Are you ready to share your project?
```
This is more encouraging.

Rephrase some confirmation messages

---

addons/scratchr2/view_all.css

Resolves #7879
Changes the height of profile pictures on Followers and Following pages to make them square.

scratchr2: fix profile picture aspect ratio

---

addons/editor-dark-mode/experimental_editor.css
addons/editor-dark-mode/extension_icons.js
libraries/common/cs/update-all-blocks.js

Makes the necessary changes to editor-dark-mode to support the new Blockly version. This PR doesn't update the code for zoom icons yet - scratch-blocks currently uses Blockly's default icons, which will probably be replaced with Scratch's ones before the new version is released.
Tested on Edge and Firefox using both the current version of scratch-gui and the spork branch.

editor-dark-mode: new Blockly

---

addons/blocks2image/addon.json
addons/editor-random-direction-block/addon.json
addons/rename-broadcasts/addon.json
addons/search-sprites/addon.json

- Adds the `codeEditor` tag to `rename-broadcasts` and `editor-random-direction-block`.
- Adds recommended tag to `search-sprites`.
- Adds the featured tag to `blocks2image`.
Tested on Chromium

Add some addon tags

---

addons/editor-dark-mode/addon.json
addons/editor-dark-mode/experimental_editor.css

Adds styles for Scratch's confirmation popup that appears when deleting a sprite (#7869) to editor-dark-mode.
Tested on scratchfoundation.github.io in Edge and Firefox.

editor-dark-mode: support delete confirmation

---

addons/remove-sprite-confirm/userscript.js

Makes `remove-sprite-confirm` do nothing if Scratch's confirmation (#7869) exists.

remove-sprite-confirm: prevent double confirmation

---

addons/block-palette-icons/userstyle.css

Fixes the block palette category icons on the new Blockly editor.

block-palette-icons: Fix on modern Blockly

---

addons/no-script-bumping/userscript.js
addons/script-snap/userscript.js

Fixes `script-snap` and `no-script-bumping` on the modern Blockly editor by calling the non-underscore functions there. The changes are easier to see with hide whitespace.
Tested on Chromium on thew website and modern Blockly locally.

Fix script-snap & no-script-bumping on new Blockly

---

addons/editor-stage-left/stageleft.css

Moves the new delete confirmation to the right side of the sprite tile if editor-stage-left is enabled.
https://github.com/ScratchAddons/ScratchAddons/issues/7869#issuecomment-2460312848

editor-stage-left: move delete confirmation to the right

---

addons/better-quoter/module.js
content-scripts/cs.js

Updates the code in cs.js that remembers the original text of scratchblocks elements.
https://github.com/ScratchAddons/ScratchAddons/issues/7910#issuecomment-2460856196

better-quoter: support new scratchblocks

---

addons/editor-dark-mode/experimental_editor.css

Scratch recently added categories to the Tutorials library. This PR adds the necessary styles to editor dark mode.
It looks like this on v1.39.1:

editor-dark-mode: style category titles in Tutorials library

---

addons/dark-www/experimental_scratchwww.css

Scratch now shows a full-screen popup with the Community Guidelines (similar to the Scratcher promotion page) to new users after joining. This PR adds the necessary dark mode CSS:
Tested on Edge and Firefox. The easiest way to test this is to set the localStorage key `shouldReviewCommunityGuidelines` to `true` and reload the Scratch homepage.

dark-www: style Community Guidelines modal

---

addon-api/content-script/blocks.js
addons/debugger/threads.js
addons/debugger/userscript.js
addons/editor-stepping/highlighter.js
addons/editor-stepping/userscript.js
addons/find-bar/blockly/BlockFlasher.js
addons/find-bar/blockly/Utils.js
addons/find-bar/userscript.js
addons/jump-to-def/userscript.js

Updates "debugger" (including the `addon.tab.addBlock()` API), "running block border", "find bar", and "jump to custom block definition" to work with the new version of Blockly. Includes some changes from #7892.

debugger, editor-stepping, find-bar, jump-to-def: new Blockly

---

addons/editor-theme3/addon.json
addons/editor-theme3/black_text.css
addons/editor-theme3/color_on_black.css
addons/editor-theme3/color_on_white.css
addons/editor-theme3/theme3.css
addons/editor-theme3/theme3.js
addons/number-pad/userscript.js

Updates "customizable block colors" and "always show number pad" to work with the new version of Blockly.

editor-theme3, number-pad: new Blockly

---

addons/dark-www/banners/darker.css
addons/dark-www/banners/desaturated.css
addons/dark-www/experimental_scratchwww.css

Adds styles for the updated Ideas and Community Guidelines pages to website dark mode.
Tested locally on Edge and Firefox.

dark-www: support new Ideas and Community Guidelines page designs

---

addons/middle-click-popup/BlockTypeInfo.js
addons/middle-click-popup/userscript.js
addons/middle-click-popup/userstyle.css

Makes "insert blocks by name" compatible with modern Blockly.
Tested both Scratch versions on Edge and Firefox. The addon still works correctly and is still compatible with theme3.

middle-click-popup: new Blockly

---

addons/addons.json
addons/no-sprite-confirm/addon.json
addons/no-sprite-confirm/hide.css
addons/no-sprite-confirm/userscript.js

Resolves #7966
Adds an addon to remove Scratch's sprite deletion confirmation. It has the danger tag but whether it's necessary is debatable since edit  > restore can still be used.
Some users really don't like the confirmation.
Tested on Chromium and Firefox.

New addon: `no-sprite-confirm`

---

addons/hide-backpack/button.css
addons/hide-backpack/userscript.js

Updates the code in hide-backpack that changes the position of zoom buttons to work with modern Blockly.

hide-backpack: new Blockly

---

addons/custom-menu-bar/addon.json
addons/custom-menu-bar/debug-hide.css
addons/custom-menu-bar/divider-hide.css
addons/custom-menu-bar/tutorials-hide.css

Resolves #7950
Adds a setting to the customizable editor menu bar addon to hide the debug button.
Some users will never use it and removing it saves some menu bar space.
Tested on Chromium. The divider is only removed when both the tutorial and and debug buttons are hidden.

custom-menu-bar: Add hide debug button setting

---

addons/dark-www/addon.json
addons/dark-www/experimental_scratchr2.css
addons/dark-www/experimental_scratchwww.css

Removes styles that have become unnecessary after the Ideas page update. Also makes the new page more similar to vanilla when the "Scratch's default colors" preset is used.

dark-www: remove styles for old Ideas page

---

.gitattributes

Fixes https://github.com/ScratchAddons/ScratchAddons/pull/8012#issuecomment-2555750817
> That didn't quite work, the "dist" folder is being included inside the chrome zip now.
This should fix the problem. Previously we were `git archive`-ing every non-dot folder including `dist`.

Don't include dist/ in archives

---

addons/custom-menu-bar/menu-icons.css

Hides the debug label and removes the right margin from both help buttons in the icon only mode of the customizable editor menu bar.
Someone sent feedback about the label on 1.39.2 but it also applies to the latest version.

Fix custom-menu-bar icons only mode

---

addons/stage-monitor/addon.json

Allows the customizable stage monitors addon to run on project embeds.
Tested on Chromium on the new ideas page.

stage-monitor: Run on embeds

---

addons/editor-theme3/forums/base.css
addons/editor-theme3/forums/color_on_black.css
addons/editor-theme3/forums/color_on_white.css

Resolves #8018
Uses a more specific selector for comment text.
This fixes the text being unreadable in the default and Scratch 2.0 presets.
Tested on Edge and Firefox with different combinations of the "comments" and "text color" settings. Example post that contains a scratchblocks comment: https://scratch.mit.edu/discuss/post/7975899/

editor-theme3: fix comment text in the forums

---

addons/mediarecorder/userscript.js

Changes the function that loads settings or default settings to use `Object.assign` in order to load saved settings on top of default settings.
If **no** settings are saved, then the setting values fall back to defaults. If **any** settings are saved, then every saved setting is restored instead of using defaults. Basically, either all the defaults or all the saved settings are filled in.
This meant **if we were ever to add new options in an update**, users who had previously used the addon would find that those settings start out as an undefined value.
For each setting, if there is a saved setting value, that is used, otherwise the default value is used.
Renamed `LENGTH_LIMIT` to `MAX_RECORD_TIME`.
Tested.

`mediarecorder` default setting fix

---

addons/jump-to-def/userscript.js

Resolves #8026
Replaces `utils.getWorkspace` in jump-to-def's userscript with `addon.tab.traps.getWorkspace` (#7892 deleted the former but didn't update the usage in jump-to-def).
Works on chrome 131.0.6778.205.

`jump-to-def` bugfix

---

addons/mediarecorder/userscript.js

I figured out how to get audio recording to work on MP4 recordings! You need to set mimeType to `"video/mp4; codecs=mp4a.40.2"`.
Tested with Edge 131 on Windows 11.

`mediarecorder`: Specify audio codec

---

webpages/settings/index.html
webpages/settings/index.js

Resolves #5422
Makes more settings linkable and replaces the more settings button with a link. Right now more settings stays open after a page reload but I can change that if it's too annoying.
So more settings can be linked to directly.
Tested on Chromium. Addon linking still works.

Make 'More Settings' linkable

---

addons/hide-backpack/button.css

Resolves #8040
Added `z-index: 2` to stylesheet in hide-backpack to fix layering issue.
Tested on Chrome 131.0.6778.205.

Fix `hide-backpack` incompatibility with auto-hiding zoom controls in `custom-zoom`

---

addons/middle-click-popup/BlockTypeInfo.js

Resolves #8042
Ignores vertical separators when adding inputs to blocks.
(Before #7949, the addon used the `argType_` attribute to determine which fields aren't inputs. This attribute doesn't exist in modern Blockly.)
Tested on Edge (current Scratch version and spork) and Firefox (current Scratch version).
As the screenshot shows, color inputs are also currently broken. I'll make a separate PR to fix those.

middle-click-popup: fix extension blocks

---

addons/middle-click-popup/BlockTypeInfo.js
addons/middle-click-popup/WorkspaceQuerier.js

Makes middle-click-popup correctly recognize color inputs. In v1.40, they work like text inputs, so it's possible to type things like "touching color apple". Now they only accept colors (for example "touching color #abcdef").
Tested on Edge (current Scratch version and Spork).

middle-click-popup: fix color inputs

---

addons/fullscreen/hideToolbar.css
addons/fullscreen/removeBorder.css
addons/player-thumb/userscript.js
addons/player-thumb/userstyle.css

Resolves #8027
Resolves #8033
Properly fixes #7928
Removes the event listener instead of hiding the thumbnail in the editor and fixes enhanced fullscreen compatibility.
To fix bugs such as one from feedback where the thumbnail gets stuck when going fullscreen from the editor.

player-thumb: Fix fullscreen bugs

---

addons/player-thumb/addon.json
addons/player-thumb/scratch3to2.css
addons/scratch3to2/main.css
addons/scratch3to2/project.css

Resolves #8072
* Fixes editor comments
* Moves styles for player-thumb compatibility into a separate file that's only loaded if player-thumb is enabled

scratch3to2: fix bugs

---

addons/dark-www/experimental_scratchr2.css

Fixes a dark mode compatibility issue with the [old Scratch 2.0 download page](https://scratch.mit.edu/help/scratch2download/).
Someone submitted feedback about this.
Tested on Chromium with and without `scratchr2`.

dark-www: Compatibility with old download page

---

addons/block-cherry-picking/addon.json

The setting description added in #8078 for testing is working fine and has been translated into multiple languages, so the notice is redundant now.

Remove flip controls notice

---

addons/scratch3to2/project.css

scratch3to2: fix gamepad compatibility

---

addons/scratch3to2/studio.css

Makes `scratch3to2` style the invite panel a bit more like scratchr2 did.
Pretty minor, but makes the addon closer to Scratchr2
Tested on Edge

`scratch3to2`: Style invites

---

addons/editor-colored-context-menus/userscript.css
addons/editor-colored-context-menus/userscript.js
addons/editor-theme3/theme3.css
addons/editor-theme3/theme3.js

Fixes `editor-colored-context-menus` compatibility the new Blockly editor.
Tested on Chromium with separators, Scratch's high contrast mode and `editor-theme3`'s colored on black setting.

Fix colored context menus on modern Blockly

---

addons/material-forum-editor-buttons/addon.json
addons/variable-manager/addon.json

Adds Material icons to the credits of material-forum-editor-buttons and variable-manager.

Add Material icons to addon credits

---

addons/dark-www/addon.json
addons/dark-www/banners/darker.css
addons/dark-www/banners/desaturated.css
addons/dark-www/experimental_scratchwww.css

This PR adds dark mode styles for the redesigned Starter Projects page. I might add 3.0 → 2.0 support later.

dark-www: support new Starter Projects page

---

addons/fix-editor-comments/userscript.js

Updates the "keep block comment connections straight" setting of "better editor comments" to work with modern Blockly. Other settings fix Scratch issues that are fixed in the new version of scratch-blocks.

fix-editor-comments: new Blockly

---

addons/reorder-custom-inputs/userscript.js

* Adds `addon.self.disabled` checks instead of unpolluting functions when the addon is disabled.
* Removes the additional `getBlockly()` call added by #7892 - there was already one near the end of the userscript. I moved it to the top to make it clearer that `Blockly` refers to the `getBlockly()` result, not `window.Blockly`.
https://scratchaddons.com/docs/develop/userscripts/best-practices/#do-not-unpollute-functions

reorder-custom-inputs: don't unpollute Scratch functions

---

addons-l10n/en/editor-searchable-dropdowns.json
addons/editor-number-arrow-keys/userscript.js
addons/editor-searchable-dropdowns/addon.json
addons/editor-searchable-dropdowns/userscript.css
addons/editor-searchable-dropdowns/userscript.js
addons/editor-theme3/black_text.css
addons/editor-theme3/theme3.css
addons/find-bar/userscript.js

Updates "block dropdown search" to be compatible with new Blockly. Also fixes two minor bugs in other addons so that the full-screen error popup doesn't appear in development versions of Scratch.
Tested both Scratch versions on Edge and Firefox. Scrolling in long dropdowns is slightly broken on new Blockly, but this isn't caused by the addon.

editor-searchable-dropdowns: new Blockly

---

addons/addons.json
addons/live-read-topics/addon.json
addons/live-read-topics/style.css
addons/live-read-topics/subforums.js
addons/live-read-topics/topics.js

Resolves #8127
Adds a new addon that automatically marks topics as read on forum category pages.
When going through topics like questions on QaS, I want to go through all the questions I haven't opened yet. I'll sometimes lose track about which topics I've opened and which I haven't. This would solve that.
Tested on Firefox

"Instant read indicators on forum category pages" addon

---

addons/editor-compact/userstyle.css
addons/editor-dark-mode/experimental_editor.css
addons/hide-flyout/style.css
addons/hide-flyout/userscript.js

Updates `editor-dark-mode` and `hide-flyout` on modern Blockly to use the new toolbox selector. 
Also adds modern Blockly support to `editor-compact`, although there might be some areas I missed.
Tested on Chromium on both versions of Scratch.

Use new toolbox selector on modern Blockly

---

addons/rename-broadcasts/userscript.js

Updates rename-broadcasts to make it compatible with modern Blockly.

rename-broadcasts: new Blockly

---

addons/reorder-custom-inputs/modified-funcs.js
addons/reorder-custom-inputs/userscript.js

Updates "rearrangeable custom block inputs" to work with modern Blockly. The important changes are all in `userscript.js`. `modified-funcs.js` only contains style changes to reflect the updated upstream code.

reorder-custom-inputs: new Blockly

---

addons/editor-comment-previews/userscript.js
addons/editor-comment-previews/userstyle.css
addons/editor-dark-mode/experimental_editor.css

Adds modern Blockly support `editor-preview-comments`. It was already mostly working but hovering over collapsed comments and the middle section of custom block definitions are now fixed.
Also moves the dark mode support out of `editor-dark-mode` and into the addon.
Tested on both editors on Chromium.

editor-preview-comments: New Blockly support and move dark mode styling

---

addons/no-sprite-confirm/userscript.js

Makes no-sprite-confirm work on React 18. There's apparently some code somewhere that calls `stopPropagation()` on the click event, so the addon now listens for pointerup instead.
Tested on Edge (current Scratch version and React 18 branch).

no-sprite-confirm: React 18 support

---

addons/swap-local-global/addon.json
addons/swap-local-global/userscript.js

Updates "variable type switching" to work with modern Blockly.
Tested both Scratch versions on Edge and Firefox. There are a few bugs, but they're not caused by this PR:
* When renaming a variable and changing its scope at the same time (these are both existing issues):
* The name shown on variable monitors isn't updated
* Undo needs to be selected twice to undo both the name and scope change
* After switching sprites or loading the project from a file, `isLocal` is set to false for all variables, so the addon thinks they're all global. (this is an upstream bug)

swap-local-global: new Blockly

---

webpages/settings/data/fuse-options.js

> I wanted to find "separate lists and variables" to turn it off, though showing "Separate" didn't work.
Adds setting names, `select` setting values and preset names to the settings page search results.
Tested on Chromium in English only.

Include settings and presets in search

---

addons/infinite-scroll/forumScroll.js

Resolves https://github.com/ScratchAddons/ScratchAddons/pull/6633#issuecomment-2725901668
Adds the sticky footer body class when the infinite scrolling forum userscript is run.
So the sticky footer's "Only on infinite scrolling pages" setting works as expected on the forums.

Add sticky footer class to forum userscript

---

addons/player-thumb/userscript.js
addons/player-thumb/userstyle.css

Resolves #7928
Adds `body:not(.sa-body-editor)` to the selector for disabling the project controls so it never happens in the editor.
I haven't seen any reports about disabled controls on the project page and if it does ever happen at least the user is able to open the editor as a workaround without reloading the page.
I can't reproduce the issue but the addon still works as before on Chromium.

`player-thumb`: Never disable controls in editor

---

addons/place-backpack-code-at-cursor/userscript.js

Makes "place backpack code at mouse" compatible with modern Blockly.
Tested on Edge and Firefox. Dropping code from the backpack is quite broken on new Blockly, even with SA disabled (for example: dropping a script twice causes all other scripts to disappear), but it does get placed at the mouse position when the addon is enabled.
To test this, you can:
1. Clone scratch-www and change the version of `@scratch/scratch-gui` in package.json to `^11.1.0-spork.15`
2. Download and run cors-anywhere
3. In the scratch-www directory: `API_HOST=http://localhost:8080/https://api.scratch.mit.edu BACKPACK_HOST=http://localhost:8080/https://backpack.scratch.mit.edu npm start`
4. Use [Redirector](https://github.com/einaregilsson/Redirector) to make `/session` work

place-backpack-code-at-cursor: new Blockly

---

addons/cat-blocks/userscript.js
addons/columns/userscript.js
addons/data-category-tweaks-v2/userscript.js
addons/hide-flyout/april-fools.js
addons/hide-flyout/userscript.js

Clone of #7308
Lessons learnt from last year:
- It's definitely not April Fools after April 3rd 2025 (if there's any problem with the detection code, we don't need to ship an update to fix it)
- Switch all addons that have this check to runAtComplete:true by waiting until page load, this ensures Redux works properly
For testing: use the Overrides feature of Chrome Devtools to set the everything_is_totally_normal flag to true on GET /session
TODOs

Disable some addons for April Fools - 2025

---

addons/preview-project-description/userscript.js

Makes the preview-project-description addon work on React 18.
Tested [React 18 branch](https://github.com/scratchfoundation/scratch-www/tree/react-18-update) on Edge.

preview-project-description: React 18 support

---

addons/transparent-orphans/addon.json
addons/transparent-orphans/userscript.js

Updates "block transparency" to work with modern Blockly.

transparent-orphans: new Blockly

---

addons/blocks2image/userscript.js

Makes the Save blocks as image addon compatible with modern Blockly.
Tested both Scratch versions on Edge and Firefox. When "Save All as Image" is used on new Blockly, comments are included in the image, which I think makes sense.

blocks2image: new Blockly

---

addons/editor-stepping/highlighter.js

Adds an editor check to `setGlowingThreads()` since `addon.tab.traps.getWorkspace()` throws an error outside the editor which wasn't the case with `Blockly.getMainWorkspace()`.
I haven't checked if this effects other addons.

Fix highlighter errors outside editor

---

addons/middle-click-popup/BlockTypeInfo.js

Blockly has renamed the `flyout_` attribute of the toolbox to `flyout` without an underscore, which broke the middle click popup addon. This PR updates it.

middle-click-popup: new Blockly fix

---

addons/forum-post-countdown/addon.json

Marks `forum-post-countdown`'s retry setting as new on the settings page. I can also add a mention about the improved accuracy but didn't for now.

Add latestUpdate to forum-post-countdown

---

addons/middle-click-popup/WorkspaceQuerier.js

This fixed an issue where with certain TurboWarp extensions installed, opening the middle click popup menu would cause a huge lag spike, up to 20-30 seconds. I forgot to put a limit on one of the loops, nothing in normal Scratch should be effected as the limit can't be hit by the vanilla blocks.

Fix huge lag spike when opening insert blocks by name menu in TurboWarp with some extensions

---

webpages/settings/components/addon-setting.js

Resolves #8268
This was actually a bug in the settings page code - it was reading the input's `value` attribute, which is a string.

Fix number settings

---

addons-l10n/en/last-edit-tooltip.json
addons/last-edit-tooltip/addon.json
addons/last-edit-tooltip/userscript.js

Resolves [#7974](https://github.com/ScratchAddons/ScratchAddons/issues/7974)
Added the creation date of the project to the tool tip.
This addon would be helpful when wanting to know the creation date, of a project.

Added date created to "last-edit-tooltip" addon

---

addons/mediarecorder/addon.json

The description of the Project video recorder addon wasn't updated when the button's label was changed from "Start Recording" to "Record".

mediarecorder: update description

---

addons/compact-messages/addon.json
addons/dark-www/addon.json
addons/editor-dark-mode/addon.json
addons/stage-monitor/addon.json
addons/workspace-dots/addon.json
webpages/settings/components/addon-body.html
webpages/settings/components/previews/compact-messages.js
webpages/settings/components/previews/dark-www.js
webpages/settings/components/previews/editor-dark-mode.js
webpages/settings/components/previews/stage-monitor.js
webpages/settings/components/previews/workspace-dots.js

Resolves #8292
Turns `addonPreview` into a boolean option.
To save a few keystrokes and to simplify the schema a little but honestly this is kind of an unnecessary change.

Make addonPreview a boolean option

---

addons/horizontal-mystuff-tabs/style.css

Aligns the text of the first tab with the My Stuff header and the sort dropdown.
Previously, the border of the first tab was aligned with the header, which looked weird when the first tab wasn't selected:

horizontal-mystuff-tabs: change alignment

---

addons-l10n/en/editor-cleanup-plus.json
addons/editor-cleanup-plus/addon.json
addons/editor-cleanup-plus/userscript.js
addons/script-snap/userscript.js
background/get-addon-settings.js

Resolves #4131
Progress on #6671
- The unsued variable and related prompts are now optional and disabled by default
- Aligns scripts to the same grid as `script-snap`
- Don't modify the unused block messages directly
- Changes a bunch of `let`s to `const`s
- ~~Renames `unusedLocals` to `unusedVariables`~~
- Gets the workspace more directly
- Enables the addon by default
It's annoying getting so many prompts and cleanup not using the same grid.

Cleanup blocks improvements

---

addons/data-category-tweaks-v2/userscript.js
addons/rename-broadcasts/userscript.js
addons/swap-local-global/userscript.js
addons/variable-manager/userscript.js

Changes some addons so that they don't use functions that will be removed in future versions of Blockly.
Tested both Scratch versions on Edge.

Remove uses of deprecated Blockly functions

---

addons/editor-theme3/addon.json
addons/editor-theme3/color_on_black.css
addons/editor-theme3/color_on_white.css
addons/editor-theme3/theme3.css

Resolves #7944
Adds a white filter to the editor comment icons when on a dark background.

editor-theme3: Add comment icon filter

---

popups/scratch-messaging/popup.html
popups/scratch-messaging/popup.js

https://github.com/ScratchAddons/ScratchAddons/pull/7513#issuecomment-2157889735

scratch-messaging: show number of identical studio activity messages

---

addons/custom-menu-bar/menu-labels.css

Fixes this with editor messages enabled and custom-menu-bar set to labels only:

Fix editor message count padding with custom-menu-bar

---

addons/editor-theme3/addon.json
webpages/settings/style.css

Resolves https://github.com/ScratchAddons/ScratchAddons/issues/8353#issuecomment-2904449426
Moves the insertion marker notice into a setting description and adds one about comments in the colored text mode. Also fixes the help icon alignment in the popup.
Although the notice was always visible it was far from the settings that effected it. Since there are multiple though this might not be any better.
Tested on Brave.

Add a couple setting descriptions to editor-theme3

---

addons/middle-click-popup/WorkspaceQuerier.js

Resolves #8397
Added an extra bounds check which should not change anything except resolving the error.

Fix insert blocks by name not working in sprites with an empty custom block 

---

addons/reorder-custom-inputs/userscript.js

Resolves #8396
* Added optional chaining to safely access `lastInput.type` in `addLabelExternal`
* Fixes crash when adding a label to an empty custom block
* Manually tested in **Chrome**
* Verified label can be added to empty block without errors
* Confirmed other custom block editing features still work as expected

fix: prevent error when adding label to empty custom block (#8396)

---

webpages/settings/components/addon-setting.html
webpages/settings/style.css

Resolves #8399
* Putting settings closer to their labels makes it easier to see which setting is which.
* Labels that wrap unnecessarily use a lot of extra space.

Fix setting layout in popup

---

addons/dark-www/experimental_scratchr2.css

Sets the reported profile comment background to be mostly transparent for dark mode support.
Tested with inspect element in Firefox and then by adding the `just_removed` class to a comment.
With the "Scratch's default colors" preset it is the same as with the addon is disabled except when using `scratchr2`, but I can add a new CSS variable if needed.

dark-www: fix profile comment report background

---

addons/middle-click-popup/WorkspaceQuerier.js

Resolves #8367, sort of resolves #8368
I have made the parser treat some characters as "special" when doing partial matching, so that they don't have to be included in the query. So now with a variable called `_my variable`, just searching for `my variable` will still show results for it. These special characters are in a list which currently contains `!@#$%^&_'".,`. We might need to add more characters to it.
I also made a partial solution for #8368. Making just number inputs count as a match causes problems with `10 ^` showing up everywhere, so I've made a compromise to count it as a match if it matches exactly, so variables called "10" will show up when you search "10". However this doesn't work for partial matching, so if you have a variable called "10 my variable" (as shown in the …

Make middle click popup results nicer with special characters / number-named variables

---

addons/copy-reporter/userscript.js

Makes "copy reporter values" work with modern Blockly.

copy-reporter: new Blockly

---

addons/dark-www/experimental_scratchwww.css

Fixes the text color of the `no-reply@scratch.mit.edu` links in the following message:
Tested on Edge. I moved the `TeacherApprovalStep` to the beginning of the `Progression` in `src/views/teacherregistration/teacherregistration.jsx` and changed its attributes to the following:
```js
<Steps.TeacherApprovalStep
confirmed={false}
educator={permissions.educator}
email={"example@example.com"}
invited={permissions.educator_invitee}
/>
```

dark-www: style new links on teacher registration page

---

addons/editor-sounds/addon.json
addons/editor-sounds/userscript.js

Updates "editor sound effects" to work with modern Blockly.

editor-sounds: new Blockly

---

addons/editor-square-inputs/userscript.js
addons/editor-theme3/theme3.js

Updates "square block inputs" to support modern Blockly. Also fixes an unrelated typo in another addon.
Tested both Scratch versions on Edge and Firefox. The square inputs don't look exactly the same in both versions, but I think the new version is better.
Scratch website:
New Blockly:

editor-square-inputs: new Blockly

---

addons/scratch3to2/messages.css

scratch3to2: remove text shadow from message count on messages page

---

.github/CONTRIBUTING.md
_locales/en/messages.json

Changes all references to "full screen settings" to say "settings page" instead.
The name "full screen settings" doesn't make sense on mobile devices because the popup is also full-screen.

Rename "full screen settings" to "settings page"

---

addons/dark-www/experimental_scratchwww.css
addons/scratch3to2/main.css
addons/scratch3to2/project.css

Scratch will add a "Set Thumbnail" button on the project page.
The modal normally only opens when the button is clicked for the first time. To open it again, delete the `isFirstManualThumbnailUpdate` key in localStorage and reload the page.

dark-www & scratch3to2: style new "Set Thumbnail" button & modal

---

addon-api/content-script/Tab.js
addons/gamepad/style.css

Before:
After:
Nothing is changed in the editor or on the current Scratch website.

gamepad: move button after Set Thumbnail

---

webpages/settings/components/addon-body.html
webpages/settings/components/addon-setting.html

Moves the setting label margin back onto the parent when in narrow mode.

Fix help icon alignment in popup

---

addon-api/content-script/Tab.js
addons/scratch3to2/project.css

Resolves #6954
Before:
After:
This makes the layout more consistent - the only element that isn't always in the same place is the share date.

Fix project actions overflow

---

webpages/settings/index.js

Resolves #7433
Fixes a bug causing two copies of the Permissions page being opened when clicking the extension icon on Firefox. One was opened by the popup and another by the settings page iframe inside the popup.

Fix Permissions page being opened twice

---

addons/editor-stage-left/stageleft.css
addons/search-sprites/search-bar.css
addons/search-sprites/userscript.js

Resolves #8449
Makes the sprite search bar expand to the right in small stage mode if editor-stage-left is enabled.

search-sprites & editor-stage-left: fix for small stage mode

---

addons/editor-theme3/theme3.js

Fixes theme3 causing define blocks to be rendered wrong - see video in https://github.com/ScratchAddons/ScratchAddons/issues/7768#issuecomment-3146905008.

editor-theme3: fix broken define hat on new Blockly

---

content-scripts/cs.js

Updates the CSS for the update notification to support narrow screens.
I decided to hide the SA logo because it takes up a lot of space without adding any information. If we ever start adding [screenshots](https://github.com/ScratchAddons/ScratchAddons/pull/1016) to update notifications again (I think we should), this will need to be changed.
Tested on Firefox for Android.

Responsive update notification

---

addons/animated-thumb/userscript.js
addons/dark-www/experimental_scratchwww.css
addons/scratch3to2/explore_and_search.css
addons/scratch3to2/main.css
addons/scratch3to2/project.css

* Adds styles for the new share confirmation modal
* Makes the dropdown button added by animated-thumb 2.0-styled when scratch3to2 is enabled
* Fixes bugs in animated-thumb and scratch3to2
Screenshots:
<p><img width="829" height="842" alt="image" src="https://github.com/user-attachments/assets/9a8ee882-1ac8-4b7f-95c1-f64d3e05cfdc" /></p>
<p><img width="274" height="73" alt="image" src="https://github.com/user-attachments/assets/7f9e2a63-c81a-480f-9830-8128bf159486" /></p>

Style share modal & other fixes

---

addons/scratch3to2/project.css

Fixes the following bugs that would happen if scratch3to2 and website dark mode were both enabled:
* The gamepad icon was white on a light background
* The full screen and gamepad buttons had a purple background when pressed

scratch3to2: stage button fixes

---

addons-l10n/en/_general.json
addons-l10n/en/delete-others.json
addons-l10n/en/folders.json
addons/delete-others/userscript.js
addons/folders/userscript.js

Moves the strings for restoring multiple items to `_general.json` to avoid duplication and to make sure they're translated identically in both folders and delete-others.

Move restore messages to `_general.json`

---

addons/editor-compact/userstyle.css
addons/recolor-custom-blocks/userstyle.css

Fixes compatability between recolor custom blocks and compact editor. I set the height to `1.9rem` since it's very close to what it was before. `!important` is used to override `[class*="modal_modal-content"] [class*="box_box"] button` but a higher specificity might be better.
Also fixes the alignment of the icons added by `reorder-custom-inputs` when `editor-compact` is enabled.
Tested on Chromium

`recolor-custom-blocks` & `reorder-custom-inputs`: support `editor-compact`

---

addons/debugger/userscript.js

Resolves #5727
- **Before changes:** The Debugger window could not be dragged on a touch screen, and doing so would scroll the page instead.
- **After changes:** The Debugger window can now be properly dragged by its title bar with both mouse and touch input.
Tested with Edge DevTools Device Emulation.

Allow dragging debugger on touchscreen

---

addons/debugger/timing/HeatmapManager.js

I noticed a bug in my timing tools PR: my css selection for textElements to force to be white (needed for when users have high contrast on, which has black text which doesn't contrast well with heatmap enabled) will exclude certain text elements meaning not all text gets changed to white.
I need to change lines 14-16 of addons\debugger\timing\HeatmapManager.js from 
```js
const textElements = Array.from(block.svgGroup_.children)
.filter((el) => !el.classList.contains("blocklyDraggable"))
.flatMap((el) => Array.from(el.querySelectorAll("text")));
```
to
```js
const textElements = block.svgGroup_.querySelectorAll(
":scope > :not(.blocklyDraggable) text, :scope > text:not(.blocklyDraggable)"
);
```
| Before | After |
|--------|-------|
| <img width="237" height="566" alt="Before" …

Fix not all text being changed to white when timing tools heatmap enabled

---

addons/find-bar/userscript.js
background/transition.js
webpages/settings/components/addon-setting.html
webpages/settings/components/addon-setting.js

Specifically some commented out `find-bar` code, the `key` setting type that was never added to the schema and the code that opened the Scratch messaging extension transion page.
Also fixes a bug that caused the welcome page to never open on install.

Fix welcome page & remove some dead code

---

addons/debugger/logs.js

In floating point math, there are two distinct values for 0 and -0. This difference is subtle, but it does make a difference in some obscure cases (eg `1/-0 === -Infinity` instead of `Infinity`). Because `(-0).toString() === "0"` when the debugger tries to log a statement which reports -0, it logs "0". [This can cause some confusion](https://github.com/TurboWarp/scratch-vm/issues/224). Making this debug tool print the value accurately (even when Scratch itself doesn't) makes sense to me.
Before: 
After:

Fix -0 being logged as 0 in debugger

---

addons/recolor-custom-blocks/userscript.js

Resolves #8607
Also removes a return value that wasn't used anywhere.

recolor-custom-blocks: fix Hide prefixes setting
